var keyStrings = {
    " (after changing, load playlist)":
        " (փոփոխությունից հետո, բեռնել նվագարկման ցուցակը)",
    " added to category ": " ավելացված է կատեգորիային ",
    " added to favorites": " ավելացված է ընտրյալներին",
    "??? No channel name": "??? Ալիքի անուն չկա",
    Actions: "Գործողություններ",
    "Add channel to category": "Ավելացնել ալիքը կատեգորիային",
    "Add channel to favorites": "Ավելացնել ալիքը ընտրյալներին",
    All: "Բոլորը",
    "Applying HTTP remote settings...":
        "HTTP հեռակառավարման կարգավորումների կիրառում...",
    "Archive hours": "Արխիվի ժամեր",
    alhabet: "աբգդեզէըթժիլխծկհձղճմյնշոչպսջվռտրցւփքօֆ",
    "Buffer Size, s": "Բուֆերի չափ, վ",
    "built-in": "ներկառուցված",
    Category: "Կատեգորիա",
    "Channel ": "Ալիք ",
    "Channel is not available!!!": "Ալիքը հասանելի չէ!!!",
    "Channel list": "Ալիքների ցուցակ",
    "Channel list not received !!!": "Ալիքների ցուցակը չի ստացվել!!!",
    "Channel list not received !!!<br/><br/>Enter the provider data and restart the player !!!<br/><br/>":
        "Ալիքների ցուցակը չի ստացվել!!!<br/><br/>Մուտքագրեք մատակարարի տվյալները և վերագործարկեք նվագարկիչը!!!<br/><br/>",
    "Channel list. Category: ": "Ալիքների ցուցակ. Կատեգորիա: ",
    "Channel parental control": "Ծնողական վերահսկողություն ալիքի համար",
    Close: "Փակել",
    "Could not update HTTP remote control.":
        "Չհաջողվեց թարմացնել HTTP հեռակառավարման կարգավորումները։",
    "Delete channel": "Ջնջել ալիքը",
    Description: "Նկարագրություն",
    "Device access code": "Սարքի մուտքի կոդ",
    "Disable HTTP remote": "Անջատել HTTP հեռակառավարումը",
    "Disabled by default. Enabling creates a new device access code.":
        "Լռելյայն անջատված է։ Միացնելիս ստեղծվում է սարքի մուտքի նոր կոդ։",
    Edit: "Խմբագրել",
    "Edit category name": "Խմբագրել կատեգորիայի անունը",
    "Edit playlist data": "Խմբագրել նվագարկման ցուցակի տվյալները",
    Editor: "Խմբագրիչ",
    "Enable HTTP remote": "Միացնել HTTP հեռակառավարումը",
    "Enter Media Library URL": "Մուտքագրեք մեդիա գրադարանի URL-ը",
    "Enter parental code": "Մուտքագրեք ծնողական կոդը",
    "Enter playlist archive hours":
        "Մուտքագրեք նվագարկման ցուցակի արխիվի ժամերը",
    "Enter playlist Name": "Մուտքագրեք նվագարկման ցուցակի անունը",
    "Enter playlist URL": "Մուտքագրեք նվագարկման ցուցակի URL-ը",
    EPG: "Հեռուստածրագիր",
    Exit: "Ելք",
    "Failed to load channel list!": "Չհաջողվեց բեռնել ալիքների ցուցակը!",
    Favorites: "Ընտրյալներ",
    "HTTP port": "HTTP պորտ",
    "HTTP remote control is unavailable on this device.":
        "HTTP հեռակառավարումն այս սարքում հասանելի չէ։",
    Info: "Տեղեկություն",
    Load: "Բեռնել",
    "Load playlist": "Բեռնել նվագարկման ցուցակը",
    "Local HTTP remote control": "Տեղային HTTP հեռակառավարում",
    lang: "Հայերեն",
    "Media Library URL": "Մեդիա գրադարանի URL",
    Menu: "Մենյու",
    "Move channel down": "Տեղափոխել ալիքը ներքև",
    "Move channel up": "Տեղափոխել ալիքը վերև",
    "m3u-m3u8 playlists": "m3u-m3u8 նվագարկման ցուցակներ",
    min: "րոպե",
    "No channel name": "Ալիքի անուն չկա",
    Nothing: "Ոչինչ",
    native: "բնիկ",
    no: "ոչ",
    "Open in PiP": "Բացել PiP-ով",
    off: "անջատված",
    on: "միացված",
    Playlist: "Նվագարկման ցուցակ",
    "Playlist file": "Նվագարկման ցուցակի ֆայլ",
    "Playlist is not loading directly...Loading via server...":
        "Նվագարկման ցուցակը չի բեռնվում ուղղակիորեն...Բեռնում սերվերի միջոցով...",
    "Playlist Name": "Նվագարկման ցուցակի անուն",
    "Playlist URL": "Նվագարկման ցուցակի URL",
    "Remote control": "Հեռակառավարում",
    "Save Settings": "Պահպանել կարգավորումները",
    Search: "Որոնել",
    "Select category to add channel":
        "Ընտրեք կատեգորիա ալիքը ավելացնելու համար",
    "Select playlist": "Ընտրեք նվագարկման ցուցակ",
    "Select playlist file": "Ընտրեք նվագարկման ցուցակի ֆայլը",
    "Send this code from your proxy in the Authorization: Bearer header.":
        "Այս կոդն ուղարկեք պրոքսիից՝ Authorization: Bearer վերնագրում։",
    Settings: "Կարգավորումներ",
    "Settings STB": "STB կարգավորումներ",
    "Settings saved": "Կարգավորումները պահպանված են",
    "Stalker portals": "Stalker պորտալներ",
    "Type of player for streaming": "Նվագարկիչի տեսակը սթրիմինգի համար",
    "Wrong parental code !!!": "Սխալ ծնողական կոդ!!!",
    yes: "այո",
};
