var keyStrings = {
    " (after changing, load playlist)": " (пасля змены, загрузіць плэйліст)",
    " added to category ": " дададзены ў катэгорыю ",
    " added to favorites": " дададзены ў выбраныя",
    "??? No channel name": "??? Няма назвы канала",
    Actions: "Дзеянні",
    "Add channel to category": "Дадаць канал у катэгорыю",
    "Add channel to favorites": "Дадаць канал у выбраныя",
    All: "Усе",
    "Applying HTTP remote settings...": "Ужыванне налад HTTP-пульта...",
    "Archive hours": "Гадзін архіва",
    alhabet: "абвгдеёжзійклмнопрстуўфхцчшыьэюя",
    "Buffer Size, s": "Памер буфера, с",
    "built-in": "убудаваны",
    Category: "Катэгорыя",
    "Channel ": "Канал ",
    "Channel is not available!!!": "Канал недаступны!!!",
    "Channel list": "Спіс каналаў",
    "Channel list not received !!!": "Не атрыманы спіс каналаў!!!",
    "Channel list not received !!!<br/><br/>Enter the provider data and restart the player !!!<br/><br/>":
        "Не атрыманы спіс каналаў!!!<br/><br/>Увядзіце даныя правайдэра і перазапусціце плэер!!!<br/><br/>",
    "Channel list. Category: ": "Спіс каналаў. Катэгорыя: ",
    "Channel parental control": "Бацькоўскі кантроль канала",
    Close: "Закрыць",
    "Could not update HTTP remote control.":
        "Не ўдалося змяніць налады HTTP-пульта.",
    "Delete channel": "Выдаліць канал",
    Description: "Апісанне",
    "Device access code": "Код доступу да прылады",
    "Disable HTTP remote": "Выключыць HTTP-пульт",
    "Disabled by default. Enabling creates a new device access code.":
        "Па змаўчанні выключаны. Пры ўключэнні ствараецца новы код доступу да прылады.",
    Edit: "Рэдагаваць",
    "Edit category name": "Рэдагаванне назвы катэгорыі",
    "Edit playlist data": "Рэдагаванне даных плэйліста",
    Editor: "Рэдактар",
    "Enable HTTP remote": "Уключыць HTTP-пульт",
    "Enter Media Library URL": "Увод URL медыятэкі",
    "Enter parental code": "Увядзіце бацькоўскі код",
    "Enter playlist archive hours":
        "Увод колькасці гадзін архіва для плэйліста",
    "Enter playlist Name": "Увод назвы плэйліста",
    "Enter playlist URL": "Увод URL плэйліста",
    EPG: "Праграма",
    Exit: "Выхад",
    "Failed to load channel list!": "Не атрымалася загрузіць спіс каналаў!",
    Favorites: "Выбраныя",
    "HTTP port": "HTTP-порт",
    "HTTP remote control is unavailable on this device.":
        "HTTP-пульт недаступны на гэтай прыладзе.",
    Info: "Інфо",
    Load: "Загрузіць",
    "Load playlist": "Загрузіць плэйліст",
    "Local HTTP remote control": "Лакальны HTTP-пульт",
    lang: "Беларуская",
    "Media Library URL": "URL медыятэкі",
    Menu: "Меню",
    "Move channel down": "Перасунуць канал уніз",
    "Move channel up": "Перасунуць канал уверх",
    "m3u-m3u8 playlists": "Плэйлісты m3u-m3u8",
    min: "хв",
    "No channel name": "Няма назвы канала",
    Nothing: "Нічога",
    native: "родны",
    no: "не",
    "Open in PiP": "Адкрыць у PiP",
    off: "выключана",
    on: "уключаны",
    Playlist: "Плэйліст",
    "Playlist file": "Файл плэйліста",
    "Playlist is not loading directly...Loading via server...":
        "Плэйліст не загружаецца напрамую...Загрузка праз сервер...",
    "Playlist Name": "Назва плэйліста",
    "Playlist URL": "URL плэйліста",
    "Remote control": "Аддаленае кіраванне",
    "Save Settings": "Захаваць налады",
    Search: "Пошук",
    "Select category to add channel": "Выбар катэгорыі для дадання канала",
    "Select playlist": "Выберыце плэйліст",
    "Select playlist file": "Выбар файла плэйліста",
    "Send this code from your proxy in the Authorization: Bearer header.":
        "Перадавайце гэты код з проксі ў загалоўку Authorization: Bearer.",
    Settings: "Налады",
    "Settings STB": "Налады прылады",
    "Settings saved": "Налады захаваны",
    "Stalker portals": "Парталы Stalker",
    "Type of player for streaming": "Тып плэера для струменевай перадачы",
    "Wrong parental code !!!": "Няправільны бацькоўскі код!!!",
    yes: "так",
};
