var keyStrings = {
    " (after changing, load playlist)": " (след промяна, заредете плейлиста)",
    " (after changing, restart player)":
        " (след промяната рестартирайте плейъра)",
    " added to category ": " добавен към категория ",
    " added to favorites": " добавен към любими",
    " m ": " мин ",
    " s": " с",
    "??? No channel name": "??? Без име на канал",
    '"As Is"': "„Без промяна“",
    '"Favorites"': "„Любими“",
    '"Sliding" infobar': "Плъзгащ се информационен панел",
    "&darr;a": "&darr;a",
    "&uarr;A": "&uarr;A",
    "<br/><br/>In archive mode:<br/>": "<br/><br/>В режим архив:<br/>",
    "<br/>Loading STB...": "<br/>Зареждане на устройството…",
    "<br/>Setup STB...": "<br/>Настройване на устройството…",
    "<br>": "<br>",
    "<br><br>": "<br><br>",
    "<br>Add<br>to category": "<br>Добавяне<br>в категория",
    "<br>Add<br>to favorites": "<br>Добавяне<br>в любими",
    "<br>Delete": "<br>Изтриване",
    "<br>Down<br>": "<br>Надолу<br>",
    "<br>Live": "<br>На живо",
    "<br>Menu": "<br>Меню",
    "<br>Parental<br>Control": "<br>Родителски<br>контрол",
    "<br>Pause<br>": "<br>Пауза<br>",
    "<br>Previous<br>channel": "<br>Предишен<br>канал",
    "<br>Rewind<br>": "<br>Превъртане<br>",
    "<br>Toggle<br>sound track": "<br>Смяна на<br>аудиопистата",
    "<br>Up<br>": "<br>Нагоре<br>",
    "1 hour": "1 час",
    "1 minute": "1 минута",
    "2 hours": "2 часа",
    "3 hours": "3 часа",
    "10 Seconds": "10 секунди",
    "30 minutes": "30 минути",
    "A command expired while the player was loading channels.":
        "Срокът на командата изтече при зареждането на каналите.",
    "A command was rejected by the player. Check its provider and settings.":
        "Плейърът отхвърли команда. Проверете доставчика и настройките.",
    About: "За програмата",
    "Access code": "Код за достъп",
    "Access denied. Check the server access code.":
        "Достъпът е отказан. Проверете кода за достъп до сървъра.",
    "Access key": "Ключ за достъп",
    "Access key is required!": "Необходим е ключ за достъп!",
    "Access settings": "Настройки за достъп",
    Actions: "Действия",
    "Active list": "Активен списък",
    Actors: "Актьори",
    "Add / rename / delete…": "Добавяне / преименуване / изтриване…",
    "Add channel to category": "Добави канал към категория",
    "Add channel to favorites": "Добави канал към любими",
    "Add new list": "Добавяне на списък",
    "Add to favorites": "Добавяне в любими",
    Age: "Възраст",
    All: "Всички",
    "All categories": "Всички категории",
    "All4you.tv": "All4you.tv",
    "All4you.tv settings": "Настройки за All4you.tv",
    "Allowlist this Device ID": "Разрешете този ID на устройство",
    "An IP without a port uses HTTP port 8081. Clear the address or select Disconnect to stop.":
        "За IP без порт се използва HTTP порт 8081. За спиране изчистете адреса или изберете „Прекъсване“.",
    "API failed, trying M3U...": "Грешка в API, опит с M3U…",
    "API Server": "API сървър",
    "API server URL": "URL на API сървъра",
    "Applying HTTP remote settings...":
        "Прилагане на настройките на HTTP дистанционното...",
    Archive: "Архив",
    "Archive - begin": "Архив — начало",
    "Archive hours": "Часове архив",
    "Archive: ENTER on past programs": "Архив: ENTER върху минало предаване",
    "Archive. Channel: ": "Архив. Канал: ",
    Aspect: "Съотношение на страните",
    Audio: "Звук",
    alhabet: "абвгдежзийклмнопрстуфхцчшщъьюяѝ",
    always: "винаги",
    "and enter code": "и въведете кода",
    Back: "Назад",
    "Back / Forward for 1 minute": "Назад / напред с 1 минута",
    "Background color": "Цвят на фона",
    "Background color of selected item": "Цвят на фона на избрания елемент",
    "BEST LiST IPTV [HLS Playlist]": "BEST LiST IPTV [HLS Playlist]",
    "BEST LiST IPTV [HLS Playlist] settings":
        "Настройки за BEST LiST IPTV [HLS Playlist]",
    "BEST LiST IPTV [Stalker]": "BEST LiST IPTV [Stalker]",
    "BEST LiST IPTV [Stalker] settings":
        "Настройки за BEST LiST IPTV [Stalker]",
    "Behavior of %1/%2 buttons in lists":
        "Действие на бутоните %1/%2 в списъците",
    "Black screen while switching the channel":
        "Черен екран при смяна на канала",
    Blue: "Син",
    "Bookmark age: %1 days": "Възраст на отметката: %1 дни",
    "Buffer Size, s": "Размер на буфера, с",
    "Built-in playlist:": "Вграден плейлист:",
    "Built-in playlists": "Вградени плейлисти",
    "Button %1 function when viewing": "Действие на бутон %1 при гледане",
    "Button function %1 when viewing archive":
        "Действие на бутон %1 при гледане на архив",
    "Buttons settings": "Настройки на бутоните",
    "By alphabet": "По азбучен ред",
    "By time": "По време",
    "begin/end": "начало/край",
    "bottom-right": "долу вдясно",
    "built-in": "вграден",
    "Call PiP": "Отваряне на PiP",
    "Call PiP / PiP exchange": "Отваряне на PiP / размяна",
    Cancel: "Отказ",
    "Cannot delete the last category":
        "Последната категория не може да бъде изтрита",
    Category: "Категория",
    "Category selection": "Избор на категория",
    "Change interface language": "Смяна на езика на интерфейса",
    "Change provider": "Смяна на доставчика",
    "Change provider - you can change the provider, and it will be remembered at the next start of player!":
        "Сменете доставчика. Изборът ще се запази при следващото стартиране на плейъра.",
    "Change value": "Промяна на стойността",
    "Channel ": "Канал ",
    "Channel has no EPG": "Каналът няма програма",
    "Channel is not available!!!": "Каналът не е достъпен!!!",
    "Channel link": "Връзка към канала",
    "Channel link is required!": "Необходима е връзка към канала!",
    "Channel list": "Списък на каналите",
    "Channel list editing style": "Режим за редактиране на списъка с канали",
    "Channel list not received !!!": "Списъкът с канали не е получен!!!",
    "Channel list not received !!!<br/><br/>Enter the provider data and restart the player !!!<br/><br/>":
        "Списъкът с канали не е получен!!!<br/><br/>Въведете данните на доставчика и рестартирайте плейъра!!!<br/><br/>",
    "Channel list settings": "Настройки на списъка с канали",
    "Channel list. Category: ": "Списък на каналите. Категория: ",
    "Channel parental control": "Родителски контрол на канала",
    Channels: "Канали",
    "Choose from": "Избор от",
    "Choose language": "Изберете език",
    "Choose provider": "Изберете доставчик",
    Classic: "Класически",
    "Clear all settings?": "Да се изтрият ли всички настройки?",
    "Clear settings": "Изтриване на настройките",
    Close: "Затвори",
    "Close PiP": "Затваряне на PiP",
    Color: "Цвят",
    "Color spectrum": "Цветова палитра",
    "Command server": "Сървър за команди",
    "Command server address, device access code, local HTTP control, and remote text entry settings":
        "Адрес на сървъра за команди, код за достъп, локално HTTP управление и дистанционно въвеждане на текст",
    "Configure All4you.tv in Settings -> Provider Settings":
        "Настройте All4you.tv в Настройки -> Настройки на доставчика",
    "Configure BEST LiST IPTV [HLS Playlist] in Settings -> Provider Settings":
        "Настройте BEST LiST IPTV [HLS Playlist] в Настройки -> Настройки на доставчика",
    "Configure BEST LiST IPTV [Stalker] in Settings -> Provider Settings":
        "Настройте BEST LiST IPTV [Stalker] в Настройки -> Настройки на доставчика",
    "Configure Diamond TV in Settings -> Provider Settings":
        "Настройте Diamond TV в Настройки -> Настройки на доставчика",
    "Configure DRVAO in Settings -> Provider Settings":
        "Настройте DRVAO в Настройки -> Настройки на доставчика",
    "Configure Dragon Media PRO in Settings -> Provider Settings":
        "Настройте Dragon Media PRO в Настройки -> Настройки на доставчика",
    "Configure Fabryka.TV in Settings -> Provider Settings":
        "Настройте Fabryka.TV в Настройки -> Настройки на доставчика",
    "Configure Fox-TV in Settings -> Provider Settings":
        "Настройте Fox-TV в Настройки -> Настройки на доставчика",
    "Configure FXML in Settings -> Provider Settings":
        "Настройте FXML в Настройки -> Настройки на доставчика",
    "Configure GlanzTV in Settings -> Provider Settings":
        "Настройте GlanzTV в Настройки -> Настройки на доставчика",
    "Configure GREAT IPTV in Settings -> Provider Settings":
        "Настройте GREAT IPTV в Настройки -> Настройки на доставчика",
    "Configure IpStream.one in Settings -> Provider Settings":
        "Настройте IpStream.one в Настройки -> Настройки на доставчика",
    "Configure KORONA TV in Settings -> Provider Settings":
        "Настройте KORONA TV в Настройки -> Настройки на доставчика",
    "Configure MaxTV in Settings -> Provider Settings":
        "Настройте MaxTV в Настройки -> Настройки на доставчика",
    "Configure New Look in Settings -> Provider Settings":
        "Настройте New Look в Настройки -> Настройки на доставчика",
    "Configure OTT Prime ONLINE in Settings -> Provider Settings":
        "Настройте OTT Prime ONLINE в Настройки -> Настройки на доставчика",
    "Configure POLMEDIA in Settings -> Provider Settings":
        "Настройте POLMEDIA в Настройки -> Настройки на доставчика",
    "Configure PROST in Settings -> Provider Settings":
        "Настройте PROST в Настройки -> Настройки на доставчика",
    "Configure RD in Settings -> Provider Settings":
        "Настройте RD в Настройки -> Настройки на доставчика",
    "Configure RUSSKOETV in Settings -> Provider Settings":
        "Настройте RUSSKOETV в Настройки -> Настройки на доставчика",
    "Configure Shara.club (ClubTV.pro) in Settings -> Provider Settings":
        "Настройте Shara.club (ClubTV.pro) в Настройки -> Настройки на доставчика",
    "Configure ShockTv in Settings -> Provider Settings":
        "Настройте ShockTv в Настройки -> Настройки на доставчика",
    "Configure Tabox in Settings -> Provider Settings":
        "Настройте Tabox в Настройки -> Настройки на доставчика",
    "Configure TOP-IPTV in Settings -> Provider Settings":
        "Настройте TOP-IPTV в Настройки -> Настройки на доставчика",
    "Configure Top-Tv in Settings -> Provider Settings":
        "Настройте Top-Tv в Настройки -> Настройки на доставчика",
    "Configure TV DOSUG in Settings -> Provider Settings":
        "Настройте TV DOSUG в Настройки -> Настройки на доставчика",
    "Configure TVClub in Settings -> Provider Settings":
        "Настройте TVClub в Настройки -> Настройки на доставчика",
    "Configure ULTIFL1X in Settings -> Provider Settings":
        "Настройте ULTIFL1X в Настройки -> Настройки на доставчика",
    "Configure VIP-IP.COM in Settings -> Provider Settings":
        "Настройте VIP-IP.COM в Настройки -> Настройки на доставчика",
    "Configure Vidok.TV in Settings -> Provider Settings":
        "Настройте Vidok.TV в Настройки -> Настройки на доставчика",
    "Configure Гомельсат (cbilling) in Settings -> Provider Settings":
        "Настройте Гомельсат (cbilling) в Настройки -> Настройки на доставчика",
    "Configure МойДом in Settings -> Provider Settings":
        "Настройте МойДом в Настройки -> Настройки на доставчика",
    "Configure Радуга in Settings -> Provider Settings":
        "Настройте Радуга в Настройки -> Настройки на доставчика",
    "Configure Шаравоз in Settings -> Provider Settings":
        "Настройте Шаравоз в Настройки -> Настройки на доставчика",
    Connect: "Свързване",
    Connected: "Свързано",
    "Connected. Waiting for the channel list...":
        "Свързано. Изчакване на списъка с канали…",
    "Connecting to Stalker portal...": "Свързване с портала Stalker…",
    "Connecting...": "Свързване…",
    "Continue watching?": "Да продължи ли гледането?",
    "Copy category": "Копиране на категорията",
    "Copy JSON": "Копиране на JSON",
    "Could not connect to the server.": "Неуспешно свързване със сървъра.",
    "Could not update HTTP remote control.":
        "Настройките на HTTP дистанционното не бяха променени.",
    Country: "Държава",
    "Create category": "Създаване на категория",
    current: "текущ",
    "Debug HUD": "Панел за диагностика",
    "Debug HUD is not available": "Панелът за диагностика не е достъпен",
    Delete: "Изтриване",
    "Delete category": "Изтриване на категорията",
    "Delete channel": "Изтрий канал",
    "Delete list": "Изтриване на списъка",
    "Demo — moving test pattern": "Демо — движеща се тестова картина",
    Description: "Описание",
    "Description of remote control buttons":
        "Описание на бутоните на дистанционното",
    "Device access code": "Код за достъп до устройството",
    "Device info:": "Информация за устройството:",
    "Device MAC is required for KBC (Kinoboom) playlists":
        "За плейлистите KBC (Kinoboom) е необходим MAC адрес на устройството",
    "Diamond TV": "Diamond TV",
    "Diamond TV settings": "Настройки за Diamond TV",
    Director: "Режисьор",
    "Disable HTTP remote": "Изключване на HTTP дистанционно",
    "Disabled by default. Enabling creates a new device access code.":
        "Изключено по подразбиране. При включване се създава нов код за достъп до устройството.",
    Disconnect: "Прекъсване",
    Disconnected: "Връзката е прекъсната",
    "Distance between lines in lists": "Разстояние между редовете в списъците",
    "Do you want to exit player?": "Да се затвори ли плейърът?",
    "Download! Wait ...": "Изтегляне… Изчакайте…",
    DRVAO: "DRVAO",
    "DRVAO settings": "Настройки за DRVAO",
    "Dragon Media PRO": "Dragon Media PRO",
    "Dragon Media PRO settings": "Настройки за Dragon Media PRO",
    Duration: "Продължителност",
    Edit: "Редактирай",
    "Edit access key": "Редактиране на ключа за достъп",
    "Edit category name": "Редактирай име на категория",
    "Edit channel link": "Редактиране на връзката към канала",
    "Edit playlist data": "Редактирай данни на плейлиста",
    "Edit VPortal link": "Редактиране на връзката VPortal",
    Editor: "Редактор",
    "Enable HTTP remote": "Включване на HTTP дистанционно",
    English: "Английски",
    "Enter a password (8 characters).": "Въведете парола (8 знака).",
    "Enter a playlist URL to access this service.":
        "Въведете URL на плейлиста за достъп до услугата.",
    "Enter a server address without spaces or a fragment.":
        "Въведете адрес на сървър без интервали и фрагмент след #.",
    "Enter a username (8 characters).": "Въведете потребителско име (8 знака).",
    "Enter a username and password to access this service.":
        "Въведете потребителско име и парола за достъп до услугата.",
    "Enter a valid server address, for example 192.168.1.20:8081.":
        "Въведете валиден адрес на сървър, например 192.168.1.20:8081.",
    "Enter access key for": "Въведете ключ за достъп за",
    "Enter an application access key (8 characters).":
        "Въведете ключа за достъп до приложението (8 знака).",
    "Enter an ID and PIN to access this service.":
        "Въведете ID и PIN за достъп до услугата.",
    "Enter an IPTV token (10 characters).": "Въведете IPTV токен (10 знака).",
    "Enter category name": "Въведете име на категорията",
    "Enter MAC address": "Въведете MAC адрес",
    "Enter MAC address (e.g. 00:1A:2B:3C:4D:5E)":
        "Въведете MAC адрес (напр. 00:1A:2B:3C:4D:5E)",
    "Enter Media Library URL": "Въведете URL на медиятеката",
    "Enter new category name": "Въведете ново име на категорията",
    "Enter Provider Code": "Въведете код на доставчика",
    "Enter Provider Code on PC or Phone":
        "Въведете кода на доставчика на компютър или телефон",
    "Enter parental code": "Въведете родителски код",
    "Enter password": "Въведете парола",
    "Enter playlist archive hours": "Въведете часове архив за плейлиста",
    "Enter playlist Name": "Въведете име на плейлиста",
    "Enter playlist URL": "Въведете URL на плейлиста",
    "Enter Stalker portal URL": "Въведете URL на портала Stalker",
    "Enter Stalker portal URL (e.g. http://your-portal:8800)":
        "Въведете URL на портала Stalker (напр. http://your-portal:8800)",
    "Enter Stalker portal URL (e.g. http://your-portal/stalker_portal/c/)":
        "Въведете URL на портала Stalker (напр. http://your-portal/stalker_portal/c/)",
    "Enter the access code separately, not in the server address.":
        "Въведете кода за достъп отделно от адреса на сървъра.",
    "Enter the command server IP or address.":
        "Въведете IP или адреса на сървъра за команди.",
    "Enter the full CDN host from the cabinet stream URL (e.g. subdomain.cdn-domain.tld), not a bare subdomain":
        "Въведете пълното име на CDN хоста от URL на потока в профила (напр. subdomain.cdn-domain.tld), а не само поддомейна",
    "Enter the server IP or address and this player's device access code from the server configuration. Saving both starts checking for volume, channel and other commands automatically.":
        "Въведете IP или адреса на сървъра и кода за достъп на плейъра от конфигурацията на сървъра. Запазването на двете стойности автоматично започва проверка за команди за сила на звука, канали и други действия.",
    "Enter the server's device access code (32–256 letters, digits, _ or -).":
        "Въведете кода за достъп на устройството от сървъра (32–256 букви, цифри, _ или -).",
    'Enter the tv.team playlist URL.<br>Playlist type: <b>OTTPlayer</b><br/><br/>The "/playlist.m3u8" suffix is added automatically if omitted.':
        'Въведете URL на плейлиста tv.team.<br>Тип плейлист: <b>OTTPlayer</b><br/><br/>Окончанието "/playlist.m3u8" се добавя автоматично, ако липсва.',
    "Enter the VPortal link as shown in the cabinet":
        "Въведете връзката VPortal от личния си профил",
    "Enter this link in VPortal link. Playlist URL requires an M3U playlist.":
        "Въведете тази връзка в полето VPortal. URL на плейлиста трябва да води към M3U плейлист.",
    "Enter this player's device access code to connect.":
        "За свързване въведете кода за достъп на този плейър.",
    "Enter username": "Въведете потребителско име",
    "Enter value": "Въведете стойност",
    "Enter Xtream server URL": "Въведете URL на сървъра Xtream",
    "Enter Xtream server URL (e.g. https://your-server:8080)":
        "Въведете URL на сървъра Xtream (напр. https://your-server:8080)",
    EPG: "ТВ програма",
    "EPG and archive. Channel: ": "Програма и архив. Канал: ",
    "ERROR!": "Грешка!",
    "Error Code!": "Невалиден код!",
    Exit: "Изход",
    "Exit player": "Изход от плейъра",
    "Export settings": "Експортиране на настройки",
    "epg.one (Ordered)": "epg.one (Подреден)",
    "epg.one (Standard)": "epg.one (Стандартен)",
    "epg.one (Thematic)": "epg.one (Тематичен)",
    "epgs...": "ТВ програма…",
    "Fabryka.TV": "Fabryka.TV",
    "Fabryka.TV settings": "Настройки за Fabryka.TV",
    "Failed to connect to Stalker portal":
        "Неуспешно свързване с портала Stalker",
    "Failed to connect to Xtream API server":
        "Неуспешно свързване със сървъра Xtream API",
    "Failed to get user data!!!":
        "Неуспешно получаване на потребителските данни!",
    "Failed to load channel list!": "Грешка при зареждане на списъка с канали!",
    "Failed to load channels from Stalker portal":
        "Неуспешно зареждане на каналите от портала Stalker",
    "Failed to load channels from Xtream API":
        "Неуспешно зареждане на каналите от Xtream API",
    "Failed to load!": "Зареждането е неуспешно!",
    "Favorite lists": "Списъци с любими",
    Favorites: "Любими",
    "File selection is not supported on this device":
        "Изборът на файл не се поддържа на това устройство",
    Filters: "Филтри",
    "First Run Setup": "Първоначална настройка",
    "Font type": "Шрифт",
    "For download settings file open":
        "За изтегляне на файла с настройки отворете",
    "For enter value open": "За въвеждане на стойност отворете",
    "For upload settings file open": "За качване на файла с настройки отворете",
    "Fox-TV": "Fox-TV",
    "Fox-TV settings": "Настройки за Fox-TV",
    FXML: "FXML",
    "FXML settings": "Настройки за FXML",
    Genre: "Жанр",
    GlanzTV: "GlanzTV",
    "GlanzTV settings": "Настройки за GlanzTV",
    "Go to": "Преминаване",
    "GREAT IPTV": "GREAT IPTV",
    "GREAT IPTV settings": "Настройки за GREAT IPTV",
    "Graphical indication": "Графични индикатори",
    Green: "Зелен",
    "Hide / Return": "Скриване / показване",
    "Hide provider settings?": "Да се скрият ли настройките на доставчика?",
    "Hide providers?": "Да се скрият ли доставчиците?",
    "History in Media Library": "История в медийната библиотека",
    "History of watched movies": "История на гледането",
    "HTTP port": "HTTP порт",
    "HTTP remote control is unavailable on this device.":
        "HTTP дистанционното не е налично на това устройство.",
    ID: "ID",
    "Import settings": "Импортиране на настройки",
    "In live mode: <br/>": "В режим на живо:<br/>",
    Info: "Инфо",
    "Infobar display timeout, s":
        "Време за показване на информационния панел, с",
    "Infobar settings": "Настройки на информационния панел",
    Information: "Информация",
    "Interface credits": "Автори на интерфейса",
    "Interface settings": "Настройки на интерфейса",
    "Interface theme": "Тема на интерфейса",
    "Interface transparency": "Прозрачност на интерфейса",
    "Invalid channel link! Enter the full host as in the cabinet stream URL (e.g. subdomain.cdn-domain.tld)":
        "Невалидна връзка към канала! Въведете пълното име на хоста от URL на потока в профила (напр. subdomain.cdn-domain.tld)",
    "IPTV token": "IPTV токен",
    "IpStream.one": "IpStream.one",
    "IpStream.one settings": "Настройки за IpStream.one",
    Joystick: "Джойстик",
    "KBC (Kinoboom) access data": "Данни за достъп до KBC (Kinoboom)",
    "KORONA TV": "KORONA TV",
    "KORONA TV settings": "Настройки за KORONA TV",
    "List created": "Списъкът е създаден",
    "List deleted": "Списъкът е изтрит",
    "List location": "Позиция на списъка",
    "List renamed": "Списъкът е преименуван",
    "List type": "Тип списък",
    "Lists settings": "Настройки на списъците",
    Live: "На живо",
    Load: "Зареди",
    "Load built-in playlist:": "Зареждане на вграден плейлист:",
    "Load playlist": "Зареди плейлист",
    "Load settings": "Зареждане на настройки",
    "Load settings from storage": "Зареждане на настройки от хранилището",
    "Load:": "Зареждане:",
    "Loading channels from Xtream API...": "Зареждане на канали от Xtream API…",
    "Loading channels...": "Зареждане на канали…",
    "Loading from API...": "Зареждане чрез API…",
    "Loading from Edem API...": "Зареждане от Edem API…",
    "Loading M3U playlist...": "Зареждане на M3U плейлист…",
    "Loading M3U...": "Зареждане на M3U…",
    "Loading via proxy...": "Зареждане чрез прокси…",
    "Loading. Please wait...": "Зареждане. Изчакайте…",
    "Loading...": "Зареждане…",
    "Local HTTP remote control": "Локално HTTP дистанционно",
    "Local URL": "Локален URL",
    Login: "Потребителско име",
    lang: "Български",
    large: "голям",
    left: "вляво",
    "left-bottom": "долу вляво",
    "logos...": "Лога…",
    M3U: "M3U",
    "M3U URL": "URL на M3U",
    "M3U URL (fallback)": "URL на M3U (резервен)",
    "MAC address": "MAC адрес",
    "Manage lists": "Управление на списъците",
    "Manage settings": "Управление на настройките",
    "Manual setup": "Ръчна настройка",
    MaxTV: "MaxTV",
    "MaxTV settings": "Настройки за MaxTV",
    Media: "Медия",
    "Media item is no longer available": "Това съдържание вече не е достъпно",
    "Media Library": "Медийна библиотека",
    "Media Library URL": "URL на медиятеката",
    Menu: "Меню",
    "Menu items settings": "Настройки на елементите на менюто",
    "Move category down": "Преместване на категорията надолу",
    "Move category up": "Преместване на категорията нагоре",
    "Move channel down": "Премести канала надолу",
    "Move channel up": "Премести канала нагоре",
    "m3u-m3u8 playlists": "Плейлисти m3u-m3u8",
    medium: "среден",
    min: "мин",
    "New Look": "New Look",
    "New Look settings": "Настройки за New Look",
    "New list name": "Име на новия списък",
    Next: "Следваща страница",
    "Next keyboard page": "Следваща страница на клавиатурата",
    "Next TV program": "Следващо предаване",
    No: "Не",
    "No channel name": "Без име на канал",
    "No saved settings found": "Няма намерени запазени настройки",
    "Not found": "Не е намерено",
    "Not reduce video when showing the list (bugfix)":
        "Без намаляване на видеото при показване на списъка (корекция)",
    Nothing: "Нищо",
    "Number of next TV programs in channel list":
        "Брой следващи предавания в списъка с канали",
    "Number of rows in lists": "Брой редове в списъците",
    native: "роден",
    no: "не",
    "no epg at current time": "Няма програма за текущия час",
    "not set": "не е зададено",
    Off: "Изключено",
    Ok: "ОК",
    Open: "Отваряне",
    "Open in PiP": "Отвори в PiP",
    "OTT Prime ONLINE": "OTT Prime ONLINE",
    "OTT Prime ONLINE settings": "Настройки за OTT Prime ONLINE",
    "OttPlay FOSS %1 is available. Download and install now?":
        "Налична е версия OttPlay FOSS %1. Да се изтегли и инсталира сега?",
    "Overwrite current settings?": "Да се презапишат ли текущите настройки?",
    off: "изключено",
    on: "включено",
    "on ": "при ",
    "or scan": "или сканирайте",
    "Parental control": "Родителски контрол",
    Password: "Парола",
    Pause: "Пауза",
    "Pause/Play": "Пауза / възпроизвеждане",
    "Permanent clock on screen": "Постоянен часовник на екрана",
    PIN: "PIN",
    "PiP exchange": "Размяна на прозорците PiP",
    "PiP window position": "Позиция на прозореца PiP",
    "PiP window size": "Размер на прозореца PiP",
    Play: "Възпроизвеждане",
    "Player and device info": "Информация за плейъра и устройството",
    "Player info:": "Информация за плейъра:",
    Playlist: "Плейлист",
    "Playlist file": "Файл на плейлиста",
    "Playlist is not loading directly...Loading via server...":
        "Плейлистът не се зарежда директно...Зареждане чрез сървъра...",
    "Playlist Name": "Име на плейлиста",
    "Playlist URL": "URL на плейлиста",
    POLMEDIA: "POLMEDIA",
    "POLMEDIA settings": "Настройки за POLMEDIA",
    "Portal URL": "URL на портала",
    "Position shift -10 seconds after pause": "Връщане с 10 секунди след пауза",
    PROST: "PROST",
    "PROST settings": "Настройки за PROST",
    Prev: "Предишна",
    "Preview in channel list": "Преглед в списъка с канали",
    Previous: "Предишен канал",
    "Privacy policy": "Политика за поверителност",
    "Protect Adult Channels": "Защита на каналите за възрастни",
    "Protect Change Provider": "Защита на смяната на доставчика",
    "Protect Settings": "Защита на настройките",
    "p...": "п…",
    paging: "прелистване",
    Quality: "Качество",
    Rating: "Рейтинг",
    RD: "RD",
    "RD settings": "Настройки за RD",
    "Reconnecting…": "Повторно свързване…",
    Records: "Записи",
    "Records for channel: ": "Записи за канал: ",
    "Records library is empty": "Библиотеката със записи е празна",
    "Records not supported by provider": "Доставчикът не поддържа записи",
    "Release date": "Дата на излизане",
    "Remember previous channels": "Запомняне на предишните канали",
    "Reminder: %1 — %2 in %3 min": "Напомняне: %1 — %2 след %3 мин",
    "Remote (color buttons N/A)": "Дистанционно без цветни бутони",
    "Remote (number buttons N/A)": "Дистанционно без цифрови бутони",
    "Remote control": "Дистанционно управление",
    "Remote session expired": "Сесията за дистанционен достъп изтече",
    "Remote text entry denied": "Дистанционното въвеждане на текст е забранено",
    "Remote text entry error": "Грешка при дистанционно въвеждане на текст",
    "Remote text entry not configured":
        "Дистанционното въвеждане на текст не е настроено",
    "Remote text entry requires a Device ID. Ask the server operator to provision one.":
        "Дистанционното въвеждане на текст изисква ID на устройство. Помолете администратора на сървъра да го предостави.",
    "Remove timer?": "Да се премахне ли таймерът?",
    Rename: "Преименуване",
    "Rename category": "Преименуване на категорията",
    "Rename to": "Преименуване на",
    "Repeat parental code": "Повторете родителския код",
    "Request sended!": "Заявката е изпратена!",
    "Restart player": "Рестартиране на плейъра",
    "Restart stream": "Рестартиране на потока",
    "Restart stream / Live": "Рестартиране на потока / на живо",
    "Resume from archive?": "Да се продължи ли от архива?",
    "Return to previous channel": "Връщане към предишния канал",
    Rewind: "Превъртане",
    "Rewind step by buttons %1/%2": "Стъпка на превъртане с бутоните %1/%2",
    RUSSKOETV: "RUSSKOETV",
    "RUSSKOETV settings": "Настройки за RUSSKOETV",
    Russian: "Руски",
    right: "вдясно",
    Saturation: "Наситеност",
    "Save & load channels": "Запазване и зареждане на каналите",
    "Save and load": "Запазване и зареждане",
    "Save and load channels": "Запазване и зареждане на каналите",
    "Save Settings": "Запази настройките",
    "Save settings": "Запазване на настройките",
    "Save settings and load channel list":
        "Запазване на настройките и зареждане на списъка с канали",
    "Save settings to storage": "Запазване на настройките в хранилището",
    Script: "Сценарий",
    Search: "Търсене",
    "Search programme": "Търсене на предаване",
    "Select a stream type:<br>%1": "Изберете тип поток:<br>%1",
    "Select category to add channel": "Изберете категория за добавяне на канал",
    "Select color": "Изберете цвят",
    "Select menu items": "Изберете елементи от менюто",
    "Select playlist": "Изберете плейлист",
    "Select playlist file": "Изберете файл на плейлиста",
    "Select playlist template source for EPG and logos":
        "Изберете шаблон на плейлист за програмата и логата",
    "Send request": "Изпращане на заявка",
    "Send settings": "Изпращане на настройки",
    "Send this code from your proxy in the Authorization: Bearer header.":
        "Изпращайте този код от проксито в заглавката Authorization: Bearer.",
    Server: "Сървър",
    "Server address": "Адрес на сървъра",
    "Server address (for example 192.168.1.20:8081)":
        "Адрес на сървъра (например 192.168.1.20:8081)",
    "Server device access code": "Код за достъп на устройството от сървъра",
    "Server URL": "URL на сървъра",
    "Server unavailable. Retrying automatically; check its address and network access.":
        "Сървърът не е достъпен. Опитът се повтаря автоматично; проверете адреса и мрежовия достъп.",
    Set: "Задаване",
    "Set parental code": "Задайте родителски код",
    "Set timer?": "Да се зададе ли таймер?",
    Settings: "Настройки",
    "Settings could not be saved": "Настройките не можаха да бъдат запазени",
    "Settings loaded from storage": "Настройките са заредени от хранилището",
    "Settings STB": "Настройки на STB",
    "Settings saved": "Настройките са запазени",
    "Settings saved to storage": "Настройките са запазени в хранилището",
    "Settings sended!": "Настройките са изпратени!",
    "Shara.club (ClubTV.pro)": "Shara.club (ClubTV.pro)",
    "Shara.club (ClubTV.pro) settings": "Настройки за Shara.club (ClubTV.pro)",
    ShockTv: "ShockTv",
    "ShockTv settings": "Настройки за ShockTv",
    "Show archive availability in list":
        "Показване на наличния архив в списъка",
    "Show channel name in list": "Показване на името на канала в списъка",
    "Show channel number in list": "Показване на номера на канала в списъка",
    "Show channel selection list": "Показване на списъка за избор на канали",
    "Show description": "Показване на описанието",
    "Show EPG and archive for channel":
        "Показване на програмата и архива на канала",
    "Show list of channel archive records": "Показване на записите на канала",
    "Show list of channel archive records without duplication":
        "Показване на записите на канала без повторения",
    "Show Media Library": "Показване на медийната библиотека",
    "Show picons in channel list": "Показване на иконите на каналите в списъка",
    "Show player menu": "Показване на менюто на плейъра",
    "Show program name": "Показване на името на предаването",
    "Show progress in channel list":
        "Показване на напредъка в списъка с канали",
    "Show provider settings?": "Да се покажат ли настройките на доставчика?",
    "Show providers?": "Да се покажат ли доставчиците?",
    "Show rewind window": "Показване на прозореца за превъртане",
    "Show scrollbar in list": "Показване на лентата за превъртане в списъците",
    "Show thumbnails": "Показване на миниатюри",
    "Show when changing program": "Показване при смяна на предаването",
    "Show when rewind": "Показване при превъртане",
    "Show when switching": "Показване при смяна на канала",
    "Sleep timer": "Таймер за заспиване",
    "Sort channels": "Сортиране на канали",
    "Stalker Portal Provider": "Доставчик на портал Stalker",
    "Stalker portal settings": "Настройки на портала Stalker",
    "Stalker portals": "Портали Stalker",
    Status: "Състояние",
    "Stop playback and return to live":
        "Спиране на възпроизвеждането и връщане на живо",
    "Stream type: %1": "Тип поток: %1",
    "String for search": "Текст за търсене",
    "Su Mo Tu We Th Fr Sa": "Нд Пн Вт Ср Чт Пт Сб",
    Subtitle: "Субтитри",
    Switch: "Превключване",
    "Switch sound track": "Смяна на аудиопистата",
    "Switch subtitle": "Смяна на субтитрите",
    "Switch to this list": "Превключване към този списък",
    "Swop URL": "URL на Swop",
    "saved on this device": "запазено на това устройство",
    select: "избор",
    small: "малък",
    system: "системен",
    Tabox: "Tabox",
    "Tabox settings": "Настройки за Tabox",
    "The device ID in the address is invalid.":
        "ID на устройството в адреса е невалиден.",
    "This HTTPS player cannot connect to an HTTP server. Use an HTTPS server or open the player over HTTP.":
        "Този HTTPS плейър не може да се свърже с HTTP сървър. Използвайте HTTPS сървър или отворете плейъра чрез HTTP.",
    "This Play app requires HTTPS. Ask your provider for an HTTPS playlist or server URL.":
        "Тази версия от Play изисква HTTPS. Поискайте от доставчика HTTPS адрес за плейлист или сървър.",
    Timer: "Таймер",
    "Timer: switch to channel?": "Таймер: да се превключи ли каналът?",
    "Timeshift: one minute back": "Отложено гледане: една минута назад",
    "Timeshift: to start of TV program":
        "Отложено гледане: към началото на предаването",
    Timezone: "Часова зона",
    TMDb: "TMDb",
    "TOP-IPTV": "TOP-IPTV",
    "TOP-IPTV settings": "Настройки за TOP-IPTV",
    "To begining": "Към началото",
    "To start of TV program / Previous TV program":
        "Към началото на предаването / предишно предаване",
    "Toggle Aspect Ratio": "Смяна на съотношението на страните",
    "Toggle on-screen debug HUD":
        "Показване или скриване на диагностичния панел",
    "Toggle Zoom Mode": "Смяна на режима на мащабиране",
    "Top-Tv": "Top-Tv",
    "Top-Tv settings": "Настройки за Top-Tv",
    "Try demo": "Изпробване на демото",
    "TV DOSUG": "TV DOSUG",
    "TV DOSUG settings": "Настройки за TV DOSUG",
    TVClub: "TVClub",
    "TVClub settings": "Настройки за TVClub",
    "Type of player for streaming": "Тип плейър за стрийминг",
    "top-left": "горе вляво",
    "top-right": "горе вдясно",
    transparent: "прозрачен",
    ULTIFL1X: "ULTIFL1X",
    "ULTIFL1X settings": "Настройки за ULTIFL1X",
    "Update installed. Please restart OttPlay FOSS.":
        "Обновяването е инсталирано. Рестартирайте OttPlay FOSS.",
    "Use an HTTP or HTTPS server address.":
        "Използвайте HTTP или HTTPS адрес на сървъра.",
    "Use HTTP or HTTPS without a username or password in the address.":
        "Използвайте HTTP или HTTPS без потребителско име и парола в адреса.",
    "Use LEFT/RIGHT to select a control, OK to activate, and UP/DOWN to scroll.":
        "НАЛЯВО/НАДЯСНО — избор на елемент, OK — активиране, НАГОРЕ/НАДОЛУ — превъртане.",
    Username: "Потребителско име",
    "Username or password is missing.": "Липсва потребителско име или парола.",
    "VIP-IP.COM": "VIP-IP.COM",
    "VIP-IP.COM settings": "Настройки за VIP-IP.COM",
    "Vidok.TV": "Vidok.TV",
    "Vidok.TV settings": "Настройки за Vidok.TV",
    "VOD not supported by provider": "Доставчикът не поддържа видео по заявка",
    "Volume step, %": "Стъпка на силата на звука, %",
    "VPortal link": "Връзка VPortal",
    "VPortal request failed":
        "Неуспешно зареждане на VPortal. Проверете връзката, ключа за достъп и достъпността на портала.",
    volume: "сила на звука",
    "Wrong parental code !!!": "Грешен родителски код!!!",
    "Xtream Codes Provider": "Доставчик Xtream Codes",
    "Xtream Codes settings": "Настройки на Xtream Codes",
    Year: "Година",
    Yellow: "Жълт",
    Yes: "Да",
    yes: "да",
    "Гомельсат (cbilling)": "Гомельсат (cbilling)",
    "Гомельсат (cbilling) settings": "Настройки за Гомельсат (cbilling)",
    МойДом: "МойДом",
    "МойДом settings": "Настройки за МойДом",
    "Ошибка обработки списка каналов! Проверьте правильность данных!!":
        "Грешка при обработка на списъка с канали! Проверете данните на доставчика!",
    Радуга: "Радуга",
    "Радуга settings": "Настройки за Радуга",
    "Редактирование ID": "Редактиране на ID",
    "Редактирование PIN": "Редактиране на PIN",
    Шаравоз: "Шаравоз",
    "Шаравоз settings": "Настройки за Шаравоз",
    "↑↓ Scroll": "↑↓ Превъртане",
};
