var keyStrings = {
    " (after changing, load playlist)": " (след промяна, заредете плейлиста)",
    " added to category ": " добавен към категория ",
    " added to favorites": " добавен към любими",
    "??? No channel name": "??? Без име на канал",
    Actions: "Действия",
    "Add channel to category": "Добави канал към категория",
    "Add channel to favorites": "Добави канал към любими",
    All: "Всички",
    "Archive hours": "Часове архив",
    alhabet: "абвгдежзийклмнопрстуфхцчшщъьюя",
    "Buffer Size, s": "Размер на буфера, с",
    "built-in": "вграден",
    Category: "Категория",
    "Channel ": "Канал ",
    "Channel is not available!!!": "Каналът не е достъпен!!!",
    "Channel list": "Списък на каналите",
    "Channel list not received !!!": "Списъкът с канали не е получен!!!",
    "Channel list not received !!!<br/><br/>Enter the provider data and restart the player !!!<br/><br/>":
        "Списъкът с канали не е получен!!!<br/><br/>Въведете данните на доставчика и рестартирайте плейъра!!!<br/><br/>",
    "Channel list. Category: ": "Списък на каналите. Категория: ",
    "Channel parental control": "Родителски контрол на канала",
    Close: "Затвори",
    "Delete channel": "Изтрий канал",
    Description: "Описание",
    Edit: "Редактирай",
    "Edit category name": "Редактирай име на категория",
    "Edit playlist data": "Редактирай данни на плейлиста",
    Editor: "Редактор",
    "Enter Media Library URL": "Въведете URL на медиятеката",
    "Enter parental code": "Въведете родителски код",
    "Enter playlist archive hours": "Въведете часове архив за плейлиста",
    "Enter playlist Name": "Въведете име на плейлиста",
    "Enter playlist URL": "Въведете URL на плейлиста",
    EPG: "ТВ програма",
    Exit: "Изход",
    "Failed to load channel list!": "Грешка при зареждане на списъка с канали!",
    Favorites: "Любими",
    Info: "Инфо",
    Load: "Зареди",
    "Load playlist": "Зареди плейлист",
    lang: "Български",
    "Media Library URL": "URL на медиятеката",
    Menu: "Меню",
    "Move channel down": "Премести канала надолу",
    "Move channel up": "Премести канала нагоре",
    "m3u-m3u8 playlists": "Плейлисти m3u-m3u8",
    min: "мин",
    "No channel name": "Без име на канал",
    Nothing: "Нищо",
    native: "роден",
    no: "не",
    "Open in PiP": "Отвори в PiP",
    off: "изключено",
    Playlist: "Плейлист",
    "Playlist file": "Файл на плейлиста",
    "Playlist is not loading directly...Loading via server...":
        "Плейлистът не се зарежда директно...Зареждане чрез сървъра...",
    "Playlist Name": "Име на плейлиста",
    "Playlist URL": "URL на плейлиста",
    "Save Settings": "Запази настройките",
    Search: "Търсене",
    "Select category to add channel": "Изберете категория за добавяне на канал",
    "Select playlist": "Изберете плейлист",
    "Select playlist file": "Изберете файл на плейлиста",
    Settings: "Настройки",
    "Settings STB": "Настройки на STB",
    "Settings saved": "Настройките са запазени",
    "Stalker portals": "Портали Stalker",
    "Type of player for streaming": "Тип плейър за стрийминг",
    "Wrong parental code !!!": "Грешен родителски код!!!",
    yes: "да",
};
