var keyStrings = {
    " (after changing, load playlist)":
        " (herlaad de afspeellijst na wijziging)",
    " (after changing, restart player)": " (herstart de speler na wijziging)",
    " added to category ": " toegevoegd aan categorie ",
    " added to favorites": " toegevoegd aan favorieten",
    " m ": " min ",
    " s": " s",
    "??? No channel name": "??? Geen zendernaam",
    '"As Is"': '"Ongewijzigd"',
    '"Favorites"': '"Favorieten"',
    '"Sliding" infobar': "Schuivende informatiebalk",
    "&darr;a": "&darr;a",
    "&uarr;A": "&uarr;A",
    "<br/><br/>In archive mode:<br/>": "<br/><br/>In archiefmodus:<br/>",
    "<br/>Loading STB...": "<br/>STB laden…",
    "<br/>Setup STB...": "<br/>STB instellen…",
    "<br>": "<br>",
    "<br><br>": "<br><br>",
    "<br>Add<br>to category": "<br>Toevoegen<br>aan categorie",
    "<br>Add<br>to favorites": "<br>Toevoegen<br>aan favorieten",
    "<br>Delete": "<br>Verwijderen",
    "<br>Down<br>": "<br>Omlaag<br>",
    "<br>Live": "<br>Live",
    "<br>Menu": "<br>Menu",
    "<br>Parental<br>Control": "<br>Ouderlijk<br>toezicht",
    "<br>Pause<br>": "<br>Pauze<br>",
    "<br>Previous<br>channel": "<br>Vorige<br>zender",
    "<br>Rewind<br>": "<br>Terugspoelen<br>",
    "<br>Toggle<br>sound track": "<br>Audiospoor<br>wisselen",
    "<br>Up<br>": "<br>Omhoog<br>",
    "1 hour": "1 uur",
    "1 minute": "1 minuut",
    "2 hours": "2 uur",
    "3 hours": "3 uur",
    "10 Seconds": "10 seconden",
    "30 minutes": "30 minuten",
    "A command expired while the player was loading channels.":
        "Een opdracht is verlopen terwijl de speler zenders laadde.",
    "A command was rejected by the player. Check its provider and settings.":
        "De speler heeft een opdracht geweigerd. Controleer de provider en instellingen.",
    About: "Over",
    "Access code": "Toegangscode",
    "Access denied. Check the server access code.":
        "Toegang geweigerd. Controleer de toegangscode van de server.",
    "Access key": "Toegangssleutel",
    "Access key is required!": "Toegangssleutel vereist!",
    "Access settings": "Toegangsinstellingen",
    Actions: "Acties",
    "Active list": "Actieve lijst",
    Actors: "Acteurs",
    "Add / rename / delete…": "Toevoegen / hernoemen / verwijderen…",
    "Add channel to category": "Zender aan categorie toevoegen",
    "Add channel to favorites": "Zender aan favorieten toevoegen",
    "Add new list": "Nieuwe lijst toevoegen",
    "Add to favorites": "Aan favorieten toevoegen",
    Age: "Leeftijd",
    All: "Alles",
    "All categories": "Alle categorieën",
    "All4you.tv": "All4you.tv",
    "All4you.tv settings": "Instellingen voor All4you.tv",
    "Allowlist this Device ID": "Deze apparaat-ID toestaan",
    "An IP without a port uses HTTP port 8081. Clear the address or select Disconnect to stop.":
        "Een IP-adres zonder poort gebruikt HTTP-poort 8081. Wis het adres of kies Verbinding verbreken om te stoppen.",
    "API failed, trying M3U...": "API mislukt, M3U proberen…",
    "API Server": "API-server",
    "API server URL": "URL van API-server",
    "Applying HTTP remote settings...":
        "Instellingen voor HTTP-afstandsbediening toepassen…",
    Archive: "Archief",
    "Archive - begin": "Archief — begin",
    "Archive hours": "Archiefuren",
    "Archive: ENTER on past programs": "Archief: ENTER bij eerdere programma's",
    "Archive. Channel: ": "Archief. Zender: ",
    Aspect: "Beeldverhouding",
    Audio: "Audio",
    alhabet: "aáäbcdeéëfghiíïj́klmnoóöpqrstuúüvwxyz",
    always: "altijd",
    "and enter code": "en voer de code in",
    Back: "Terug",
    "Back / Forward for 1 minute": "1 minuut terug / vooruit",
    "Background color": "Achtergrondkleur",
    "Background color of selected item":
        "Achtergrondkleur van geselecteerd item",
    "BEST LiST IPTV [HLS Playlist]": "BEST LiST IPTV [HLS Playlist]",
    "BEST LiST IPTV [HLS Playlist] settings":
        "Instellingen voor BEST LiST IPTV [HLS Playlist]",
    "BEST LiST IPTV [Stalker]": "BEST LiST IPTV [Stalker]",
    "BEST LiST IPTV [Stalker] settings":
        "Instellingen voor BEST LiST IPTV [Stalker]",
    "Behavior of %1/%2 buttons in lists":
        "Gedrag van de knoppen %1/%2 in lijsten",
    "Black screen while switching the channel": "Zwart scherm bij zenderwissel",
    Blue: "Blauw",
    "Bookmark age: %1 days": "Leeftijd van bladwijzer: %1 dagen",
    "Buffer Size, s": "Buffergrootte, s",
    "Built-in playlist:": "Ingebouwde afspeellijst:",
    "Built-in playlists": "Ingebouwde afspeellijsten",
    "Button %1 function when viewing": "Functie van knop %1 tijdens het kijken",
    "Button function %1 when viewing archive":
        "Functie van knop %1 tijdens archiefweergave",
    "Buttons settings": "Knopinstellingen",
    "By alphabet": "Alfabetisch",
    "By time": "Chronologisch",
    "begin/end": "begin/einde",
    "bottom-right": "rechtsonder",
    "built-in": "ingebouwd",
    "Call PiP": "PiP openen",
    "Call PiP / PiP exchange": "PiP openen / PiP wisselen",
    Cancel: "Annuleren",
    "Cannot delete the last category":
        "De laatste categorie kan niet worden verwijderd",
    Category: "Categorie",
    "Category selection": "Categorie kiezen",
    "Change interface language": "Interfacetaal wijzigen",
    "Change provider": "Provider wijzigen",
    "Change provider - you can change the provider, and it will be remembered at the next start of player!":
        "Wijzig de provider. Uw keuze wordt onthouden bij de volgende start van de speler.",
    "Change value": "Waarde wijzigen",
    "Channel ": "Zender ",
    "Channel has no EPG": "Zender heeft geen EPG",
    "Channel is not available!!!": "Zender niet beschikbaar!",
    "Channel link": "Zenderlink",
    "Channel link is required!": "Zenderlink vereist!",
    "Channel list": "Zenderlijst",
    "Channel list editing style": "Bewerkmodus voor zenderlijst",
    "Channel list not received !!!": "Zenderlijst niet ontvangen!",
    "Channel list not received !!!<br/><br/>Enter the provider data and restart the player !!!<br/><br/>":
        "Zenderlijst niet ontvangen!<br/><br/>Voer de providergegevens in en herstart de speler.<br/><br/>",
    "Channel list settings": "Zenderlijstinstellingen",
    "Channel list. Category: ": "Zenderlijst. Categorie: ",
    "Channel parental control": "Ouderlijk toezicht op zenders",
    Channels: "Zenders",
    "Choose from": "Kiezen uit",
    "Choose language": "Taal kiezen",
    "Choose provider": "Provider kiezen",
    Classic: "Klassiek",
    "Clear all settings?": "Alle instellingen wissen?",
    "Clear settings": "Instellingen wissen",
    Close: "Sluiten",
    "Close PiP": "PiP sluiten",
    Color: "Kleur",
    "Color spectrum": "Kleurenspectrum",
    "Command server": "Opdrachtserver",
    "Command server address, device access code, local HTTP control, and remote text entry settings":
        "Adres van opdrachtserver, toegangscode voor apparaat, lokale HTTP-bediening en tekstinvoer op afstand",
    "Configure All4you.tv in Settings -> Provider Settings":
        "Configureer All4you.tv via Instellingen -> Providerinstellingen",
    "Configure BEST LiST IPTV [HLS Playlist] in Settings -> Provider Settings":
        "Configureer BEST LiST IPTV [HLS Playlist] via Instellingen -> Providerinstellingen",
    "Configure BEST LiST IPTV [Stalker] in Settings -> Provider Settings":
        "Configureer BEST LiST IPTV [Stalker] via Instellingen -> Providerinstellingen",
    "Configure Diamond TV in Settings -> Provider Settings":
        "Configureer Diamond TV via Instellingen -> Providerinstellingen",
    "Configure DRVAO in Settings -> Provider Settings":
        "Configureer DRVAO via Instellingen -> Providerinstellingen",
    "Configure Dragon Media PRO in Settings -> Provider Settings":
        "Configureer Dragon Media PRO via Instellingen -> Providerinstellingen",
    "Configure Fabryka.TV in Settings -> Provider Settings":
        "Configureer Fabryka.TV via Instellingen -> Providerinstellingen",
    "Configure Fox-TV in Settings -> Provider Settings":
        "Configureer Fox-TV via Instellingen -> Providerinstellingen",
    "Configure FXML in Settings -> Provider Settings":
        "Configureer FXML via Instellingen -> Providerinstellingen",
    "Configure GlanzTV in Settings -> Provider Settings":
        "Configureer GlanzTV via Instellingen -> Providerinstellingen",
    "Configure GREAT IPTV in Settings -> Provider Settings":
        "Configureer GREAT IPTV via Instellingen -> Providerinstellingen",
    "Configure IpStream.one in Settings -> Provider Settings":
        "Configureer IpStream.one via Instellingen -> Providerinstellingen",
    "Configure KORONA TV in Settings -> Provider Settings":
        "Configureer KORONA TV via Instellingen -> Providerinstellingen",
    "Configure MaxTV in Settings -> Provider Settings":
        "Configureer MaxTV via Instellingen -> Providerinstellingen",
    "Configure New Look in Settings -> Provider Settings":
        "Configureer New Look via Instellingen -> Providerinstellingen",
    "Configure OTT Prime ONLINE in Settings -> Provider Settings":
        "Configureer OTT Prime ONLINE via Instellingen -> Providerinstellingen",
    "Configure POLMEDIA in Settings -> Provider Settings":
        "Configureer POLMEDIA via Instellingen -> Providerinstellingen",
    "Configure PROST in Settings -> Provider Settings":
        "Configureer PROST via Instellingen -> Providerinstellingen",
    "Configure RD in Settings -> Provider Settings":
        "Configureer RD via Instellingen -> Providerinstellingen",
    "Configure RUSSKOETV in Settings -> Provider Settings":
        "Configureer RUSSKOETV via Instellingen -> Providerinstellingen",
    "Configure Shara.club (ClubTV.pro) in Settings -> Provider Settings":
        "Configureer Shara.club (ClubTV.pro) via Instellingen -> Providerinstellingen",
    "Configure ShockTv in Settings -> Provider Settings":
        "Configureer ShockTv via Instellingen -> Providerinstellingen",
    "Configure Tabox in Settings -> Provider Settings":
        "Configureer Tabox via Instellingen -> Providerinstellingen",
    "Configure TOP-IPTV in Settings -> Provider Settings":
        "Configureer TOP-IPTV via Instellingen -> Providerinstellingen",
    "Configure Top-Tv in Settings -> Provider Settings":
        "Configureer Top-Tv via Instellingen -> Providerinstellingen",
    "Configure TV DOSUG in Settings -> Provider Settings":
        "Configureer TV DOSUG via Instellingen -> Providerinstellingen",
    "Configure TVClub in Settings -> Provider Settings":
        "Configureer TVClub via Instellingen -> Providerinstellingen",
    "Configure ULTIFL1X in Settings -> Provider Settings":
        "Configureer ULTIFL1X via Instellingen -> Providerinstellingen",
    "Configure VIP-IP.COM in Settings -> Provider Settings":
        "Configureer VIP-IP.COM via Instellingen -> Providerinstellingen",
    "Configure Vidok.TV in Settings -> Provider Settings":
        "Configureer Vidok.TV via Instellingen -> Providerinstellingen",
    "Configure Гомельсат (cbilling) in Settings -> Provider Settings":
        "Configureer Гомельсат (cbilling) via Instellingen -> Providerinstellingen",
    "Configure МойДом in Settings -> Provider Settings":
        "Configureer МойДом via Instellingen -> Providerinstellingen",
    "Configure Радуга in Settings -> Provider Settings":
        "Configureer Радуга via Instellingen -> Providerinstellingen",
    "Configure Шаравоз in Settings -> Provider Settings":
        "Configureer Шаравоз via Instellingen -> Providerinstellingen",
    Connect: "Verbinden",
    Connected: "Verbonden",
    "Connected. Waiting for the channel list...":
        "Verbonden. Wachten op de zenderlijst…",
    "Connecting to Stalker portal...": "Verbinden met Stalker-portaal…",
    "Connecting...": "Verbinden…",
    "Continue watching?": "Verder kijken?",
    "Copy category": "Categorie kopiëren",
    "Copy JSON": "JSON kopiëren",
    "Could not connect to the server.":
        "Kan geen verbinding maken met de server.",
    "Could not update HTTP remote control.":
        "Kan HTTP-afstandsbediening niet bijwerken.",
    Country: "Land",
    "Create category": "Categorie maken",
    current: "huidig",
    "Debug HUD": "Debugpaneel",
    "Debug HUD is not available": "Debugpaneel niet beschikbaar",
    Delete: "Verwijderen",
    "Delete category": "Categorie verwijderen",
    "Delete channel": "Zender verwijderen",
    "Delete list": "Lijst verwijderen",
    "Demo — moving test pattern": "Demo — bewegend testbeeld",
    Description: "Beschrijving",
    "Description of remote control buttons":
        "Uitleg van afstandsbedieningsknoppen",
    "Device access code": "Toegangscode voor apparaat",
    "Device info:": "Apparaatgegevens:",
    "Device MAC is required for KBC (Kinoboom) playlists":
        "Voor KBC-afspeellijsten (Kinoboom) is het MAC-adres van het apparaat vereist",
    "Diamond TV": "Diamond TV",
    "Diamond TV settings": "Instellingen voor Diamond TV",
    Director: "Regisseur",
    "Disable HTTP remote": "HTTP-afstandsbediening uitschakelen",
    "Disabled by default. Enabling creates a new device access code.":
        "Standaard uitgeschakeld. Inschakelen maakt een nieuwe toegangscode voor het apparaat aan.",
    Disconnect: "Verbinding verbreken",
    Disconnected: "Niet verbonden",
    "Distance between lines in lists": "Regelafstand in lijsten",
    "Do you want to exit player?": "Wilt u de speler afsluiten?",
    "Download! Wait ...": "Downloaden… even geduld…",
    DRVAO: "DRVAO",
    "DRVAO settings": "Instellingen voor DRVAO",
    "Dragon Media PRO": "Dragon Media PRO",
    "Dragon Media PRO settings": "Instellingen voor Dragon Media PRO",
    Duration: "Duur",
    Edit: "Bewerken",
    "Edit access key": "Toegangssleutel bewerken",
    "Edit category name": "Categorienaam bewerken",
    "Edit channel link": "Zenderlink bewerken",
    "Edit playlist data": "Afspeellijstgegevens bewerken",
    "Edit VPortal link": "VPortal-link bewerken",
    Editor: "Editor",
    "Enable HTTP remote": "HTTP-afstandsbediening inschakelen",
    English: "Engels",
    "Enter a password (8 characters).": "Voer een wachtwoord in (8 tekens).",
    "Enter a playlist URL to access this service.":
        "Voer een afspeellijst-URL in om deze dienst te gebruiken.",
    "Enter a server address without spaces or a fragment.":
        "Voer een serveradres zonder spaties of fragment in.",
    "Enter a username (8 characters).":
        "Voer een gebruikersnaam in (8 tekens).",
    "Enter a username and password to access this service.":
        "Voer een gebruikersnaam en wachtwoord in om deze dienst te gebruiken.",
    "Enter a valid server address, for example 192.168.1.20:8081.":
        "Voer een geldig serveradres in, bijvoorbeeld 192.168.1.20:8081.",
    "Enter access key for": "Toegangssleutel invoeren voor",
    "Enter an application access key (8 characters).":
        "Voer een toegangssleutel voor toepassingen in (8 tekens).",
    "Enter an ID and PIN to access this service.":
        "Voer een ID en pincode in om deze dienst te gebruiken.",
    "Enter an IPTV token (10 characters).":
        "Voer een IPTV-token in (10 tekens).",
    "Enter category name": "Categorienaam invoeren",
    "Enter MAC address": "MAC-adres invoeren",
    "Enter MAC address (e.g. 00:1A:2B:3C:4D:5E)":
        "MAC-adres invoeren (bijv. 00:1A:2B:3C:4D:5E)",
    "Enter Media Library URL": "URL van mediabibliotheek invoeren",
    "Enter new category name": "Nieuwe categorienaam invoeren",
    "Enter Provider Code": "Providercode invoeren",
    "Enter Provider Code on PC or Phone":
        "Providercode op pc of telefoon invoeren",
    "Enter parental code": "Ouderlijke code invoeren",
    "Enter password": "Wachtwoord invoeren",
    "Enter playlist archive hours": "Archiefuren van afspeellijst invoeren",
    "Enter playlist Name": "Naam van afspeellijst invoeren",
    "Enter playlist URL": "URL van afspeellijst invoeren",
    "Enter Stalker portal URL": "URL van Stalker-portaal invoeren",
    "Enter Stalker portal URL (e.g. http://your-portal:8800)":
        "URL van Stalker-portaal invoeren (bijv. http://your-portal:8800)",
    "Enter Stalker portal URL (e.g. http://your-portal/stalker_portal/c/)":
        "URL van Stalker-portaal invoeren (bijv. http://your-portal/stalker_portal/c/)",
    "Enter the access code separately, not in the server address.":
        "Voer de toegangscode apart in, niet in het serveradres.",
    "Enter the command server IP or address.":
        "Voer het IP-adres of adres van de opdrachtserver in.",
    "Enter the full CDN host from the cabinet stream URL (e.g. subdomain.cdn-domain.tld), not a bare subdomain":
        "Voer de volledige CDN-host uit de stream-URL in het klantportaal in (bijv. subdomain.cdn-domain.tld), niet alleen een subdomein",
    "Enter the server IP or address and this player's device access code from the server configuration. Saving both starts checking for volume, channel and other commands automatically.":
        "Voer het IP-adres of adres van de server en de toegangscode van deze speler uit de serverconfiguratie in. Na het opslaan worden volume-, zender- en andere opdrachten automatisch opgehaald.",
    "Enter the server's device access code (32–256 letters, digits, _ or -).":
        "Voer de toegangscode voor het apparaat van de server in (32–256 letters, cijfers, _ of -).",
    'Enter the tv.team playlist URL.<br>Playlist type: <b>OTTPlayer</b><br/><br/>The "/playlist.m3u8" suffix is added automatically if omitted.':
        'Voer de URL van de tv.team-afspeellijst in.<br>Type afspeellijst: <b>OTTPlayer</b><br/><br/>Het achtervoegsel "/playlist.m3u8" wordt automatisch toegevoegd als het ontbreekt.',
    "Enter the VPortal link as shown in the cabinet":
        "Voer de VPortal-link in zoals weergegeven in het klantportaal",
    "Enter this link in VPortal link. Playlist URL requires an M3U playlist.":
        "Voer deze link in bij VPortal-link. De afspeellijst-URL vereist een M3U-afspeellijst.",
    "Enter this player's device access code to connect.":
        "Voer de toegangscode van deze speler in om te verbinden.",
    "Enter username": "Gebruikersnaam invoeren",
    "Enter value": "Waarde invoeren",
    "Enter Xtream server URL": "URL van Xtream-server invoeren",
    "Enter Xtream server URL (e.g. https://your-server:8080)":
        "URL van Xtream-server invoeren (bijv. https://your-server:8080)",
    EPG: "EPG",
    "EPG and archive. Channel: ": "EPG en archief. Zender: ",
    "ERROR!": "Fout!",
    "Error Code!": "Ongeldige code!",
    Exit: "Afsluiten",
    "Exit player": "Speler afsluiten",
    "Export settings": "Instellingen exporteren",
    "epg.one (Ordered)": "epg.one (gesorteerd)",
    "epg.one (Standard)": "epg.one (standaard)",
    "epg.one (Thematic)": "epg.one (thematisch)",
    "epgs...": "EPG's…",
    "Fabryka.TV": "Fabryka.TV",
    "Fabryka.TV settings": "Instellingen voor Fabryka.TV",
    "Failed to connect to Stalker portal":
        "Verbinding met Stalker-portaal mislukt",
    "Failed to connect to Xtream API server":
        "Verbinding met Xtream-API-server mislukt",
    "Failed to get user data!!!": "Gebruikersgegevens ophalen mislukt!",
    "Failed to load channel list!": "Zenderlijst laden mislukt!",
    "Failed to load channels from Stalker portal":
        "Zenders laden vanaf Stalker-portaal mislukt",
    "Failed to load channels from Xtream API":
        "Zenders laden via Xtream-API mislukt",
    "Failed to load!": "Laden mislukt!",
    "Favorite lists": "Favorietenlijsten",
    Favorites: "Favorieten",
    "File selection is not supported on this device":
        "Bestandsselectie wordt niet ondersteund op dit apparaat",
    Filters: "Filters",
    "First Run Setup": "Eerste configuratie",
    "Font type": "Lettertype",
    "For download settings file open":
        "Open voor het downloaden van het instellingenbestand",
    "For enter value open": "Open voor het invoeren van een waarde",
    "For upload settings file open":
        "Open voor het uploaden van het instellingenbestand",
    "Fox-TV": "Fox-TV",
    "Fox-TV settings": "Instellingen voor Fox-TV",
    FXML: "FXML",
    "FXML settings": "Instellingen voor FXML",
    Genre: "Genre",
    GlanzTV: "GlanzTV",
    "GlanzTV settings": "Instellingen voor GlanzTV",
    "Go to": "Ga naar",
    "GREAT IPTV": "GREAT IPTV",
    "GREAT IPTV settings": "Instellingen voor GREAT IPTV",
    "Graphical indication": "Grafische indicatoren",
    Green: "Groen",
    "Hide / Return": "Verbergen / tonen",
    "Hide provider settings?": "Providerinstellingen verbergen?",
    "Hide providers?": "Providers verbergen?",
    "History in Media Library": "Geschiedenis in mediabibliotheek",
    "History of watched movies": "Kijkgeschiedenis",
    "HTTP port": "HTTP-poort",
    "HTTP remote control is unavailable on this device.":
        "HTTP-afstandsbediening is niet beschikbaar op dit apparaat.",
    ID: "ID",
    "Import settings": "Instellingen importeren",
    "In live mode: <br/>": "In livemodus:<br/>",
    Info: "Info",
    "Infobar display timeout, s": "Weergaveduur van informatiebalk, s",
    "Infobar settings": "Instellingen van informatiebalk",
    Information: "Informatie",
    "Interface credits": "Credits van de interface",
    "Interface settings": "Interface-instellingen",
    "Interface theme": "Interfacethema",
    "Interface transparency": "Transparantie van interface",
    "Invalid channel link! Enter the full host as in the cabinet stream URL (e.g. subdomain.cdn-domain.tld)":
        "Ongeldige zenderlink! Voer de volledige host uit de stream-URL in het klantportaal in (bijv. subdomain.cdn-domain.tld)",
    "IPTV token": "IPTV-token",
    "IpStream.one": "IpStream.one",
    "IpStream.one settings": "Instellingen voor IpStream.one",
    Joystick: "Joystick",
    "KBC (Kinoboom) access data": "Toegangsgegevens voor KBC (Kinoboom)",
    "KORONA TV": "KORONA TV",
    "KORONA TV settings": "Instellingen voor KORONA TV",
    "List created": "Lijst gemaakt",
    "List deleted": "Lijst verwijderd",
    "List location": "Lijstpositie",
    "List renamed": "Lijst hernoemd",
    "List type": "Lijsttype",
    "Lists settings": "Lijstinstellingen",
    Live: "Live",
    Load: "Laden",
    "Load built-in playlist:": "Ingebouwde afspeellijst laden:",
    "Load playlist": "Afspeellijst laden",
    "Load settings": "Instellingen laden",
    "Load settings from storage": "Instellingen uit opslag laden",
    "Load:": "Laden:",
    "Loading channels from Xtream API...": "Zenders laden via Xtream-API…",
    "Loading channels...": "Zenders laden…",
    "Loading from API...": "Laden via API…",
    "Loading from Edem API...": "Laden via Edem-API…",
    "Loading M3U playlist...": "M3U-afspeellijst laden…",
    "Loading M3U...": "M3U laden…",
    "Loading via proxy...": "Laden via proxy…",
    "Loading. Please wait...": "Laden… even geduld…",
    "Loading...": "Laden…",
    "Local HTTP remote control": "Lokale HTTP-afstandsbediening",
    "Local URL": "Lokale URL",
    Login: "Aanmelding",
    lang: "Nederlands",
    large: "groot",
    left: "links",
    "left-bottom": "linksonder",
    "logos...": "Logo's…",
    M3U: "M3U",
    "M3U URL": "M3U-URL",
    "M3U URL (fallback)": "M3U-URL (terugvaloptie)",
    "MAC address": "MAC-adres",
    "Manage lists": "Lijsten beheren",
    "Manage settings": "Instellingen beheren",
    "Manual setup": "Handmatige configuratie",
    MaxTV: "MaxTV",
    "MaxTV settings": "Instellingen voor MaxTV",
    Media: "Media",
    "Media item is no longer available": "Media-item is niet meer beschikbaar",
    "Media Library": "Mediabibliotheek",
    "Media Library URL": "URL van mediabibliotheek",
    Menu: "Menu",
    "Menu items settings": "Instellingen voor menu-items",
    "Move category down": "Categorie omlaag verplaatsen",
    "Move category up": "Categorie omhoog verplaatsen",
    "Move channel down": "Zender omlaag verplaatsen",
    "Move channel up": "Zender omhoog verplaatsen",
    "m3u-m3u8 playlists": "M3U-/M3U8-afspeellijsten",
    medium: "middel",
    min: "min",
    "New Look": "New Look",
    "New Look settings": "Instellingen voor New Look",
    "New list name": "Naam van nieuwe lijst",
    Next: "Volgende pagina",
    "Next keyboard page": "Volgende toetsenbordpagina",
    "Next TV program": "Volgend programma",
    No: "Nee",
    "No channel name": "Geen zendernaam",
    "No saved settings found": "Geen opgeslagen instellingen gevonden",
    "Not found": "Niet gevonden",
    "Not reduce video when showing the list (bugfix)":
        "Video niet verkleinen bij tonen van de lijst (foutoplossing)",
    Nothing: "Niets",
    "Number of next TV programs in channel list":
        "Aantal volgende programma's in zenderlijst",
    "Number of rows in lists": "Aantal rijen in lijsten",
    native: "systeemeigen",
    no: "nee",
    "no epg at current time": "Momenteel geen EPG",
    "not set": "niet ingesteld",
    Off: "Uit",
    Ok: "OK",
    Open: "Openen",
    "Open in PiP": "In PiP openen",
    "OTT Prime ONLINE": "OTT Prime ONLINE",
    "OTT Prime ONLINE settings": "Instellingen voor OTT Prime ONLINE",
    "OttPlay FOSS %1 is available. Download and install now?":
        "OttPlay FOSS %1 is beschikbaar. Nu downloaden en installeren?",
    "Overwrite current settings?": "Huidige instellingen overschrijven?",
    off: "uit",
    on: "aan",
    "on ": "aan ",
    "or scan": "of scan",
    "Parental control": "Ouderlijk toezicht",
    Password: "Wachtwoord",
    Pause: "Pauze",
    "Pause/Play": "Pauze / afspelen",
    "Permanent clock on screen": "Klok altijd op scherm tonen",
    PIN: "PIN",
    "PiP exchange": "PiP wisselen",
    "PiP window position": "Positie van PiP-venster",
    "PiP window size": "Grootte van PiP-venster",
    Play: "Afspelen",
    "Player and device info": "Speler- en apparaatgegevens",
    "Player info:": "Spelergegevens:",
    Playlist: "Afspeellijst",
    "Playlist file": "Afspeellijstbestand",
    "Playlist is not loading directly...Loading via server...":
        "Afspeellijst kon niet rechtstreeks worden geladen. Laden via server…",
    "Playlist Name": "Naam van afspeellijst",
    "Playlist URL": "URL van afspeellijst",
    POLMEDIA: "POLMEDIA",
    "POLMEDIA settings": "Instellingen voor POLMEDIA",
    "Portal URL": "Portaal-URL",
    "Position shift -10 seconds after pause":
        "Na pauze 10 seconden terugspringen",
    PROST: "PROST",
    "PROST settings": "Instellingen voor PROST",
    Prev: "Vorige",
    "Preview in channel list": "Voorbeeld in zenderlijst",
    Previous: "Vorige",
    "Privacy policy": "Privacybeleid",
    "Protect Adult Channels": "Volwassenenzenders beveiligen",
    "Protect Change Provider": "Providerwijziging beveiligen",
    "Protect Settings": "Instellingen beveiligen",
    "p...": "p...",
    paging: "paginagewijs",
    Quality: "Kwaliteit",
    Rating: "Beoordeling",
    RD: "RD",
    "RD settings": "Instellingen voor RD",
    "Reconnecting…": "Opnieuw verbinden…",
    Records: "Opnamen",
    "Records for channel: ": "Opnamen voor zender: ",
    "Records library is empty": "Opnamebibliotheek is leeg",
    "Records not supported by provider":
        "Opnamen worden niet ondersteund door deze provider",
    "Release date": "Verschijningsdatum",
    "Remember previous channels": "Vorige zenders onthouden",
    "Reminder: %1 — %2 in %3 min": "Herinnering: %1 — %2 over %3 min",
    "Remote (color buttons N/A)": "Afstandsbediening zonder kleurknoppen",
    "Remote (number buttons N/A)": "Afstandsbediening zonder cijferknoppen",
    "Remote control": "Afstandsbediening",
    "Remote session expired": "Externe sessie verlopen",
    "Remote text entry denied": "Tekstinvoer op afstand geweigerd",
    "Remote text entry error": "Fout bij tekstinvoer op afstand",
    "Remote text entry not configured":
        "Tekstinvoer op afstand niet geconfigureerd",
    "Remote text entry requires a Device ID. Ask the server operator to provision one.":
        "Tekstinvoer op afstand vereist een apparaat-ID. Vraag de serverbeheerder er een aan te maken.",
    "Remove timer?": "Timer verwijderen?",
    Rename: "Hernoemen",
    "Rename category": "Categorie hernoemen",
    "Rename to": "Hernoemen naar",
    "Repeat parental code": "Ouderlijke code opnieuw invoeren",
    "Request sended!": "Verzoek verzonden!",
    "Restart player": "Speler herstarten",
    "Restart stream": "Stream herstarten",
    "Restart stream / Live": "Stream herstarten / live",
    "Resume from archive?": "Hervatten vanuit archief?",
    "Return to previous channel": "Terug naar vorige zender",
    Rewind: "Spoelen",
    "Rewind step by buttons %1/%2": "Spoelstap voor knoppen %1/%2",
    RUSSKOETV: "RUSSKOETV",
    "RUSSKOETV settings": "Instellingen voor RUSSKOETV",
    Russian: "Russisch",
    right: "rechts",
    Saturation: "Verzadiging",
    "Save & load channels": "Opslaan en zenders laden",
    "Save and load": "Opslaan en laden",
    "Save and load channels": "Opslaan en zenders laden",
    "Save Settings": "Instellingen opslaan",
    "Save settings": "Instellingen opslaan",
    "Save settings and load channel list":
        "Instellingen opslaan en zenderlijst laden",
    "Save settings to storage": "Instellingen in opslag bewaren",
    Script: "Scenario",
    Search: "Zoeken",
    "Search programme": "Programma zoeken",
    "Select a stream type:<br>%1": "Kies een streamtype:<br>%1",
    "Select category to add channel":
        "Categorie kiezen om zender toe te voegen",
    "Select color": "Kleur kiezen",
    "Select menu items": "Menu-items kiezen",
    "Select playlist": "Afspeellijst kiezen",
    "Select playlist file": "Afspeellijstbestand kiezen",
    "Select playlist template source for EPG and logos":
        "Sjabloonbron voor EPG en logo's van afspeellijst kiezen",
    "Send request": "Verzoek verzenden",
    "Send settings": "Instellingen verzenden",
    "Send this code from your proxy in the Authorization: Bearer header.":
        "Verzend deze code vanuit uw proxy in de header Authorization: Bearer.",
    Server: "Server",
    "Server address": "Serveradres",
    "Server address (for example 192.168.1.20:8081)":
        "Serveradres (bijvoorbeeld 192.168.1.20:8081)",
    "Server device access code": "Toegangscode voor apparaat op server",
    "Server URL": "Server-URL",
    "Server unavailable. Retrying automatically; check its address and network access.":
        "Server niet beschikbaar. Automatisch opnieuw proberen; controleer het adres en de netwerktoegang.",
    Set: "Instellen",
    "Set parental code": "Ouderlijke code instellen",
    "Set timer?": "Timer instellen?",
    Settings: "Instellingen",
    "Settings could not be saved": "Instellingen konden niet worden opgeslagen",
    "Settings loaded from storage": "Instellingen geladen uit opslag",
    "Settings STB": "STB-instellingen",
    "Settings saved": "Instellingen opgeslagen",
    "Settings saved to storage": "Instellingen bewaard in opslag",
    "Settings sended!": "Instellingen verzonden!",
    "Shara.club (ClubTV.pro)": "Shara.club (ClubTV.pro)",
    "Shara.club (ClubTV.pro) settings":
        "Instellingen voor Shara.club (ClubTV.pro)",
    ShockTv: "ShockTv",
    "ShockTv settings": "Instellingen voor ShockTv",
    "Show archive availability in list":
        "Beschikbaarheid van archief in lijst tonen",
    "Show channel name in list": "Zendernaam in lijst tonen",
    "Show channel number in list": "Zendernummer in lijst tonen",
    "Show channel selection list": "Zenderkeuzelijst tonen",
    "Show description": "Beschrijving tonen",
    "Show EPG and archive for channel": "EPG en archief van zender tonen",
    "Show list of channel archive records": "Zenderopnamen tonen",
    "Show list of channel archive records without duplication":
        "Zenderopnamen zonder duplicaten tonen",
    "Show Media Library": "Mediabibliotheek tonen",
    "Show picons in channel list": "Zenderlogo's in lijst tonen",
    "Show player menu": "Spelermenu tonen",
    "Show program name": "Programmanaam tonen",
    "Show progress in channel list": "Voortgang in zenderlijst tonen",
    "Show provider settings?": "Providerinstellingen tonen?",
    "Show providers?": "Providers tonen?",
    "Show rewind window": "Spoelvenster tonen",
    "Show scrollbar in list": "Schuifbalk in lijsten tonen",
    "Show thumbnails": "Miniaturen tonen",
    "Show when changing program": "Tonen bij programmawisseling",
    "Show when rewind": "Tonen bij spoelen",
    "Show when switching": "Tonen bij zenderwisseling",
    "Sleep timer": "Slaaptimer",
    "Sort channels": "Zenders sorteren",
    "Stalker Portal Provider": "Stalker-portaalprovider",
    "Stalker portal settings": "Instellingen van Stalker-portaal",
    "Stalker portals": "Stalker-portalen",
    Status: "Status",
    "Stop playback and return to live":
        "Afspelen stoppen en terugkeren naar live",
    "Stream type: %1": "Streamtype: %1",
    "String for search": "Zoektekst",
    "Su Mo Tu We Th Fr Sa": "Zo Ma Di Wo Do Vr Za",
    Subtitle: "Ondertitels",
    Switch: "Wisselen",
    "Switch sound track": "Audiospoor wisselen",
    "Switch subtitle": "Ondertitels wisselen",
    "Switch to this list": "Naar deze lijst wisselen",
    "Swop URL": "Swop URL",
    "saved on this device": "opgeslagen op dit apparaat",
    select: "selecteren",
    small: "klein",
    system: "systeem",
    Tabox: "Tabox",
    "Tabox settings": "Instellingen voor Tabox",
    "The device ID in the address is invalid.":
        "De apparaat-ID in het adres is ongeldig.",
    "This HTTPS player cannot connect to an HTTP server. Use an HTTPS server or open the player over HTTP.":
        "Deze HTTPS-speler kan geen verbinding maken met een HTTP-server. Gebruik een HTTPS-server of open de speler via HTTP.",
    "This Play app requires HTTPS. Ask your provider for an HTTPS playlist or server URL.":
        "Deze Play-app vereist HTTPS. Vraag uw provider om een HTTPS-afspeellijst of server-URL.",
    Timer: "Timer",
    "Timer: switch to channel?": "Timer: naar deze zender schakelen?",
    "Timeshift: one minute back": "Timeshift: één minuut terug",
    "Timeshift: to start of TV program": "Timeshift: naar programmabegin",
    Timezone: "Tijdzone",
    TMDb: "TMDb",
    "TOP-IPTV": "TOP-IPTV",
    "TOP-IPTV settings": "Instellingen voor TOP-IPTV",
    "To begining": "Naar begin",
    "To start of TV program / Previous TV program":
        "Naar programmabegin / vorig programma",
    "Toggle Aspect Ratio": "Beeldverhouding wijzigen",
    "Toggle on-screen debug HUD": "Debugpaneel in- of uitschakelen",
    "Toggle Zoom Mode": "Zoommodus wijzigen",
    "Top-Tv": "Top-Tv",
    "Top-Tv settings": "Instellingen voor Top-Tv",
    "Try demo": "Demo proberen",
    "TV DOSUG": "TV DOSUG",
    "TV DOSUG settings": "Instellingen voor TV DOSUG",
    TVClub: "TVClub",
    "TVClub settings": "Instellingen voor TVClub",
    "Type of player for streaming": "Spelertype voor streaming",
    "top-left": "linksboven",
    "top-right": "rechtsboven",
    transparent: "transparant",
    ULTIFL1X: "ULTIFL1X",
    "ULTIFL1X settings": "Instellingen voor ULTIFL1X",
    "Update installed. Please restart OttPlay FOSS.":
        "Update geïnstalleerd. Herstart OttPlay FOSS.",
    "Use an HTTP or HTTPS server address.":
        "Gebruik een HTTP- of HTTPS-serveradres.",
    "Use HTTP or HTTPS without a username or password in the address.":
        "Gebruik HTTP of HTTPS zonder gebruikersnaam of wachtwoord in het adres.",
    "Use LEFT/RIGHT to select a control, OK to activate, and UP/DOWN to scroll.":
        "Gebruik LINKS/RECHTS om een bedieningselement te kiezen, OK om het te activeren en OMHOOG/OMLAAG om te scrollen.",
    Username: "Gebruikersnaam",
    "Username or password is missing.":
        "Gebruikersnaam of wachtwoord ontbreekt.",
    "VIP-IP.COM": "VIP-IP.COM",
    "VIP-IP.COM settings": "Instellingen voor VIP-IP.COM",
    "Vidok.TV": "Vidok.TV",
    "Vidok.TV settings": "Instellingen voor Vidok.TV",
    "VOD not supported by provider":
        "VOD wordt niet ondersteund door deze provider",
    "Volume step, %": "Volumestap, %",
    "VPortal link": "VPortal-link",
    "VPortal request failed":
        "VPortal kon niet worden geladen. Controleer de link, toegangssleutel en beschikbaarheid van het portaal.",
    volume: "volume",
    "Wrong parental code !!!": "Onjuiste ouderlijke code!",
    "Xtream Codes Provider": "Xtream Codes-provider",
    "Xtream Codes settings": "Xtream Codes-instellingen",
    Year: "Jaar",
    Yellow: "Geel",
    Yes: "Ja",
    yes: "ja",
    "Гомельсат (cbilling)": "Гомельсат (cbilling)",
    "Гомельсат (cbilling) settings": "Instellingen voor Гомельсат (cbilling)",
    МойДом: "МойДом",
    "МойДом settings": "Instellingen voor МойДом",
    "Ошибка обработки списка каналов! Проверьте правильность данных!!":
        "Zenderlijst kon niet worden verwerkt. Controleer uw providergegevens!",
    Радуга: "Радуга",
    "Радуга settings": "Instellingen voor Радуга",
    "Редактирование ID": "ID bewerken",
    "Редактирование PIN": "PIN bewerken",
    Шаравоз: "Шаравоз",
    "Шаравоз settings": "Instellingen voor Шаравоз",
    "↑↓ Scroll": "↑↓ Scrollen",
};
