var keyStrings = {
    " (after changing, load playlist)": " (reload the playlist after changing)",
    " (after changing, restart player)": " (restart the player after changing)",
    " added to category ": " added to category ",
    " added to favorites": " added to favorites",
    " m ": " m ",
    " s": " s",
    "??? No channel name": "??? No channel name",
    '"As Is"': '"As is"',
    '"Favorites"': '"Favorites"',
    '"Sliding" infobar': "Sliding info bar",
    "&darr;a": "&darr;a",
    "&uarr;A": "&uarr;A",
    "<br/><br/>In archive mode:<br/>": "<br/><br/>In archive mode:<br/>",
    "<br/>Loading STB...": "<br/>Loading STB…",
    "<br/>Setup STB...": "<br/>Setting up STB…",
    "<br>": "<br>",
    "<br><br>": "<br><br>",
    "<br>Add<br>to category": "<br>Add<br>to category",
    "<br>Add<br>to favorites": "<br>Add<br>to favorites",
    "<br>Delete": "<br>Delete",
    "<br>Down<br>": "<br>Down<br>",
    "<br>Live": "<br>Live",
    "<br>Menu": "<br>Menu",
    "<br>Parental<br>Control": "<br>Parental<br>control",
    "<br>Pause<br>": "<br>Pause<br>",
    "<br>Previous<br>channel": "<br>Previous<br>channel",
    "<br>Rewind<br>": "<br>Rewind<br>",
    "<br>Toggle<br>sound track": "<br>Switch<br>audio track",
    "<br>Up<br>": "<br>Up<br>",
    "1 hour": "1 hour",
    "1 minute": "1 minute",
    "2 hours": "2 hours",
    "3 hours": "3 hours",
    "10 Seconds": "10 seconds",
    "30 minutes": "30 minutes",
    "A command expired while the player was loading channels.":
        "A command expired while the player was loading channels.",
    "A command was rejected by the player. Check its provider and settings.":
        "A command was rejected by the player. Check its provider and settings.",
    About: "About",
    "Access code": "Access code",
    "Access denied. Check the server access code.":
        "Access denied. Check the server access code.",
    "Access key": "Access key",
    "Access key is required!": "Access key is required!",
    "Access settings": "Access settings",
    Actions: "Actions",
    "Active list": "Active list",
    Actors: "Actors",
    "Add / rename / delete…": "Add / rename / delete…",
    "Add channel to category": "Add channel to category",
    "Add channel to favorites": "Add channel to favorites",
    "Add new list": "Add new list",
    "Add to favorites": "Add to favorites",
    Age: "Age",
    All: "All",
    "All categories": "All categories",
    "All4you.tv": "All4you.tv",
    "All4you.tv settings": "All4you.tv settings",
    "Allowlist this Device ID": "Allowlist this Device ID",
    "An IP without a port uses HTTP port 8081. Clear the address or select Disconnect to stop.":
        "An IP without a port uses HTTP port 8081. Clear the address or select Disconnect to stop.",
    "API failed, trying M3U...": "API failed, trying M3U…",
    "API Server": "API server",
    "API server URL": "API server URL",
    "Applying HTTP remote settings...": "Applying HTTP remote settings...",
    Archive: "Archive",
    "Archive - begin": "Archive — start",
    "Archive hours": "Archive hours",
    "Archive: ENTER on past programs": "Archive: ENTER on past programs",
    "Archive. Channel: ": "Archive. Channel: ",
    Aspect: "Aspect",
    Audio: "Audio",
    alhabet: "абвгдеёжзийклмнопрстуфхцчшщъыьэюя",
    always: "always",
    "and enter code": "and enter the code",
    Back: "Back",
    "Back / Forward for 1 minute": "Skip back / forward 1 minute",
    "Background color": "Background color",
    "Background color of selected item": "Background color of selected item",
    "BEST LiST IPTV [HLS Playlist]": "BEST LiST IPTV [HLS Playlist]",
    "BEST LiST IPTV [HLS Playlist] settings":
        "BEST LiST IPTV [HLS Playlist] settings",
    "BEST LiST IPTV [Stalker]": "BEST LiST IPTV [Stalker]",
    "BEST LiST IPTV [Stalker] settings": "BEST LiST IPTV [Stalker] settings",
    "Behavior of %1/%2 buttons in lists":
        "Behavior of the %1/%2 buttons in lists",
    "Black screen while switching the channel":
        "Black screen when switching channels",
    Blue: "Blue",
    "Bookmark age: %1 days": "Bookmark age: %1 days",
    "Buffer Size, s": "Buffer size, s",
    "Built-in playlist:": "Built-in playlist:",
    "Built-in playlists": "Built-in playlists",
    "Button %1 function when viewing":
        "Function of the %1 button while watching",
    "Button function %1 when viewing archive":
        "Button function %1 while viewing archive",
    "Buttons settings": "Button settings",
    "By alphabet": "Alphabetical",
    "By time": "Chronological",
    "begin/end": "begin/end",
    "bottom-right": "bottom-right",
    "built-in": "built-in",
    "Call PiP": "Open PiP",
    "Call PiP / PiP exchange": "Open PiP / swap PiP",
    Cancel: "Cancel",
    "Cannot delete the last category": "Cannot delete the last category",
    Category: "Category",
    "Category selection": "Category selection",
    "Change interface language": "Change interface language",
    "Change provider": "Change provider",
    "Change provider - you can change the provider, and it will be remembered at the next start of player!":
        "Change the provider. Your selection will be remembered the next time you start the player.",
    "Change value": "Change value",
    "Channel ": "Channel ",
    "Channel has no EPG": "Channel has no EPG",
    "Channel is not available!!!": "Channel is not available!",
    "Channel link": "Channel link",
    "Channel link is required!": "Channel link is required!",
    "Channel list": "Channel list",
    "Channel list editing style": "Channel list editing mode",
    "Channel list not received !!!": "Channel list not received!",
    "Channel list not received !!!<br/><br/>Enter the provider data and restart the player !!!<br/><br/>":
        "Channel list not received!<br/><br/>Enter your provider details and restart the player.<br/><br/>",
    "Channel list settings": "Channel list settings",
    "Channel list. Category: ": "Channel list. Category: ",
    "Channel parental control": "Channel parental control",
    Channels: "Channels",
    "Choose from": "Choose from",
    "Choose language": "Choose language",
    "Choose provider": "Choose provider",
    Classic: "Classic",
    "Clear all settings?": "Clear all settings?",
    "Clear settings": "Clear settings",
    Close: "Close",
    "Close PiP": "Close PiP",
    Color: "Color",
    "Color spectrum": "Color spectrum",
    "Command server": "Command server",
    "Command server address, device access code, local HTTP control, and remote text entry settings":
        "Command server address, device access code, local HTTP control, and remote text entry settings",
    "Configure All4you.tv in Settings -> Provider Settings":
        "Configure All4you.tv in Settings -> Provider Settings",
    "Configure BEST LiST IPTV [HLS Playlist] in Settings -> Provider Settings":
        "Configure BEST LiST IPTV [HLS Playlist] in Settings -> Provider Settings",
    "Configure BEST LiST IPTV [Stalker] in Settings -> Provider Settings":
        "Configure BEST LiST IPTV [Stalker] in Settings -> Provider Settings",
    "Configure Diamond TV in Settings -> Provider Settings":
        "Configure Diamond TV in Settings -> Provider Settings",
    "Configure DRVAO in Settings -> Provider Settings":
        "Configure DRVAO in Settings -> Provider Settings",
    "Configure Dragon Media PRO in Settings -> Provider Settings":
        "Configure Dragon Media PRO in Settings -> Provider Settings",
    "Configure Fabryka.TV in Settings -> Provider Settings":
        "Configure Fabryka.TV in Settings -> Provider Settings",
    "Configure Fox-TV in Settings -> Provider Settings":
        "Configure Fox-TV in Settings -> Provider Settings",
    "Configure FXML in Settings -> Provider Settings":
        "Configure FXML in Settings -> Provider Settings",
    "Configure GlanzTV in Settings -> Provider Settings":
        "Configure GlanzTV in Settings -> Provider Settings",
    "Configure GREAT IPTV in Settings -> Provider Settings":
        "Configure GREAT IPTV in Settings -> Provider Settings",
    "Configure IpStream.one in Settings -> Provider Settings":
        "Configure IpStream.one in Settings -> Provider Settings",
    "Configure KORONA TV in Settings -> Provider Settings":
        "Configure KORONA TV in Settings -> Provider Settings",
    "Configure MaxTV in Settings -> Provider Settings":
        "Configure MaxTV in Settings -> Provider Settings",
    "Configure New Look in Settings -> Provider Settings":
        "Configure New Look in Settings -> Provider Settings",
    "Configure OTT Prime ONLINE in Settings -> Provider Settings":
        "Configure OTT Prime ONLINE in Settings -> Provider Settings",
    "Configure POLMEDIA in Settings -> Provider Settings":
        "Configure POLMEDIA in Settings -> Provider Settings",
    "Configure PROST in Settings -> Provider Settings":
        "Configure PROST in Settings -> Provider Settings",
    "Configure RD in Settings -> Provider Settings":
        "Configure RD in Settings -> Provider Settings",
    "Configure RUSSKOETV in Settings -> Provider Settings":
        "Configure RUSSKOETV in Settings -> Provider Settings",
    "Configure Shara.club (ClubTV.pro) in Settings -> Provider Settings":
        "Configure Shara.club (ClubTV.pro) in Settings -> Provider Settings",
    "Configure ShockTv in Settings -> Provider Settings":
        "Configure ShockTv in Settings -> Provider Settings",
    "Configure Tabox in Settings -> Provider Settings":
        "Configure Tabox in Settings -> Provider Settings",
    "Configure TOP-IPTV in Settings -> Provider Settings":
        "Configure TOP-IPTV in Settings -> Provider Settings",
    "Configure Top-Tv in Settings -> Provider Settings":
        "Configure Top-Tv in Settings -> Provider Settings",
    "Configure TV DOSUG in Settings -> Provider Settings":
        "Configure TV DOSUG in Settings -> Provider Settings",
    "Configure TVClub in Settings -> Provider Settings":
        "Configure TVClub in Settings -> Provider Settings",
    "Configure ULTIFL1X in Settings -> Provider Settings":
        "Configure ULTIFL1X in Settings -> Provider Settings",
    "Configure VIP-IP.COM in Settings -> Provider Settings":
        "Configure VIP-IP.COM in Settings -> Provider Settings",
    "Configure Vidok.TV in Settings -> Provider Settings":
        "Configure Vidok.TV in Settings -> Provider Settings",
    "Configure Гомельсат (cbilling) in Settings -> Provider Settings":
        "Configure Гомельсат (cbilling) in Settings -> Provider Settings",
    "Configure МойДом in Settings -> Provider Settings":
        "Configure МойДом in Settings -> Provider Settings",
    "Configure Радуга in Settings -> Provider Settings":
        "Configure Радуга in Settings -> Provider Settings",
    "Configure Шаравоз in Settings -> Provider Settings":
        "Configure Шаравоз in Settings -> Provider Settings",
    Connect: "Connect",
    Connected: "Connected",
    "Connected. Waiting for the channel list...":
        "Connected. Waiting for the channel list...",
    "Connecting to Stalker portal...": "Connecting to Stalker portal…",
    "Connecting...": "Connecting…",
    "Continue watching?": "Continue watching?",
    "Copy category": "Copy category",
    "Copy JSON": "Copy JSON",
    "Could not connect to the server.": "Could not connect to the server.",
    "Could not update HTTP remote control.":
        "Could not update HTTP remote control.",
    Country: "Country",
    "Create category": "Create category",
    current: "current",
    "Debug HUD": "Debug HUD",
    "Debug HUD is not available": "Debug HUD is not available",
    Delete: "Delete",
    "Delete category": "Delete category",
    "Delete channel": "Delete channel",
    "Delete list": "Delete list",
    "Demo — moving test pattern": "Demo — moving test pattern",
    Description: "Description",
    "Description of remote control buttons": "Remote control button guide",
    "Device access code": "Device access code",
    "Device info:": "Device info:",
    "Device MAC is required for KBC (Kinoboom) playlists":
        "Device MAC is required for KBC (Kinoboom) playlists",
    "Diamond TV": "Diamond TV",
    "Diamond TV settings": "Diamond TV settings",
    Director: "Director",
    "Disable HTTP remote": "Disable HTTP remote",
    "Disabled by default. Enabling creates a new device access code.":
        "Disabled by default. Enabling creates a new device access code.",
    Disconnect: "Disconnect",
    Disconnected: "Disconnected",
    "Distance between lines in lists": "Line spacing in lists",
    "Do you want to exit player?": "Do you want to exit the player?",
    "Download! Wait ...": "Downloading… please wait…",
    DRVAO: "DRVAO",
    "DRVAO settings": "DRVAO settings",
    "Dragon Media PRO": "Dragon Media PRO",
    "Dragon Media PRO settings": "Dragon Media PRO settings",
    Duration: "Duration",
    Edit: "Edit",
    "Edit access key": "Edit access key",
    "Edit category name": "Edit category name",
    "Edit channel link": "Edit channel link",
    "Edit playlist data": "Edit playlist details",
    "Edit VPortal link": "Edit VPortal link",
    Editor: "Editor",
    "Enable HTTP remote": "Enable HTTP remote",
    English: "English",
    "Enter a password (8 characters).": "Enter a password (8 characters).",
    "Enter a playlist URL to access this service.":
        "Enter a playlist URL to access this service.",
    "Enter a server address without spaces or a fragment.":
        "Enter a server address without spaces or a fragment.",
    "Enter a username (8 characters).": "Enter a username (8 characters).",
    "Enter a username and password to access this service.":
        "Enter a username and password to access this service.",
    "Enter a valid server address, for example 192.168.1.20:8081.":
        "Enter a valid server address, for example 192.168.1.20:8081.",
    "Enter access key for": "Enter access key for",
    "Enter an application access key (8 characters).":
        "Enter an application access key (8 characters).",
    "Enter an ID and PIN to access this service.":
        "Enter an ID and PIN to access this service.",
    "Enter an IPTV token (10 characters).":
        "Enter an IPTV token (10 characters).",
    "Enter category name": "Enter category name",
    "Enter MAC address": "Enter MAC address",
    "Enter MAC address (e.g. 00:1A:2B:3C:4D:5E)":
        "Enter MAC address (e.g. 00:1A:2B:3C:4D:5E)",
    "Enter Media Library URL": "Enter media library URL",
    "Enter new category name": "Enter new category name",
    "Enter Provider Code": "Enter provider code",
    "Enter Provider Code on PC or Phone":
        "Enter provider code on a PC or phone",
    "Enter parental code": "Enter parental code",
    "Enter password": "Enter password",
    "Enter playlist archive hours": "Enter playlist archive hours",
    "Enter playlist Name": "Enter playlist name",
    "Enter playlist URL": "Enter playlist URL",
    "Enter Stalker portal URL": "Enter Stalker portal URL",
    "Enter Stalker portal URL (e.g. http://your-portal:8800)":
        "Enter Stalker portal URL (e.g. http://your-portal:8800)",
    "Enter Stalker portal URL (e.g. http://your-portal/stalker_portal/c/)":
        "Enter Stalker portal URL (e.g. http://your-portal/stalker_portal/c/)",
    "Enter the access code separately, not in the server address.":
        "Enter the access code separately, not in the server address.",
    "Enter the command server IP or address.":
        "Enter the command server IP or address.",
    "Enter the full CDN host from the cabinet stream URL (e.g. subdomain.cdn-domain.tld), not a bare subdomain":
        "Enter the full CDN host from the cabinet stream URL (e.g. subdomain.cdn-domain.tld), not a bare subdomain",
    "Enter the server IP or address and this player's device access code from the server configuration. Saving both starts checking for volume, channel and other commands automatically.":
        "Enter the server IP or address and this player's device access code from the server configuration. Saving both starts checking for volume, channel and other commands automatically.",
    "Enter the server's device access code (32–256 letters, digits, _ or -).":
        "Enter the server's device access code (32–256 letters, digits, _ or -).",
    'Enter the tv.team playlist URL.<br>Playlist type: <b>OTTPlayer</b><br/><br/>The "/playlist.m3u8" suffix is added automatically if omitted.':
        'Enter the tv.team playlist URL.<br>Playlist type: <b>OTTPlayer</b><br/><br/>The "/playlist.m3u8" suffix is added automatically if omitted.',
    "Enter the VPortal link as shown in the cabinet":
        "Enter the VPortal link as shown in the cabinet",
    "Enter this link in VPortal link. Playlist URL requires an M3U playlist.":
        "Enter this link in VPortal link. Playlist URL requires an M3U playlist.",
    "Enter this player's device access code to connect.":
        "Enter this player's device access code to connect.",
    "Enter username": "Enter username",
    "Enter value": "Enter value",
    "Enter Xtream server URL": "Enter Xtream server URL",
    "Enter Xtream server URL (e.g. https://your-server:8080)":
        "Enter Xtream server URL (e.g. https://your-server:8080)",
    EPG: "EPG",
    "EPG and archive. Channel: ": "EPG and archive. Channel: ",
    "ERROR!": "Error!",
    "Error Code!": "Invalid code!",
    Exit: "Exit",
    "Exit player": "Exit player",
    "Export settings": "Export settings",
    "epg.one (Ordered)": "epg.one (Ordered)",
    "epg.one (Standard)": "epg.one (Standard)",
    "epg.one (Thematic)": "epg.one (Thematic)",
    "epgs...": "EPGs…",
    "Fabryka.TV": "Fabryka.TV",
    "Fabryka.TV settings": "Fabryka.TV settings",
    "Failed to connect to Stalker portal":
        "Failed to connect to Stalker portal",
    "Failed to connect to Xtream API server":
        "Failed to connect to Xtream API server",
    "Failed to get user data!!!": "Failed to retrieve user details!",
    "Failed to load channel list!": "Failed to load channel list!",
    "Failed to load channels from Stalker portal":
        "Failed to load channels from Stalker portal",
    "Failed to load channels from Xtream API":
        "Failed to load channels from Xtream API",
    "Failed to load!": "Failed to load!",
    "Favorite lists": "Favorite lists",
    Favorites: "Favorites",
    "File selection is not supported on this device":
        "File selection is not supported on this device",
    Filters: "Filters",
    "First Run Setup": "First-run setup",
    "Font type": "Font type",
    "For download settings file open": "To download the settings file, open",
    "For enter value open": "To enter a value, open",
    "For upload settings file open": "To upload the settings file, open",
    "Fox-TV": "Fox-TV",
    "Fox-TV settings": "Fox-TV settings",
    FXML: "FXML",
    "FXML settings": "FXML settings",
    Genre: "Genre",
    GlanzTV: "GlanzTV",
    "GlanzTV settings": "GlanzTV settings",
    "Go to": "Go to",
    "GREAT IPTV": "GREAT IPTV",
    "GREAT IPTV settings": "GREAT IPTV settings",
    "Graphical indication": "Graphical indicators",
    Green: "Green",
    "Hide / Return": "Hide / show",
    "Hide provider settings?": "Hide provider settings?",
    "Hide providers?": "Hide providers?",
    "History in Media Library": "History in media library",
    "History of watched movies": "Watch history",
    "HTTP port": "HTTP port",
    "HTTP remote control is unavailable on this device.":
        "HTTP remote control is unavailable on this device.",
    ID: "ID",
    "Import settings": "Import settings",
    "In live mode: <br/>": "In live mode:<br/>",
    Info: "Info",
    "Infobar display timeout, s": "Info bar display timeout, s",
    "Infobar settings": "Info bar settings",
    Information: "Information",
    "Interface credits": "Interface credits",
    "Interface settings": "Interface settings",
    "Interface theme": "Interface theme",
    "Interface transparency": "Interface transparency",
    "Invalid channel link! Enter the full host as in the cabinet stream URL (e.g. subdomain.cdn-domain.tld)":
        "Invalid channel link! Enter the full host as in the cabinet stream URL (e.g. subdomain.cdn-domain.tld)",
    "IPTV token": "IPTV token",
    "IpStream.one": "IpStream.one",
    "IpStream.one settings": "IpStream.one settings",
    Joystick: "Joystick",
    "KBC (Kinoboom) access data": "KBC (Kinoboom) access details",
    "KORONA TV": "KORONA TV",
    "KORONA TV settings": "KORONA TV settings",
    "List created": "List created",
    "List deleted": "List deleted",
    "List location": "List position",
    "List renamed": "List renamed",
    "List type": "List type",
    "Lists settings": "List settings",
    Live: "Live",
    Load: "Load",
    "Load built-in playlist:": "Load built-in playlist:",
    "Load playlist": "Load playlist",
    "Load settings": "Load settings",
    "Load settings from storage": "Load settings from storage",
    "Load:": "Load:",
    "Loading channels from Xtream API...": "Loading channels from Xtream API…",
    "Loading channels...": "Loading channels…",
    "Loading from API...": "Loading from API…",
    "Loading from Edem API...": "Loading from Edem API…",
    "Loading M3U playlist...": "Loading M3U playlist…",
    "Loading M3U...": "Loading M3U…",
    "Loading via proxy...": "Loading via proxy…",
    "Loading. Please wait...": "Loading… please wait…",
    "Loading...": "Loading…",
    "Local HTTP remote control": "Local HTTP remote control",
    "Local URL": "Local URL",
    Login: "Login",
    lang: "English",
    large: "large",
    left: "left",
    "left-bottom": "bottom-left",
    "logos...": "Logos…",
    M3U: "M3U",
    "M3U URL": "M3U URL",
    "M3U URL (fallback)": "M3U URL (fallback)",
    "MAC address": "MAC address",
    "Manage lists": "Manage lists",
    "Manage settings": "Manage settings",
    "Manual setup": "Manual setup",
    MaxTV: "MaxTV",
    "MaxTV settings": "MaxTV settings",
    Media: "Media",
    "Media item is no longer available": "Media item is no longer available",
    "Media Library": "Media library",
    "Media Library URL": "Media library URL",
    Menu: "Menu",
    "Menu items settings": "Menu item settings",
    "Move category down": "Move category down",
    "Move category up": "Move category up",
    "Move channel down": "Move channel down",
    "Move channel up": "Move channel up",
    "m3u-m3u8 playlists": "M3U / M3U8 playlists",
    medium: "medium",
    min: "min",
    "New Look": "New Look",
    "New Look settings": "New Look settings",
    "New list name": "New list name",
    Next: "Next page",
    "Next keyboard page": "Next keyboard page",
    "Next TV program": "Next program",
    No: "No",
    "No channel name": "No channel name",
    "No saved settings found": "No saved settings found",
    "Not found": "Not found",
    "Not reduce video when showing the list (bugfix)":
        "Do not shrink video when showing the list (bug fix)",
    Nothing: "Nothing",
    "Number of next TV programs in channel list":
        "Number of next programs in channel list",
    "Number of rows in lists": "Number of rows in lists",
    native: "native",
    no: "no",
    "no epg at current time": "No EPG at the current time",
    "not set": "not set",
    Off: "Off",
    Ok: "OK",
    Open: "Open",
    "Open in PiP": "Open in PiP",
    "OTT Prime ONLINE": "OTT Prime ONLINE",
    "OTT Prime ONLINE settings": "OTT Prime ONLINE settings",
    "OttPlay FOSS %1 is available. Download and install now?":
        "OttPlay FOSS %1 is available. Download and install now?",
    "Overwrite current settings?": "Overwrite current settings?",
    off: "off",
    on: "on",
    "on ": "on ",
    "or scan": "or scan",
    "Parental control": "Parental control",
    Password: "Password",
    Pause: "Pause",
    "Pause/Play": "Pause / play",
    "Permanent clock on screen": "Always show clock on screen",
    PIN: "PIN",
    "PiP exchange": "Swap PiP",
    "PiP window position": "PiP window position",
    "PiP window size": "PiP window size",
    Play: "Play",
    "Player and device info": "Player and device information",
    "Player info:": "Player information:",
    Playlist: "Playlist",
    "Playlist file": "Playlist file",
    "Playlist is not loading directly...Loading via server...":
        "Playlist could not be loaded directly. Loading via server…",
    "Playlist Name": "Playlist name",
    "Playlist URL": "Playlist URL",
    POLMEDIA: "POLMEDIA",
    "POLMEDIA settings": "POLMEDIA settings",
    "Portal URL": "Portal URL",
    "Position shift -10 seconds after pause":
        "Seek back 10 seconds after pause",
    PROST: "PROST",
    "PROST settings": "PROST settings",
    Prev: "Previous",
    "Preview in channel list": "Preview in channel list",
    Previous: "Previous",
    "Privacy policy": "Privacy policy",
    "Protect Adult Channels": "Protect adult channels",
    "Protect Change Provider": "Protect provider change",
    "Protect Settings": "Protect settings",
    "p...": "p...",
    paging: "paging",
    Quality: "Quality",
    Rating: "Rating",
    RD: "RD",
    "RD settings": "RD settings",
    "Reconnecting…": "Reconnecting…",
    Records: "Recordings",
    "Records for channel: ": "Recordings for channel: ",
    "Records library is empty": "Recordings library is empty",
    "Records not supported by provider":
        "Recordings are not supported by this provider",
    "Release date": "Release date",
    "Remember previous channels": "Remember previous channels",
    "Reminder: %1 — %2 in %3 min": "Reminder: %1 — %2 in %3 min",
    "Remote (color buttons N/A)": "Remote (no color buttons)",
    "Remote (number buttons N/A)": "Remote (no number buttons)",
    "Remote control": "Remote control",
    "Remote session expired": "Remote session expired",
    "Remote text entry denied": "Remote text entry denied",
    "Remote text entry error": "Remote text entry error",
    "Remote text entry not configured": "Remote text entry not configured",
    "Remote text entry requires a Device ID. Ask the server operator to provision one.":
        "Remote text entry requires a Device ID. Ask the server operator to provision one.",
    "Remove timer?": "Remove timer?",
    Rename: "Rename",
    "Rename category": "Rename category",
    "Rename to": "Rename to",
    "Repeat parental code": "Re-enter parental code",
    "Request sended!": "Request sent!",
    "Restart player": "Restart player",
    "Restart stream": "Restart stream",
    "Restart stream / Live": "Restart stream / Live",
    "Resume from archive?": "Resume from archive?",
    "Return to previous channel": "Return to the previous channel",
    Rewind: "Seek",
    "Rewind step by buttons %1/%2": "Rewind step for buttons %1/%2",
    RUSSKOETV: "RUSSKOETV",
    "RUSSKOETV settings": "RUSSKOETV settings",
    Russian: "Russian",
    right: "right",
    Saturation: "Saturation",
    "Save & load channels": "Save & load channels",
    "Save and load": "Save and load",
    "Save and load channels": "Save and load channels",
    "Save Settings": "Save settings",
    "Save settings": "Save settings",
    "Save settings and load channel list":
        "Save settings and load channel list",
    "Save settings to storage": "Save settings to storage",
    Script: "Screenplay",
    Search: "Search",
    "Search programme": "Search programme",
    "Select a stream type:<br>%1": "Select a stream type:<br>%1",
    "Select category to add channel": "Select a category to add the channel",
    "Select color": "Select color",
    "Select menu items": "Select menu items",
    "Select playlist": "Select playlist",
    "Select playlist file": "Select playlist file",
    "Select playlist template source for EPG and logos":
        "Select playlist template source for EPG and logos",
    "Send request": "Send request",
    "Send settings": "Send settings",
    "Send this code from your proxy in the Authorization: Bearer header.":
        "Send this code from your proxy in the Authorization: Bearer header.",
    Server: "Server",
    "Server address": "Server address",
    "Server address (for example 192.168.1.20:8081)":
        "Server address (for example 192.168.1.20:8081)",
    "Server device access code": "Server device access code",
    "Server URL": "Server URL",
    "Server unavailable. Retrying automatically; check its address and network access.":
        "Server unavailable. Retrying automatically; check its address and network access.",
    Set: "Set",
    "Set parental code": "Set parental code",
    "Set timer?": "Set timer?",
    Settings: "Settings",
    "Settings could not be saved": "Settings could not be saved",
    "Settings loaded from storage": "Settings loaded from storage",
    "Settings STB": "STB settings",
    "Settings saved": "Settings saved",
    "Settings saved to storage": "Settings saved to storage",
    "Settings sended!": "Settings sent!",
    "Shara.club (ClubTV.pro)": "Shara.club (ClubTV.pro)",
    "Shara.club (ClubTV.pro) settings": "Shara.club (ClubTV.pro) settings",
    ShockTv: "ShockTv",
    "ShockTv settings": "ShockTv settings",
    "Show archive availability in list": "Show archive availability in list",
    "Show channel name in list": "Show channel name in list",
    "Show channel number in list": "Show channel number in list",
    "Show channel selection list": "Show channel selection list",
    "Show description": "Show description",
    "Show EPG and archive for channel": "Show channel EPG and archive",
    "Show list of channel archive records": "Show channel recordings",
    "Show list of channel archive records without duplication":
        "Show channel recordings without duplicates",
    "Show Media Library": "Show media library",
    "Show picons in channel list": "Show channel icons in list",
    "Show player menu": "Show player menu",
    "Show program name": "Show program name",
    "Show progress in channel list": "Show progress in channel list",
    "Show provider settings?": "Show provider settings?",
    "Show providers?": "Show providers?",
    "Show rewind window": "Show seek window",
    "Show scrollbar in list": "Show scrollbar in lists",
    "Show thumbnails": "Show thumbnails",
    "Show when changing program": "Show when the program changes",
    "Show when rewind": "Show when rewinding",
    "Show when switching": "Show when switching channels",
    "Sleep timer": "Sleep timer",
    "Sort channels": "Sort channels",
    "Stalker Portal Provider": "Stalker portal provider",
    "Stalker portal settings": "Stalker portal settings",
    "Stalker portals": "Stalker portals",
    Status: "Status",
    "Stop playback and return to live": "Stop playback and return to live",
    "Stream type: %1": "Stream type: %1",
    "String for search": "Search query",
    "Su Mo Tu We Th Fr Sa": "Su Mo Tu We Th Fr Sa",
    Subtitle: "Subtitles",
    Switch: "Switch",
    "Switch sound track": "Switch audio track",
    "Switch subtitle": "Switch subtitles",
    "Switch to this list": "Switch to this list",
    "Swop URL": "Swop URL",
    "saved on this device": "saved on this device",
    select: "select",
    small: "small",
    system: "system",
    Tabox: "Tabox",
    "Tabox settings": "Tabox settings",
    "The device ID in the address is invalid.":
        "The device ID in the address is invalid.",
    "This HTTPS player cannot connect to an HTTP server. Use an HTTPS server or open the player over HTTP.":
        "This HTTPS player cannot connect to an HTTP server. Use an HTTPS server or open the player over HTTP.",
    "This Play app requires HTTPS. Ask your provider for an HTTPS playlist or server URL.":
        "This Play app requires HTTPS. Ask your provider for an HTTPS playlist or server URL.",
    Timer: "Timer",
    "Timer: switch to channel?": "Timer: switch to this channel?",
    "Timeshift: one minute back": "Timeshift: one minute back",
    "Timeshift: to start of TV program": "Timeshift: to start of program",
    Timezone: "Timezone",
    TMDb: "TMDb",
    "TOP-IPTV": "TOP-IPTV",
    "TOP-IPTV settings": "TOP-IPTV settings",
    "To begining": "To beginning",
    "To start of TV program / Previous TV program":
        "Go to start of program / previous program",
    "Toggle Aspect Ratio": "Change aspect ratio",
    "Toggle on-screen debug HUD": "Toggle on-screen debug HUD",
    "Toggle Zoom Mode": "Change zoom mode",
    "Top-Tv": "Top-Tv",
    "Top-Tv settings": "Top-Tv settings",
    "Try demo": "Try demo",
    "TV DOSUG": "TV DOSUG",
    "TV DOSUG settings": "TV DOSUG settings",
    TVClub: "TVClub",
    "TVClub settings": "TVClub settings",
    "Type of player for streaming": "Streaming player type",
    "top-left": "top-left",
    "top-right": "top-right",
    transparent: "transparent",
    ULTIFL1X: "ULTIFL1X",
    "ULTIFL1X settings": "ULTIFL1X settings",
    "Update installed. Please restart OttPlay FOSS.":
        "Update installed. Please restart OttPlay FOSS.",
    "Use an HTTP or HTTPS server address.":
        "Use an HTTP or HTTPS server address.",
    "Use HTTP or HTTPS without a username or password in the address.":
        "Use HTTP or HTTPS without a username or password in the address.",
    "Use LEFT/RIGHT to select a control, OK to activate, and UP/DOWN to scroll.":
        "Use LEFT/RIGHT to select a control, OK to activate it, and UP/DOWN to scroll.",
    Username: "Username",
    "Username or password is missing.": "Username or password is missing.",
    "VIP-IP.COM": "VIP-IP.COM",
    "VIP-IP.COM settings": "VIP-IP.COM settings",
    "Vidok.TV": "Vidok.TV",
    "Vidok.TV settings": "Vidok.TV settings",
    "VOD not supported by provider": "VOD is not supported by this provider",
    "Volume step, %": "Volume step, %",
    "VPortal link": "VPortal link",
    "VPortal request failed":
        "Could not load VPortal. Check the link, access key, and portal availability.",
    volume: "volume",
    "Wrong parental code !!!": "Wrong parental code!",
    "Xtream Codes Provider": "Xtream Codes Provider",
    "Xtream Codes settings": "Xtream Codes settings",
    Year: "Year",
    Yellow: "Yellow",
    Yes: "Yes",
    yes: "yes",
    "Гомельсат (cbilling)": "Гомельсат (cbilling)",
    "Гомельсат (cbilling) settings": "Гомельсат (cbilling) settings",
    МойДом: "МойДом",
    "МойДом settings": "МойДом settings",
    "Ошибка обработки списка каналов! Проверьте правильность данных!!":
        "Could not process the channel list. Check your provider details!",
    Радуга: "Радуга",
    "Радуга settings": "Радуга settings",
    "Редактирование ID": "Edit ID",
    "Редактирование PIN": "Edit PIN",
    Шаравоз: "Шаравоз",
    "Шаравоз settings": "Шаравоз settings",
    "↑↓ Scroll": "↑↓ Scroll",
};
