var keyStrings = {
    " (after changing, load playlist)": " (reload the playlist after changing)",
    " added to category ": " added to category ",
    " added to favorites": " added to favorites",
    "??? No channel name": "??? No channel name",
    Actions: "Actions",
    "Add channel to category": "Add channel to category",
    "Add channel to favorites": "Add channel to favorites",
    All: "All",
    "Archive hours": "Archive hours",
    alhabet: "абвгдеёжзийклмнопрстуфхцчшщъыьэюя",
    "Buffer Size, s": "Buffer size, s",
    "built-in": "built-in",
    Category: "Category",
    "Channel ": "Channel ",
    "Channel is not available!!!": "Channel is not available!",
    "Channel list": "Channel list",
    "Channel list not received !!!": "Channel list not received!",
    "Channel list not received !!!<br/><br/>Enter the provider data and restart the player !!!<br/><br/>":
        "Channel list not received!<br/><br/>Enter your provider details and restart the player.<br/><br/>",
    "Channel list. Category: ": "Channel list. Category: ",
    "Channel parental control": "Channel parental control",
    Close: "Close",
    "Delete channel": "Delete channel",
    Description: "Description",
    Edit: "Edit",
    "Edit category name": "Edit category name",
    "Edit playlist data": "Edit playlist details",
    Editor: "Editor",
    "Enter Media Library URL": "Enter media library URL",
    "Enter parental code": "Enter parental code",
    "Enter playlist archive hours": "Enter playlist archive hours",
    "Enter playlist Name": "Enter playlist name",
    "Enter playlist URL": "Enter playlist URL",
    EPG: "EPG",
    Exit: "Exit",
    "Failed to load channel list!": "Failed to load channel list!",
    Favorites: "Favorites",
    Info: "Info",
    Load: "Load",
    "Load playlist": "Load playlist",
    lang: "English",
    "Media Library URL": "Media library URL",
    Menu: "Menu",
    "Move channel down": "Move channel down",
    "Move channel up": "Move channel up",
    "m3u-m3u8 playlists": "M3U / M3U8 playlists",
    min: "min",
    "No channel name": "No channel name",
    Nothing: "Nothing",
    native: "native",
    no: "no",
    "Open in PiP": "Open in PiP",
    off: "off",
    Playlist: "Playlist",
    "Playlist file": "Playlist file",
    "Playlist is not loading directly...Loading via server...":
        "Playlist could not be loaded directly. Loading via server…",
    "Playlist Name": "Playlist name",
    "Playlist URL": "Playlist URL",
    "Save Settings": "Save settings",
    Search: "Search",
    "Select category to add channel": "Select a category to add the channel",
    "Select playlist": "Select playlist",
    "Select playlist file": "Select playlist file",
    Settings: "Settings",
    "Settings STB": "STB settings",
    "Settings saved": "Settings saved",
    "Stalker portals": "Stalker portals",
    "Type of player for streaming": "Streaming player type",
    "Wrong parental code !!!": "Wrong parental code!",
    yes: "yes",
    "\"Sliding\" infobar": "Sliding info bar",
    "10 Seconds": "10 seconds",
    "<br/>Loading STB...": "<br/>Loading STB…",
    "<br/>Setup STB...": "<br/>Setting up STB…",
    "and enter code": "and enter the code",
    "API failed, trying M3U...": "API failed, trying M3U…",
    "API Server": "API server",
    "Archive - begin": "Archive — start",
    "Back / Forward for 1 minute": "Skip back / forward 1 minute",
    "Behavior of %1/%2 buttons in lists": "Behavior of the %1/%2 buttons in lists",
    "Black screen while switching the channel": "Black screen when switching channels",
    "Button %1 function when viewing": "Function of the %1 button while watching",
    "Button function %1 when viewing archive": "Button function %1 while viewing archive",
    "Buttons settings": "Button settings",
    "Connecting to Stalker portal...": "Connecting to Stalker portal…",
    "Description of remote control buttons": "Remote control button guide",
    "Distance between lines in lists": "Line spacing in lists",
    "Do you want to exit player?": "Do you want to exit the player?",
    "Download! Wait ...": "Downloading… please wait…",
    "Enter Provider Code": "Enter provider code",
    "Enter Provider Code on PC or Phone": "Enter provider code on a PC or phone",
    "epgs...": "EPGs…",
    "First Run Setup": "First-run setup",
    "For download settings file open": "To download the settings file, open",
    "For enter value open": "To enter a value, open",
    "For upload settings file open": "To upload the settings file, open",
    "Graphical indication": "Graphical indicators",
    "Hide / Return": "Hide / show",
    "History in Media Library": "History in media library",
    "In live mode: <br/>": "In live mode:<br/>",
    "Infobar display timeout, s": "Info bar display timeout, s",
    "Infobar settings": "Info bar settings",
    "left-bottom": "bottom-left",
    "Lists settings": "List settings",
    "Loading channels from Xtream API...": "Loading channels from Xtream API…",
    "Loading channels...": "Loading channels…",
    "Loading from API...": "Loading from API…",
    "Loading from Edem API...": "Loading from Edem API…",
    "Loading M3U playlist...": "Loading M3U playlist…",
    "Loading M3U...": "Loading M3U…",
    "Loading via proxy...": "Loading via proxy…",
    "logos...": "Logos…",
    "Media Library": "Media library",
    "Menu items settings": "Menu item settings",
    "no epg at current time": "No EPG at the current time",
    "Not reduce video when showing the list (bugfix)":
        "Do not shrink video when showing the list (bug fix)",
    "Number of next TV programs in channel list": "Number of next programs in channel list",
    "Pause/Play": "Pause / play",
    "Permanent clock on screen": "Always show clock on screen",
    "Position shift -10 seconds after pause": "Seek back 10 seconds after pause",
    Prev: "Previous",
    "Protect Adult Channels": "Protect adult channels",
    "Protect Change Provider": "Protect provider change",
    "Protect Settings": "Protect settings",
    Records: "Recordings",
    "Records for channel: ": "Recordings for channel: ",
    "Records library is empty": "Recordings library is empty",
    "Records not supported by provider": "Recordings are not supported by this provider",
    "Remote (color buttons N/A)": "Remote (no color buttons)",
    "Remote (number buttons N/A)": "Remote (no number buttons)",
    "Repeat parental code": "Re-enter parental code",
    "Request sended!": "Request sent!",
    "Rewind step by buttons %1/%2": "Rewind step for buttons %1/%2",
    "Settings sended!": "Settings sent!",
    "Show picons in channel list": "Show channel icons in list",
    "Show when changing program": "Show when the program changes",
    "Show when rewind": "Show when rewinding",
    "Show when switching": "Show when switching channels",
    "String for search": "Search query",
    Subtitle: "Subtitles",
    "Timer: switch to channel?": "Timer: switch to this channel?",
    "Timeshift: to start of TV program": "Timeshift: to start of program",
    "To begining": "To beginning",
    "To start of TV program / Previous TV program": "Go to start of program / previous program",
    "VOD not supported by provider": "VOD is not supported by this provider"
};
