var keyStrings = {
    " (after changing, load playlist)": " (nach Änderung, Playlist laden)",
    " (after changing, restart player)": " (nach Änderung Player neu starten)",
    " added to category ": " zur Kategorie hinzugefügt ",
    " added to favorites": " zu den Favoriten hinzugefügt",
    " m ": " Min. ",
    " s": " s",
    "??? No channel name": "??? Kein Sendername",
    '"As Is"': '"Unverändert"',
    '"Favorites"': '"Favoriten"',
    '"Sliding" infobar': "Gleitende Infoleiste",
    "&darr;a": "&darr;a",
    "&uarr;A": "&uarr;A",
    "<br/><br/>In archive mode:<br/>": "<br/><br/>Im Archivmodus:<br/>",
    "<br/>Loading STB...": "<br/>STB wird geladen…",
    "<br/>Setup STB...": "<br/>STB wird eingerichtet…",
    "<br>": "<br>",
    "<br><br>": "<br><br>",
    "<br>Add<br>to category": "<br>Zur Kategorie<br>hinzufügen",
    "<br>Add<br>to favorites": "<br>Zu Favoriten<br>hinzufügen",
    "<br>Delete": "<br>Löschen",
    "<br>Down<br>": "<br>Abwärts<br>",
    "<br>Live": "<br>Live",
    "<br>Menu": "<br>Menü",
    "<br>Parental<br>Control": "<br>Jugend-<br>schutz",
    "<br>Pause<br>": "<br>Pause<br>",
    "<br>Previous<br>channel": "<br>Vorheriger<br>Sender",
    "<br>Rewind<br>": "<br>Zurückspulen<br>",
    "<br>Toggle<br>sound track": "<br>Tonspur<br>wechseln",
    "<br>Up<br>": "<br>Aufwärts<br>",
    "1 hour": "1 Stunde",
    "1 minute": "1 Minute",
    "2 hours": "2 Stunden",
    "3 hours": "3 Stunden",
    "10 Seconds": "10 Sekunden",
    "30 minutes": "30 Minuten",
    "A command expired while the player was loading channels.":
        "Ein Befehl ist während des Ladens der Sender abgelaufen.",
    "A command was rejected by the player. Check its provider and settings.":
        "Der Player hat einen Befehl abgelehnt. Prüfen Sie Anbieter und Einstellungen.",
    About: "Über",
    "Access code": "Zugangscode",
    "Access denied. Check the server access code.":
        "Zugriff verweigert. Prüfen Sie den Zugangscode des Servers.",
    "Access key": "Zugangsschlüssel",
    "Access key is required!": "Zugangsschlüssel erforderlich!",
    "Access settings": "Zugangseinstellungen",
    Actions: "Aktionen",
    "Active list": "Aktive Liste",
    Actors: "Darsteller",
    "Add / rename / delete…": "Hinzufügen / umbenennen / löschen…",
    "Add channel to category": "Sender zur Kategorie hinzufügen",
    "Add channel to favorites": "Sender zu Favoriten hinzufügen",
    "Add new list": "Neue Liste hinzufügen",
    "Add to favorites": "Zu Favoriten hinzufügen",
    Age: "Alter",
    All: "Alle",
    "All categories": "Alle Kategorien",
    "All4you.tv": "All4you.tv",
    "All4you.tv settings": "Einstellungen für All4you.tv",
    "Allowlist this Device ID": "Diese Geräte-ID zur Freigabeliste hinzufügen",
    "An IP without a port uses HTTP port 8081. Clear the address or select Disconnect to stop.":
        "Eine IP ohne Port verwendet HTTP-Port 8081. Löschen Sie die Adresse oder wählen Sie Trennen zum Beenden.",
    "API failed, trying M3U...": "API fehlgeschlagen, M3U wird versucht…",
    "API Server": "API-Server",
    "API server URL": "URL des API-Servers",
    "Applying HTTP remote settings...":
        "Einstellungen der HTTP-Fernsteuerung werden angewendet...",
    Archive: "Archiv",
    "Archive - begin": "Archiv — Anfang",
    "Archive hours": "Archivstunden",
    "Archive: ENTER on past programs":
        "Archiv: ENTER bei vergangenen Sendungen",
    "Archive. Channel: ": "Archiv. Sender: ",
    Aspect: "Bildformat",
    Audio: "Audio",
    alhabet: "aäbcdefghijklmnoöpqrsßtuüvwxyz",
    always: "immer",
    "and enter code": "und geben Sie den Code ein",
    Back: "Zurück",
    "Back / Forward for 1 minute": "1 Minute zurück / vor",
    "Background color": "Hintergrundfarbe",
    "Background color of selected item":
        "Hintergrundfarbe des ausgewählten Eintrags",
    "BEST LiST IPTV [HLS Playlist]": "BEST LiST IPTV [HLS Playlist]",
    "BEST LiST IPTV [HLS Playlist] settings":
        "Einstellungen für BEST LiST IPTV [HLS Playlist]",
    "BEST LiST IPTV [Stalker]": "BEST LiST IPTV [Stalker]",
    "BEST LiST IPTV [Stalker] settings":
        "Einstellungen für BEST LiST IPTV [Stalker]",
    "Behavior of %1/%2 buttons in lists":
        "Verhalten der Tasten %1/%2 in Listen",
    "Black screen while switching the channel":
        "Schwarzes Bild beim Senderwechsel",
    Blue: "Blau",
    "Bookmark age: %1 days": "Alter des Lesezeichens: %1 Tage",
    "Buffer Size, s": "Puffergröße, s",
    "Built-in playlist:": "Integrierte Wiedergabeliste:",
    "Built-in playlists": "Integrierte Wiedergabelisten",
    "Button %1 function when viewing": "Funktion der Taste %1 beim Fernsehen",
    "Button function %1 when viewing archive":
        "Funktion der Taste %1 bei Archivwiedergabe",
    "Buttons settings": "Tasteneinstellungen",
    "By alphabet": "Alphabetisch",
    "By time": "Chronologisch",
    "begin/end": "Anfang/Ende",
    "bottom-right": "unten rechts",
    "built-in": "integriert",
    "Call PiP": "PiP öffnen",
    "Call PiP / PiP exchange": "PiP öffnen / PiP tauschen",
    Cancel: "Abbrechen",
    "Cannot delete the last category":
        "Die letzte Kategorie kann nicht gelöscht werden",
    Category: "Kategorie",
    "Category selection": "Kategorieauswahl",
    "Change interface language": "Sprache der Oberfläche ändern",
    "Change provider": "Anbieter wechseln",
    "Change provider - you can change the provider, and it will be remembered at the next start of player!":
        "Anbieter wechseln. Ihre Auswahl wird beim nächsten Start des Players beibehalten.",
    "Change value": "Wert ändern",
    "Channel ": "Sender ",
    "Channel has no EPG": "Sender hat keinen EPG",
    "Channel is not available!!!": "Sender nicht verfügbar !!!",
    "Channel link": "Senderlink",
    "Channel link is required!": "Senderlink erforderlich!",
    "Channel list": "Senderliste",
    "Channel list editing style": "Bearbeitungsmodus der Senderliste",
    "Channel list not received !!!": "Senderliste nicht empfangen !!!",
    "Channel list not received !!!<br/><br/>Enter the provider data and restart the player !!!<br/><br/>":
        "Senderliste nicht empfangen !!!<br/><br/>Geben Sie die Anbieterdaten ein und starten Sie den Player neu !!!<br/><br/>",
    "Channel list settings": "Senderlisteneinstellungen",
    "Channel list. Category: ": "Senderliste. Kategorie: ",
    "Channel parental control": "Sender-Jugendschutz",
    Channels: "Sender",
    "Choose from": "Auswählen aus",
    "Choose language": "Sprache wählen",
    "Choose provider": "Anbieter wählen",
    Classic: "Klassisch",
    "Clear all settings?": "Alle Einstellungen löschen?",
    "Clear settings": "Einstellungen löschen",
    Close: "Schließen",
    "Close PiP": "PiP schließen",
    Color: "Farbe",
    "Color spectrum": "Farbspektrum",
    "Command server": "Befehlsserver",
    "Command server address, device access code, local HTTP control, and remote text entry settings":
        "Adresse des Befehlsservers, Gerätezugangscode, lokale HTTP-Steuerung und Ferntexteingabe",
    "Configure All4you.tv in Settings -> Provider Settings":
        "Konfigurieren Sie All4you.tv unter Einstellungen -> Anbietereinstellungen",
    "Configure BEST LiST IPTV [HLS Playlist] in Settings -> Provider Settings":
        "Konfigurieren Sie BEST LiST IPTV [HLS Playlist] unter Einstellungen -> Anbietereinstellungen",
    "Configure BEST LiST IPTV [Stalker] in Settings -> Provider Settings":
        "Konfigurieren Sie BEST LiST IPTV [Stalker] unter Einstellungen -> Anbietereinstellungen",
    "Configure Diamond TV in Settings -> Provider Settings":
        "Konfigurieren Sie Diamond TV unter Einstellungen -> Anbietereinstellungen",
    "Configure DRVAO in Settings -> Provider Settings":
        "Konfigurieren Sie DRVAO unter Einstellungen -> Anbietereinstellungen",
    "Configure Dragon Media PRO in Settings -> Provider Settings":
        "Konfigurieren Sie Dragon Media PRO unter Einstellungen -> Anbietereinstellungen",
    "Configure Fabryka.TV in Settings -> Provider Settings":
        "Konfigurieren Sie Fabryka.TV unter Einstellungen -> Anbietereinstellungen",
    "Configure Fox-TV in Settings -> Provider Settings":
        "Konfigurieren Sie Fox-TV unter Einstellungen -> Anbietereinstellungen",
    "Configure FXML in Settings -> Provider Settings":
        "Konfigurieren Sie FXML unter Einstellungen -> Anbietereinstellungen",
    "Configure GlanzTV in Settings -> Provider Settings":
        "Konfigurieren Sie GlanzTV unter Einstellungen -> Anbietereinstellungen",
    "Configure GREAT IPTV in Settings -> Provider Settings":
        "Konfigurieren Sie GREAT IPTV unter Einstellungen -> Anbietereinstellungen",
    "Configure IpStream.one in Settings -> Provider Settings":
        "Konfigurieren Sie IpStream.one unter Einstellungen -> Anbietereinstellungen",
    "Configure KORONA TV in Settings -> Provider Settings":
        "Konfigurieren Sie KORONA TV unter Einstellungen -> Anbietereinstellungen",
    "Configure MaxTV in Settings -> Provider Settings":
        "Konfigurieren Sie MaxTV unter Einstellungen -> Anbietereinstellungen",
    "Configure New Look in Settings -> Provider Settings":
        "Konfigurieren Sie New Look unter Einstellungen -> Anbietereinstellungen",
    "Configure OTT Prime ONLINE in Settings -> Provider Settings":
        "Konfigurieren Sie OTT Prime ONLINE unter Einstellungen -> Anbietereinstellungen",
    "Configure POLMEDIA in Settings -> Provider Settings":
        "Konfigurieren Sie POLMEDIA unter Einstellungen -> Anbietereinstellungen",
    "Configure PROST in Settings -> Provider Settings":
        "Konfigurieren Sie PROST unter Einstellungen -> Anbietereinstellungen",
    "Configure RD in Settings -> Provider Settings":
        "Konfigurieren Sie RD unter Einstellungen -> Anbietereinstellungen",
    "Configure RUSSKOETV in Settings -> Provider Settings":
        "Konfigurieren Sie RUSSKOETV unter Einstellungen -> Anbietereinstellungen",
    "Configure Shara.club (ClubTV.pro) in Settings -> Provider Settings":
        "Konfigurieren Sie Shara.club (ClubTV.pro) unter Einstellungen -> Anbietereinstellungen",
    "Configure ShockTv in Settings -> Provider Settings":
        "Konfigurieren Sie ShockTv unter Einstellungen -> Anbietereinstellungen",
    "Configure Tabox in Settings -> Provider Settings":
        "Konfigurieren Sie Tabox unter Einstellungen -> Anbietereinstellungen",
    "Configure TOP-IPTV in Settings -> Provider Settings":
        "Konfigurieren Sie TOP-IPTV unter Einstellungen -> Anbietereinstellungen",
    "Configure Top-Tv in Settings -> Provider Settings":
        "Konfigurieren Sie Top-Tv unter Einstellungen -> Anbietereinstellungen",
    "Configure TV DOSUG in Settings -> Provider Settings":
        "Konfigurieren Sie TV DOSUG unter Einstellungen -> Anbietereinstellungen",
    "Configure TVClub in Settings -> Provider Settings":
        "Konfigurieren Sie TVClub unter Einstellungen -> Anbietereinstellungen",
    "Configure ULTIFL1X in Settings -> Provider Settings":
        "Konfigurieren Sie ULTIFL1X unter Einstellungen -> Anbietereinstellungen",
    "Configure VIP-IP.COM in Settings -> Provider Settings":
        "Konfigurieren Sie VIP-IP.COM unter Einstellungen -> Anbietereinstellungen",
    "Configure Vidok.TV in Settings -> Provider Settings":
        "Konfigurieren Sie Vidok.TV unter Einstellungen -> Anbietereinstellungen",
    "Configure Гомельсат (cbilling) in Settings -> Provider Settings":
        "Konfigurieren Sie Гомельсат (cbilling) unter Einstellungen -> Anbietereinstellungen",
    "Configure МойДом in Settings -> Provider Settings":
        "Konfigurieren Sie МойДом unter Einstellungen -> Anbietereinstellungen",
    "Configure Радуга in Settings -> Provider Settings":
        "Konfigurieren Sie Радуга unter Einstellungen -> Anbietereinstellungen",
    "Configure Шаравоз in Settings -> Provider Settings":
        "Konfigurieren Sie Шаравоз unter Einstellungen -> Anbietereinstellungen",
    Connect: "Verbinden",
    Connected: "Verbunden",
    "Connected. Waiting for the channel list...":
        "Verbunden. Warten auf die Senderliste…",
    "Connecting to Stalker portal...":
        "Verbindung zum Stalker-Portal wird hergestellt…",
    "Connecting...": "Verbindung wird hergestellt…",
    "Continue watching?": "Weiterschauen?",
    "Copy category": "Kategorie kopieren",
    "Copy JSON": "JSON kopieren",
    "Could not connect to the server.": "Verbindung zum Server fehlgeschlagen.",
    "Could not update HTTP remote control.":
        "Die HTTP-Fernsteuerung konnte nicht aktualisiert werden.",
    Country: "Land",
    "Create category": "Kategorie erstellen",
    current: "aktuell",
    "Debug HUD": "Debug-Anzeige",
    "Debug HUD is not available": "Debug-Anzeige nicht verfügbar",
    Delete: "Löschen",
    "Delete category": "Kategorie löschen",
    "Delete channel": "Sender löschen",
    "Delete list": "Liste löschen",
    "Demo — moving test pattern": "Demo — bewegtes Testbild",
    Description: "Beschreibung",
    "Description of remote control buttons":
        "Anleitung zu den Fernbedienungstasten",
    "Device access code": "Gerätezugangscode",
    "Device info:": "Geräteinformationen:",
    "Device MAC is required for KBC (Kinoboom) playlists":
        "Für KBC-Wiedergabelisten (Kinoboom) ist die Geräte-MAC erforderlich",
    "Diamond TV": "Diamond TV",
    "Diamond TV settings": "Einstellungen für Diamond TV",
    Director: "Regie",
    "Disable HTTP remote": "HTTP-Fernsteuerung ausschalten",
    "Disabled by default. Enabling creates a new device access code.":
        "Standardmäßig ausgeschaltet. Beim Einschalten wird ein neuer Gerätezugangscode erstellt.",
    Disconnect: "Trennen",
    Disconnected: "Getrennt",
    "Distance between lines in lists": "Zeilenabstand in Listen",
    "Do you want to exit player?": "Möchten Sie den Player beenden?",
    "Download! Wait ...": "Wird heruntergeladen… bitte warten…",
    DRVAO: "DRVAO",
    "DRVAO settings": "Einstellungen für DRVAO",
    "Dragon Media PRO": "Dragon Media PRO",
    "Dragon Media PRO settings": "Einstellungen für Dragon Media PRO",
    Duration: "Dauer",
    Edit: "Bearbeiten",
    "Edit access key": "Zugangsschlüssel bearbeiten",
    "Edit category name": "Kategoriename bearbeiten",
    "Edit channel link": "Senderlink bearbeiten",
    "Edit playlist data": "Playlist-Daten bearbeiten",
    "Edit VPortal link": "VPortal-Link bearbeiten",
    Editor: "Editor",
    "Enable HTTP remote": "HTTP-Fernsteuerung einschalten",
    English: "Englisch",
    "Enter a password (8 characters).":
        "Geben Sie ein Passwort ein (8 Zeichen).",
    "Enter a playlist URL to access this service.":
        "Geben Sie eine Wiedergabelisten-URL ein, um auf diesen Dienst zuzugreifen.",
    "Enter a server address without spaces or a fragment.":
        "Geben Sie eine Serveradresse ohne Leerzeichen oder Fragment ein.",
    "Enter a username (8 characters).":
        "Geben Sie einen Benutzernamen ein (8 Zeichen).",
    "Enter a username and password to access this service.":
        "Geben Sie einen Benutzernamen und ein Passwort ein, um auf diesen Dienst zuzugreifen.",
    "Enter a valid server address, for example 192.168.1.20:8081.":
        "Geben Sie eine gültige Serveradresse ein, z. B. 192.168.1.20:8081.",
    "Enter access key for": "Zugangsschlüssel eingeben für",
    "Enter an application access key (8 characters).":
        "Geben Sie einen Anwendungszugangsschlüssel ein (8 Zeichen).",
    "Enter an ID and PIN to access this service.":
        "Geben Sie eine ID und PIN ein, um auf diesen Dienst zuzugreifen.",
    "Enter an IPTV token (10 characters).":
        "Geben Sie einen IPTV-Token ein (10 Zeichen).",
    "Enter category name": "Kategorienamen eingeben",
    "Enter MAC address": "MAC-Adresse eingeben",
    "Enter MAC address (e.g. 00:1A:2B:3C:4D:5E)":
        "MAC-Adresse eingeben (z. B. 00:1A:2B:3C:4D:5E)",
    "Enter Media Library URL": "Mediathek-URL eingeben",
    "Enter new category name": "Neuen Kategorienamen eingeben",
    "Enter Provider Code": "Anbietercode eingeben",
    "Enter Provider Code on PC or Phone":
        "Anbietercode am PC oder Telefon eingeben",
    "Enter parental code": "Jugendschutz-PIN eingeben",
    "Enter password": "Passwort eingeben",
    "Enter playlist archive hours": "Archivstunden für Playlist eingeben",
    "Enter playlist Name": "Playlist-Namen eingeben",
    "Enter playlist URL": "Playlist-URL eingeben",
    "Enter Stalker portal URL": "URL des Stalker-Portals eingeben",
    "Enter Stalker portal URL (e.g. http://your-portal:8800)":
        "URL des Stalker-Portals eingeben (z. B. http://your-portal:8800)",
    "Enter Stalker portal URL (e.g. http://your-portal/stalker_portal/c/)":
        "URL des Stalker-Portals eingeben (z. B. http://your-portal/stalker_portal/c/)",
    "Enter the access code separately, not in the server address.":
        "Geben Sie den Zugangscode separat ein, nicht in der Serveradresse.",
    "Enter the command server IP or address.":
        "Geben Sie die IP oder Adresse des Befehlsservers ein.",
    "Enter the full CDN host from the cabinet stream URL (e.g. subdomain.cdn-domain.tld), not a bare subdomain":
        "Geben Sie den vollständigen CDN-Host aus der Stream-URL im Kundenbereich ein (z. B. subdomain.cdn-domain.tld), nicht nur eine Subdomain",
    "Enter the server IP or address and this player's device access code from the server configuration. Saving both starts checking for volume, channel and other commands automatically.":
        "Geben Sie die IP oder Adresse des Servers und den Gerätezugangscode dieses Players aus der Serverkonfiguration ein. Nach dem Speichern beider Angaben werden Lautstärke-, Sender- und andere Befehle automatisch abgefragt.",
    "Enter the server's device access code (32–256 letters, digits, _ or -).":
        "Geben Sie den Gerätezugangscode des Servers ein (32–256 Buchstaben, Ziffern, _ oder -).",
    'Enter the tv.team playlist URL.<br>Playlist type: <b>OTTPlayer</b><br/><br/>The "/playlist.m3u8" suffix is added automatically if omitted.':
        'Geben Sie die URL der tv.team-Wiedergabeliste ein.<br>Wiedergabelistentyp: <b>OTTPlayer</b><br/><br/>Die Endung "/playlist.m3u8" wird automatisch ergänzt, falls sie fehlt.',
    "Enter the VPortal link as shown in the cabinet":
        "Geben Sie den VPortal-Link wie im Kundenbereich angegeben ein",
    "Enter this link in VPortal link. Playlist URL requires an M3U playlist.":
        "Geben Sie diesen Link unter VPortal-Link ein. Die Wiedergabelisten-URL muss auf eine M3U-Wiedergabeliste verweisen.",
    "Enter this player's device access code to connect.":
        "Geben Sie zum Verbinden den Gerätezugangscode dieses Players ein.",
    "Enter username": "Benutzernamen eingeben",
    "Enter value": "Wert eingeben",
    "Enter Xtream server URL": "URL des Xtream-Servers eingeben",
    "Enter Xtream server URL (e.g. https://your-server:8080)":
        "URL des Xtream-Servers eingeben (z. B. https://your-server:8080)",
    EPG: "Programm",
    "EPG and archive. Channel: ": "EPG und Archiv. Sender: ",
    "ERROR!": "Fehler!",
    "Error Code!": "Ungültiger Code!",
    Exit: "Beenden",
    "Exit player": "Player beenden",
    "Export settings": "Einstellungen exportieren",
    "epg.one (Ordered)": "epg.one (geordnet)",
    "epg.one (Standard)": "epg.one (Standard)",
    "epg.one (Thematic)": "epg.one (thematisch)",
    "epgs...": "EPGs…",
    "Fabryka.TV": "Fabryka.TV",
    "Fabryka.TV settings": "Einstellungen für Fabryka.TV",
    "Failed to connect to Stalker portal":
        "Verbindung zum Stalker-Portal fehlgeschlagen",
    "Failed to connect to Xtream API server":
        "Verbindung zum Xtream-API-Server fehlgeschlagen",
    "Failed to get user data!!!":
        "Benutzerdaten konnten nicht abgerufen werden!",
    "Failed to load channel list!": "Senderliste konnte nicht geladen werden!",
    "Failed to load channels from Stalker portal":
        "Sender konnten nicht vom Stalker-Portal geladen werden",
    "Failed to load channels from Xtream API":
        "Sender konnten nicht über die Xtream-API geladen werden",
    "Failed to load!": "Laden fehlgeschlagen!",
    "Favorite lists": "Favoritenlisten",
    Favorites: "Favoriten",
    "File selection is not supported on this device":
        "Dateiauswahl wird auf diesem Gerät nicht unterstützt",
    Filters: "Filter",
    "First Run Setup": "Ersteinrichtung",
    "Font type": "Schriftart",
    "For download settings file open":
        "Zum Herunterladen der Einstellungsdatei öffnen Sie",
    "For enter value open": "Zur Eingabe eines Werts öffnen Sie",
    "For upload settings file open":
        "Zum Hochladen der Einstellungsdatei öffnen Sie",
    "Fox-TV": "Fox-TV",
    "Fox-TV settings": "Einstellungen für Fox-TV",
    FXML: "FXML",
    "FXML settings": "Einstellungen für FXML",
    Genre: "Genre",
    GlanzTV: "GlanzTV",
    "GlanzTV settings": "Einstellungen für GlanzTV",
    "Go to": "Gehe zu",
    "GREAT IPTV": "GREAT IPTV",
    "GREAT IPTV settings": "Einstellungen für GREAT IPTV",
    "Graphical indication": "Grafische Anzeigen",
    Green: "Grün",
    "Hide / Return": "Ausblenden / einblenden",
    "Hide provider settings?": "Anbietereinstellungen ausblenden?",
    "Hide providers?": "Anbieter ausblenden?",
    "History in Media Library": "Verlauf in der Mediathek",
    "History of watched movies": "Wiedergabeverlauf",
    "HTTP port": "HTTP-Port",
    "HTTP remote control is unavailable on this device.":
        "Die HTTP-Fernsteuerung ist auf diesem Gerät nicht verfügbar.",
    ID: "ID",
    "Import settings": "Einstellungen importieren",
    "In live mode: <br/>": "Im Live-Modus:<br/>",
    Info: "Info",
    "Infobar display timeout, s": "Anzeigedauer der Infoleiste, s",
    "Infobar settings": "Einstellungen der Infoleiste",
    Information: "Informationen",
    "Interface credits": "Mitwirkende an der Oberfläche",
    "Interface settings": "Oberflächeneinstellungen",
    "Interface theme": "Oberflächendesign",
    "Interface transparency": "Transparenz der Oberfläche",
    "Invalid channel link! Enter the full host as in the cabinet stream URL (e.g. subdomain.cdn-domain.tld)":
        "Ungültiger Senderlink! Geben Sie den vollständigen Host wie in der Stream-URL im Kundenbereich ein (z. B. subdomain.cdn-domain.tld)",
    "IPTV token": "IPTV-Token",
    "IpStream.one": "IpStream.one",
    "IpStream.one settings": "Einstellungen für IpStream.one",
    Joystick: "Joystick",
    "KBC (Kinoboom) access data": "Zugangsdaten für KBC (Kinoboom)",
    "KORONA TV": "KORONA TV",
    "KORONA TV settings": "Einstellungen für KORONA TV",
    "List created": "Liste erstellt",
    "List deleted": "Liste gelöscht",
    "List location": "Listenposition",
    "List renamed": "Liste umbenannt",
    "List type": "Listentyp",
    "Lists settings": "Listeneinstellungen",
    Live: "Live",
    Load: "Laden",
    "Load built-in playlist:": "Integrierte Wiedergabeliste laden:",
    "Load playlist": "Playlist laden",
    "Load settings": "Einstellungen laden",
    "Load settings from storage": "Einstellungen aus dem Speicher laden",
    "Load:": "Laden:",
    "Loading channels from Xtream API...":
        "Sender werden über die Xtream-API geladen…",
    "Loading channels...": "Sender werden geladen…",
    "Loading from API...": "Laden über die API…",
    "Loading from Edem API...": "Laden über die Edem-API…",
    "Loading M3U playlist...": "M3U-Wiedergabeliste wird geladen…",
    "Loading M3U...": "M3U wird geladen…",
    "Loading via proxy...": "Laden über Proxy…",
    "Loading. Please wait...": "Wird geladen… bitte warten…",
    "Loading...": "Wird geladen…",
    "Local HTTP remote control": "Lokale HTTP-Fernsteuerung",
    "Local URL": "Lokale URL",
    Login: "Anmeldung",
    lang: "Deutsch",
    large: "groß",
    left: "links",
    "left-bottom": "unten links",
    "logos...": "Logos…",
    M3U: "M3U",
    "M3U URL": "M3U-URL",
    "M3U URL (fallback)": "M3U-URL (Ausweichlösung)",
    "MAC address": "MAC-Adresse",
    "Manage lists": "Listen verwalten",
    "Manage settings": "Einstellungen verwalten",
    "Manual setup": "Manuelle Einrichtung",
    MaxTV: "MaxTV",
    "MaxTV settings": "Einstellungen für MaxTV",
    Media: "Medien",
    "Media item is no longer available":
        "Medienelement ist nicht mehr verfügbar",
    "Media Library": "Mediathek",
    "Media Library URL": "Mediathek-URL",
    Menu: "Menü",
    "Menu items settings": "Einstellungen der Menüeinträge",
    "Move category down": "Kategorie nach unten verschieben",
    "Move category up": "Kategorie nach oben verschieben",
    "Move channel down": "Sender nach unten verschieben",
    "Move channel up": "Sender nach oben verschieben",
    "m3u-m3u8 playlists": "M3U-M3U8-Playlists",
    medium: "mittel",
    min: "Min.",
    "New Look": "New Look",
    "New Look settings": "Einstellungen für New Look",
    "New list name": "Name der neuen Liste",
    Next: "Nächste Seite",
    "Next keyboard page": "Nächste Tastaturseite",
    "Next TV program": "Nächste Sendung",
    No: "Nein",
    "No channel name": "Kein Sendername",
    "No saved settings found": "Keine gespeicherten Einstellungen gefunden",
    "Not found": "Nicht gefunden",
    "Not reduce video when showing the list (bugfix)":
        "Video beim Anzeigen der Liste nicht verkleinern (Fehlerbehebung)",
    Nothing: "Nichts",
    "Number of next TV programs in channel list":
        "Anzahl kommender Sendungen in der Senderliste",
    "Number of rows in lists": "Zeilenanzahl in Listen",
    native: "nativ",
    no: "nein",
    "no epg at current time": "Aktuell kein EPG",
    "not set": "nicht festgelegt",
    Off: "Aus",
    Ok: "OK",
    Open: "Öffnen",
    "Open in PiP": "In PiP öffnen",
    "OTT Prime ONLINE": "OTT Prime ONLINE",
    "OTT Prime ONLINE settings": "Einstellungen für OTT Prime ONLINE",
    "OttPlay FOSS %1 is available. Download and install now?":
        "OttPlay FOSS %1 ist verfügbar. Jetzt herunterladen und installieren?",
    "Overwrite current settings?": "Aktuelle Einstellungen überschreiben?",
    off: "aus",
    on: "ein",
    "on ": "ein ",
    "or scan": "oder scannen Sie",
    "Parental control": "Jugendschutz",
    Password: "Passwort",
    Pause: "Pause",
    "Pause/Play": "Pause / Wiedergabe",
    "Permanent clock on screen": "Uhr dauerhaft anzeigen",
    PIN: "PIN",
    "PiP exchange": "PiP tauschen",
    "PiP window position": "Position des PiP-Fensters",
    "PiP window size": "Größe des PiP-Fensters",
    Play: "Wiedergabe",
    "Player and device info": "Player- und Geräteinformationen",
    "Player info:": "Player-Informationen:",
    Playlist: "Playlist",
    "Playlist file": "Playlist-Datei",
    "Playlist is not loading directly...Loading via server...":
        "Playlist wird nicht direkt geladen...Lade über Server...",
    "Playlist Name": "Playlist-Name",
    "Playlist URL": "Playlist-URL",
    POLMEDIA: "POLMEDIA",
    "POLMEDIA settings": "Einstellungen für POLMEDIA",
    "Portal URL": "Portal-URL",
    "Position shift -10 seconds after pause":
        "Nach Pause 10 Sekunden zurückspringen",
    PROST: "PROST",
    "PROST settings": "Einstellungen für PROST",
    Prev: "Zurück",
    "Preview in channel list": "Vorschau in der Senderliste",
    Previous: "Vorherige",
    "Privacy policy": "Datenschutzerklärung",
    "Protect Adult Channels": "Erwachsenensender schützen",
    "Protect Change Provider": "Anbieterwechsel schützen",
    "Protect Settings": "Einstellungen schützen",
    "p...": "p...",
    paging: "seitenweise",
    Quality: "Qualität",
    Rating: "Bewertung",
    RD: "RD",
    "RD settings": "Einstellungen für RD",
    "Reconnecting…": "Verbindung wird erneut hergestellt…",
    Records: "Aufnahmen",
    "Records for channel: ": "Aufnahmen für Sender: ",
    "Records library is empty": "Aufnahmebibliothek ist leer",
    "Records not supported by provider":
        "Aufnahmen werden von diesem Anbieter nicht unterstützt",
    "Release date": "Veröffentlichungsdatum",
    "Remember previous channels": "Vorherige Sender merken",
    "Reminder: %1 — %2 in %3 min": "Erinnerung: %1 — %2 in %3 Min.",
    "Remote (color buttons N/A)": "Fernbedienung ohne Farbtasten",
    "Remote (number buttons N/A)": "Fernbedienung ohne Zifferntasten",
    "Remote control": "Fernsteuerung",
    "Remote session expired": "Fernsitzung abgelaufen",
    "Remote text entry denied": "Ferntexteingabe verweigert",
    "Remote text entry error": "Fehler bei der Ferntexteingabe",
    "Remote text entry not configured": "Ferntexteingabe nicht eingerichtet",
    "Remote text entry requires a Device ID. Ask the server operator to provision one.":
        "Für die Ferntexteingabe ist eine Geräte-ID erforderlich. Bitten Sie den Serverbetreiber, eine bereitzustellen.",
    "Remove timer?": "Timer entfernen?",
    Rename: "Umbenennen",
    "Rename category": "Kategorie umbenennen",
    "Rename to": "Umbenennen in",
    "Repeat parental code": "Jugendschutzcode erneut eingeben",
    "Request sended!": "Anfrage gesendet!",
    "Restart player": "Player neu starten",
    "Restart stream": "Stream neu starten",
    "Restart stream / Live": "Stream neu starten / Live",
    "Resume from archive?": "Aus dem Archiv fortsetzen?",
    "Return to previous channel": "Zum vorherigen Sender zurückkehren",
    Rewind: "Spulen",
    "Rewind step by buttons %1/%2": "Spulschritt für Tasten %1/%2",
    RUSSKOETV: "RUSSKOETV",
    "RUSSKOETV settings": "Einstellungen für RUSSKOETV",
    Russian: "Russisch",
    right: "rechts",
    Saturation: "Sättigung",
    "Save & load channels": "Speichern und Sender laden",
    "Save and load": "Speichern und laden",
    "Save and load channels": "Speichern und Sender laden",
    "Save Settings": "Einstellungen speichern",
    "Save settings": "Einstellungen speichern",
    "Save settings and load channel list":
        "Einstellungen speichern und Senderliste laden",
    "Save settings to storage": "Einstellungen im Speicher sichern",
    Script: "Drehbuch",
    Search: "Suchen",
    "Search programme": "Sendung suchen",
    "Select a stream type:<br>%1": "Wählen Sie einen Streamtyp:<br>%1",
    "Select category to add channel":
        "Kategorie zum Hinzufügen des Senders auswählen",
    "Select color": "Farbe auswählen",
    "Select menu items": "Menüeinträge auswählen",
    "Select playlist": "Playlist auswählen",
    "Select playlist file": "Playlist-Datei auswählen",
    "Select playlist template source for EPG and logos":
        "Vorlagenquelle für EPG und Logos der Wiedergabeliste auswählen",
    "Send request": "Anfrage senden",
    "Send settings": "Einstellungen senden",
    "Send this code from your proxy in the Authorization: Bearer header.":
        "Senden Sie diesen Code vom Proxy im Header Authorization: Bearer.",
    Server: "Server",
    "Server address": "Serveradresse",
    "Server address (for example 192.168.1.20:8081)":
        "Serveradresse (z. B. 192.168.1.20:8081)",
    "Server device access code": "Gerätezugangscode des Servers",
    "Server URL": "Server-URL",
    "Server unavailable. Retrying automatically; check its address and network access.":
        "Server nicht verfügbar. Automatischer Neuversuch; prüfen Sie Adresse und Netzwerkzugriff.",
    Set: "Festlegen",
    "Set parental code": "Jugendschutzcode festlegen",
    "Set timer?": "Timer einstellen?",
    Settings: "Einstellungen",
    "Settings could not be saved":
        "Einstellungen konnten nicht gespeichert werden",
    "Settings loaded from storage": "Einstellungen aus dem Speicher geladen",
    "Settings STB": "STB-Einstellungen",
    "Settings saved": "Einstellungen gespeichert",
    "Settings saved to storage": "Einstellungen im Speicher gesichert",
    "Settings sended!": "Einstellungen gesendet!",
    "Shara.club (ClubTV.pro)": "Shara.club (ClubTV.pro)",
    "Shara.club (ClubTV.pro) settings":
        "Einstellungen für Shara.club (ClubTV.pro)",
    ShockTv: "ShockTv",
    "ShockTv settings": "Einstellungen für ShockTv",
    "Show archive availability in list":
        "Archivverfügbarkeit in der Liste anzeigen",
    "Show channel name in list": "Sendernamen in der Liste anzeigen",
    "Show channel number in list": "Sendernummer in der Liste anzeigen",
    "Show channel selection list": "Senderauswahlliste anzeigen",
    "Show description": "Beschreibung anzeigen",
    "Show EPG and archive for channel": "EPG und Archiv des Senders anzeigen",
    "Show list of channel archive records": "Senderaufnahmen anzeigen",
    "Show list of channel archive records without duplication":
        "Senderaufnahmen ohne Duplikate anzeigen",
    "Show Media Library": "Mediathek anzeigen",
    "Show picons in channel list": "Senderlogos in der Liste anzeigen",
    "Show player menu": "Playermenü anzeigen",
    "Show program name": "Sendungsnamen anzeigen",
    "Show progress in channel list": "Fortschritt in der Senderliste anzeigen",
    "Show provider settings?": "Anbietereinstellungen anzeigen?",
    "Show providers?": "Anbieter anzeigen?",
    "Show rewind window": "Spulfenster anzeigen",
    "Show scrollbar in list": "Bildlaufleiste in Listen anzeigen",
    "Show thumbnails": "Vorschaubilder anzeigen",
    "Show when changing program": "Bei Sendungswechsel anzeigen",
    "Show when rewind": "Beim Spulen anzeigen",
    "Show when switching": "Bei Senderwechsel anzeigen",
    "Sleep timer": "Ausschalttimer",
    "Sort channels": "Sender sortieren",
    "Stalker Portal Provider": "Stalker-Portal-Anbieter",
    "Stalker portal settings": "Stalker-Portal-Einstellungen",
    "Stalker portals": "Stalker-Portale",
    Status: "Status",
    "Stop playback and return to live":
        "Wiedergabe beenden und zu Live zurückkehren",
    "Stream type: %1": "Streamtyp: %1",
    "String for search": "Suchbegriff",
    "Su Mo Tu We Th Fr Sa": "So Mo Di Mi Do Fr Sa",
    Subtitle: "Untertitel",
    Switch: "Umschalten",
    "Switch sound track": "Tonspur wechseln",
    "Switch subtitle": "Untertitel wechseln",
    "Switch to this list": "Zu dieser Liste wechseln",
    "Swop URL": "Swop URL",
    "saved on this device": "auf diesem Gerät gespeichert",
    select: "auswählen",
    small: "klein",
    system: "System",
    Tabox: "Tabox",
    "Tabox settings": "Einstellungen für Tabox",
    "The device ID in the address is invalid.":
        "Die Geräte-ID in der Adresse ist ungültig.",
    "This HTTPS player cannot connect to an HTTP server. Use an HTTPS server or open the player over HTTP.":
        "Dieser HTTPS-Player kann sich nicht mit einem HTTP-Server verbinden. Verwenden Sie einen HTTPS-Server oder öffnen Sie den Player über HTTP.",
    "This Play app requires HTTPS. Ask your provider for an HTTPS playlist or server URL.":
        "Diese Play-App erfordert HTTPS. Fragen Sie Ihren Anbieter nach einer HTTPS-Wiedergabeliste oder Server-URL.",
    Timer: "Timer",
    "Timer: switch to channel?": "Timer: zu diesem Sender wechseln?",
    "Timeshift: one minute back": "Timeshift: eine Minute zurück",
    "Timeshift: to start of TV program": "Timeshift: zum Sendungsbeginn",
    Timezone: "Zeitzone",
    TMDb: "TMDb",
    "TOP-IPTV": "TOP-IPTV",
    "TOP-IPTV settings": "Einstellungen für TOP-IPTV",
    "To begining": "Zum Anfang",
    "To start of TV program / Previous TV program":
        "Zum Sendungsbeginn / zur vorherigen Sendung",
    "Toggle Aspect Ratio": "Bildformat ändern",
    "Toggle on-screen debug HUD": "Debug-Anzeige ein-/ausblenden",
    "Toggle Zoom Mode": "Zoommodus ändern",
    "Top-Tv": "Top-Tv",
    "Top-Tv settings": "Einstellungen für Top-Tv",
    "Try demo": "Demo ausprobieren",
    "TV DOSUG": "TV DOSUG",
    "TV DOSUG settings": "Einstellungen für TV DOSUG",
    TVClub: "TVClub",
    "TVClub settings": "Einstellungen für TVClub",
    "Type of player for streaming": "Player-Typ für Streaming",
    "top-left": "oben links",
    "top-right": "oben rechts",
    transparent: "transparent",
    ULTIFL1X: "ULTIFL1X",
    "ULTIFL1X settings": "Einstellungen für ULTIFL1X",
    "Update installed. Please restart OttPlay FOSS.":
        "Update installiert. Bitte starten Sie OttPlay FOSS neu.",
    "Use an HTTP or HTTPS server address.":
        "Verwenden Sie eine HTTP- oder HTTPS-Serveradresse.",
    "Use HTTP or HTTPS without a username or password in the address.":
        "Verwenden Sie HTTP oder HTTPS ohne Benutzernamen oder Passwort in der Adresse.",
    "Use LEFT/RIGHT to select a control, OK to activate, and UP/DOWN to scroll.":
        "Wählen Sie mit LINKS/RECHTS ein Steuerelement, aktivieren Sie es mit OK und scrollen Sie mit AUF/AB.",
    Username: "Benutzername",
    "Username or password is missing.": "Benutzername oder Passwort fehlt.",
    "VIP-IP.COM": "VIP-IP.COM",
    "VIP-IP.COM settings": "Einstellungen für VIP-IP.COM",
    "Vidok.TV": "Vidok.TV",
    "Vidok.TV settings": "Einstellungen für Vidok.TV",
    "VOD not supported by provider":
        "VOD wird von diesem Anbieter nicht unterstützt",
    "Volume step, %": "Lautstärkeschritt, %",
    "VPortal link": "VPortal-Link",
    "VPortal request failed":
        "VPortal konnte nicht geladen werden. Prüfen Sie Link, Zugangsschlüssel und Verfügbarkeit des Portals.",
    volume: "Lautstärke",
    "Wrong parental code !!!": "Falscher Jugendschutz-PIN !!!",
    "Xtream Codes Provider": "Xtream-Codes-Anbieter",
    "Xtream Codes settings": "Xtream-Codes-Einstellungen",
    Year: "Jahr",
    Yellow: "Gelb",
    Yes: "Ja",
    yes: "ja",
    "Гомельсат (cbilling)": "Гомельсат (cbilling)",
    "Гомельсат (cbilling) settings": "Einstellungen für Гомельсат (cbilling)",
    МойДом: "МойДом",
    "МойДом settings": "Einstellungen für МойДом",
    "Ошибка обработки списка каналов! Проверьте правильность данных!!":
        "Senderliste konnte nicht verarbeitet werden. Prüfen Sie Ihre Anbieterdaten!",
    Радуга: "Радуга",
    "Радуга settings": "Einstellungen für Радуга",
    "Редактирование ID": "ID bearbeiten",
    "Редактирование PIN": "PIN bearbeiten",
    Шаравоз: "Шаравоз",
    "Шаравоз settings": "Einstellungen für Шаравоз",
    "↑↓ Scroll": "↑↓ Scrollen",
};
