var keyStrings = {
    " (after changing, load playlist)": " (nach Änderung, Playlist laden)",
    " added to category ": " zur Kategorie hinzugefügt ",
    " added to favorites": " zu den Favoriten hinzugefügt",
    "??? No channel name": "??? Kein Sendername",
    Actions: "Aktionen",
    "Add channel to category": "Sender zur Kategorie hinzufügen",
    "Add channel to favorites": "Sender zu Favoriten hinzufügen",
    All: "Alle",
    "Applying HTTP remote settings...":
        "Einstellungen der HTTP-Fernsteuerung werden angewendet...",
    "Archive hours": "Archivstunden",
    alhabet: "abcdefghijklmnoöpqrsßtuüvwxyz",
    "Buffer Size, s": "Puffergröße, s",
    "built-in": "integriert",
    Category: "Kategorie",
    "Channel ": "Sender ",
    "Channel is not available!!!": "Sender nicht verfügbar !!!",
    "Channel list": "Senderliste",
    "Channel list not received !!!": "Senderliste nicht empfangen !!!",
    "Channel list not received !!!<br/><br/>Enter the provider data and restart the player !!!<br/><br/>":
        "Senderliste nicht empfangen !!!<br/><br/>Geben Sie die Anbieterdaten ein und starten Sie den Player neu !!!<br/><br/>",
    "Channel list. Category: ": "Senderliste. Kategorie: ",
    "Channel parental control": "Sender-Jugendschutz",
    Close: "Schließen",
    "Could not update HTTP remote control.":
        "Die HTTP-Fernsteuerung konnte nicht aktualisiert werden.",
    "Delete channel": "Sender löschen",
    Description: "Beschreibung",
    "Device access code": "Gerätezugangscode",
    "Disable HTTP remote": "HTTP-Fernsteuerung ausschalten",
    "Disabled by default. Enabling creates a new device access code.":
        "Standardmäßig ausgeschaltet. Beim Einschalten wird ein neuer Gerätezugangscode erstellt.",
    Edit: "Bearbeiten",
    "Edit category name": "Kategoriename bearbeiten",
    "Edit playlist data": "Playlist-Daten bearbeiten",
    Editor: "Editor",
    "Enable HTTP remote": "HTTP-Fernsteuerung einschalten",
    "Enter Media Library URL": "Mediathek-URL eingeben",
    "Enter parental code": "Jugendschutz-PIN eingeben",
    "Enter playlist archive hours": "Archivstunden für Playlist eingeben",
    "Enter playlist Name": "Playlist-Namen eingeben",
    "Enter playlist URL": "Playlist-URL eingeben",
    EPG: "Programm",
    Exit: "Beenden",
    "Failed to load channel list!": "Senderliste konnte nicht geladen werden!",
    Favorites: "Favoriten",
    "HTTP port": "HTTP-Port",
    "HTTP remote control is unavailable on this device.":
        "Die HTTP-Fernsteuerung ist auf diesem Gerät nicht verfügbar.",
    Info: "Info",
    Load: "Laden",
    "Load playlist": "Playlist laden",
    "Local HTTP remote control": "Lokale HTTP-Fernsteuerung",
    lang: "Deutsch",
    "Media Library URL": "Mediathek-URL",
    Menu: "Menü",
    "Move channel down": "Sender nach unten verschieben",
    "Move channel up": "Sender nach oben verschieben",
    "m3u-m3u8 playlists": "M3U-M3U8-Playlists",
    min: "Min.",
    "No channel name": "Kein Sendername",
    Nothing: "Nichts",
    native: "nativ",
    no: "nein",
    "Open in PiP": "Im PiB öffnen",
    off: "aus",
    on: "ein",
    Playlist: "Playlist",
    "Playlist file": "Playlist-Datei",
    "Playlist is not loading directly...Loading via server...":
        "Playlist wird nicht direkt geladen...Lade über Server...",
    "Playlist Name": "Playlist-Name",
    "Playlist URL": "Playlist-URL",
    "Remote control": "Fernsteuerung",
    "Save Settings": "Einstellungen speichern",
    Search: "Suchen",
    "Select category to add channel":
        "Kategorie zum Hinzufügen des Senders auswählen",
    "Select playlist": "Playlist auswählen",
    "Select playlist file": "Playlist-Datei auswählen",
    "Send this code from your proxy in the Authorization: Bearer header.":
        "Senden Sie diesen Code vom Proxy im Header Authorization: Bearer.",
    Settings: "Einstellungen",
    "Settings STB": "STB-Einstellungen",
    "Settings saved": "Einstellungen gespeichert",
    "Stalker portals": "Stalker-Portale",
    "Type of player for streaming": "Player-Typ für Streaming",
    "Wrong parental code !!!": "Falscher Jugendschutz-PIN !!!",
    yes: "ja",
};
