var keyStrings = {
    " (after changing, load playlist)":
        " (μετά την αλλαγή, φορτώστε τη λίστα αναπαραγωγής)",
    " added to category ": " προστέθηκε στην κατηγορία ",
    " added to favorites": " προστέθηκε στα αγαπημένα",
    "??? No channel name": "??? Χωρίς όνομα καναλιού",
    Actions: "Ενέργειες",
    "Add channel to category": "Προσθήκη καναλιού σε κατηγορία",
    "Add channel to favorites": "Προσθήκη καναλιού στα αγαπημένα",
    All: "Όλα",
    "Applying HTTP remote settings...":
        "Εφαρμογή ρυθμίσεων τηλεχειρισμού HTTP...",
    "Archive hours": "Ώρες αρχείου",
    alhabet: "αβγδεζηθικλμνξοπρστυφχψως",
    "Buffer Size, s": "Μέγεθος buffer, s",
    "built-in": "ενσωματωμένο",
    Category: "Κατηγορία",
    "Channel ": "Κανάλι ",
    "Channel is not available!!!": "Το κανάλι δεν είναι διαθέσιμο!!!",
    "Channel list": "Λίστα καναλιών",
    "Channel list not received !!!": "Η λίστα καναλιών δεν ελήφθη!!!",
    "Channel list not received !!!<br/><br/>Enter the provider data and restart the player !!!<br/><br/>":
        "Η λίστα καναλιών δεν ελήφθη!!!<br/><br/>Εισαγάγετε τα δεδομένα παρόχου και επανεκκινήστε τη συσκευή αναπαραγωγής!!!<br/><br/>",
    "Channel list. Category: ": "Λίστα καναλιών. Κατηγορία: ",
    "Channel parental control": "Γονικός έλεγχος καναλιού",
    Close: "Κλείσιμο",
    "Could not update HTTP remote control.":
        "Δεν ήταν δυνατή η ενημέρωση του τηλεχειρισμού HTTP.",
    "Delete channel": "Διαγραφή καναλιού",
    Description: "Περιγραφή",
    "Device access code": "Κωδικός πρόσβασης συσκευής",
    "Disable HTTP remote": "Απενεργοποίηση τηλεχειρισμού HTTP",
    "Disabled by default. Enabling creates a new device access code.":
        "Απενεργοποιημένος από προεπιλογή. Η ενεργοποίηση δημιουργεί νέο κωδικό πρόσβασης συσκευής.",
    Edit: "Επεξεργασία",
    "Edit category name": "Επεξεργασία ονόματος κατηγορίας",
    "Edit playlist data": "Επεξεργασία δεδομένων λίστας αναπαραγωγής",
    Editor: "Επεξεργαστής",
    "Enable HTTP remote": "Ενεργοποίηση τηλεχειρισμού HTTP",
    "Enter Media Library URL": "Εισαγάγετε URL βιβλιοθήκης πολυμέσων",
    "Enter parental code": "Εισαγάγετε γονικό κωδικό",
    "Enter playlist archive hours":
        "Εισαγάγετε ώρες αρχείου για τη λίστα αναπαραγωγής",
    "Enter playlist Name": "Εισαγάγετε όνομα λίστας αναπαραγωγής",
    "Enter playlist URL": "Εισαγάγετε URL λίστας αναπαραγωγής",
    EPG: "Οδηγός TV",
    Exit: "Έξοδος",
    "Failed to load channel list!": "Αποτυχία φόρτωσης λίστας καναλιών!",
    Favorites: "Αγαπημένα",
    "HTTP port": "Θύρα HTTP",
    "HTTP remote control is unavailable on this device.":
        "Ο τηλεχειρισμός HTTP δεν είναι διαθέσιμος σε αυτήν τη συσκευή.",
    Info: "Πληροφορίες",
    Load: "Φόρτωση",
    "Load playlist": "Φόρτωση λίστας αναπαραγωγής",
    "Local HTTP remote control": "Τοπικός τηλεχειρισμός HTTP",
    lang: "Ελληνικά",
    "Media Library URL": "URL βιβλιοθήκης πολυμέσων",
    Menu: "Μενού",
    "Move channel down": "Μετακίνηση καναλιού κάτω",
    "Move channel up": "Μετακίνηση καναλιού πάνω",
    "m3u-m3u8 playlists": "Λίστες αναπαραγωγής m3u-m3u8",
    min: "λεπ",
    "No channel name": "Χωρίς όνομα καναλιού",
    Nothing: "Τίποτα",
    native: "εγγενές",
    no: "όχι",
    "Open in PiP": "Άνοιγμα σε PiP",
    off: "απενεργοποιημένο",
    on: "ενεργός",
    Playlist: "Λίστα αναπαραγωγής",
    "Playlist file": "Αρχείο λίστας αναπαραγωγής",
    "Playlist is not loading directly...Loading via server...":
        "Η λίστα αναπαραγωγής δεν φορτώνεται απευθείας...Φόρτωση μέσω διακομιστή...",
    "Playlist Name": "Όνομα λίστας αναπαραγωγής",
    "Playlist URL": "URL λίστας αναπαραγωγής",
    "Remote control": "Τηλεχειρισμός",
    "Save Settings": "Αποθήκευση ρυθμίσεων",
    Search: "Αναζήτηση",
    "Select category to add channel":
        "Επιλέξτε κατηγορία για προσθήκη καναλιού",
    "Select playlist": "Επιλέξτε λίστα αναπαραγωγής",
    "Select playlist file": "Επιλέξτε αρχείο λίστας αναπαραγωγής",
    "Send this code from your proxy in the Authorization: Bearer header.":
        "Στείλτε αυτόν τον κωδικό από τον διακομιστή μεσολάβησης στην κεφαλίδα Authorization: Bearer.",
    Settings: "Ρυθμίσεις",
    "Settings STB": "Ρυθμίσεις STB",
    "Settings saved": "Οι ρυθμίσεις αποθηκεύτηκαν",
    "Stalker portals": "Πύλες Stalker",
    "Type of player for streaming": "Τύπος προγράμματος αναπαραγωγής για ροή",
    "Wrong parental code !!!": "Λάθος γονικός κωδικός!!!",
    yes: "ναι",
};
