var keyStrings = {
 "lang": "Ελληνικά",
 "alhabet": "αβγδεζηθικλμνξοπρστυφχψως",
 "Channel list. Category: ": "Λίστα καναλιών. Κατηγορία: ",
 "EPG": "Οδηγός TV",
 "Category": "Κατηγορία",
 "Actions": "Ενέργειες",
 "Description": "Περιγραφή",
 "Open in PiP": "Άνοιγμα σε PiP",
 "Move channel up": "Μετακίνηση καναλιού πάνω",
 "Move channel down": "Μετακίνηση καναλιού κάτω",
 "Delete channel": "Διαγραφή καναλιού",
 "Add channel to category": "Προσθήκη καναλιού σε κατηγορία",
 "Add channel to favorites": "Προσθήκη καναλιού στα αγαπημένα",
 "Channel parental control": "Γονικός έλεγχος καναλιού",
 "Channel is not available!!!": "Το κανάλι δεν είναι διαθέσιμο!!!",
 "min": "λεπ",
 "Channel ": "Κανάλι ",
 " added to category ": " προστέθηκε στην κατηγορία ",
 " added to favorites": " προστέθηκε στα αγαπημένα",
 "Favorites": "Αγαπημένα",
 "Select category to add channel": "Επιλέξτε κατηγορία για προσθήκη καναλιού",
 "Enter parental code": "Εισαγάγετε γονικό κωδικό",
 "Wrong parental code !!!": "Λάθος γονικός κωδικός!!!",
 "Close": "Κλείσιμο",
 "Edit category name": "Επεξεργασία ονόματος κατηγορίας",
 "Menu": "Μενού",
 "Channel list": "Λίστα καναλιών",
 "Settings": "Ρυθμίσεις",
 "Settings saved": "Οι ρυθμίσεις αποθηκεύτηκαν",
 "no": "όχι",
 "yes": "ναι",
 "Info": "Πληροφορίες",
 "Nothing": "Τίποτα",
 "Exit": "Έξοδος",
 "off": "απενεργοποιημένο",
 "Failed to load channel list!": "Αποτυχία φόρτωσης λίστας καναλιών!",
 "??? No channel name": "??? Χωρίς όνομα καναλιού",
 "Playlist URL": "URL λίστας αναπαραγωγής",
 "Archive hours": "Ώρες αρχείου",
 "Enter playlist URL": "Εισαγάγετε URL λίστας αναπαραγωγής",
 "Playlist Name": "Όνομα λίστας αναπαραγωγής",
 "Enter playlist Name": "Εισαγάγετε όνομα λίστας αναπαραγωγής",
 "Media Library URL": "URL βιβλιοθήκης πολυμέσων",
 "Enter Media Library URL": "Εισαγάγετε URL βιβλιοθήκης πολυμέσων",
 "Playlist": "Λίστα αναπαραγωγής",
 "Playlist is not loading directly...Loading via server...": "Η λίστα αναπαραγωγής δεν φορτώνεται απευθείας...Φόρτωση μέσω διακομιστή...",
 "Select playlist": "Επιλέξτε λίστα αναπαραγωγής",
 "Edit": "Επεξεργασία",
 "Load": "Φόρτωση",
 "Edit playlist data": "Επεξεργασία δεδομένων λίστας αναπαραγωγής",
 "All": "Όλα",
 "Search": "Αναζήτηση",
 "m3u-m3u8 playlists": "Λίστες αναπαραγωγής m3u-m3u8",
 "Stalker portals": "Πύλες Stalker",
 "Settings STB": "Ρυθμίσεις STB",
 "Type of player for streaming": "Τύπος προγράμματος αναπαραγωγής για ροή",
 "Buffer Size, s": "Μέγεθος buffer, s",
 "Save Settings": "Αποθήκευση ρυθμίσεων",
 "Editor": "Επεξεργαστής",
 "built-in": "ενσωματωμένο",
 "native": "εγγενές",
 "No channel name": "Χωρίς όνομα καναλιού",
 " (after changing, load playlist)": " (μετά την αλλαγή, φορτώστε τη λίστα αναπαραγωγής)",
 "Enter playlist archive hours": "Εισαγάγετε ώρες αρχείου για τη λίστα αναπαραγωγής",
 "Load playlist": "Φόρτωση λίστας αναπαραγωγής",
 "Playlist file": "Αρχείο λίστας αναπαραγωγής",
 "Select playlist file": "Επιλέξτε αρχείο λίστας αναπαραγωγής",
 "Channel list not received !!!<br/><br/>Enter the provider data and restart the player !!!<br/><br/>": "Η λίστα καναλιών δεν ελήφθη!!!<br/><br/>Εισαγάγετε τα δεδομένα παρόχου και επανεκκινήστε τη συσκευή αναπαραγωγής!!!<br/><br/>",
 "Channel list not received !!!": "Η λίστα καναλιών δεν ελήφθη!!!"
};
