var keyStrings = {
    " (after changing, load playlist)": " (לאחר השינוי, טען פלייליסט)",
    " added to category ": " נוסף לקטגוריה ",
    " added to favorites": " נוסף למועדפים",
    "??? No channel name": "??? אין שם ערוץ",
    Actions: "פעולות",
    "Add channel to category": "הוסף ערוץ לקטגוריה",
    "Add channel to favorites": "הוסף ערוץ למועדפים",
    All: "הכל",
    "Archive hours": "שעות ארכיון",
    alhabet: "אבגדהוזחטיכלמנסעפצקרשת",
    "Buffer Size, s": "גודל חוצץ, שנ",
    "built-in": "מובנה",
    Category: "קטגוריה",
    "Channel ": "ערוץ ",
    "Channel is not available!!!": "הערוץ לא זמין!!!",
    "Channel list": "רשימת ערוצים",
    "Channel list not received !!!": "רשימת הערוצים לא התקבלה!!!",
    "Channel list not received !!!<br/><br/>Enter the provider data and restart the player !!!<br/><br/>":
        "רשימת הערוצים לא התקבלה!!!<br/><br/>הזן את נתוני הספק והפעל מחדש את הנגן!!!<br/><br/>",
    "Channel list. Category: ": "רשימת ערוצים. קטגוריה: ",
    "Channel parental control": "בקרת הורים לערוץ",
    Close: "סגור",
    "Delete channel": "מחק ערוץ",
    Description: "תיאור",
    Edit: "ערוך",
    "Edit category name": "ערוך שם קטגוריה",
    "Edit playlist data": "ערוך נתוני פלייליסט",
    Editor: "עורך",
    "Enter Media Library URL": "הזן כתובת ספריית מדיה",
    "Enter parental code": "הזן קוד הורים",
    "Enter playlist archive hours": "הזן שעות ארכיון לפלייליסט",
    "Enter playlist Name": "הזן שם פלייליסט",
    "Enter playlist URL": "הזן כתובת פלייליסט",
    EPG: "לוח שידורים",
    Exit: "יציאה",
    "Failed to load channel list!": "טעינת רשימת הערוצים נכשלה!",
    Favorites: "מועדפים",
    Info: "מידע",
    Load: "טען",
    "Load playlist": "טען פלייליסט",
    lang: "עברית",
    "Media Library URL": "כתובת ספריית מדיה",
    Menu: "תפריט",
    "Move channel down": "הזז ערוץ למטה",
    "Move channel up": "הזז ערוץ למעלה",
    "m3u-m3u8 playlists": "פלייליסטים m3u-m3u8",
    min: "דק",
    "No channel name": "אין שם ערוץ",
    Nothing: "כלום",
    native: "מקורי",
    no: "לא",
    "Open in PiP": "פתח ב-PiP",
    off: "כבוי",
    Playlist: "פלייליסט",
    "Playlist file": "קובץ פלייליסט",
    "Playlist is not loading directly...Loading via server...":
        "הפלייליסט לא נטען ישירות...טעינה דרך השרת...",
    "Playlist Name": "שם פלייליסט",
    "Playlist URL": "כתובת פלייליסט",
    "Save Settings": "שמור הגדרות",
    Search: "חיפוש",
    "Select category to add channel": "בחר קטגוריה להוספת ערוץ",
    "Select playlist": "בחר פלייליסט",
    "Select playlist file": "בחר קובץ פלייליסט",
    Settings: "הגדרות",
    "Settings STB": "הגדרות STB",
    "Settings saved": "ההגדרות נשמרו",
    "Stalker portals": "פורטלי Stalker",
    "Type of player for streaming": "סוג נגן לסטרימינג",
    "Wrong parental code !!!": "קוד הורים שגוי!!!",
    yes: "כן",
};
