var keyStrings = {
    " (after changing, load playlist)": " (לאחר השינוי, טען פלייליסט)",
    " (after changing, restart player)":
        " (יש להפעיל מחדש את הנגן לאחר השינוי)",
    " added to category ": " נוסף לקטגוריה ",
    " added to favorites": " נוסף למועדפים",
    " m ": " דק׳ ",
    " s": " שנ׳",
    "??? No channel name": "??? אין שם ערוץ",
    '"As Is"': '"כמו שהוא"',
    '"Favorites"': '"מועדפים"',
    '"Sliding" infobar': "סרגל מידע נגלל",
    "&darr;a": "&darr;a",
    "&uarr;A": "&uarr;A",
    "<br/><br/>In archive mode:<br/>": "<br/><br/>במצב ארכיון:<br/>",
    "<br/>Loading STB...": "<br/>טוען STB…",
    "<br/>Setup STB...": "<br/>מגדיר STB…",
    "<br>": "<br>",
    "<br><br>": "<br><br>",
    "<br>Add<br>to category": "<br>הוסף<br>לקטגוריה",
    "<br>Add<br>to favorites": "<br>הוסף<br>למועדפים",
    "<br>Delete": "<br>מחק",
    "<br>Down<br>": "<br>למטה<br>",
    "<br>Live": "<br>שידור חי",
    "<br>Menu": "<br>תפריט",
    "<br>Parental<br>Control": "<br>בקרת<br>הורים",
    "<br>Pause<br>": "<br>השהה<br>",
    "<br>Previous<br>channel": "<br>הערוץ<br>הקודם",
    "<br>Rewind<br>": "<br>הרץ אחורה<br>",
    "<br>Toggle<br>sound track": "<br>החלף<br>רצועת שמע",
    "<br>Up<br>": "<br>למעלה<br>",
    "1 hour": "שעה אחת",
    "1 minute": "דקה אחת",
    "2 hours": "שעתיים",
    "3 hours": "3 שעות",
    "10 Seconds": "10 שניות",
    "30 minutes": "30 דקות",
    "A command expired while the player was loading channels.":
        "תוקף פקודה פג בזמן טעינת הערוצים.",
    "A command was rejected by the player. Check its provider and settings.":
        "הנגן דחה פקודה. בדוק את הספק ואת ההגדרות שלו.",
    About: "אודות",
    "Access code": "קוד גישה",
    "Access denied. Check the server access code.":
        "הגישה נדחתה. בדוק את קוד הגישה לשרת.",
    "Access key": "מפתח גישה",
    "Access key is required!": "נדרש מפתח גישה!",
    "Access settings": "הגדרות גישה",
    Actions: "פעולות",
    "Active list": "רשימה פעילה",
    Actors: "שחקנים",
    "Add / rename / delete…": "הוסף / שנה שם / מחק…",
    "Add channel to category": "הוסף ערוץ לקטגוריה",
    "Add channel to favorites": "הוסף ערוץ למועדפים",
    "Add new list": "הוסף רשימה חדשה",
    "Add to favorites": "הוסף למועדפים",
    Age: "גיל",
    All: "הכל",
    "All categories": "כל הקטגוריות",
    "All4you.tv": "All4you.tv",
    "All4you.tv settings": "הגדרות All4you.tv",
    "Allowlist this Device ID": "הוסף את מזהה המכשיר הזה לרשימת המורשים",
    "An IP without a port uses HTTP port 8081. Clear the address or select Disconnect to stop.":
        "כתובת IP ללא יציאה משתמשת ביציאת HTTP 8081. כדי להפסיק, נקה את הכתובת או בחר ניתוק.",
    "API failed, trying M3U...": "ה-API נכשל, מנסה M3U…",
    "API Server": "שרת API",
    "API server URL": "כתובת שרת API",
    "Applying HTTP remote settings...": "החלת הגדרות השליטה דרך HTTP...",
    Archive: "ארכיון",
    "Archive - begin": "ארכיון — התחלה",
    "Archive hours": "שעות ארכיון",
    "Archive: ENTER on past programs": "ארכיון: ENTER על תוכניות קודמות",
    "Archive. Channel: ": "ארכיון. ערוץ: ",
    Aspect: "יחס תמונה",
    Audio: "שמע",
    alhabet: "אבגדהוזחטיכךלמםנןסעפףצץקרשת",
    always: "תמיד",
    "and enter code": "והזן את הקוד",
    Back: "חזרה",
    "Back / Forward for 1 minute": "דלג דקה אחורה / קדימה",
    "Background color": "צבע רקע",
    "Background color of selected item": "צבע הרקע של הפריט הנבחר",
    "BEST LiST IPTV [HLS Playlist]": "BEST LiST IPTV [HLS Playlist]",
    "BEST LiST IPTV [HLS Playlist] settings":
        "הגדרות BEST LiST IPTV [HLS Playlist]",
    "BEST LiST IPTV [Stalker]": "BEST LiST IPTV [Stalker]",
    "BEST LiST IPTV [Stalker] settings": "הגדרות BEST LiST IPTV [Stalker]",
    "Behavior of %1/%2 buttons in lists": "פעולת הלחצנים %1/%2 ברשימות",
    "Black screen while switching the channel": "מסך שחור בעת החלפת ערוצים",
    Blue: "כחול",
    "Bookmark age: %1 days": "גיל הסימנייה: %1 ימים",
    "Buffer Size, s": "גודל חוצץ, שנ",
    "Built-in playlist:": "פלייליסט מובנה:",
    "Built-in playlists": "פלייליסטים מובנים",
    "Button %1 function when viewing": "פעולת הלחצן %1 בזמן צפייה",
    "Button function %1 when viewing archive": "פעולת הלחצן %1 בצפייה בארכיון",
    "Buttons settings": "הגדרות לחצנים",
    "By alphabet": "לפי האלפבית",
    "By time": "לפי זמן",
    "begin/end": "התחלה/סוף",
    "bottom-right": "למטה מימין",
    "built-in": "מובנה",
    "Call PiP": "פתח PiP",
    "Call PiP / PiP exchange": "פתח PiP / החלף PiP",
    Cancel: "ביטול",
    "Cannot delete the last category": "לא ניתן למחוק את הקטגוריה האחרונה",
    Category: "קטגוריה",
    "Category selection": "בחירת קטגוריה",
    "Change interface language": "שנה את שפת הממשק",
    "Change provider": "החלף ספק",
    "Change provider - you can change the provider, and it will be remembered at the next start of player!":
        "החלף ספק. הבחירה שלך תישמר להפעלה הבאה של הנגן.",
    "Change value": "שנה ערך",
    "Channel ": "ערוץ ",
    "Channel has no EPG": "לערוץ אין לוח שידורים",
    "Channel is not available!!!": "הערוץ לא זמין!!!",
    "Channel link": "קישור לערוץ",
    "Channel link is required!": "נדרש קישור לערוץ!",
    "Channel list": "רשימת ערוצים",
    "Channel list editing style": "מצב עריכת רשימת הערוצים",
    "Channel list not received !!!": "רשימת הערוצים לא התקבלה!!!",
    "Channel list not received !!!<br/><br/>Enter the provider data and restart the player !!!<br/><br/>":
        "רשימת הערוצים לא התקבלה!!!<br/><br/>הזן את נתוני הספק והפעל מחדש את הנגן!!!<br/><br/>",
    "Channel list settings": "הגדרות Channel list",
    "Channel list. Category: ": "רשימת ערוצים. קטגוריה: ",
    "Channel parental control": "בקרת הורים לערוץ",
    Channels: "ערוצים",
    "Choose from": "בחר מתוך",
    "Choose language": "בחר שפה",
    "Choose provider": "בחר ספק",
    Classic: "קלאסי",
    "Clear all settings?": "לנקות את כל ההגדרות?",
    "Clear settings": "נקה הגדרות",
    Close: "סגור",
    "Close PiP": "סגור PiP",
    Color: "צבע",
    "Color spectrum": "ספקטרום צבעים",
    "Command server": "שרת פקודות",
    "Command server address, device access code, local HTTP control, and remote text entry settings":
        "כתובת שרת הפקודות, קוד גישה למכשיר, שליטה מקומית דרך HTTP והגדרות הזנת טקסט מרחוק",
    "Configure All4you.tv in Settings -> Provider Settings":
        "הגדר את All4you.tv בהגדרות -> הגדרות ספק",
    "Configure BEST LiST IPTV [HLS Playlist] in Settings -> Provider Settings":
        "הגדר את BEST LiST IPTV [HLS Playlist] בהגדרות -> הגדרות ספק",
    "Configure BEST LiST IPTV [Stalker] in Settings -> Provider Settings":
        "הגדר את BEST LiST IPTV [Stalker] בהגדרות -> הגדרות ספק",
    "Configure Diamond TV in Settings -> Provider Settings":
        "הגדר את Diamond TV בהגדרות -> הגדרות ספק",
    "Configure DRVAO in Settings -> Provider Settings":
        "הגדר את DRVAO בהגדרות -> הגדרות ספק",
    "Configure Dragon Media PRO in Settings -> Provider Settings":
        "הגדר את Dragon Media PRO בהגדרות -> הגדרות ספק",
    "Configure Fabryka.TV in Settings -> Provider Settings":
        "הגדר את Fabryka.TV בהגדרות -> הגדרות ספק",
    "Configure Fox-TV in Settings -> Provider Settings":
        "הגדר את Fox-TV בהגדרות -> הגדרות ספק",
    "Configure FXML in Settings -> Provider Settings":
        "הגדר את FXML בהגדרות -> הגדרות ספק",
    "Configure GlanzTV in Settings -> Provider Settings":
        "הגדר את GlanzTV בהגדרות -> הגדרות ספק",
    "Configure GREAT IPTV in Settings -> Provider Settings":
        "הגדר את GREAT IPTV בהגדרות -> הגדרות ספק",
    "Configure IpStream.one in Settings -> Provider Settings":
        "הגדר את IpStream.one בהגדרות -> הגדרות ספק",
    "Configure KORONA TV in Settings -> Provider Settings":
        "הגדר את KORONA TV בהגדרות -> הגדרות ספק",
    "Configure MaxTV in Settings -> Provider Settings":
        "הגדר את MaxTV בהגדרות -> הגדרות ספק",
    "Configure New Look in Settings -> Provider Settings":
        "הגדר את New Look בהגדרות -> הגדרות ספק",
    "Configure OTT Prime ONLINE in Settings -> Provider Settings":
        "הגדר את OTT Prime ONLINE בהגדרות -> הגדרות ספק",
    "Configure POLMEDIA in Settings -> Provider Settings":
        "הגדר את POLMEDIA בהגדרות -> הגדרות ספק",
    "Configure PROST in Settings -> Provider Settings":
        "הגדר את PROST בהגדרות -> הגדרות ספק",
    "Configure RD in Settings -> Provider Settings":
        "הגדר את RD בהגדרות -> הגדרות ספק",
    "Configure RUSSKOETV in Settings -> Provider Settings":
        "הגדר את RUSSKOETV בהגדרות -> הגדרות ספק",
    "Configure Shara.club (ClubTV.pro) in Settings -> Provider Settings":
        "הגדר את Shara.club (ClubTV.pro) בהגדרות -> הגדרות ספק",
    "Configure ShockTv in Settings -> Provider Settings":
        "הגדר את ShockTv בהגדרות -> הגדרות ספק",
    "Configure Tabox in Settings -> Provider Settings":
        "הגדר את Tabox בהגדרות -> הגדרות ספק",
    "Configure TOP-IPTV in Settings -> Provider Settings":
        "הגדר את TOP-IPTV בהגדרות -> הגדרות ספק",
    "Configure Top-Tv in Settings -> Provider Settings":
        "הגדר את Top-Tv בהגדרות -> הגדרות ספק",
    "Configure TV DOSUG in Settings -> Provider Settings":
        "הגדר את TV DOSUG בהגדרות -> הגדרות ספק",
    "Configure TVClub in Settings -> Provider Settings":
        "הגדר את TVClub בהגדרות -> הגדרות ספק",
    "Configure ULTIFL1X in Settings -> Provider Settings":
        "הגדר את ULTIFL1X בהגדרות -> הגדרות ספק",
    "Configure VIP-IP.COM in Settings -> Provider Settings":
        "הגדר את VIP-IP.COM בהגדרות -> הגדרות ספק",
    "Configure Vidok.TV in Settings -> Provider Settings":
        "הגדר את Vidok.TV בהגדרות -> הגדרות ספק",
    "Configure Гомельсат (cbilling) in Settings -> Provider Settings":
        "הגדר את Гомельсат (cbilling) בהגדרות -> הגדרות ספק",
    "Configure МойДом in Settings -> Provider Settings":
        "הגדר את МойДом בהגדרות -> הגדרות ספק",
    "Configure Радуга in Settings -> Provider Settings":
        "הגדר את Радуга בהגדרות -> הגדרות ספק",
    "Configure Шаравоз in Settings -> Provider Settings":
        "הגדר את Шаравоз בהגדרות -> הגדרות ספק",
    Connect: "התחבר",
    Connected: "מחובר",
    "Connected. Waiting for the channel list...":
        "מחובר. ממתין לרשימת הערוצים…",
    "Connecting to Stalker portal...": "מתחבר לפורטל Stalker…",
    "Connecting...": "מתחבר…",
    "Continue watching?": "להמשיך לצפות?",
    "Copy category": "העתק קטגוריה",
    "Copy JSON": "העתק JSON",
    "Could not connect to the server.": "לא ניתן להתחבר לשרת.",
    "Could not update HTTP remote control.":
        "לא ניתן לעדכן את הגדרות השליטה דרך HTTP.",
    Country: "מדינה",
    "Create category": "צור קטגוריה",
    current: "נוכחי",
    "Debug HUD": "לוח ניפוי שגיאות",
    "Debug HUD is not available": "לוח ניפוי השגיאות אינו זמין",
    Delete: "מחק",
    "Delete category": "מחק קטגוריה",
    "Delete channel": "מחק ערוץ",
    "Delete list": "מחק רשימה",
    "Demo — moving test pattern": "הדגמה — תבנית בדיקה נעה",
    Description: "תיאור",
    "Description of remote control buttons": "מדריך לחצני השלט",
    "Device access code": "קוד גישה למכשיר",
    "Device info:": "פרטי המכשיר:",
    "Device MAC is required for KBC (Kinoboom) playlists":
        "נדרשת כתובת MAC של המכשיר לפלייליסטים של KBC (Kinoboom)",
    "Diamond TV": "Diamond TV",
    "Diamond TV settings": "הגדרות Diamond TV",
    Director: "במאי",
    "Disable HTTP remote": "כיבוי שליטת HTTP",
    "Disabled by default. Enabling creates a new device access code.":
        "כבוי כברירת מחדל. ההפעלה יוצרת קוד גישה חדש למכשיר.",
    Disconnect: "ניתוק",
    Disconnected: "מנותק",
    "Distance between lines in lists": "מרווח שורות ברשימות",
    "Do you want to exit player?": "האם לצאת מהנגן?",
    "Download! Wait ...": "מוריד… נא להמתין…",
    DRVAO: "DRVAO",
    "DRVAO settings": "הגדרות DRVAO",
    "Dragon Media PRO": "Dragon Media PRO",
    "Dragon Media PRO settings": "הגדרות Dragon Media PRO",
    Duration: "משך",
    Edit: "ערוך",
    "Edit access key": "ערוך מפתח גישה",
    "Edit category name": "ערוך שם קטגוריה",
    "Edit channel link": "ערוך קישור לערוץ",
    "Edit playlist data": "ערוך נתוני פלייליסט",
    "Edit VPortal link": "ערוך קישור VPortal",
    Editor: "עורך",
    "Enable HTTP remote": "הפעלת שליטת HTTP",
    English: "אנגלית",
    "Enter a password (8 characters).": "הזן סיסמה (8 תווים).",
    "Enter a playlist URL to access this service.":
        "הזן כתובת פלייליסט כדי לגשת לשירות זה.",
    "Enter a server address without spaces or a fragment.":
        "הזן כתובת שרת ללא רווחים או מקטע אחרי #.",
    "Enter a username (8 characters).": "הזן שם משתמש (8 תווים).",
    "Enter a username and password to access this service.":
        "הזן שם משתמש וסיסמה כדי לגשת לשירות זה.",
    "Enter a valid server address, for example 192.168.1.20:8081.":
        "הזן כתובת שרת תקינה, למשל 192.168.1.20:8081.",
    "Enter access key for": "הזן מפתח גישה עבור",
    "Enter an application access key (8 characters).":
        "הזן מפתח גישה ליישום (8 תווים).",
    "Enter an ID and PIN to access this service.":
        "הזן מזהה ו-PIN כדי לגשת לשירות זה.",
    "Enter an IPTV token (10 characters).": "הזן אסימון IPTV (10 תווים).",
    "Enter category name": "הזן שם קטגוריה",
    "Enter MAC address": "הזן כתובת MAC",
    "Enter MAC address (e.g. 00:1A:2B:3C:4D:5E)":
        "הזן כתובת MAC (למשל 00:1A:2B:3C:4D:5E)",
    "Enter Media Library URL": "הזן כתובת ספריית מדיה",
    "Enter new category name": "הזן שם חדש לקטגוריה",
    "Enter Provider Code": "הזן קוד ספק",
    "Enter Provider Code on PC or Phone": "הזן קוד ספק במחשב או בטלפון",
    "Enter parental code": "הזן קוד הורים",
    "Enter password": "הזן סיסמה",
    "Enter playlist archive hours": "הזן שעות ארכיון לפלייליסט",
    "Enter playlist Name": "הזן שם פלייליסט",
    "Enter playlist URL": "הזן כתובת פלייליסט",
    "Enter Stalker portal URL": "הזן כתובת פורטל Stalker",
    "Enter Stalker portal URL (e.g. http://your-portal:8800)":
        "הזן כתובת פורטל Stalker (למשל http://your-portal:8800)",
    "Enter Stalker portal URL (e.g. http://your-portal/stalker_portal/c/)":
        "הזן כתובת פורטל Stalker (למשל http://your-portal/stalker_portal/c/)",
    "Enter the access code separately, not in the server address.":
        "הזן את קוד הגישה בנפרד, ולא בכתובת השרת.",
    "Enter the command server IP or address.":
        "הזן את כתובת ה-IP או את כתובת שרת הפקודות.",
    "Enter the full CDN host from the cabinet stream URL (e.g. subdomain.cdn-domain.tld), not a bare subdomain":
        "הזן את שם מארח ה-CDN המלא מכתובת השידור באזור האישי (למשל subdomain.cdn-domain.tld), ולא רק תת-דומיין",
    "Enter the server IP or address and this player's device access code from the server configuration. Saving both starts checking for volume, channel and other commands automatically.":
        "הזן את כתובת ה-IP או כתובת השרת ואת קוד הגישה של מכשיר זה מתוך הגדרות השרת. שמירת שניהם מתחילה בדיקה אוטומטית של פקודות עוצמת קול, ערוצים ופקודות נוספות.",
    "Enter the server's device access code (32–256 letters, digits, _ or -).":
        "הזן את קוד הגישה למכשיר שבשרת (32–256 אותיות, ספרות, _ או -).",
    'Enter the tv.team playlist URL.<br>Playlist type: <b>OTTPlayer</b><br/><br/>The "/playlist.m3u8" suffix is added automatically if omitted.':
        'הזן את כתובת הפלייליסט של tv.team.<br>סוג הפלייליסט: <b>OTTPlayer</b><br/><br/>הסיומת "/playlist.m3u8" מתווספת אוטומטית אם היא חסרה.',
    "Enter the VPortal link as shown in the cabinet":
        "הזן את קישור VPortal כפי שהוא מופיע באזור האישי",
    "Enter this link in VPortal link. Playlist URL requires an M3U playlist.":
        "הזן קישור זה בשדה קישור VPortal. כתובת הפלייליסט דורשת פלייליסט M3U.",
    "Enter this player's device access code to connect.":
        "הזן את קוד הגישה למכשיר של נגן זה כדי להתחבר.",
    "Enter username": "הזן שם משתמש",
    "Enter value": "הזן ערך",
    "Enter Xtream server URL": "הזן כתובת שרת Xtream",
    "Enter Xtream server URL (e.g. https://your-server:8080)":
        "הזן כתובת שרת Xtream (למשל https://your-server:8080)",
    EPG: "לוח שידורים",
    "EPG and archive. Channel: ": "לוח שידורים וארכיון. ערוץ: ",
    "ERROR!": "שגיאה!",
    "Error Code!": "קוד לא תקין!",
    Exit: "יציאה",
    "Exit player": "צא מהנגן",
    "Export settings": "ייצא הגדרות",
    "epg.one (Ordered)": "epg.one (ממוין)",
    "epg.one (Standard)": "epg.one (רגיל)",
    "epg.one (Thematic)": "epg.one (נושאי)",
    "epgs...": "לוחות שידורים…",
    "Fabryka.TV": "Fabryka.TV",
    "Fabryka.TV settings": "הגדרות Fabryka.TV",
    "Failed to connect to Stalker portal": "ההתחברות לפורטל Stalker נכשלה",
    "Failed to connect to Xtream API server": "ההתחברות לשרת Xtream API נכשלה",
    "Failed to get user data!!!": "שליפת פרטי המשתמש נכשלה!",
    "Failed to load channel list!": "טעינת רשימת הערוצים נכשלה!",
    "Failed to load channels from Stalker portal":
        "טעינת הערוצים מפורטל Stalker נכשלה",
    "Failed to load channels from Xtream API":
        "טעינת הערוצים מ-Xtream API נכשלה",
    "Failed to load!": "הטעינה נכשלה!",
    "Favorite lists": "רשימות מועדפים",
    Favorites: "מועדפים",
    "File selection is not supported on this device":
        "בחירת קבצים אינה נתמכת במכשיר זה",
    Filters: "מסננים",
    "First Run Setup": "הגדרות הפעלה ראשונה",
    "Font type": "סוג גופן",
    "For download settings file open": "כדי להוריד את קובץ ההגדרות, פתח",
    "For enter value open": "כדי להזין ערך, פתח",
    "For upload settings file open": "כדי להעלות את קובץ ההגדרות, פתח",
    "Fox-TV": "Fox-TV",
    "Fox-TV settings": "הגדרות Fox-TV",
    FXML: "FXML",
    "FXML settings": "הגדרות FXML",
    Genre: "ז'אנר",
    GlanzTV: "GlanzTV",
    "GlanzTV settings": "הגדרות GlanzTV",
    "Go to": "עבור אל",
    "GREAT IPTV": "GREAT IPTV",
    "GREAT IPTV settings": "הגדרות GREAT IPTV",
    "Graphical indication": "מחוונים גרפיים",
    Green: "ירוק",
    "Hide / Return": "הסתר / הצג",
    "Hide provider settings?": "להסתיר את הגדרות הספק?",
    "Hide providers?": "להסתיר ספקים?",
    "History in Media Library": "היסטוריה בספריית המדיה",
    "History of watched movies": "היסטוריית צפייה",
    "HTTP port": "יציאת HTTP",
    "HTTP remote control is unavailable on this device.":
        "שליטה דרך HTTP אינה זמינה במכשיר זה.",
    ID: "מזהה",
    "Import settings": "ייבא הגדרות",
    "In live mode: <br/>": "במצב שידור חי:<br/>",
    Info: "מידע",
    "Infobar display timeout, s": "משך הצגת סרגל המידע, שנ׳",
    "Infobar settings": "הגדרות סרגל מידע",
    Information: "מידע",
    "Interface credits": "יוצרי הממשק",
    "Interface settings": "הגדרות ממשק",
    "Interface theme": "ערכת נושא לממשק",
    "Interface transparency": "שקיפות הממשק",
    "Invalid channel link! Enter the full host as in the cabinet stream URL (e.g. subdomain.cdn-domain.tld)":
        "קישור הערוץ אינו תקין! הזן את שם המארח המלא כמו בכתובת השידור באזור האישי (למשל subdomain.cdn-domain.tld)",
    "IPTV token": "אסימון IPTV",
    "IpStream.one": "IpStream.one",
    "IpStream.one settings": "הגדרות IpStream.one",
    Joystick: "ג'ויסטיק",
    "KBC (Kinoboom) access data": "פרטי גישה ל-KBC (Kinoboom)",
    "KORONA TV": "KORONA TV",
    "KORONA TV settings": "הגדרות KORONA TV",
    "List created": "הרשימה נוצרה",
    "List deleted": "הרשימה נמחקה",
    "List location": "מיקום הרשימה",
    "List renamed": "שם הרשימה שונה",
    "List type": "סוג רשימה",
    "Lists settings": "הגדרות רשימות",
    Live: "שידור חי",
    Load: "טען",
    "Load built-in playlist:": "טען פלייליסט מובנה:",
    "Load playlist": "טען פלייליסט",
    "Load settings": "הגדרות Load",
    "Load settings from storage": "טען הגדרות מהאחסון",
    "Load:": "טען:",
    "Loading channels from Xtream API...": "טוען ערוצים מ-Xtream API…",
    "Loading channels...": "טוען ערוצים…",
    "Loading from API...": "טוען מה-API…",
    "Loading from Edem API...": "טוען מ-Edem API…",
    "Loading M3U playlist...": "טוען פלייליסט M3U…",
    "Loading M3U...": "טוען M3U…",
    "Loading via proxy...": "טוען דרך פרוקסי…",
    "Loading. Please wait...": "טוען… נא להמתין…",
    "Loading...": "טוען…",
    "Local HTTP remote control": "שליטה מקומית דרך HTTP",
    "Local URL": "כתובת מקומית",
    Login: "כניסה",
    lang: "עברית",
    large: "גדול",
    left: "שמאל",
    "left-bottom": "למטה משמאל",
    "logos...": "סמלים…",
    M3U: "M3U",
    "M3U URL": "כתובת M3U",
    "M3U URL (fallback)": "כתובת M3U (חלופית)",
    "MAC address": "כתובת MAC",
    "Manage lists": "נהל רשימות",
    "Manage settings": "נהל הגדרות",
    "Manual setup": "הגדרה ידנית",
    MaxTV: "MaxTV",
    "MaxTV settings": "הגדרות MaxTV",
    Media: "מדיה",
    "Media item is no longer available": "פריט המדיה אינו זמין עוד",
    "Media Library": "ספריית מדיה",
    "Media Library URL": "כתובת ספריית מדיה",
    Menu: "תפריט",
    "Menu items settings": "הגדרות פריטי תפריט",
    "Move category down": "הזז קטגוריה למטה",
    "Move category up": "הזז קטגוריה למעלה",
    "Move channel down": "הזז ערוץ למטה",
    "Move channel up": "הזז ערוץ למעלה",
    "m3u-m3u8 playlists": "פלייליסטים m3u-m3u8",
    medium: "בינוני",
    min: "דק",
    "New Look": "New Look",
    "New Look settings": "הגדרות New Look",
    "New list name": "שם רשימה חדשה",
    Next: "העמוד הבא",
    "Next keyboard page": "העמוד הבא במקלדת",
    "Next TV program": "התוכנית הבאה",
    No: "לא",
    "No channel name": "אין שם ערוץ",
    "No saved settings found": "לא נמצאו הגדרות שמורות",
    "Not found": "לא נמצא",
    "Not reduce video when showing the list (bugfix)":
        "אל תקטין את הווידאו בעת הצגת הרשימה (תיקון תקלה)",
    Nothing: "כלום",
    "Number of next TV programs in channel list":
        "מספר התוכניות הבאות ברשימת הערוצים",
    "Number of rows in lists": "מספר השורות ברשימות",
    native: "מקורי",
    no: "לא",
    "no epg at current time": "אין לוח שידורים לזמן הנוכחי",
    "not set": "לא הוגדר",
    Off: "כבוי",
    Ok: "אישור",
    Open: "פתח",
    "Open in PiP": "פתח ב-PiP",
    "OTT Prime ONLINE": "OTT Prime ONLINE",
    "OTT Prime ONLINE settings": "הגדרות OTT Prime ONLINE",
    "OttPlay FOSS %1 is available. Download and install now?":
        "OttPlay FOSS %1 זמין. להוריד ולהתקין עכשיו?",
    "Overwrite current settings?": "לדרוס את ההגדרות הנוכחיות?",
    off: "כבוי",
    on: "פעיל",
    "on ": "פעיל ",
    "or scan": "או סרוק",
    "Parental control": "בקרת הורים",
    Password: "סיסמה",
    Pause: "השהה",
    "Pause/Play": "השהה / נגן",
    "Permanent clock on screen": "הצג תמיד שעון על המסך",
    PIN: "PIN",
    "PiP exchange": "החלף PiP",
    "PiP window position": "מיקום חלון PiP",
    "PiP window size": "גודל חלון PiP",
    Play: "נגן",
    "Player and device info": "פרטי הנגן והמכשיר",
    "Player info:": "פרטי הנגן:",
    Playlist: "פלייליסט",
    "Playlist file": "קובץ פלייליסט",
    "Playlist is not loading directly...Loading via server...":
        "הפלייליסט לא נטען ישירות...טעינה דרך השרת...",
    "Playlist Name": "שם פלייליסט",
    "Playlist URL": "כתובת פלייליסט",
    POLMEDIA: "POLMEDIA",
    "POLMEDIA settings": "הגדרות POLMEDIA",
    "Portal URL": "כתובת פורטל",
    "Position shift -10 seconds after pause": "חזור 10 שניות אחורה לאחר השהיה",
    PROST: "PROST",
    "PROST settings": "הגדרות PROST",
    Prev: "הקודם",
    "Preview in channel list": "תצוגה מקדימה ברשימת הערוצים",
    Previous: "הקודם",
    "Privacy policy": "מדיניות פרטיות",
    "Protect Adult Channels": "הגן על ערוצי מבוגרים",
    "Protect Change Provider": "הגן על החלפת ספק",
    "Protect Settings": "הגן על ההגדרות",
    "p...": "p...",
    paging: "דפדוף בין עמודים",
    Quality: "איכות",
    Rating: "דירוג",
    RD: "RD",
    "RD settings": "הגדרות RD",
    "Reconnecting…": "מתחבר מחדש…",
    Records: "הקלטות",
    "Records for channel: ": "הקלטות לערוץ: ",
    "Records library is empty": "ספריית ההקלטות ריקה",
    "Records not supported by provider": "הספק הזה אינו תומך בהקלטות",
    "Release date": "תאריך יציאה",
    "Remember previous channels": "זכור ערוצים קודמים",
    "Reminder: %1 — %2 in %3 min": "תזכורת: %1 — %2 בעוד %3 דקות",
    "Remote (color buttons N/A)": "שלט (ללא לחצנים צבעוניים)",
    "Remote (number buttons N/A)": "שלט (ללא לחצני מספרים)",
    "Remote control": "שליטה מרחוק",
    "Remote session expired": "תוקף ההפעלה המרוחקת פג",
    "Remote text entry denied": "הזנת טקסט מרחוק נדחתה",
    "Remote text entry error": "שגיאה בהזנת טקסט מרחוק",
    "Remote text entry not configured": "הזנת טקסט מרחוק לא הוגדרה",
    "Remote text entry requires a Device ID. Ask the server operator to provision one.":
        "הזנת טקסט מרחוק דורשת מזהה מכשיר. בקש ממפעיל השרת להקצות מזהה.",
    "Remove timer?": "להסיר את הטיימר?",
    Rename: "שנה שם",
    "Rename category": "שנה שם קטגוריה",
    "Rename to": "שנה שם ל-",
    "Repeat parental code": "הזן שוב קוד הורים",
    "Request sended!": "הבקשה נשלחה!",
    "Restart player": "הפעל מחדש את הנגן",
    "Restart stream": "הפעל מחדש את השידור",
    "Restart stream / Live": "הפעל שידור מחדש / שידור חי",
    "Resume from archive?": "להמשיך מהארכיון?",
    "Return to previous channel": "חזור לערוץ הקודם",
    Rewind: "דלג בזמן",
    "Rewind step by buttons %1/%2": "מרווח דילוג לאחור בלחצנים %1/%2",
    RUSSKOETV: "RUSSKOETV",
    "RUSSKOETV settings": "הגדרות RUSSKOETV",
    Russian: "רוסית",
    right: "ימין",
    Saturation: "רוויה",
    "Save & load channels": "שמור וטען ערוצים",
    "Save and load": "שמור וטען",
    "Save and load channels": "שמור וטען ערוצים",
    "Save Settings": "שמור הגדרות",
    "Save settings": "שמור הגדרות",
    "Save settings and load channel list": "שמור הגדרות וטען רשימת ערוצים",
    "Save settings to storage": "שמור הגדרות באחסון",
    Script: "תסריט",
    Search: "חיפוש",
    "Search programme": "חפש תוכנית",
    "Select a stream type:<br>%1": "בחר סוג שידור:<br>%1",
    "Select category to add channel": "בחר קטגוריה להוספת ערוץ",
    "Select color": "בחר צבע",
    "Select menu items": "בחר פריטי תפריט",
    "Select playlist": "בחר פלייליסט",
    "Select playlist file": "בחר קובץ פלייליסט",
    "Select playlist template source for EPG and logos":
        "בחר מקור תבנית פלייליסט ללוח שידורים ולסמלים",
    "Send request": "שלח בקשה",
    "Send settings": "שלח הגדרות",
    "Send this code from your proxy in the Authorization: Bearer header.":
        "יש לשלוח קוד זה מהפרוקסי בכותרת Authorization: Bearer.",
    Server: "שרת",
    "Server address": "כתובת שרת",
    "Server address (for example 192.168.1.20:8081)":
        "כתובת שרת (למשל 192.168.1.20:8081)",
    "Server device access code": "קוד גישה למכשיר בשרת",
    "Server URL": "כתובת URL של השרת",
    "Server unavailable. Retrying automatically; check its address and network access.":
        "השרת אינו זמין. ניסיון חוזר יבוצע אוטומטית; בדוק את הכתובת ואת הגישה לרשת.",
    Set: "הגדר",
    "Set parental code": "הגדר קוד הורים",
    "Set timer?": "להגדיר טיימר?",
    Settings: "הגדרות",
    "Settings could not be saved": "לא ניתן לשמור את ההגדרות",
    "Settings loaded from storage": "ההגדרות נטענו מהאחסון",
    "Settings STB": "הגדרות STB",
    "Settings saved": "ההגדרות נשמרו",
    "Settings saved to storage": "ההגדרות נשמרו באחסון",
    "Settings sended!": "ההגדרות נשלחו!",
    "Shara.club (ClubTV.pro)": "Shara.club (ClubTV.pro)",
    "Shara.club (ClubTV.pro) settings": "הגדרות Shara.club (ClubTV.pro)",
    ShockTv: "ShockTv",
    "ShockTv settings": "הגדרות ShockTv",
    "Show archive availability in list": "הצג זמינות ארכיון ברשימה",
    "Show channel name in list": "הצג שם ערוץ ברשימה",
    "Show channel number in list": "הצג מספר ערוץ ברשימה",
    "Show channel selection list": "הצג רשימת בחירת ערוצים",
    "Show description": "הצג תיאור",
    "Show EPG and archive for channel": "הצג לוח שידורים וארכיון לערוץ",
    "Show list of channel archive records": "הצג הקלטות ערוץ",
    "Show list of channel archive records without duplication":
        "הצג הקלטות ערוץ ללא כפילויות",
    "Show Media Library": "הצג ספריית מדיה",
    "Show picons in channel list": "הצג סמלי ערוצים ברשימה",
    "Show player menu": "הצג את תפריט הנגן",
    "Show program name": "הצג שם תוכנית",
    "Show progress in channel list": "הצג התקדמות ברשימת הערוצים",
    "Show provider settings?": "להציג את הגדרות הספק?",
    "Show providers?": "להציג ספקים?",
    "Show rewind window": "הצג חלון דילוג בזמן",
    "Show scrollbar in list": "הצג פס גלילה ברשימות",
    "Show thumbnails": "הצג תמונות ממוזערות",
    "Show when changing program": "הצג בעת שינוי תוכנית",
    "Show when rewind": "הצג בעת הרצה לאחור",
    "Show when switching": "הצג בעת החלפת ערוצים",
    "Sleep timer": "טיימר שינה",
    "Sort channels": "מיין ערוצים",
    "Stalker Portal Provider": "ספק פורטל Stalker",
    "Stalker portal settings": "הגדרות פורטל Stalker",
    "Stalker portals": "פורטלי Stalker",
    Status: "מצב",
    "Stop playback and return to live": "הפסק ניגון וחזור לשידור חי",
    "Stream type: %1": "סוג שידור: %1",
    "String for search": "שאילתת חיפוש",
    "Su Mo Tu We Th Fr Sa": "א ב ג ד ה ו ש",
    Subtitle: "כתוביות",
    Switch: "החלף",
    "Switch sound track": "החלף רצועת שמע",
    "Switch subtitle": "החלף כתוביות",
    "Switch to this list": "עבור לרשימה זו",
    "Swop URL": "כתובת Swop",
    "saved on this device": "נשמר במכשיר זה",
    select: "בחר",
    small: "קטן",
    system: "מערכת",
    Tabox: "Tabox",
    "Tabox settings": "הגדרות Tabox",
    "The device ID in the address is invalid.": "מזהה המכשיר בכתובת אינו תקין.",
    "This HTTPS player cannot connect to an HTTP server. Use an HTTPS server or open the player over HTTP.":
        "נגן HTTPS זה אינו יכול להתחבר לשרת HTTP. השתמש בשרת HTTPS או פתח את הנגן דרך HTTP.",
    "This Play app requires HTTPS. Ask your provider for an HTTPS playlist or server URL.":
        "יישום Play זה דורש HTTPS. בקש מהספק פלייליסט או כתובת שרת ב-HTTPS.",
    Timer: "טיימר",
    "Timer: switch to channel?": "טיימר: לעבור לערוץ זה?",
    "Timeshift: one minute back": "השהיית שידור: דקה אחורה",
    "Timeshift: to start of TV program": "השהיית שידור: לתחילת התוכנית",
    Timezone: "אזור זמן",
    TMDb: "TMDb",
    "TOP-IPTV": "TOP-IPTV",
    "TOP-IPTV settings": "הגדרות TOP-IPTV",
    "To begining": "להתחלה",
    "To start of TV program / Previous TV program":
        "עבור לתחילת התוכנית / לתוכנית הקודמת",
    "Toggle Aspect Ratio": "שנה יחס תמונה",
    "Toggle on-screen debug HUD": "הצג / הסתר לוח ניפוי שגיאות",
    "Toggle Zoom Mode": "שנה מצב זום",
    "Top-Tv": "Top-Tv",
    "Top-Tv settings": "הגדרות Top-Tv",
    "Try demo": "נסה הדגמה",
    "TV DOSUG": "TV DOSUG",
    "TV DOSUG settings": "הגדרות TV DOSUG",
    TVClub: "TVClub",
    "TVClub settings": "הגדרות TVClub",
    "Type of player for streaming": "סוג נגן לסטרימינג",
    "top-left": "למעלה משמאל",
    "top-right": "למעלה מימין",
    transparent: "שקוף",
    ULTIFL1X: "ULTIFL1X",
    "ULTIFL1X settings": "הגדרות ULTIFL1X",
    "Update installed. Please restart OttPlay FOSS.":
        "העדכון הותקן. הפעל מחדש את OttPlay FOSS.",
    "Use an HTTP or HTTPS server address.": "השתמש בכתובת שרת HTTP או HTTPS.",
    "Use HTTP or HTTPS without a username or password in the address.":
        "השתמש ב-HTTP או HTTPS ללא שם משתמש או סיסמה בכתובת.",
    "Use LEFT/RIGHT to select a control, OK to activate, and UP/DOWN to scroll.":
        "השתמש בשמאל/ימין לבחירת פקד, ב-OK להפעלתו ובמעלה/מטה לגלילה.",
    Username: "שם משתמש",
    "Username or password is missing.": "שם המשתמש או הסיסמה חסרים.",
    "VIP-IP.COM": "VIP-IP.COM",
    "VIP-IP.COM settings": "הגדרות VIP-IP.COM",
    "Vidok.TV": "Vidok.TV",
    "Vidok.TV settings": "הגדרות Vidok.TV",
    "VOD not supported by provider": "הספק הזה אינו תומך ב-VOD",
    "Volume step, %": "מרווח עוצמת קול, %",
    "VPortal link": "קישור VPortal",
    "VPortal request failed":
        "לא ניתן לטעון את VPortal. בדוק את הקישור, מפתח הגישה וזמינות הפורטל.",
    volume: "עוצמת קול",
    "Wrong parental code !!!": "קוד הורים שגוי!!!",
    "Xtream Codes Provider": "ספק Xtream Codes",
    "Xtream Codes settings": "הגדרות Xtream Codes",
    Year: "שנה",
    Yellow: "צהוב",
    Yes: "כן",
    yes: "כן",
    "Гомельсат (cbilling)": "Гомельсат (cbilling)",
    "Гомельсат (cbilling) settings": "הגדרות Гомельсат (cbilling)",
    МойДом: "МойДом",
    "МойДом settings": "הגדרות МойДом",
    "Ошибка обработки списка каналов! Проверьте правильность данных!!":
        "לא ניתן לעבד את רשימת הערוצים. בדוק את פרטי הספק!",
    Радуга: "Радуга",
    "Радуга settings": "הגדרות Радуга",
    "Редактирование ID": "ערוך מזהה",
    "Редактирование PIN": "ערוך PIN",
    Шаравоз: "Шаравоз",
    "Шаравоз settings": "הגדרות Шаравоз",
    "↑↓ Scroll": "↑↓ גלילה",
};
