var keyStrings = {
    " (after changing, load playlist)":
        " (változtatás után, töltse be a playlistet)",
    " added to category ": " hozzáadva a kategóriához ",
    " added to favorites": " hozzáadva a kedvencekhez",
    "??? No channel name": "??? Nincs csatornanév",
    Actions: "Műveletek",
    "Add channel to category": "Csatorna hozzáadása kategóriához",
    "Add channel to favorites": "Csatorna hozzáadása kedvencekhez",
    All: "Mind",
    "Archive hours": "Archívum órák",
    alhabet: "aábcdeéfghiíjklmnoóöőpqrstuúüűvwxyz",
    "Buffer Size, s": "Puffer mérete, s",
    "built-in": "beépített",
    Category: "Kategória",
    "Channel ": "Csatorna ",
    "Channel is not available!!!": "A csatorna nem elérhető!!!",
    "Channel list": "Csatornalista",
    "Channel list not received !!!": "Csatornalista nem érkezett!!!",
    "Channel list not received !!!<br/><br/>Enter the provider data and restart the player !!!<br/><br/>":
        "Csatornalista nem érkezett!!!<br/><br/>Adja meg a szolgáltató adatait és indítsa újra a lejátszót!!!<br/><br/>",
    "Channel list. Category: ": "Csatornalista. Kategória: ",
    "Channel parental control": "Csatorna szülői felügyelete",
    Close: "Bezár",
    "Delete channel": "Csatorna törlése",
    Description: "Leírás",
    Edit: "Szerkesztés",
    "Edit category name": "Kategória név szerkesztése",
    "Edit playlist data": "Playlist adatok szerkesztése",
    Editor: "Szerkesztő",
    "Enter Media Library URL": "Adja meg a médiatár URL-t",
    "Enter parental code": "Adja meg a szülői kódot",
    "Enter playlist archive hours": "Adja meg a playlist archívum óráit",
    "Enter playlist Name": "Adja meg a playlist nevét",
    "Enter playlist URL": "Adja meg a playlist URL-t",
    EPG: "Műsorújság",
    Exit: "Kilépés",
    "Failed to load channel list!": "A csatornalista betöltése sikertelen!",
    Favorites: "Kedvencek",
    Info: "Információ",
    Load: "Betöltés",
    "Load playlist": "Playlist betöltése",
    lang: "Magyar",
    "Media Library URL": "Médiatár URL",
    Menu: "Menü",
    "Move channel down": "Csatorna lejjebb",
    "Move channel up": "Csatorna feljebb",
    "m3u-m3u8 playlists": "M3U-m3U8 playlistek",
    min: "perc",
    "No channel name": "Nincs csatornanév",
    Nothing: "Semmi",
    native: "natív",
    no: "nem",
    "Open in PiP": "Megnyitás PiP-ben",
    off: "kikapcsolva",
    Playlist: "Playlist",
    "Playlist file": "Playlist fájl",
    "Playlist is not loading directly...Loading via server...":
        "A playlist nem töltődik be közvetlenül...Betöltés szerveren keresztül...",
    "Playlist Name": "Playlist neve",
    "Playlist URL": "Playlist URL",
    "Save Settings": "Beállítások mentése",
    Search: "Keresés",
    "Select category to add channel":
        "Válasszon kategóriát a csatorna hozzáadásához",
    "Select playlist": "Válasszon playlistet",
    "Select playlist file": "Válassza ki a playlist fájlt",
    Settings: "Beállítások",
    "Settings STB": "STB beállítások",
    "Settings saved": "Beállítások elmentve",
    "Stalker portals": "Stalker portálok",
    "Type of player for streaming": "Lejátszó típusa streaminghez",
    "Wrong parental code !!!": "Hibás szülői kód!!!",
    yes: "igen",
};
