var keyStrings = {
 "lang": "Magyar",
 "alhabet": "aábcdeéfghiíjklmnoóöőpqrstuúüűvwxyz",
 "Channel list. Category: ": "Csatornalista. Kategória: ",
 "EPG": "Műsorújság",
 "Category": "Kategória",
 "Actions": "Műveletek",
 "Description": "Leírás",
 "Open in PiP": "Megnyitás PiP-ben",
 "Move channel up": "Csatorna feljebb",
 "Move channel down": "Csatorna lejjebb",
 "Delete channel": "Csatorna törlése",
 "Add channel to category": "Csatorna hozzáadása kategóriához",
 "Add channel to favorites": "Csatorna hozzáadása kedvencekhez",
 "Channel parental control": "Csatorna szülői felügyelete",
 "Channel is not available!!!": "A csatorna nem elérhető!!!",
 "min": "perc",
 "Channel ": "Csatorna ",
 " added to category ": " hozzáadva a kategóriához ",
 " added to favorites": " hozzáadva a kedvencekhez",
 "Favorites": "Kedvencek",
 "Select category to add channel": "Válasszon kategóriát a csatorna hozzáadásához",
 "Enter parental code": "Adja meg a szülői kódot",
 "Wrong parental code !!!": "Hibás szülői kód!!!",
 "Close": "Bezár",
 "Edit category name": "Kategória név szerkesztése",
 "Menu": "Menü",
 "Channel list": "Csatornalista",
 "Settings": "Beállítások",
 "Settings saved": "Beállítások elmentve",
 "no": "nem",
 "yes": "igen",
 "Info": "Információ",
 "Nothing": "Semmi",
 "Exit": "Kilépés",
 "off": "kikapcsolva",
 "Failed to load channel list!": "A csatornalista betöltése sikertelen!",
 "??? No channel name": "??? Nincs csatornanév",
 "Playlist URL": "Playlist URL",
 "Archive hours": "Archívum órák",
 "Enter playlist URL": "Adja meg a playlist URL-t",
 "Playlist Name": "Playlist neve",
 "Enter playlist Name": "Adja meg a playlist nevét",
 "Media Library URL": "Médiatár URL",
 "Enter Media Library URL": "Adja meg a médiatár URL-t",
 "Playlist": "Playlist",
 "Playlist is not loading directly...Loading via server...": "A playlist nem töltődik be közvetlenül...Betöltés szerveren keresztül...",
 "Select playlist": "Válasszon playlistet",
 "Edit": "Szerkesztés",
 "Load": "Betöltés",
 "Edit playlist data": "Playlist adatok szerkesztése",
 "All": "Mind",
 "Search": "Keresés",
 "m3u-m3u8 playlists": "M3U-m3U8 playlistek",
 "Stalker portals": "Stalker portálok",
 "Settings STB": "STB beállítások",
 "Type of player for streaming": "Lejátszó típusa streaminghez",
 "Buffer Size, s": "Puffer mérete, s",
 "Save Settings": "Beállítások mentése",
 "Editor": "Szerkesztő",
 "built-in": "beépített",
 "native": "natív",
 "No channel name": "Nincs csatornanév",
 " (after changing, load playlist)": " (változtatás után, töltse be a playlistet)",
 "Enter playlist archive hours": "Adja meg a playlist archívum óráit",
 "Load playlist": "Playlist betöltése",
 "Playlist file": "Playlist fájl",
 "Select playlist file": "Válassza ki a playlist fájlt",
 "Channel list not received !!!<br/><br/>Enter the provider data and restart the player !!!<br/><br/>": "Csatornalista nem érkezett!!!<br/><br/>Adja meg a szolgáltató adatait és indítsa újra a lejátszót!!!<br/><br/>",
 "Channel list not received !!!": "Csatornalista nem érkezett!!!"
};
