var keyStrings = {
    " (after changing, load playlist)":
        " (dopo la modifica, caricare la playlist)",
    " added to category ": " aggiunto alla categoria ",
    " added to favorites": " aggiunto ai preferiti",
    "??? No channel name": "??? Nessun nome canale",
    Actions: "Azioni",
    "Add channel to category": "Aggiungi canale alla categoria",
    "Add channel to favorites": "Aggiungi canale ai preferiti",
    All: "Tutti",
    "Applying HTTP remote settings...":
        "Applicazione delle impostazioni del controllo remoto HTTP...",
    "Archive hours": "Ore di archivio",
    alhabet: "aàbcdeéèfghiìíjklmnoóòpqrstuúùvwxyz",
    "Buffer Size, s": "Dimensione buffer, s",
    "built-in": "integrato",
    Category: "Categoria",
    "Channel ": "Canale ",
    "Channel is not available!!!": "Canale non disponibile!!!",
    "Channel list": "Elenco canali",
    "Channel list not received !!!": "Elenco canali non ricevuto!!!",
    "Channel list not received !!!<br/><br/>Enter the provider data and restart the player !!!<br/><br/>":
        "Elenco canali non ricevuto!!!<br/><br/>Inserisci i dati del fornitore e riavvia il lettore!!!<br/><br/>",
    "Channel list. Category: ": "Elenco canali. Categoria: ",
    "Channel parental control": "Controllo parentale del canale",
    Close: "Chiudi",
    "Could not update HTTP remote control.":
        "Impossibile aggiornare il controllo remoto HTTP.",
    "Delete channel": "Elimina canale",
    Description: "Descrizione",
    "Device access code": "Codice di accesso al dispositivo",
    "Disable HTTP remote": "Disattiva controllo HTTP",
    "Disabled by default. Enabling creates a new device access code.":
        "Disattivato per impostazione predefinita. L’attivazione genera un nuovo codice di accesso al dispositivo.",
    Edit: "Modifica",
    "Edit category name": "Modifica nome categoria",
    "Edit playlist data": "Modifica dati playlist",
    Editor: "Editor",
    "Enable HTTP remote": "Attiva controllo HTTP",
    "Enter Media Library URL": "Inserisci URL mediateca",
    "Enter parental code": "Inserisci codice parentale",
    "Enter playlist archive hours": "Inserisci ore di archivio della playlist",
    "Enter playlist Name": "Inserisci nome playlist",
    "Enter playlist URL": "Inserisci URL playlist",
    EPG: "Guida TV",
    Exit: "Esci",
    "Failed to load channel list!": "Caricamento elenco canali fallito!",
    Favorites: "Preferiti",
    "HTTP port": "Porta HTTP",
    "HTTP remote control is unavailable on this device.":
        "Il controllo remoto HTTP non è disponibile su questo dispositivo.",
    Info: "Informazioni",
    Load: "Carica",
    "Load playlist": "Carica playlist",
    "Local HTTP remote control": "Controllo remoto HTTP locale",
    lang: "Italiano",
    "Media Library URL": "URL mediateca",
    Menu: "Menù",
    "Move channel down": "Sposta canale giù",
    "Move channel up": "Sposta canale su",
    "m3u-m3u8 playlists": "Playlist m3u-m3u8",
    min: "min",
    "No channel name": "Nessun nome canale",
    Nothing: "Niente",
    native: "nativo",
    no: "no",
    "Open in PiP": "Apri in PiP",
    off: "spento",
    on: "attivo",
    Playlist: "Playlist",
    "Playlist file": "File playlist",
    "Playlist is not loading directly...Loading via server...":
        "La playlist non si carica direttamente...Caricamento tramite server...",
    "Playlist Name": "Nome playlist",
    "Playlist URL": "URL playlist",
    "Remote control": "Controllo remoto",
    "Save Settings": "Salva impostazioni",
    Search: "Cerca",
    "Select category to add channel":
        "Seleziona categoria per aggiungere canale",
    "Select playlist": "Seleziona playlist",
    "Select playlist file": "Seleziona file playlist",
    "Send this code from your proxy in the Authorization: Bearer header.":
        "Invia questo codice dal proxy nell’intestazione Authorization: Bearer.",
    Settings: "Impostazioni",
    "Settings STB": "Impostazioni STB",
    "Settings saved": "Impostazioni salvate",
    "Stalker portals": "Portali Stalker",
    "Type of player for streaming": "Tipo di lettore per streaming",
    "Wrong parental code !!!": "Codice parentale errato!!!",
    yes: "sì",
};
