var keyStrings = {
 "lang": "Italiano",
 "alhabet": "aàbcdeéèfghiìíjklmnoóòpqrstuúùvwxyz",
 "Channel list. Category: ": "Elenco canali. Categoria: ",
 "EPG": "Guida TV",
 "Category": "Categoria",
 "Actions": "Azioni",
 "Description": "Descrizione",
 "Open in PiP": "Apri in PiP",
 "Move channel up": "Sposta canale su",
 "Move channel down": "Sposta canale giù",
 "Delete channel": "Elimina canale",
 "Add channel to category": "Aggiungi canale alla categoria",
 "Add channel to favorites": "Aggiungi canale ai preferiti",
 "Channel parental control": "Controllo parentale del canale",
 "Channel is not available!!!": "Canale non disponibile!!!",
 "min": "min",
 "Channel ": "Canale ",
 " added to category ": " aggiunto alla categoria ",
 " added to favorites": " aggiunto ai preferiti",
 "Favorites": "Preferiti",
 "Select category to add channel": "Seleziona categoria per aggiungere canale",
 "Enter parental code": "Inserisci codice parentale",
 "Wrong parental code !!!": "Codice parentale errato!!!",
 "Close": "Chiudi",
 "Edit category name": "Modifica nome categoria",
 "Menu": "Menù",
 "Channel list": "Elenco canali",
 "Settings": "Impostazioni",
 "Settings saved": "Impostazioni salvate",
 "no": "no",
 "yes": "sì",
 "Info": "Informazioni",
 "Nothing": "Niente",
 "Exit": "Esci",
 "off": "spento",
 "Failed to load channel list!": "Caricamento elenco canali fallito!",
 "??? No channel name": "??? Nessun nome canale",
 "Playlist URL": "URL playlist",
 "Archive hours": "Ore di archivio",
 "Enter playlist URL": "Inserisci URL playlist",
 "Playlist Name": "Nome playlist",
 "Enter playlist Name": "Inserisci nome playlist",
 "Media Library URL": "URL mediateca",
 "Enter Media Library URL": "Inserisci URL mediateca",
 "Playlist": "Playlist",
 "Playlist is not loading directly...Loading via server...": "La playlist non si carica direttamente...Caricamento tramite server...",
 "Select playlist": "Seleziona playlist",
 "Edit": "Modifica",
 "Load": "Carica",
 "Edit playlist data": "Modifica dati playlist",
 "All": "Tutti",
 "Search": "Cerca",
 "m3u-m3u8 playlists": "Playlist m3u-m3u8",
 "Stalker portals": "Portali Stalker",
 "Settings STB": "Impostazioni STB",
 "Type of player for streaming": "Tipo di lettore per streaming",
 "Buffer Size, s": "Dimensione buffer, s",
 "Save Settings": "Salva impostazioni",
 "Editor": "Editor",
 "built-in": "integrato",
 "native": "nativo",
 "No channel name": "Nessun nome canale",
 " (after changing, load playlist)": " (dopo la modifica, caricare la playlist)",
 "Enter playlist archive hours": "Inserisci ore di archivio della playlist",
 "Load playlist": "Carica playlist",
 "Playlist file": "File playlist",
 "Select playlist file": "Seleziona file playlist",
 "Channel list not received !!!<br/><br/>Enter the provider data and restart the player !!!<br/><br/>": "Elenco canali non ricevuto!!!<br/><br/>Inserisci i dati del fornitore e riavvia il lettore!!!<br/><br/>",
 "Channel list not received !!!": "Elenco canali non ricevuto!!!"
};
