var keyStrings = {
    " (after changing, load playlist)":
        " (dopo la modifica, caricare la playlist)",
    " (after changing, restart player)":
        " (riavvia il lettore dopo la modifica)",
    " added to category ": " aggiunto alla categoria ",
    " added to favorites": " aggiunto ai preferiti",
    " m ": " min ",
    " s": " s",
    "??? No channel name": "??? Nessun nome canale",
    '"As Is"': '"Originale"',
    '"Favorites"': '"Preferiti"',
    '"Sliding" infobar': "Barra informazioni scorrevole",
    "&darr;a": "&darr;a",
    "&uarr;A": "&uarr;A",
    "<br/><br/>In archive mode:<br/>": "<br/><br/>In modalità archivio:<br/>",
    "<br/>Loading STB...": "<br/>Caricamento decoder…",
    "<br/>Setup STB...": "<br/>Configurazione decoder…",
    "<br>": "<br>",
    "<br><br>": "<br><br>",
    "<br>Add<br>to category": "<br>Aggiungi<br>alla categoria",
    "<br>Add<br>to favorites": "<br>Aggiungi<br>ai preferiti",
    "<br>Delete": "<br>Elimina",
    "<br>Down<br>": "<br>Giù<br>",
    "<br>Live": "<br>Diretta",
    "<br>Menu": "<br>Menu",
    "<br>Parental<br>Control": "<br>Controllo<br>parentale",
    "<br>Pause<br>": "<br>Pausa<br>",
    "<br>Previous<br>channel": "<br>Canale<br>precedente",
    "<br>Rewind<br>": "<br>Riavvolgi<br>",
    "<br>Toggle<br>sound track": "<br>Cambia<br>traccia audio",
    "<br>Up<br>": "<br>Su<br>",
    "1 hour": "1 ora",
    "1 minute": "1 minuto",
    "2 hours": "2 ore",
    "3 hours": "3 ore",
    "10 Seconds": "10 secondi",
    "30 minutes": "30 minuti",
    "A command expired while the player was loading channels.":
        "Un comando è scaduto durante il caricamento dei canali.",
    "A command was rejected by the player. Check its provider and settings.":
        "Il lettore ha rifiutato un comando. Controlla il fornitore e le impostazioni.",
    About: "Informazioni",
    "Access code": "Codice di accesso",
    "Access denied. Check the server access code.":
        "Accesso negato. Controlla il codice di accesso del server.",
    "Access key": "Chiave di accesso",
    "Access key is required!": "Chiave di accesso obbligatoria!",
    "Access settings": "Impostazioni di accesso",
    Actions: "Azioni",
    "Active list": "Elenco attivo",
    Actors: "Attori",
    "Add / rename / delete…": "Aggiungi / rinomina / elimina…",
    "Add channel to category": "Aggiungi canale alla categoria",
    "Add channel to favorites": "Aggiungi canale ai preferiti",
    "Add new list": "Aggiungi nuovo elenco",
    "Add to favorites": "Aggiungi ai preferiti",
    Age: "Età",
    All: "Tutti",
    "All categories": "Tutte le categorie",
    "All4you.tv": "All4you.tv",
    "All4you.tv settings": "Impostazioni di All4you.tv",
    "Allowlist this Device ID": "Autorizza questo ID dispositivo",
    "An IP without a port uses HTTP port 8081. Clear the address or select Disconnect to stop.":
        "Un IP senza porta usa la porta HTTP 8081. Cancella l'indirizzo o seleziona Disconnetti per interrompere.",
    "API failed, trying M3U...": "API non riuscita, tentativo con M3U…",
    "API Server": "Server API",
    "API server URL": "URL del server API",
    "Applying HTTP remote settings...":
        "Applicazione delle impostazioni del controllo remoto HTTP...",
    Archive: "Archivio",
    "Archive - begin": "Archivio — inizio",
    "Archive hours": "Ore di archivio",
    "Archive: ENTER on past programs": "Archivio: INVIO sui programmi passati",
    "Archive. Channel: ": "Archivio. Canale: ",
    Aspect: "Formato immagine",
    Audio: "Audio",
    alhabet: "aàbcdeéèfghiìíjklmnoóòpqrstuúùvwxyz",
    always: "sempre",
    "and enter code": "e inserisci il codice",
    Back: "Indietro",
    "Back / Forward for 1 minute": "Indietro / avanti di 1 minuto",
    "Background color": "Colore di sfondo",
    "Background color of selected item":
        "Colore di sfondo dell'elemento selezionato",
    "BEST LiST IPTV [HLS Playlist]": "BEST LiST IPTV [HLS Playlist]",
    "BEST LiST IPTV [HLS Playlist] settings":
        "Impostazioni di BEST LiST IPTV [HLS Playlist]",
    "BEST LiST IPTV [Stalker]": "BEST LiST IPTV [Stalker]",
    "BEST LiST IPTV [Stalker] settings":
        "Impostazioni di BEST LiST IPTV [Stalker]",
    "Behavior of %1/%2 buttons in lists":
        "Comportamento dei tasti %1/%2 negli elenchi",
    "Black screen while switching the channel":
        "Schermo nero durante il cambio canale",
    Blue: "Blu",
    "Bookmark age: %1 days": "Età del segnalibro: %1 giorni",
    "Buffer Size, s": "Dimensione buffer, s",
    "Built-in playlist:": "Playlist integrata:",
    "Built-in playlists": "Playlist integrate",
    "Button %1 function when viewing":
        "Funzione del tasto %1 durante la visione",
    "Button function %1 when viewing archive":
        "Funzione del tasto %1 durante la visione dell'archivio",
    "Buttons settings": "Impostazioni dei tasti",
    "By alphabet": "In ordine alfabetico",
    "By time": "In ordine cronologico",
    "begin/end": "inizio/fine",
    "bottom-right": "in basso a destra",
    "built-in": "integrato",
    "Call PiP": "Apri PiP",
    "Call PiP / PiP exchange": "Apri PiP / scambia PiP",
    Cancel: "Annulla",
    "Cannot delete the last category":
        "Impossibile eliminare l'ultima categoria",
    Category: "Categoria",
    "Category selection": "Selezione categoria",
    "Change interface language": "Cambia lingua dell'interfaccia",
    "Change provider": "Cambia fornitore",
    "Change provider - you can change the provider, and it will be remembered at the next start of player!":
        "Cambia fornitore. La scelta verrà mantenuta al prossimo avvio del lettore.",
    "Change value": "Modifica valore",
    "Channel ": "Canale ",
    "Channel has no EPG": "Il canale non ha EPG",
    "Channel is not available!!!": "Canale non disponibile!!!",
    "Channel link": "Link del canale",
    "Channel link is required!": "Link del canale obbligatorio!",
    "Channel list": "Elenco canali",
    "Channel list editing style": "Modalità modifica elenco canali",
    "Channel list not received !!!": "Elenco canali non ricevuto!!!",
    "Channel list not received !!!<br/><br/>Enter the provider data and restart the player !!!<br/><br/>":
        "Elenco canali non ricevuto!!!<br/><br/>Inserisci i dati del fornitore e riavvia il lettore!!!<br/><br/>",
    "Channel list settings": "Impostazioni elenco canali",
    "Channel list. Category: ": "Elenco canali. Categoria: ",
    "Channel parental control": "Controllo parentale del canale",
    Channels: "Canali",
    "Choose from": "Scegli tra",
    "Choose language": "Scegli lingua",
    "Choose provider": "Scegli fornitore",
    Classic: "Classico",
    "Clear all settings?": "Cancellare tutte le impostazioni?",
    "Clear settings": "Cancella impostazioni",
    Close: "Chiudi",
    "Close PiP": "Chiudi PiP",
    Color: "Colore",
    "Color spectrum": "Spettro dei colori",
    "Command server": "Server comandi",
    "Command server address, device access code, local HTTP control, and remote text entry settings":
        "Indirizzo del server comandi, codice di accesso del dispositivo, controllo HTTP locale e inserimento testo remoto",
    "Configure All4you.tv in Settings -> Provider Settings":
        "Configura All4you.tv in Impostazioni -> Impostazioni del fornitore",
    "Configure BEST LiST IPTV [HLS Playlist] in Settings -> Provider Settings":
        "Configura BEST LiST IPTV [HLS Playlist] in Impostazioni -> Impostazioni del fornitore",
    "Configure BEST LiST IPTV [Stalker] in Settings -> Provider Settings":
        "Configura BEST LiST IPTV [Stalker] in Impostazioni -> Impostazioni del fornitore",
    "Configure Diamond TV in Settings -> Provider Settings":
        "Configura Diamond TV in Impostazioni -> Impostazioni del fornitore",
    "Configure DRVAO in Settings -> Provider Settings":
        "Configura DRVAO in Impostazioni -> Impostazioni del fornitore",
    "Configure Dragon Media PRO in Settings -> Provider Settings":
        "Configura Dragon Media PRO in Impostazioni -> Impostazioni del fornitore",
    "Configure Fabryka.TV in Settings -> Provider Settings":
        "Configura Fabryka.TV in Impostazioni -> Impostazioni del fornitore",
    "Configure Fox-TV in Settings -> Provider Settings":
        "Configura Fox-TV in Impostazioni -> Impostazioni del fornitore",
    "Configure FXML in Settings -> Provider Settings":
        "Configura FXML in Impostazioni -> Impostazioni del fornitore",
    "Configure GlanzTV in Settings -> Provider Settings":
        "Configura GlanzTV in Impostazioni -> Impostazioni del fornitore",
    "Configure GREAT IPTV in Settings -> Provider Settings":
        "Configura GREAT IPTV in Impostazioni -> Impostazioni del fornitore",
    "Configure IpStream.one in Settings -> Provider Settings":
        "Configura IpStream.one in Impostazioni -> Impostazioni del fornitore",
    "Configure KORONA TV in Settings -> Provider Settings":
        "Configura KORONA TV in Impostazioni -> Impostazioni del fornitore",
    "Configure MaxTV in Settings -> Provider Settings":
        "Configura MaxTV in Impostazioni -> Impostazioni del fornitore",
    "Configure New Look in Settings -> Provider Settings":
        "Configura New Look in Impostazioni -> Impostazioni del fornitore",
    "Configure OTT Prime ONLINE in Settings -> Provider Settings":
        "Configura OTT Prime ONLINE in Impostazioni -> Impostazioni del fornitore",
    "Configure POLMEDIA in Settings -> Provider Settings":
        "Configura POLMEDIA in Impostazioni -> Impostazioni del fornitore",
    "Configure PROST in Settings -> Provider Settings":
        "Configura PROST in Impostazioni -> Impostazioni del fornitore",
    "Configure RD in Settings -> Provider Settings":
        "Configura RD in Impostazioni -> Impostazioni del fornitore",
    "Configure RUSSKOETV in Settings -> Provider Settings":
        "Configura RUSSKOETV in Impostazioni -> Impostazioni del fornitore",
    "Configure Shara.club (ClubTV.pro) in Settings -> Provider Settings":
        "Configura Shara.club (ClubTV.pro) in Impostazioni -> Impostazioni del fornitore",
    "Configure ShockTv in Settings -> Provider Settings":
        "Configura ShockTv in Impostazioni -> Impostazioni del fornitore",
    "Configure Tabox in Settings -> Provider Settings":
        "Configura Tabox in Impostazioni -> Impostazioni del fornitore",
    "Configure TOP-IPTV in Settings -> Provider Settings":
        "Configura TOP-IPTV in Impostazioni -> Impostazioni del fornitore",
    "Configure Top-Tv in Settings -> Provider Settings":
        "Configura Top-Tv in Impostazioni -> Impostazioni del fornitore",
    "Configure TV DOSUG in Settings -> Provider Settings":
        "Configura TV DOSUG in Impostazioni -> Impostazioni del fornitore",
    "Configure TVClub in Settings -> Provider Settings":
        "Configura TVClub in Impostazioni -> Impostazioni del fornitore",
    "Configure ULTIFL1X in Settings -> Provider Settings":
        "Configura ULTIFL1X in Impostazioni -> Impostazioni del fornitore",
    "Configure VIP-IP.COM in Settings -> Provider Settings":
        "Configura VIP-IP.COM in Impostazioni -> Impostazioni del fornitore",
    "Configure Vidok.TV in Settings -> Provider Settings":
        "Configura Vidok.TV in Impostazioni -> Impostazioni del fornitore",
    "Configure Гомельсат (cbilling) in Settings -> Provider Settings":
        "Configura Гомельсат (cbilling) in Impostazioni -> Impostazioni del fornitore",
    "Configure МойДом in Settings -> Provider Settings":
        "Configura МойДом in Impostazioni -> Impostazioni del fornitore",
    "Configure Радуга in Settings -> Provider Settings":
        "Configura Радуга in Impostazioni -> Impostazioni del fornitore",
    "Configure Шаравоз in Settings -> Provider Settings":
        "Configura Шаравоз in Impostazioni -> Impostazioni del fornitore",
    Connect: "Connetti",
    Connected: "Connesso",
    "Connected. Waiting for the channel list...":
        "Connesso. In attesa dell'elenco canali…",
    "Connecting to Stalker portal...": "Connessione al portale Stalker…",
    "Connecting...": "Connessione…",
    "Continue watching?": "Continuare la visione?",
    "Copy category": "Copia categoria",
    "Copy JSON": "Copia JSON",
    "Could not connect to the server.": "Impossibile connettersi al server.",
    "Could not update HTTP remote control.":
        "Impossibile aggiornare il controllo remoto HTTP.",
    Country: "Paese",
    "Create category": "Crea categoria",
    current: "attuale",
    "Debug HUD": "Pannello di debug",
    "Debug HUD is not available": "Pannello di debug non disponibile",
    Delete: "Elimina",
    "Delete category": "Elimina categoria",
    "Delete channel": "Elimina canale",
    "Delete list": "Elimina elenco",
    "Demo — moving test pattern": "Demo — immagine di prova animata",
    Description: "Descrizione",
    "Description of remote control buttons": "Guida ai tasti del telecomando",
    "Device access code": "Codice di accesso al dispositivo",
    "Device info:": "Informazioni dispositivo:",
    "Device MAC is required for KBC (Kinoboom) playlists":
        "Le playlist KBC (Kinoboom) richiedono il MAC del dispositivo",
    "Diamond TV": "Diamond TV",
    "Diamond TV settings": "Impostazioni di Diamond TV",
    Director: "Regista",
    "Disable HTTP remote": "Disattiva controllo HTTP",
    "Disabled by default. Enabling creates a new device access code.":
        "Disattivato per impostazione predefinita. L’attivazione genera un nuovo codice di accesso al dispositivo.",
    Disconnect: "Disconnetti",
    Disconnected: "Disconnesso",
    "Distance between lines in lists": "Spaziatura righe negli elenchi",
    "Do you want to exit player?": "Vuoi uscire dal lettore?",
    "Download! Wait ...": "Download in corso… attendere…",
    DRVAO: "DRVAO",
    "DRVAO settings": "Impostazioni di DRVAO",
    "Dragon Media PRO": "Dragon Media PRO",
    "Dragon Media PRO settings": "Impostazioni di Dragon Media PRO",
    Duration: "Durata",
    Edit: "Modifica",
    "Edit access key": "Modifica chiave di accesso",
    "Edit category name": "Modifica nome categoria",
    "Edit channel link": "Modifica link del canale",
    "Edit playlist data": "Modifica dati playlist",
    "Edit VPortal link": "Modifica link VPortal",
    Editor: "Editor",
    "Enable HTTP remote": "Attiva controllo HTTP",
    English: "Inglese",
    "Enter a password (8 characters).": "Inserisci una password (8 caratteri).",
    "Enter a playlist URL to access this service.":
        "Inserisci l'URL di una playlist per accedere al servizio.",
    "Enter a server address without spaces or a fragment.":
        "Inserisci un indirizzo server senza spazi o frammenti.",
    "Enter a username (8 characters).":
        "Inserisci un nome utente (8 caratteri).",
    "Enter a username and password to access this service.":
        "Inserisci nome utente e password per accedere al servizio.",
    "Enter a valid server address, for example 192.168.1.20:8081.":
        "Inserisci un indirizzo server valido, ad esempio 192.168.1.20:8081.",
    "Enter access key for": "Inserisci chiave di accesso per",
    "Enter an application access key (8 characters).":
        "Inserisci una chiave di accesso per applicazioni (8 caratteri).",
    "Enter an ID and PIN to access this service.":
        "Inserisci ID e PIN per accedere al servizio.",
    "Enter an IPTV token (10 characters).":
        "Inserisci un token IPTV (10 caratteri).",
    "Enter category name": "Inserisci nome categoria",
    "Enter MAC address": "Inserisci indirizzo MAC",
    "Enter MAC address (e.g. 00:1A:2B:3C:4D:5E)":
        "Inserisci indirizzo MAC (es. 00:1A:2B:3C:4D:5E)",
    "Enter Media Library URL": "Inserisci URL mediateca",
    "Enter new category name": "Inserisci nuovo nome categoria",
    "Enter Provider Code": "Inserisci codice fornitore",
    "Enter Provider Code on PC or Phone":
        "Inserisci il codice fornitore su PC o telefono",
    "Enter parental code": "Inserisci codice parentale",
    "Enter password": "Inserisci password",
    "Enter playlist archive hours": "Inserisci ore di archivio della playlist",
    "Enter playlist Name": "Inserisci nome playlist",
    "Enter playlist URL": "Inserisci URL playlist",
    "Enter Stalker portal URL": "Inserisci URL del portale Stalker",
    "Enter Stalker portal URL (e.g. http://your-portal:8800)":
        "Inserisci URL del portale Stalker (es. http://your-portal:8800)",
    "Enter Stalker portal URL (e.g. http://your-portal/stalker_portal/c/)":
        "Inserisci URL del portale Stalker (es. http://your-portal/stalker_portal/c/)",
    "Enter the access code separately, not in the server address.":
        "Inserisci il codice di accesso separatamente, non nell'indirizzo del server.",
    "Enter the command server IP or address.":
        "Inserisci l'IP o l'indirizzo del server comandi.",
    "Enter the full CDN host from the cabinet stream URL (e.g. subdomain.cdn-domain.tld), not a bare subdomain":
        "Inserisci l'host CDN completo dall'URL del flusso nell'area clienti (es. subdomain.cdn-domain.tld), non solo il sottodominio",
    "Enter the server IP or address and this player's device access code from the server configuration. Saving both starts checking for volume, channel and other commands automatically.":
        "Inserisci l'IP o l'indirizzo del server e il codice di accesso di questo lettore dalla configurazione del server. Salvando entrambi si avvia automaticamente il controllo dei comandi di volume, canale e altro.",
    "Enter the server's device access code (32–256 letters, digits, _ or -).":
        "Inserisci il codice di accesso del dispositivo sul server (32–256 lettere, cifre, _ o -).",
    'Enter the tv.team playlist URL.<br>Playlist type: <b>OTTPlayer</b><br/><br/>The "/playlist.m3u8" suffix is added automatically if omitted.':
        'Inserisci l\'URL della playlist tv.team.<br>Tipo di playlist: <b>OTTPlayer</b><br/><br/>Il suffisso "/playlist.m3u8" viene aggiunto automaticamente se omesso.',
    "Enter the VPortal link as shown in the cabinet":
        "Inserisci il link VPortal come indicato nell'area clienti",
    "Enter this link in VPortal link. Playlist URL requires an M3U playlist.":
        "Inserisci questo link nel campo Link VPortal. L'URL della playlist richiede una playlist M3U.",
    "Enter this player's device access code to connect.":
        "Inserisci il codice di accesso di questo lettore per connetterti.",
    "Enter username": "Inserisci nome utente",
    "Enter value": "Inserisci valore",
    "Enter Xtream server URL": "Inserisci URL del server Xtream",
    "Enter Xtream server URL (e.g. https://your-server:8080)":
        "Inserisci URL del server Xtream (es. https://your-server:8080)",
    EPG: "Guida TV",
    "EPG and archive. Channel: ": "EPG e archivio. Canale: ",
    "ERROR!": "Errore!",
    "Error Code!": "Codice non valido!",
    Exit: "Esci",
    "Exit player": "Esci dal lettore",
    "Export settings": "Esporta impostazioni",
    "epg.one (Ordered)": "epg.one (ordinato)",
    "epg.one (Standard)": "epg.one (standard)",
    "epg.one (Thematic)": "epg.one (tematico)",
    "epgs...": "Guide EPG…",
    "Fabryka.TV": "Fabryka.TV",
    "Fabryka.TV settings": "Impostazioni di Fabryka.TV",
    "Failed to connect to Stalker portal":
        "Connessione al portale Stalker non riuscita",
    "Failed to connect to Xtream API server":
        "Connessione al server API Xtream non riuscita",
    "Failed to get user data!!!": "Impossibile recuperare i dati utente!",
    "Failed to load channel list!": "Caricamento elenco canali fallito!",
    "Failed to load channels from Stalker portal":
        "Impossibile caricare i canali dal portale Stalker",
    "Failed to load channels from Xtream API":
        "Impossibile caricare i canali dall'API Xtream",
    "Failed to load!": "Caricamento non riuscito!",
    "Favorite lists": "Elenchi preferiti",
    Favorites: "Preferiti",
    "File selection is not supported on this device":
        "La selezione dei file non è supportata su questo dispositivo",
    Filters: "Filtri",
    "First Run Setup": "Configurazione iniziale",
    "Font type": "Tipo di carattere",
    "For download settings file open":
        "Per scaricare il file delle impostazioni, apri",
    "For enter value open": "Per inserire un valore, apri",
    "For upload settings file open":
        "Per caricare il file delle impostazioni, apri",
    "Fox-TV": "Fox-TV",
    "Fox-TV settings": "Impostazioni di Fox-TV",
    FXML: "FXML",
    "FXML settings": "Impostazioni di FXML",
    Genre: "Genere",
    GlanzTV: "GlanzTV",
    "GlanzTV settings": "Impostazioni di GlanzTV",
    "Go to": "Vai a",
    "GREAT IPTV": "GREAT IPTV",
    "GREAT IPTV settings": "Impostazioni di GREAT IPTV",
    "Graphical indication": "Indicatori grafici",
    Green: "Verde",
    "Hide / Return": "Nascondi / mostra",
    "Hide provider settings?": "Nascondere le impostazioni del fornitore?",
    "Hide providers?": "Nascondere i fornitori?",
    "History in Media Library": "Cronologia nella raccolta multimediale",
    "History of watched movies": "Cronologia di visione",
    "HTTP port": "Porta HTTP",
    "HTTP remote control is unavailable on this device.":
        "Il controllo remoto HTTP non è disponibile su questo dispositivo.",
    ID: "ID",
    "Import settings": "Importa impostazioni",
    "In live mode: <br/>": "In modalità diretta:<br/>",
    Info: "Informazioni",
    "Infobar display timeout, s": "Durata della barra informazioni, s",
    "Infobar settings": "Impostazioni barra informazioni",
    Information: "Informazioni",
    "Interface credits": "Crediti dell'interfaccia",
    "Interface settings": "Impostazioni interfaccia",
    "Interface theme": "Tema dell'interfaccia",
    "Interface transparency": "Trasparenza dell'interfaccia",
    "Invalid channel link! Enter the full host as in the cabinet stream URL (e.g. subdomain.cdn-domain.tld)":
        "Link del canale non valido! Inserisci l'host completo come nell'URL del flusso dell'area clienti (es. subdomain.cdn-domain.tld)",
    "IPTV token": "Token IPTV",
    "IpStream.one": "IpStream.one",
    "IpStream.one settings": "Impostazioni di IpStream.one",
    Joystick: "Joystick",
    "KBC (Kinoboom) access data": "Dati di accesso KBC (Kinoboom)",
    "KORONA TV": "KORONA TV",
    "KORONA TV settings": "Impostazioni di KORONA TV",
    "List created": "Elenco creato",
    "List deleted": "Elenco eliminato",
    "List location": "Posizione elenco",
    "List renamed": "Elenco rinominato",
    "List type": "Tipo di elenco",
    "Lists settings": "Impostazioni elenchi",
    Live: "Diretta",
    Load: "Carica",
    "Load built-in playlist:": "Carica playlist integrata:",
    "Load playlist": "Carica playlist",
    "Load settings": "Carica impostazioni",
    "Load settings from storage": "Carica impostazioni dalla memoria",
    "Load:": "Carica:",
    "Loading channels from Xtream API...":
        "Caricamento canali dall'API Xtream…",
    "Loading channels...": "Caricamento canali…",
    "Loading from API...": "Caricamento dall'API…",
    "Loading from Edem API...": "Caricamento dall'API Edem…",
    "Loading M3U playlist...": "Caricamento playlist M3U…",
    "Loading M3U...": "Caricamento M3U…",
    "Loading via proxy...": "Caricamento tramite proxy…",
    "Loading. Please wait...": "Caricamento… attendere…",
    "Loading...": "Caricamento…",
    "Local HTTP remote control": "Controllo remoto HTTP locale",
    "Local URL": "URL locale",
    Login: "Accesso",
    lang: "Italiano",
    large: "grande",
    left: "sinistra",
    "left-bottom": "in basso a sinistra",
    "logos...": "Loghi…",
    M3U: "M3U",
    "M3U URL": "URL M3U",
    "M3U URL (fallback)": "URL M3U (alternativa)",
    "MAC address": "Indirizzo MAC",
    "Manage lists": "Gestisci elenchi",
    "Manage settings": "Gestisci impostazioni",
    "Manual setup": "Configurazione manuale",
    MaxTV: "MaxTV",
    "MaxTV settings": "Impostazioni di MaxTV",
    Media: "Media",
    "Media item is no longer available":
        "L'elemento multimediale non è più disponibile",
    "Media Library": "Raccolta multimediale",
    "Media Library URL": "URL mediateca",
    Menu: "Menù",
    "Menu items settings": "Impostazioni voci del menu",
    "Move category down": "Sposta categoria in basso",
    "Move category up": "Sposta categoria in alto",
    "Move channel down": "Sposta canale giù",
    "Move channel up": "Sposta canale su",
    "m3u-m3u8 playlists": "Playlist m3u-m3u8",
    medium: "medio",
    min: "min",
    "New Look": "New Look",
    "New Look settings": "Impostazioni di New Look",
    "New list name": "Nome del nuovo elenco",
    Next: "Pagina successiva",
    "Next keyboard page": "Pagina successiva della tastiera",
    "Next TV program": "Programma successivo",
    No: "No",
    "No channel name": "Nessun nome canale",
    "No saved settings found": "Nessuna impostazione salvata trovata",
    "Not found": "Non trovato",
    "Not reduce video when showing the list (bugfix)":
        "Non ridurre il video quando viene mostrato l'elenco (correzione)",
    Nothing: "Niente",
    "Number of next TV programs in channel list":
        "Numero di programmi successivi nell'elenco canali",
    "Number of rows in lists": "Numero di righe negli elenchi",
    native: "nativo",
    no: "no",
    "no epg at current time": "Nessun EPG per l'ora attuale",
    "not set": "non impostato",
    Off: "Disattivato",
    Ok: "OK",
    Open: "Apri",
    "Open in PiP": "Apri in PiP",
    "OTT Prime ONLINE": "OTT Prime ONLINE",
    "OTT Prime ONLINE settings": "Impostazioni di OTT Prime ONLINE",
    "OttPlay FOSS %1 is available. Download and install now?":
        "OttPlay FOSS %1 è disponibile. Scaricare e installare ora?",
    "Overwrite current settings?": "Sovrascrivere le impostazioni attuali?",
    off: "spento",
    on: "attivo",
    "on ": "attivato ",
    "or scan": "o scansiona",
    "Parental control": "Controllo parentale",
    Password: "Password",
    Pause: "Pausa",
    "Pause/Play": "Pausa / riproduci",
    "Permanent clock on screen": "Mostra sempre l'orologio sullo schermo",
    PIN: "PIN",
    "PiP exchange": "Scambia PiP",
    "PiP window position": "Posizione finestra PiP",
    "PiP window size": "Dimensione finestra PiP",
    Play: "Riproduci",
    "Player and device info": "Informazioni su lettore e dispositivo",
    "Player info:": "Informazioni lettore:",
    Playlist: "Playlist",
    "Playlist file": "File playlist",
    "Playlist is not loading directly...Loading via server...":
        "La playlist non si carica direttamente...Caricamento tramite server...",
    "Playlist Name": "Nome playlist",
    "Playlist URL": "URL playlist",
    POLMEDIA: "POLMEDIA",
    "POLMEDIA settings": "Impostazioni di POLMEDIA",
    "Portal URL": "URL del portale",
    "Position shift -10 seconds after pause":
        "Torna indietro di 10 secondi dopo una pausa",
    PROST: "PROST",
    "PROST settings": "Impostazioni di PROST",
    Prev: "Precedente",
    "Preview in channel list": "Anteprima nell'elenco canali",
    Previous: "Precedente",
    "Privacy policy": "Informativa sulla privacy",
    "Protect Adult Channels": "Proteggi canali per adulti",
    "Protect Change Provider": "Proteggi cambio fornitore",
    "Protect Settings": "Proteggi impostazioni",
    "p...": "p...",
    paging: "per pagina",
    Quality: "Qualità",
    Rating: "Valutazione",
    RD: "RD",
    "RD settings": "Impostazioni di RD",
    "Reconnecting…": "Riconnessione…",
    Records: "Registrazioni",
    "Records for channel: ": "Registrazioni del canale: ",
    "Records library is empty": "La raccolta registrazioni è vuota",
    "Records not supported by provider":
        "Le registrazioni non sono supportate dal fornitore",
    "Release date": "Data di uscita",
    "Remember previous channels": "Ricorda i canali precedenti",
    "Reminder: %1 — %2 in %3 min": "Promemoria: %1 — %2 tra %3 min",
    "Remote (color buttons N/A)": "Telecomando senza tasti colorati",
    "Remote (number buttons N/A)": "Telecomando senza tasti numerici",
    "Remote control": "Controllo remoto",
    "Remote session expired": "Sessione remota scaduta",
    "Remote text entry denied": "Inserimento testo remoto negato",
    "Remote text entry error": "Errore nell'inserimento testo remoto",
    "Remote text entry not configured":
        "Inserimento testo remoto non configurato",
    "Remote text entry requires a Device ID. Ask the server operator to provision one.":
        "L'inserimento testo remoto richiede un ID dispositivo. Chiedi al gestore del server di fornirne uno.",
    "Remove timer?": "Rimuovere il timer?",
    Rename: "Rinomina",
    "Rename category": "Rinomina categoria",
    "Rename to": "Rinomina in",
    "Repeat parental code": "Ripeti codice parentale",
    "Request sended!": "Richiesta inviata!",
    "Restart player": "Riavvia lettore",
    "Restart stream": "Riavvia flusso",
    "Restart stream / Live": "Riavvia flusso / diretta",
    "Resume from archive?": "Riprendere dall'archivio?",
    "Return to previous channel": "Torna al canale precedente",
    Rewind: "Sposta riproduzione",
    "Rewind step by buttons %1/%2":
        "Intervallo di riavvolgimento con i tasti %1/%2",
    RUSSKOETV: "RUSSKOETV",
    "RUSSKOETV settings": "Impostazioni di RUSSKOETV",
    Russian: "Russo",
    right: "destra",
    Saturation: "Saturazione",
    "Save & load channels": "Salva e carica canali",
    "Save and load": "Salva e carica",
    "Save and load channels": "Salva e carica canali",
    "Save Settings": "Salva impostazioni",
    "Save settings": "Salva impostazioni",
    "Save settings and load channel list":
        "Salva impostazioni e carica elenco canali",
    "Save settings to storage": "Salva impostazioni nella memoria",
    Script: "Sceneggiatura",
    Search: "Cerca",
    "Search programme": "Cerca programma",
    "Select a stream type:<br>%1": "Seleziona un tipo di flusso:<br>%1",
    "Select category to add channel":
        "Seleziona categoria per aggiungere canale",
    "Select color": "Seleziona colore",
    "Select menu items": "Seleziona voci del menu",
    "Select playlist": "Seleziona playlist",
    "Select playlist file": "Seleziona file playlist",
    "Select playlist template source for EPG and logos":
        "Seleziona origine del modello playlist per EPG e loghi",
    "Send request": "Invia richiesta",
    "Send settings": "Invia impostazioni",
    "Send this code from your proxy in the Authorization: Bearer header.":
        "Invia questo codice dal proxy nell’intestazione Authorization: Bearer.",
    Server: "Server",
    "Server address": "Indirizzo server",
    "Server address (for example 192.168.1.20:8081)":
        "Indirizzo server (ad esempio 192.168.1.20:8081)",
    "Server device access code": "Codice di accesso dispositivo sul server",
    "Server URL": "URL del server",
    "Server unavailable. Retrying automatically; check its address and network access.":
        "Server non disponibile. Nuovo tentativo automatico; controlla l'indirizzo e l'accesso alla rete.",
    Set: "Imposta",
    "Set parental code": "Imposta codice parentale",
    "Set timer?": "Impostare il timer?",
    Settings: "Impostazioni",
    "Settings could not be saved": "Impossibile salvare le impostazioni",
    "Settings loaded from storage": "Impostazioni caricate dalla memoria",
    "Settings STB": "Impostazioni STB",
    "Settings saved": "Impostazioni salvate",
    "Settings saved to storage": "Impostazioni salvate nella memoria",
    "Settings sended!": "Impostazioni inviate!",
    "Shara.club (ClubTV.pro)": "Shara.club (ClubTV.pro)",
    "Shara.club (ClubTV.pro) settings":
        "Impostazioni di Shara.club (ClubTV.pro)",
    ShockTv: "ShockTv",
    "ShockTv settings": "Impostazioni di ShockTv",
    "Show archive availability in list":
        "Mostra disponibilità archivio nell'elenco",
    "Show channel name in list": "Mostra nome canale nell'elenco",
    "Show channel number in list": "Mostra numero canale nell'elenco",
    "Show channel selection list": "Mostra elenco di selezione canali",
    "Show description": "Mostra descrizione",
    "Show EPG and archive for channel": "Mostra EPG e archivio del canale",
    "Show list of channel archive records": "Mostra registrazioni del canale",
    "Show list of channel archive records without duplication":
        "Mostra registrazioni del canale senza duplicati",
    "Show Media Library": "Mostra raccolta multimediale",
    "Show picons in channel list": "Mostra icone dei canali nell'elenco",
    "Show player menu": "Mostra menu del lettore",
    "Show program name": "Mostra nome programma",
    "Show progress in channel list": "Mostra avanzamento nell'elenco canali",
    "Show provider settings?": "Mostrare le impostazioni del fornitore?",
    "Show providers?": "Mostrare i fornitori?",
    "Show rewind window": "Mostra finestra di ricerca temporale",
    "Show scrollbar in list": "Mostra barra di scorrimento negli elenchi",
    "Show thumbnails": "Mostra miniature",
    "Show when changing program": "Mostra al cambio programma",
    "Show when rewind": "Mostra durante il riavvolgimento",
    "Show when switching": "Mostra al cambio canale",
    "Sleep timer": "Timer di spegnimento",
    "Sort channels": "Ordina canali",
    "Stalker Portal Provider": "Fornitore portale Stalker",
    "Stalker portal settings": "Impostazioni portale Stalker",
    "Stalker portals": "Portali Stalker",
    Status: "Stato",
    "Stop playback and return to live":
        "Interrompi riproduzione e torna alla diretta",
    "Stream type: %1": "Tipo di flusso: %1",
    "String for search": "Testo da cercare",
    "Su Mo Tu We Th Fr Sa": "Do Lu Ma Me Gi Ve Sa",
    Subtitle: "Sottotitoli",
    Switch: "Cambia",
    "Switch sound track": "Cambia traccia audio",
    "Switch subtitle": "Cambia sottotitoli",
    "Switch to this list": "Passa a questo elenco",
    "Swop URL": "Swop URL",
    "saved on this device": "salvato su questo dispositivo",
    select: "seleziona",
    small: "piccolo",
    system: "sistema",
    Tabox: "Tabox",
    "Tabox settings": "Impostazioni di Tabox",
    "The device ID in the address is invalid.":
        "L'ID dispositivo nell'indirizzo non è valido.",
    "This HTTPS player cannot connect to an HTTP server. Use an HTTPS server or open the player over HTTP.":
        "Questo lettore HTTPS non può connettersi a un server HTTP. Usa un server HTTPS o apri il lettore tramite HTTP.",
    "This Play app requires HTTPS. Ask your provider for an HTTPS playlist or server URL.":
        "Questa app Play richiede HTTPS. Chiedi al fornitore una playlist o un URL server HTTPS.",
    Timer: "Timer",
    "Timer: switch to channel?": "Timer: passare a questo canale?",
    "Timeshift: one minute back": "Timeshift: un minuto indietro",
    "Timeshift: to start of TV program": "Timeshift: inizio del programma",
    Timezone: "Fuso orario",
    TMDb: "TMDb",
    "TOP-IPTV": "TOP-IPTV",
    "TOP-IPTV settings": "Impostazioni di TOP-IPTV",
    "To begining": "All'inizio",
    "To start of TV program / Previous TV program":
        "All'inizio del programma / programma precedente",
    "Toggle Aspect Ratio": "Cambia formato immagine",
    "Toggle on-screen debug HUD": "Attiva o disattiva il pannello di debug",
    "Toggle Zoom Mode": "Cambia modalità zoom",
    "Top-Tv": "Top-Tv",
    "Top-Tv settings": "Impostazioni di Top-Tv",
    "Try demo": "Prova demo",
    "TV DOSUG": "TV DOSUG",
    "TV DOSUG settings": "Impostazioni di TV DOSUG",
    TVClub: "TVClub",
    "TVClub settings": "Impostazioni di TVClub",
    "Type of player for streaming": "Tipo di lettore per streaming",
    "top-left": "in alto a sinistra",
    "top-right": "in alto a destra",
    transparent: "trasparente",
    ULTIFL1X: "ULTIFL1X",
    "ULTIFL1X settings": "Impostazioni di ULTIFL1X",
    "Update installed. Please restart OttPlay FOSS.":
        "Aggiornamento installato. Riavvia OttPlay FOSS.",
    "Use an HTTP or HTTPS server address.":
        "Usa un indirizzo server HTTP o HTTPS.",
    "Use HTTP or HTTPS without a username or password in the address.":
        "Usa HTTP o HTTPS senza nome utente o password nell'indirizzo.",
    "Use LEFT/RIGHT to select a control, OK to activate, and UP/DOWN to scroll.":
        "Usa SINISTRA/DESTRA per selezionare un controllo, OK per attivarlo e SU/GIÙ per scorrere.",
    Username: "Nome utente",
    "Username or password is missing.": "Nome utente o password mancante.",
    "VIP-IP.COM": "VIP-IP.COM",
    "VIP-IP.COM settings": "Impostazioni di VIP-IP.COM",
    "Vidok.TV": "Vidok.TV",
    "Vidok.TV settings": "Impostazioni di Vidok.TV",
    "VOD not supported by provider": "La VOD non è supportata dal fornitore",
    "Volume step, %": "Incremento volume, %",
    "VPortal link": "Link VPortal",
    "VPortal request failed":
        "Impossibile caricare VPortal. Controlla il link, la chiave di accesso e la disponibilità del portale.",
    volume: "volume",
    "Wrong parental code !!!": "Codice parentale errato!!!",
    "Xtream Codes Provider": "Fornitore Xtream Codes",
    "Xtream Codes settings": "Impostazioni Xtream Codes",
    Year: "Anno",
    Yellow: "Giallo",
    Yes: "Sì",
    yes: "sì",
    "Гомельсат (cbilling)": "Гомельсат (cbilling)",
    "Гомельсат (cbilling) settings": "Impostazioni di Гомельсат (cbilling)",
    МойДом: "МойДом",
    "МойДом settings": "Impostazioni di МойДом",
    "Ошибка обработки списка каналов! Проверьте правильность данных!!":
        "Impossibile elaborare l'elenco canali. Controlla i dati del fornitore!",
    Радуга: "Радуга",
    "Радуга settings": "Impostazioni di Радуга",
    "Редактирование ID": "Modifica ID",
    "Редактирование PIN": "Modifica PIN",
    Шаравоз: "Шаравоз",
    "Шаравоз settings": "Impostazioni di Шаравоз",
    "↑↓ Scroll": "↑↓ Scorri",
};
