var keyStrings = {
    " (after changing, load playlist)":
        " (өзгерткен соң ойнату тізімін қайта жүктеңіз)",
    " (after changing, restart player)":
        " (өзгерткен соң ойнатқышты қайта іске қосыңыз)",
    " added to category ": " мына санатқа қосылды: ",
    " added to favorites": " таңдаулыларға қосылды",
    " m ": " мин ",
    " s": " с",
    "??? No channel name": "??? Арна атауы жоқ",
    '"As Is"': "«Өзгеріссіз»",
    '"Favorites"': "«Таңдаулылар»",
    '"Sliding" infobar': "Сырғымалы ақпарат тақтасы",
    "&darr;a": "&darr;a",
    "&uarr;A": "&uarr;A",
    "<br/><br/>In archive mode:<br/>": "<br/><br/>Мұрағат режимінде:<br/>",
    "<br/>Loading STB...": "<br/>Құрылғы жүктелуде…",
    "<br/>Setup STB...": "<br/>Құрылғы бапталуда…",
    "<br>": "<br>",
    "<br><br>": "<br><br>",
    "<br>Add<br>to category": "<br>Санатқа<br>қосу",
    "<br>Add<br>to favorites": "<br>Таңдаулыларға<br>қосу",
    "<br>Delete": "<br>Жою",
    "<br>Down<br>": "<br>Төмен<br>",
    "<br>Live": "<br>Тікелей эфир",
    "<br>Menu": "<br>Мәзір",
    "<br>Parental<br>Control": "<br>Ата-ана<br>бақылауы",
    "<br>Pause<br>": "<br>Кідірту<br>",
    "<br>Previous<br>channel": "<br>Алдыңғы<br>арна",
    "<br>Rewind<br>": "<br>Айналдыру<br>",
    "<br>Toggle<br>sound track": "<br>Дыбыс жолын<br>ауыстыру",
    "<br>Up<br>": "<br>Жоғары<br>",
    "1 hour": "1 сағат",
    "1 minute": "1 минут",
    "2 hours": "2 сағат",
    "3 hours": "3 сағат",
    "10 Seconds": "10 секунд",
    "30 minutes": "30 минут",
    "A command expired while the player was loading channels.":
        "Ойнатқыш арналарды жүктеп жатқанда пәрменнің мерзімі аяқталды.",
    "A command was rejected by the player. Check its provider and settings.":
        "Ойнатқыш пәрменді қабылдамады. Провайдерді және баптауларды тексеріңіз.",
    About: "Қолданба туралы",
    "Access code": "Кіру коды",
    "Access denied. Check the server access code.":
        "Кіруге рұқсат жоқ. Сервердің кіру кодын тексеріңіз.",
    "Access key": "Кіру кілті",
    "Access key is required!": "Кіру кілті қажет!",
    "Access settings": "Кіру баптаулары",
    Actions: "Әрекеттер",
    "Active list": "Белсенді тізім",
    Actors: "Актерлер",
    "Add / rename / delete…": "Қосу / атын өзгерту / жою…",
    "Add channel to category": "Арнаны санатқа қосу",
    "Add channel to favorites": "Арнаны таңдаулыларға қосу",
    "Add new list": "Жаңа тізім қосу",
    "Add to favorites": "Таңдаулыларға қосу",
    Age: "Жас",
    All: "Барлығы",
    "All categories": "Барлық санаттар",
    "All4you.tv": "All4you.tv",
    "All4you.tv settings": "All4you.tv баптаулары",
    "Allowlist this Device ID": "Осы құрылғы ID-іне рұқсат беріңіз",
    "An IP without a port uses HTTP port 8081. Clear the address or select Disconnect to stop.":
        "Портсыз IP үшін HTTP 8081 порты қолданылады. Тоқтату үшін мекенжайды тазалаңыз немесе Ажырату түймесін таңдаңыз.",
    "API failed, trying M3U...": "API қатесі, M3U қолданылуда…",
    "API Server": "API сервері",
    "API server URL": "API серверінің URL мекенжайы",
    "Applying HTTP remote settings...":
        "HTTP қашықтан басқару баптаулары қолданылуда…",
    Archive: "Мұрағат",
    "Archive - begin": "Мұрағат — басы",
    "Archive hours": "Мұрағат сағаттары",
    "Archive: ENTER on past programs": "Мұрағат: өткен бағдарламаларда ENTER",
    "Archive. Channel: ": "Мұрағат. Арна: ",
    Aspect: "Кадр арақатынасы",
    Audio: "Дыбыс",
    alhabet: "аәбвгғдеёжзийкқлмнңоөпрстуұүфхһцчшщъыіьэюя",
    always: "әрқашан",
    "and enter code": "және кодты енгізіңіз",
    Back: "Артқа",
    "Back / Forward for 1 minute": "1 минут артқа / алға",
    "Background color": "Фон түсі",
    "Background color of selected item": "Таңдалған элементтің фон түсі",
    "BEST LiST IPTV [HLS Playlist]": "BEST LiST IPTV [HLS Playlist]",
    "BEST LiST IPTV [HLS Playlist] settings":
        "BEST LiST IPTV [HLS Playlist] баптаулары",
    "BEST LiST IPTV [Stalker]": "BEST LiST IPTV [Stalker]",
    "BEST LiST IPTV [Stalker] settings": "BEST LiST IPTV [Stalker] баптаулары",
    "Behavior of %1/%2 buttons in lists":
        "Тізімдердегі %1/%2 түймелерінің әрекеті",
    "Black screen while switching the channel":
        "Арнаны ауыстырғанда қара экран",
    Blue: "Көк",
    "Bookmark age: %1 days": "Бетбелгі жасы: %1 күн",
    "Buffer Size, s": "Буфер өлшемі, с",
    "Built-in playlist:": "Кірістірілген ойнату тізімі:",
    "Built-in playlists": "Кірістірілген ойнату тізімдері",
    "Button %1 function when viewing": "Көру кезіндегі %1 түймесінің әрекеті",
    "Button function %1 when viewing archive":
        "Мұрағатты көру кезіндегі %1 түймесінің әрекеті",
    "Buttons settings": "Түйме баптаулары",
    "By alphabet": "Әліпби бойынша",
    "By time": "Уақыт бойынша",
    "begin/end": "басы/соңы",
    "bottom-right": "төменгі оң жақ",
    "built-in": "кірістірілген",
    "Call PiP": "PiP ашу",
    "Call PiP / PiP exchange": "PiP ашу / PiP ауыстыру",
    Cancel: "Бас тарту",
    "Cannot delete the last category": "Соңғы санатты жою мүмкін емес",
    Category: "Санат",
    "Category selection": "Санат таңдау",
    "Change interface language": "Интерфейс тілін өзгерту",
    "Change provider": "Провайдерді ауыстыру",
    "Change provider - you can change the provider, and it will be remembered at the next start of player!":
        "Провайдерді ауыстырыңыз. Таңдауыңыз ойнатқышты келесі іске қосқанда сақталады.",
    "Change value": "Мәнді өзгерту",
    "Channel ": "Арна ",
    "Channel has no EPG": "Арнаның бағдарлама кестесі жоқ",
    "Channel is not available!!!": "Арна қолжетімсіз!",
    "Channel link": "Арна сілтемесі",
    "Channel link is required!": "Арна сілтемесі қажет!",
    "Channel list": "Арналар тізімі",
    "Channel list editing style": "Арналар тізімін өңдеу режимі",
    "Channel list not received !!!": "Арналар тізімі алынбады!",
    "Channel list not received !!!<br/><br/>Enter the provider data and restart the player !!!<br/><br/>":
        "Арналар тізімі алынбады!<br/><br/>Провайдер деректерін енгізіп, ойнатқышты қайта іске қосыңыз.<br/><br/>",
    "Channel list settings": "Арналар тізімінің баптаулары",
    "Channel list. Category: ": "Арналар тізімі. Санат: ",
    "Channel parental control": "Арнаның ата-ана бақылауы",
    Channels: "Арналар",
    "Choose from": "Мынадан таңдау",
    "Choose language": "Тілді таңдаңыз",
    "Choose provider": "Провайдерді таңдаңыз",
    Classic: "Классикалық",
    "Clear all settings?": "Барлық баптаулар жойылсын ба?",
    "Clear settings": "Баптауларды жою",
    Close: "Жабу",
    "Close PiP": "PiP жабу",
    Color: "Түс",
    "Color spectrum": "Түстер палитрасы",
    "Command server": "Пәрмен сервері",
    "Command server address, device access code, local HTTP control, and remote text entry settings":
        "Пәрмен серверінің мекенжайы, құрылғының кіру коды, жергілікті HTTP басқару және қашықтан мәтін енгізу баптаулары",
    "Configure All4you.tv in Settings -> Provider Settings":
        "All4you.tv қызметін Баптаулар -> Провайдер баптаулары бөлімінде баптаңыз",
    "Configure BEST LiST IPTV [HLS Playlist] in Settings -> Provider Settings":
        "BEST LiST IPTV [HLS Playlist] қызметін Баптаулар -> Провайдер баптаулары бөлімінде баптаңыз",
    "Configure BEST LiST IPTV [Stalker] in Settings -> Provider Settings":
        "BEST LiST IPTV [Stalker] қызметін Баптаулар -> Провайдер баптаулары бөлімінде баптаңыз",
    "Configure Diamond TV in Settings -> Provider Settings":
        "Diamond TV қызметін Баптаулар -> Провайдер баптаулары бөлімінде баптаңыз",
    "Configure DRVAO in Settings -> Provider Settings":
        "DRVAO қызметін Баптаулар -> Провайдер баптаулары бөлімінде баптаңыз",
    "Configure Dragon Media PRO in Settings -> Provider Settings":
        "Dragon Media PRO қызметін Баптаулар -> Провайдер баптаулары бөлімінде баптаңыз",
    "Configure Fabryka.TV in Settings -> Provider Settings":
        "Fabryka.TV қызметін Баптаулар -> Провайдер баптаулары бөлімінде баптаңыз",
    "Configure Fox-TV in Settings -> Provider Settings":
        "Fox-TV қызметін Баптаулар -> Провайдер баптаулары бөлімінде баптаңыз",
    "Configure FXML in Settings -> Provider Settings":
        "FXML қызметін Баптаулар -> Провайдер баптаулары бөлімінде баптаңыз",
    "Configure GlanzTV in Settings -> Provider Settings":
        "GlanzTV қызметін Баптаулар -> Провайдер баптаулары бөлімінде баптаңыз",
    "Configure GREAT IPTV in Settings -> Provider Settings":
        "GREAT IPTV қызметін Баптаулар -> Провайдер баптаулары бөлімінде баптаңыз",
    "Configure IpStream.one in Settings -> Provider Settings":
        "IpStream.one қызметін Баптаулар -> Провайдер баптаулары бөлімінде баптаңыз",
    "Configure KORONA TV in Settings -> Provider Settings":
        "KORONA TV қызметін Баптаулар -> Провайдер баптаулары бөлімінде баптаңыз",
    "Configure MaxTV in Settings -> Provider Settings":
        "MaxTV қызметін Баптаулар -> Провайдер баптаулары бөлімінде баптаңыз",
    "Configure New Look in Settings -> Provider Settings":
        "New Look қызметін Баптаулар -> Провайдер баптаулары бөлімінде баптаңыз",
    "Configure OTT Prime ONLINE in Settings -> Provider Settings":
        "OTT Prime ONLINE қызметін Баптаулар -> Провайдер баптаулары бөлімінде баптаңыз",
    "Configure POLMEDIA in Settings -> Provider Settings":
        "POLMEDIA қызметін Баптаулар -> Провайдер баптаулары бөлімінде баптаңыз",
    "Configure PROST in Settings -> Provider Settings":
        "PROST қызметін Баптаулар -> Провайдер баптаулары бөлімінде баптаңыз",
    "Configure RD in Settings -> Provider Settings":
        "RD қызметін Баптаулар -> Провайдер баптаулары бөлімінде баптаңыз",
    "Configure RUSSKOETV in Settings -> Provider Settings":
        "RUSSKOETV қызметін Баптаулар -> Провайдер баптаулары бөлімінде баптаңыз",
    "Configure Shara.club (ClubTV.pro) in Settings -> Provider Settings":
        "Shara.club (ClubTV.pro) қызметін Баптаулар -> Провайдер баптаулары бөлімінде баптаңыз",
    "Configure ShockTv in Settings -> Provider Settings":
        "ShockTv қызметін Баптаулар -> Провайдер баптаулары бөлімінде баптаңыз",
    "Configure Tabox in Settings -> Provider Settings":
        "Tabox қызметін Баптаулар -> Провайдер баптаулары бөлімінде баптаңыз",
    "Configure TOP-IPTV in Settings -> Provider Settings":
        "TOP-IPTV қызметін Баптаулар -> Провайдер баптаулары бөлімінде баптаңыз",
    "Configure Top-Tv in Settings -> Provider Settings":
        "Top-Tv қызметін Баптаулар -> Провайдер баптаулары бөлімінде баптаңыз",
    "Configure TV DOSUG in Settings -> Provider Settings":
        "TV DOSUG қызметін Баптаулар -> Провайдер баптаулары бөлімінде баптаңыз",
    "Configure TVClub in Settings -> Provider Settings":
        "TVClub қызметін Баптаулар -> Провайдер баптаулары бөлімінде баптаңыз",
    "Configure ULTIFL1X in Settings -> Provider Settings":
        "ULTIFL1X қызметін Баптаулар -> Провайдер баптаулары бөлімінде баптаңыз",
    "Configure VIP-IP.COM in Settings -> Provider Settings":
        "VIP-IP.COM қызметін Баптаулар -> Провайдер баптаулары бөлімінде баптаңыз",
    "Configure Vidok.TV in Settings -> Provider Settings":
        "Vidok.TV қызметін Баптаулар -> Провайдер баптаулары бөлімінде баптаңыз",
    "Configure Гомельсат (cbilling) in Settings -> Provider Settings":
        "Гомельсат (cbilling) қызметін Баптаулар -> Провайдер баптаулары бөлімінде баптаңыз",
    "Configure МойДом in Settings -> Provider Settings":
        "МойДом қызметін Баптаулар -> Провайдер баптаулары бөлімінде баптаңыз",
    "Configure Радуга in Settings -> Provider Settings":
        "Радуга қызметін Баптаулар -> Провайдер баптаулары бөлімінде баптаңыз",
    "Configure Шаравоз in Settings -> Provider Settings":
        "Шаравоз қызметін Баптаулар -> Провайдер баптаулары бөлімінде баптаңыз",
    Connect: "Қосылу",
    Connected: "Қосылды",
    "Connected. Waiting for the channel list...":
        "Қосылды. Арналар тізімі күтілуде…",
    "Connecting to Stalker portal...": "Stalker порталына қосылуда…",
    "Connecting...": "Қосылуда…",
    "Continue watching?": "Көруді жалғастыру керек пе?",
    "Copy category": "Санатты көшіру",
    "Copy JSON": "JSON көшіру",
    "Could not connect to the server.": "Серверге қосылу мүмкін болмады.",
    "Could not update HTTP remote control.":
        "HTTP қашықтан басқаруды жаңарту мүмкін болмады.",
    Country: "Ел",
    "Create category": "Санат жасау",
    current: "ағымдағы",
    "Debug HUD": "Жөндеу тақтасы",
    "Debug HUD is not available": "Жөндеу тақтасы қолжетімсіз",
    Delete: "Жою",
    "Delete category": "Санатты жою",
    "Delete channel": "Арнаны жою",
    "Delete list": "Тізімді жою",
    "Demo — moving test pattern": "Демо — қозғалмалы сынақ бейнесі",
    Description: "Сипаттама",
    "Description of remote control buttons":
        "Қашықтан басқару түймелерінің сипаттамасы",
    "Device access code": "Құрылғының кіру коды",
    "Device info:": "Құрылғы туралы ақпарат:",
    "Device MAC is required for KBC (Kinoboom) playlists":
        "KBC (Kinoboom) ойнату тізімдеріне құрылғының MAC мекенжайы қажет",
    "Diamond TV": "Diamond TV",
    "Diamond TV settings": "Diamond TV баптаулары",
    Director: "Режиссер",
    "Disable HTTP remote": "HTTP қашықтан басқаруды өшіру",
    "Disabled by default. Enabling creates a new device access code.":
        "Әдепкіде өшірілген. Қосу құрылғы үшін жаңа кіру кодын жасайды.",
    Disconnect: "Ажырату",
    Disconnected: "Ажыратылды",
    "Distance between lines in lists": "Тізімдердегі жол аралығы",
    "Do you want to exit player?": "Ойнатқыштан шығу керек пе?",
    "Download! Wait ...": "Жүктелуде… күтіңіз…",
    DRVAO: "DRVAO",
    "DRVAO settings": "DRVAO баптаулары",
    "Dragon Media PRO": "Dragon Media PRO",
    "Dragon Media PRO settings": "Dragon Media PRO баптаулары",
    Duration: "Ұзақтығы",
    Edit: "Өңдеу",
    "Edit access key": "Кіру кілтін өңдеу",
    "Edit category name": "Санат атауын өңдеу",
    "Edit channel link": "Арна сілтемесін өңдеу",
    "Edit playlist data": "Ойнату тізімінің деректерін өңдеу",
    "Edit VPortal link": "VPortal сілтемесін өңдеу",
    Editor: "Редактор",
    "Enable HTTP remote": "HTTP қашықтан басқаруды қосу",
    English: "Ағылшын тілі",
    "Enter a password (8 characters).": "Құпиясөзді енгізіңіз (8 таңба).",
    "Enter a playlist URL to access this service.":
        "Бұл қызметке кіру үшін ойнату тізімінің URL мекенжайын енгізіңіз.",
    "Enter a server address without spaces or a fragment.":
        "Сервер мекенжайын бос орынсыз және # таңбасынан кейінгі үзіндісіз енгізіңіз.",
    "Enter a username (8 characters).": "Пайдаланушы атын енгізіңіз (8 таңба).",
    "Enter a username and password to access this service.":
        "Бұл қызметке кіру үшін пайдаланушы аты мен құпиясөзді енгізіңіз.",
    "Enter a valid server address, for example 192.168.1.20:8081.":
        "Жарамды сервер мекенжайын енгізіңіз, мысалы, 192.168.1.20:8081.",
    "Enter access key for": "Мынау үшін кіру кілтін енгізіңіз:",
    "Enter an application access key (8 characters).":
        "Қолданбаның кіру кілтін енгізіңіз (8 таңба).",
    "Enter an ID and PIN to access this service.":
        "Бұл қызметке кіру үшін ID мен PIN енгізіңіз.",
    "Enter an IPTV token (10 characters).":
        "IPTV токенін енгізіңіз (10 таңба).",
    "Enter category name": "Санат атауын енгізіңіз",
    "Enter MAC address": "MAC мекенжайын енгізіңіз",
    "Enter MAC address (e.g. 00:1A:2B:3C:4D:5E)":
        "MAC мекенжайын енгізіңіз (мысалы, 00:1A:2B:3C:4D:5E)",
    "Enter Media Library URL": "Медиа кітапханасының URL мекенжайын енгізіңіз",
    "Enter new category name": "Санаттың жаңа атауын енгізіңіз",
    "Enter Provider Code": "Провайдер кодын енгізіңіз",
    "Enter Provider Code on PC or Phone":
        "Провайдер кодын компьютерде немесе телефонда енгізіңіз",
    "Enter parental code": "Ата-ана кодын енгізіңіз",
    "Enter password": "Құпиясөзді енгізіңіз",
    "Enter playlist archive hours":
        "Ойнату тізімінің мұрағат сағаттарын енгізіңіз",
    "Enter playlist Name": "Ойнату тізімінің атауын енгізіңіз",
    "Enter playlist URL": "Ойнату тізімінің URL мекенжайын енгізіңіз",
    "Enter Stalker portal URL": "Stalker порталының URL мекенжайын енгізіңіз",
    "Enter Stalker portal URL (e.g. http://your-portal:8800)":
        "Stalker порталының URL мекенжайын енгізіңіз (мысалы, http://your-portal:8800)",
    "Enter Stalker portal URL (e.g. http://your-portal/stalker_portal/c/)":
        "Stalker порталының URL мекенжайын енгізіңіз (мысалы, http://your-portal/stalker_portal/c/)",
    "Enter the access code separately, not in the server address.":
        "Кіру кодын сервер мекенжайынан бөлек енгізіңіз.",
    "Enter the command server IP or address.":
        "Пәрмен серверінің IP немесе мекенжайын енгізіңіз.",
    "Enter the full CDN host from the cabinet stream URL (e.g. subdomain.cdn-domain.tld), not a bare subdomain":
        "Жеке кабинеттегі ағын URL мекенжайынан толық CDN хост атауын енгізіңіз (мысалы, subdomain.cdn-domain.tld), тек ішкі доменді емес",
    "Enter the server IP or address and this player's device access code from the server configuration. Saving both starts checking for volume, channel and other commands automatically.":
        "Сервердің IP немесе мекенжайын және сервер баптауларынан осы ойнатқыштың кіру кодын енгізіңіз. Екеуін де сақтау дыбыс, арна және басқа пәрмендерді автоматты тексеруді бастайды.",
    "Enter the server's device access code (32–256 letters, digits, _ or -).":
        "Сервердегі құрылғының кіру кодын енгізіңіз (32–256 әріп, цифр, _ немесе -).",
    'Enter the tv.team playlist URL.<br>Playlist type: <b>OTTPlayer</b><br/><br/>The "/playlist.m3u8" suffix is added automatically if omitted.':
        'tv.team ойнату тізімінің URL мекенжайын енгізіңіз.<br>Тізім түрі: <b>OTTPlayer</b><br/><br/>"/playlist.m3u8" жұрнағы болмаса, автоматты түрде қосылады.',
    "Enter the VPortal link as shown in the cabinet":
        "Жеке кабинетте көрсетілген VPortal сілтемесін енгізіңіз",
    "Enter this link in VPortal link. Playlist URL requires an M3U playlist.":
        "Бұл сілтемені VPortal сілтемесі өрісіне енгізіңіз. Ойнату тізімінің URL мекенжайы M3U тізіміне апаруы керек.",
    "Enter this player's device access code to connect.":
        "Қосылу үшін осы ойнатқыштың кіру кодын енгізіңіз.",
    "Enter username": "Пайдаланушы атын енгізіңіз",
    "Enter value": "Мәнді енгізіңіз",
    "Enter Xtream server URL": "Xtream серверінің URL мекенжайын енгізіңіз",
    "Enter Xtream server URL (e.g. https://your-server:8080)":
        "Xtream серверінің URL мекенжайын енгізіңіз (мысалы, https://your-server:8080)",
    EPG: "Бағдарлама кестесі",
    "EPG and archive. Channel: ": "Бағдарлама кестесі және мұрағат. Арна: ",
    "ERROR!": "Қате!",
    "Error Code!": "Жарамсыз код!",
    Exit: "Шығу",
    "Exit player": "Ойнатқыштан шығу",
    "Export settings": "Баптауларды экспорттау",
    "epg.one (Ordered)": "epg.one (Реттелген)",
    "epg.one (Standard)": "epg.one (Стандартты)",
    "epg.one (Thematic)": "epg.one (Тақырыптық)",
    "epgs...": "Бағдарлама кестелері…",
    "Fabryka.TV": "Fabryka.TV",
    "Fabryka.TV settings": "Fabryka.TV баптаулары",
    "Failed to connect to Stalker portal":
        "Stalker порталына қосылу мүмкін болмады",
    "Failed to connect to Xtream API server":
        "Xtream API серверіне қосылу мүмкін болмады",
    "Failed to get user data!!!": "Пайдаланушы деректерін алу мүмкін болмады!",
    "Failed to load channel list!": "Арналар тізімін жүктеу мүмкін болмады!",
    "Failed to load channels from Stalker portal":
        "Stalker порталынан арналарды жүктеу мүмкін болмады",
    "Failed to load channels from Xtream API":
        "Xtream API арқылы арналарды жүктеу мүмкін болмады",
    "Failed to load!": "Жүктеу мүмкін болмады!",
    "Favorite lists": "Таңдаулылар тізімдері",
    Favorites: "Таңдаулылар",
    "File selection is not supported on this device":
        "Бұл құрылғыда файл таңдау қолдау көрсетілмейді",
    Filters: "Сүзгілер",
    "First Run Setup": "Алғашқы іске қосу баптауы",
    "Font type": "Қаріп түрі",
    "For download settings file open":
        "Баптаулар файлын жүктеп алу үшін ашыңыз",
    "For enter value open": "Мәнді енгізу үшін ашыңыз",
    "For upload settings file open": "Баптаулар файлын жіберу үшін ашыңыз",
    "Fox-TV": "Fox-TV",
    "Fox-TV settings": "Fox-TV баптаулары",
    FXML: "FXML",
    "FXML settings": "FXML баптаулары",
    Genre: "Жанр",
    GlanzTV: "GlanzTV",
    "GlanzTV settings": "GlanzTV баптаулары",
    "Go to": "Өту",
    "GREAT IPTV": "GREAT IPTV",
    "GREAT IPTV settings": "GREAT IPTV баптаулары",
    "Graphical indication": "Графикалық индикаторлар",
    Green: "Жасыл",
    "Hide / Return": "Жасыру / көрсету",
    "Hide provider settings?": "Провайдер баптаулары жасырылсын ба?",
    "Hide providers?": "Провайдерлер жасырылсын ба?",
    "History in Media Library": "Медиа кітапханасындағы тарих",
    "History of watched movies": "Көру тарихы",
    "HTTP port": "HTTP порты",
    "HTTP remote control is unavailable on this device.":
        "Бұл құрылғыда HTTP қашықтан басқару қолжетімсіз.",
    ID: "ID",
    "Import settings": "Баптауларды импорттау",
    "In live mode: <br/>": "Тікелей эфир режимінде:<br/>",
    Info: "Ақпарат",
    "Infobar display timeout, s": "Ақпарат тақтасын көрсету ұзақтығы, с",
    "Infobar settings": "Ақпарат тақтасының баптаулары",
    Information: "Ақпарат",
    "Interface credits": "Интерфейс авторлары",
    "Interface settings": "Интерфейс баптаулары",
    "Interface theme": "Интерфейс тақырыбы",
    "Interface transparency": "Интерфейс мөлдірлігі",
    "Invalid channel link! Enter the full host as in the cabinet stream URL (e.g. subdomain.cdn-domain.tld)":
        "Арна сілтемесі жарамсыз! Жеке кабинеттегі ағын URL мекенжайының толық хост атауын енгізіңіз (мысалы, subdomain.cdn-domain.tld)",
    "IPTV token": "IPTV токені",
    "IpStream.one": "IpStream.one",
    "IpStream.one settings": "IpStream.one баптаулары",
    Joystick: "Джойстик",
    "KBC (Kinoboom) access data": "KBC (Kinoboom) кіру деректері",
    "KORONA TV": "KORONA TV",
    "KORONA TV settings": "KORONA TV баптаулары",
    "List created": "Тізім жасалды",
    "List deleted": "Тізім жойылды",
    "List location": "Тізім орны",
    "List renamed": "Тізім атауы өзгертілді",
    "List type": "Тізім түрі",
    "Lists settings": "Тізім баптаулары",
    Live: "Тікелей эфир",
    Load: "Жүктеу",
    "Load built-in playlist:": "Кірістірілген ойнату тізімін жүктеу:",
    "Load playlist": "Ойнату тізімін жүктеу",
    "Load settings": "Баптауларды жүктеу",
    "Load settings from storage": "Баптауларды жадтан жүктеу",
    "Load:": "Жүктеу:",
    "Loading channels from Xtream API...":
        "Xtream API арқылы арналар жүктелуде…",
    "Loading channels...": "Арналар жүктелуде…",
    "Loading from API...": "API арқылы жүктелуде…",
    "Loading from Edem API...": "Edem API арқылы жүктелуде…",
    "Loading M3U playlist...": "M3U ойнату тізімі жүктелуде…",
    "Loading M3U...": "M3U жүктелуде…",
    "Loading via proxy...": "Прокси арқылы жүктелуде…",
    "Loading. Please wait...": "Жүктелуде. Күтіңіз…",
    "Loading...": "Жүктелуде…",
    "Local HTTP remote control": "Жергілікті HTTP қашықтан басқару",
    "Local URL": "Жергілікті URL",
    Login: "Кіру аты",
    lang: "Қазақша",
    large: "үлкен",
    left: "сол жақ",
    "left-bottom": "төменгі сол жақ",
    "logos...": "Логотиптер…",
    M3U: "M3U",
    "M3U URL": "M3U URL мекенжайы",
    "M3U URL (fallback)": "M3U URL мекенжайы (қосалқы)",
    "MAC address": "MAC мекенжайы",
    "Manage lists": "Тізімдерді басқару",
    "Manage settings": "Баптауларды басқару",
    "Manual setup": "Қолмен баптау",
    MaxTV: "MaxTV",
    "MaxTV settings": "MaxTV баптаулары",
    Media: "Медиа",
    "Media item is no longer available": "Бұл медиа енді қолжетімсіз",
    "Media Library": "Медиа кітапханасы",
    "Media Library URL": "Медиа кітапханасының URL мекенжайы",
    Menu: "Мәзір",
    "Menu items settings": "Мәзір элементтерінің баптаулары",
    "Move category down": "Санатты төмен жылжыту",
    "Move category up": "Санатты жоғары жылжыту",
    "Move channel down": "Арнаны төмен жылжыту",
    "Move channel up": "Арнаны жоғары жылжыту",
    "m3u-m3u8 playlists": "M3U / M3U8 ойнату тізімдері",
    medium: "орташа",
    min: "мин",
    "New Look": "New Look",
    "New Look settings": "New Look баптаулары",
    "New list name": "Жаңа тізім атауы",
    Next: "Келесі бет",
    "Next keyboard page": "Пернетақтаның келесі беті",
    "Next TV program": "Келесі бағдарлама",
    No: "Жоқ",
    "No channel name": "Арна атауы жоқ",
    "No saved settings found": "Сақталған баптаулар табылмады",
    "Not found": "Табылмады",
    "Not reduce video when showing the list (bugfix)":
        "Тізімді көрсеткенде бейнені кішірейтпеу (қатені түзету)",
    Nothing: "Ештеңе",
    "Number of next TV programs in channel list":
        "Арналар тізіміндегі келесі бағдарламалар саны",
    "Number of rows in lists": "Тізімдердегі жолдар саны",
    native: "жүйелік",
    no: "жоқ",
    "no epg at current time": "Ағымдағы уақытқа бағдарлама кестесі жоқ",
    "not set": "орнатылмаған",
    Off: "Өшірулі",
    Ok: "OK",
    Open: "Ашу",
    "Open in PiP": "PiP ішінде ашу",
    "OTT Prime ONLINE": "OTT Prime ONLINE",
    "OTT Prime ONLINE settings": "OTT Prime ONLINE баптаулары",
    "OttPlay FOSS %1 is available. Download and install now?":
        "OttPlay FOSS %1 қолжетімді. Қазір жүктеп алып, орнату керек пе?",
    "Overwrite current settings?": "Ағымдағы баптаулар қайта жазылсын ба?",
    off: "өшірулі",
    on: "қосулы",
    "on ": "мына түймемен ",
    "or scan": "немесе сканерлеңіз",
    "Parental control": "Ата-ана бақылауы",
    Password: "Құпиясөз",
    Pause: "Кідірту",
    "Pause/Play": "Кідірту / ойнату",
    "Permanent clock on screen": "Экрандағы тұрақты сағат",
    PIN: "PIN",
    "PiP exchange": "PiP терезелерін ауыстыру",
    "PiP window position": "PiP терезесінің орны",
    "PiP window size": "PiP терезесінің өлшемі",
    Play: "Ойнату",
    "Player and device info": "Ойнатқыш және құрылғы туралы ақпарат",
    "Player info:": "Ойнатқыш туралы ақпарат:",
    Playlist: "Ойнату тізімі",
    "Playlist file": "Ойнату тізімінің файлы",
    "Playlist is not loading directly...Loading via server...":
        "Ойнату тізімі тікелей жүктелмеді. Сервер арқылы жүктелуде…",
    "Playlist Name": "Ойнату тізімінің атауы",
    "Playlist URL": "Ойнату тізімінің URL мекенжайы",
    POLMEDIA: "POLMEDIA",
    "POLMEDIA settings": "POLMEDIA баптаулары",
    "Portal URL": "Порталдың URL мекенжайы",
    "Position shift -10 seconds after pause":
        "Кідіртуден кейін 10 секунд артқа қайту",
    PROST: "PROST",
    "PROST settings": "PROST баптаулары",
    Prev: "Алдыңғы",
    "Preview in channel list": "Арналар тізіміндегі алдын ала қарау",
    Previous: "Алдыңғы арна",
    "Privacy policy": "Құпиялық саясаты",
    "Protect Adult Channels": "Ересектерге арналған арналарды қорғау",
    "Protect Change Provider": "Провайдерді ауыстыруды қорғау",
    "Protect Settings": "Баптауларды қорғау",
    "p...": "т…",
    paging: "беттерді ауыстыру",
    Quality: "Сапа",
    Rating: "Рейтинг",
    RD: "RD",
    "RD settings": "RD баптаулары",
    "Reconnecting…": "Қайта қосылуда…",
    Records: "Жазбалар",
    "Records for channel: ": "Арна жазбалары: ",
    "Records library is empty": "Жазбалар кітапханасы бос",
    "Records not supported by provider": "Провайдер жазбаларды қолдамайды",
    "Release date": "Шығарылған күні",
    "Remember previous channels": "Алдыңғы арналарды есте сақтау",
    "Reminder: %1 — %2 in %3 min": "Еске салу: %1 — %2, %3 минуттан кейін",
    "Remote (color buttons N/A)": "Түрлі түсті түймелері жоқ пульт",
    "Remote (number buttons N/A)": "Сандық түймелері жоқ пульт",
    "Remote control": "Қашықтан басқару",
    "Remote session expired": "Қашықтағы сеанстың мерзімі аяқталды",
    "Remote text entry denied": "Қашықтан мәтін енгізуге рұқсат жоқ",
    "Remote text entry error": "Қашықтан мәтін енгізу қатесі",
    "Remote text entry not configured": "Қашықтан мәтін енгізу бапталмаған",
    "Remote text entry requires a Device ID. Ask the server operator to provision one.":
        "Қашықтан мәтін енгізу үшін құрылғы ID-і қажет. Оны сервер әкімшісінен сұраңыз.",
    "Remove timer?": "Таймер жойылсын ба?",
    Rename: "Атын өзгерту",
    "Rename category": "Санат атауын өзгерту",
    "Rename to": "Жаңа атау",
    "Repeat parental code": "Ата-ана кодын қайталаңыз",
    "Request sended!": "Сұрау жіберілді!",
    "Restart player": "Ойнатқышты қайта іске қосу",
    "Restart stream": "Ағынды қайта іске қосу",
    "Restart stream / Live": "Ағынды қайта іске қосу / тікелей эфир",
    "Resume from archive?": "Мұрағаттан жалғастыру керек пе?",
    "Return to previous channel": "Алдыңғы арнаға қайту",
    Rewind: "Айналдыру",
    "Rewind step by buttons %1/%2": "%1/%2 түймелерімен айналдыру қадамы",
    RUSSKOETV: "RUSSKOETV",
    "RUSSKOETV settings": "RUSSKOETV баптаулары",
    Russian: "Орыс тілі",
    right: "оң жақ",
    Saturation: "Қанықтық",
    "Save & load channels": "Сақтау және арналарды жүктеу",
    "Save and load": "Сақтау және жүктеу",
    "Save and load channels": "Сақтау және арналарды жүктеу",
    "Save Settings": "Баптауларды сақтау",
    "Save settings": "Баптауларды сақтау",
    "Save settings and load channel list":
        "Баптауларды сақтау және арналар тізімін жүктеу",
    "Save settings to storage": "Баптауларды жадқа сақтау",
    Script: "Сценарий",
    Search: "Іздеу",
    "Search programme": "Бағдарламаны іздеу",
    "Select a stream type:<br>%1": "Ағын түрін таңдаңыз:<br>%1",
    "Select category to add channel": "Арнаны қосатын санатты таңдаңыз",
    "Select color": "Түсті таңдаңыз",
    "Select menu items": "Мәзір элементтерін таңдаңыз",
    "Select playlist": "Ойнату тізімін таңдаңыз",
    "Select playlist file": "Ойнату тізімінің файлын таңдаңыз",
    "Select playlist template source for EPG and logos":
        "Бағдарлама кестесі мен логотиптер үшін ойнату тізімінің үлгісін таңдаңыз",
    "Send request": "Сұрау жіберу",
    "Send settings": "Баптауларды жіберу",
    "Send this code from your proxy in the Authorization: Bearer header.":
        "Бұл кодты проксиден Authorization: Bearer тақырыбында жіберіңіз.",
    Server: "Сервер",
    "Server address": "Сервер мекенжайы",
    "Server address (for example 192.168.1.20:8081)":
        "Сервер мекенжайы (мысалы, 192.168.1.20:8081)",
    "Server device access code": "Сервердегі құрылғының кіру коды",
    "Server URL": "Сервердің URL мекенжайы",
    "Server unavailable. Retrying automatically; check its address and network access.":
        "Сервер қолжетімсіз. Әрекет автоматты түрде қайталанады; мекенжай мен желіге кіруді тексеріңіз.",
    Set: "Орнату",
    "Set parental code": "Ата-ана кодын орнатыңыз",
    "Set timer?": "Таймер орнатылсын ба?",
    Settings: "Баптаулар",
    "Settings could not be saved": "Баптауларды сақтау мүмкін болмады",
    "Settings loaded from storage": "Баптаулар жадтан жүктелді",
    "Settings STB": "Құрылғы баптаулары",
    "Settings saved": "Баптаулар сақталды",
    "Settings saved to storage": "Баптаулар жадқа сақталды",
    "Settings sended!": "Баптаулар жіберілді!",
    "Shara.club (ClubTV.pro)": "Shara.club (ClubTV.pro)",
    "Shara.club (ClubTV.pro) settings": "Shara.club (ClubTV.pro) баптаулары",
    ShockTv: "ShockTv",
    "ShockTv settings": "ShockTv баптаулары",
    "Show archive availability in list": "Тізімде мұрағаттың бар-жоғын көрсету",
    "Show channel name in list": "Тізімде арна атауын көрсету",
    "Show channel number in list": "Тізімде арна нөмірін көрсету",
    "Show channel selection list": "Арна таңдау тізімін көрсету",
    "Show description": "Сипаттаманы көрсету",
    "Show EPG and archive for channel":
        "Арнаның бағдарлама кестесі мен мұрағатын көрсету",
    "Show list of channel archive records":
        "Арнаның мұрағат жазбаларын көрсету",
    "Show list of channel archive records without duplication":
        "Арнаның мұрағат жазбаларын қайталаусыз көрсету",
    "Show Media Library": "Медиа кітапханасын көрсету",
    "Show picons in channel list": "Арналар тізімінде белгішелерді көрсету",
    "Show player menu": "Ойнатқыш мәзірін көрсету",
    "Show program name": "Бағдарлама атауын көрсету",
    "Show progress in channel list":
        "Арналар тізімінде орындалу барысын көрсету",
    "Show provider settings?": "Провайдер баптаулары көрсетілсін бе?",
    "Show providers?": "Провайдерлер көрсетілсін бе?",
    "Show rewind window": "Айналдыру терезесін көрсету",
    "Show scrollbar in list": "Тізімде айналдыру жолағын көрсету",
    "Show thumbnails": "Нобайларды көрсету",
    "Show when changing program": "Бағдарлама ауысқанда көрсету",
    "Show when rewind": "Айналдыру кезінде көрсету",
    "Show when switching": "Арна ауысқанда көрсету",
    "Sleep timer": "Ұйқы таймері",
    "Sort channels": "Арналарды сұрыптау",
    "Stalker Portal Provider": "Stalker порталының провайдері",
    "Stalker portal settings": "Stalker порталының баптаулары",
    "Stalker portals": "Stalker порталдары",
    Status: "Күй",
    "Stop playback and return to live":
        "Ойнатуды тоқтатып, тікелей эфирге қайту",
    "Stream type: %1": "Ағын түрі: %1",
    "String for search": "Іздеу мәтіні",
    "Su Mo Tu We Th Fr Sa": "Жс Дс Сс Ср Бс Жм Сб",
    Subtitle: "Субтитрлер",
    Switch: "Ауыстыру",
    "Switch sound track": "Дыбыс жолын ауыстыру",
    "Switch subtitle": "Субтитрді ауыстыру",
    "Switch to this list": "Осы тізімге ауысу",
    "Swop URL": "Swop URL мекенжайы",
    "saved on this device": "осы құрылғыда сақталған",
    select: "таңдау",
    small: "кіші",
    system: "жүйелік",
    Tabox: "Tabox",
    "Tabox settings": "Tabox баптаулары",
    "The device ID in the address is invalid.":
        "Мекенжайдағы құрылғы ID-і жарамсыз.",
    "This HTTPS player cannot connect to an HTTP server. Use an HTTPS server or open the player over HTTP.":
        "Бұл HTTPS ойнатқышы HTTP серверіне қосыла алмайды. HTTPS серверін қолданыңыз немесе ойнатқышты HTTP арқылы ашыңыз.",
    "This Play app requires HTTPS. Ask your provider for an HTTPS playlist or server URL.":
        "Бұл Play қолданбасына HTTPS қажет. Провайдерден HTTPS ойнату тізімін немесе сервер URL мекенжайын сұраңыз.",
    Timer: "Таймер",
    "Timer: switch to channel?": "Таймер: арнаға ауысу керек пе?",
    "Timeshift: one minute back": "Уақыт ығысуы: бір минут артқа",
    "Timeshift: to start of TV program": "Уақыт ығысуы: бағдарламаның басына",
    Timezone: "Уақыт белдеуі",
    TMDb: "TMDb",
    "TOP-IPTV": "TOP-IPTV",
    "TOP-IPTV settings": "TOP-IPTV баптаулары",
    "To begining": "Басына",
    "To start of TV program / Previous TV program":
        "Бағдарламаның басына / алдыңғы бағдарлама",
    "Toggle Aspect Ratio": "Кадр арақатынасын өзгерту",
    "Toggle on-screen debug HUD":
        "Экрандағы жөндеу тақтасын көрсету немесе жасыру",
    "Toggle Zoom Mode": "Масштаб режимін өзгерту",
    "Top-Tv": "Top-Tv",
    "Top-Tv settings": "Top-Tv баптаулары",
    "Try demo": "Демоны көру",
    "TV DOSUG": "TV DOSUG",
    "TV DOSUG settings": "TV DOSUG баптаулары",
    TVClub: "TVClub",
    "TVClub settings": "TVClub баптаулары",
    "Type of player for streaming": "Ағынға арналған ойнатқыш түрі",
    "top-left": "жоғарғы сол жақ",
    "top-right": "жоғарғы оң жақ",
    transparent: "мөлдір",
    ULTIFL1X: "ULTIFL1X",
    "ULTIFL1X settings": "ULTIFL1X баптаулары",
    "Update installed. Please restart OttPlay FOSS.":
        "Жаңарту орнатылды. OttPlay FOSS қолданбасын қайта іске қосыңыз.",
    "Use an HTTP or HTTPS server address.":
        "HTTP немесе HTTPS сервер мекенжайын қолданыңыз.",
    "Use HTTP or HTTPS without a username or password in the address.":
        "Мекенжайда пайдаланушы аты мен құпиясөзі жоқ HTTP немесе HTTPS қолданыңыз.",
    "Use LEFT/RIGHT to select a control, OK to activate, and UP/DOWN to scroll.":
        "Элементті таңдау үшін СОЛ/ОҢ, іске қосу үшін OK, айналдыру үшін ЖОҒАРЫ/ТӨМЕН түймелерін пайдаланыңыз.",
    Username: "Пайдаланушы аты",
    "Username or password is missing.": "Пайдаланушы аты немесе құпиясөз жоқ.",
    "VIP-IP.COM": "VIP-IP.COM",
    "VIP-IP.COM settings": "VIP-IP.COM баптаулары",
    "Vidok.TV": "Vidok.TV",
    "Vidok.TV settings": "Vidok.TV баптаулары",
    "VOD not supported by provider":
        "Провайдер сұраныс бойынша бейнені қолдамайды",
    "Volume step, %": "Дыбыс деңгейінің қадамы, %",
    "VPortal link": "VPortal сілтемесі",
    "VPortal request failed":
        "VPortal жүктелмеді. Сілтемені, кіру кілтін және порталдың қолжетімділігін тексеріңіз.",
    volume: "дыбыс деңгейі",
    "Wrong parental code !!!": "Ата-ана коды қате!",
    "Xtream Codes Provider": "Xtream Codes провайдері",
    "Xtream Codes settings": "Xtream Codes баптаулары",
    Year: "Жыл",
    Yellow: "Сары",
    Yes: "Иә",
    yes: "иә",
    "Гомельсат (cbilling)": "Гомельсат (cbilling)",
    "Гомельсат (cbilling) settings": "Гомельсат (cbilling) баптаулары",
    МойДом: "МойДом",
    "МойДом settings": "МойДом баптаулары",
    "Ошибка обработки списка каналов! Проверьте правильность данных!!":
        "Арналар тізімін өңдеу мүмкін болмады. Провайдер деректерін тексеріңіз!",
    Радуга: "Радуга",
    "Радуга settings": "Радуга баптаулары",
    "Редактирование ID": "ID өңдеу",
    "Редактирование PIN": "PIN өңдеу",
    Шаравоз: "Шаравоз",
    "Шаравоз settings": "Шаравоз баптаулары",
    "↑↓ Scroll": "↑↓ Айналдыру",
};
