var keyStrings = {
 "lang": "Latviešu",
 "alhabet": "aābcčdeēfgģhiījkķlļmnņoprsštuūvzž",
 "Channel list. Category: ": "Kanālu saraksts. Kategorija: ",
 "EPG": "Programma",
 "Category": "Kategorija",
 "Actions": "Darbības",
 "Description": "Apraksts",
 "Open in PiP": "Atvērt PiP",
 "Move channel up": "Pārvietot kanālu uz augšu",
 "Move channel down": "Pārvietot kanālu uz leju",
 "Delete channel": "Dzēst kanālu",
 "Add channel to category": "Pievienot kanālu kategorijai",
 "Add channel to favorites": "Pievienot kanālu izlasei",
 "Channel parental control": "Kanāla vecāku kontrole",
 "Channel is not available!!!": "Kanāls nav pieejams!!!",
 "min": "min",
 "Channel ": "Kanāls ",
 " added to category ": " pievienots kategorijai ",
 " added to favorites": " pievienots izlasei",
 "Favorites": "Izlase",
 "Select category to add channel": "Izvēlieties kategoriju, lai pievienotu kanālu",
 "Enter parental code": "Ievadiet vecāku kodu",
 "Wrong parental code !!!": "Nepareizs vecāku kods!!!",
 "Close": "Aizvērt",
 "Edit category name": "Rediģēt kategorijas nosaukumu",
 "Menu": "Izvēlne",
 "Channel list": "Kanālu saraksts",
 "Settings": "Iestatījumi",
 "Settings saved": "Iestatījumi saglabāti",
 "no": "nē",
 "yes": "jā",
 "Info": "Informācija",
 "Nothing": "Nekas",
 "Exit": "Iziet",
 "off": "izslēgts",
 "Failed to load channel list!": "Neizdevās ielādēt kanālu sarakstu!",
 "??? No channel name": "??? Nav kanāla nosaukuma",
 "Playlist URL": "Atskaņošanas saraksta URL",
 "Archive hours": "Arhīva stundas",
 "Enter playlist URL": "Ievadiet atskaņošanas saraksta URL",
 "Playlist Name": "Atskaņošanas saraksta nosaukums",
 "Enter playlist Name": "Ievadiet atskaņošanas saraksta nosaukumu",
 "Media Library URL": "Mediotēkas URL",
 "Enter Media Library URL": "Ievadiet mediotēkas URL",
 "Playlist": "Atskaņošanas saraksts",
 "Playlist is not loading directly...Loading via server...": "Atskaņošanas saraksts netiek ielādēts tieši...Ielāde caur serveri...",
 "Select playlist": "Izvēlieties atskaņošanas sarakstu",
 "Edit": "Rediģēt",
 "Load": "Ielādēt",
 "Edit playlist data": "Rediģēt atskaņošanas saraksta datus",
 "All": "Visi",
 "Search": "Meklēt",
 "m3u-m3u8 playlists": "m3u-m3u8 atskaņošanas saraksti",
 "Stalker portals": "Stalker portāli",
 "Settings STB": "STB iestatījumi",
 "Type of player for streaming": "Atskaņotāja veids straumēšanai",
 "Buffer Size, s": "Bufera lielums, s",
 "Save Settings": "Saglabāt iestatījumus",
 "Editor": "Redaktors",
 "built-in": "iebūvēts",
 "native": "vietējais",
 "No channel name": "Nav kanāla nosaukuma",
 " (after changing, load playlist)": " (pēc izmaiņām, ielādējiet atskaņošanas sarakstu)",
 "Enter playlist archive hours": "Ievadiet atskaņošanas saraksta arhīva stundas",
 "Load playlist": "Ielādēt atskaņošanas sarakstu",
 "Playlist file": "Atskaņošanas saraksta fails",
 "Select playlist file": "Izvēlieties atskaņošanas saraksta failu",
 "Channel list not received !!!<br/><br/>Enter the provider data and restart the player !!!<br/><br/>": "Kanālu saraksts nav saņemts!!!<br/><br/>Ievadiet pakalpojumu sniedzēja datus un restartējiet atskaņotāju!!!<br/><br/>",
 "Channel list not received !!!": "Kanālu saraksts nav saņemts!!!"
};
