var keyStrings = {
    " (after changing, load playlist)":
        " (pēc izmaiņām, ielādējiet atskaņošanas sarakstu)",
    " (after changing, restart player)":
        " (pēc maiņas pārstartējiet atskaņotāju)",
    " added to category ": " pievienots kategorijai ",
    " added to favorites": " pievienots izlasei",
    " m ": " min ",
    " s": " s",
    "??? No channel name": "??? Nav kanāla nosaukuma",
    '"As Is"': "„Kā ir”",
    '"Favorites"': "„Izlase”",
    '"Sliding" infobar': "Slīdoša informācijas josla",
    "&darr;a": "&darr;a",
    "&uarr;A": "&uarr;A",
    "<br/><br/>In archive mode:<br/>": "<br/><br/>Arhīva režīmā:<br/>",
    "<br/>Loading STB...": "<br/>STB ielāde…",
    "<br/>Setup STB...": "<br/>STB iestatīšana…",
    "<br>": "<br>",
    "<br><br>": "<br><br>",
    "<br>Add<br>to category": "<br>Pievienot<br>kategorijai",
    "<br>Add<br>to favorites": "<br>Pievienot<br>izlasei",
    "<br>Delete": "<br>Dzēst",
    "<br>Down<br>": "<br>Uz leju<br>",
    "<br>Live": "<br>Tiešraide",
    "<br>Menu": "<br>Izvēlne",
    "<br>Parental<br>Control": "<br>Vecāku<br>kontrole",
    "<br>Pause<br>": "<br>Pauze<br>",
    "<br>Previous<br>channel": "<br>Iepriekšējais<br>kanāls",
    "<br>Rewind<br>": "<br>Attīt<br>",
    "<br>Toggle<br>sound track": "<br>Mainīt<br>skaņas celiņu",
    "<br>Up<br>": "<br>Uz augšu<br>",
    "1 hour": "1 stunda",
    "1 minute": "1 minūte",
    "2 hours": "2 stundas",
    "3 hours": "3 stundas",
    "10 Seconds": "10 sekundes",
    "30 minutes": "30 minūtes",
    "A command expired while the player was loading channels.":
        "Kanālu ielādes laikā beidzās komandas derīgums.",
    "A command was rejected by the player. Check its provider and settings.":
        "Atskaņotājs noraidīja komandu. Pārbaudiet tā pakalpojuma sniedzēju un iestatījumus.",
    About: "Par programmu",
    "Access code": "Piekļuves kods",
    "Access denied. Check the server access code.":
        "Piekļuve liegta. Pārbaudiet servera piekļuves kodu.",
    "Access key": "Piekļuves atslēga",
    "Access key is required!": "Nepieciešama piekļuves atslēga!",
    "Access settings": "Piekļuves iestatījumi",
    Actions: "Darbības",
    "Active list": "Aktīvais saraksts",
    Actors: "Aktieri",
    "Add / rename / delete…": "Pievienot / pārdēvēt / dzēst…",
    "Add channel to category": "Pievienot kanālu kategorijai",
    "Add channel to favorites": "Pievienot kanālu izlasei",
    "Add new list": "Pievienot jaunu sarakstu",
    "Add to favorites": "Pievienot izlasei",
    Age: "Vecums",
    All: "Visi",
    "All categories": "Visas kategorijas",
    "All4you.tv": "All4you.tv",
    "All4you.tv settings": "All4you.tv iestatījumi",
    "Allowlist this Device ID": "Atļaut šo ierīces ID",
    "An IP without a port uses HTTP port 8081. Clear the address or select Disconnect to stop.":
        "IP adrese bez porta izmanto HTTP portu 8081. Lai apturētu, notīriet adresi vai izvēlieties Atvienot.",
    "API failed, trying M3U...": "API kļūme, mēģina M3U…",
    "API Server": "API serveris",
    "API server URL": "API servera URL",
    "Applying HTTP remote settings...":
        "Tiek piemēroti HTTP tālvadības iestatījumi...",
    Archive: "Arhīvs",
    "Archive - begin": "Arhīvs — sākums",
    "Archive hours": "Arhīva stundas",
    "Archive: ENTER on past programs":
        "Arhīvs: ENTER uz iepriekšējiem raidījumiem",
    "Archive. Channel: ": "Arhīvs. Kanāls: ",
    Aspect: "Attēla proporcijas",
    Audio: "Skaņa",
    alhabet: "aābcčdeēfgģhiījkķlļmnņoprsštuūvzž",
    always: "vienmēr",
    "and enter code": "un ievadiet kodu",
    Back: "Atpakaļ",
    "Back / Forward for 1 minute": "1 minūti atpakaļ / uz priekšu",
    "Background color": "Fona krāsa",
    "Background color of selected item": "Atlasītā vienuma fona krāsa",
    "BEST LiST IPTV [HLS Playlist]": "BEST LiST IPTV [HLS Playlist]",
    "BEST LiST IPTV [HLS Playlist] settings":
        "BEST LiST IPTV [HLS Playlist] iestatījumi",
    "BEST LiST IPTV [Stalker]": "BEST LiST IPTV [Stalker]",
    "BEST LiST IPTV [Stalker] settings": "BEST LiST IPTV [Stalker] iestatījumi",
    "Behavior of %1/%2 buttons in lists": "Pogu %1/%2 darbība sarakstos",
    "Black screen while switching the channel":
        "Melns ekrāns, pārslēdzot kanālus",
    Blue: "Zils",
    "Bookmark age: %1 days": "Grāmatzīmes vecums: %1 dienas",
    "Buffer Size, s": "Bufera lielums, s",
    "Built-in playlist:": "Iebūvētais atskaņošanas saraksts:",
    "Built-in playlists": "Iebūvētie atskaņošanas saraksti",
    "Button %1 function when viewing": "Pogas %1 funkcija skatīšanās laikā",
    "Button function %1 when viewing archive":
        "Pogas %1 funkcija arhīva skatīšanās laikā",
    "Buttons settings": "Pogu iestatījumi",
    "By alphabet": "Alfabētiski",
    "By time": "Hronoloģiski",
    "begin/end": "sākums/beigas",
    "bottom-right": "apakšā pa labi",
    "built-in": "iebūvēts",
    "Call PiP": "Atvērt PiP",
    "Call PiP / PiP exchange": "Atvērt PiP / samainīt PiP",
    Cancel: "Atcelt",
    "Cannot delete the last category": "Pēdējo kategoriju nevar dzēst",
    Category: "Kategorija",
    "Category selection": "Kategorijas izvēle",
    "Change interface language": "Mainīt saskarnes valodu",
    "Change provider": "Mainīt pakalpojuma sniedzēju",
    "Change provider - you can change the provider, and it will be remembered at the next start of player!":
        "Mainiet pakalpojuma sniedzēju. Izvēle tiks saglabāta nākamajai atskaņotāja palaišanai.",
    "Change value": "Mainīt vērtību",
    "Channel ": "Kanāls ",
    "Channel has no EPG": "Kanālam nav EPG",
    "Channel is not available!!!": "Kanāls nav pieejams!!!",
    "Channel link": "Kanāla saite",
    "Channel link is required!": "Nepieciešama kanāla saite!",
    "Channel list": "Kanālu saraksts",
    "Channel list editing style": "Kanālu saraksta rediģēšanas režīms",
    "Channel list not received !!!": "Kanālu saraksts nav saņemts!!!",
    "Channel list not received !!!<br/><br/>Enter the provider data and restart the player !!!<br/><br/>":
        "Kanālu saraksts nav saņemts!!!<br/><br/>Ievadiet pakalpojumu sniedzēja datus un restartējiet atskaņotāju!!!<br/><br/>",
    "Channel list settings": "Channel list iestatījumi",
    "Channel list. Category: ": "Kanālu saraksts. Kategorija: ",
    "Channel parental control": "Kanāla vecāku kontrole",
    Channels: "Kanāli",
    "Choose from": "Izvēlēties no",
    "Choose language": "Izvēlēties valodu",
    "Choose provider": "Izvēlēties pakalpojuma sniedzēju",
    Classic: "Klasisks",
    "Clear all settings?": "Notīrīt visus iestatījumus?",
    "Clear settings": "Notīrīt iestatījumus",
    Close: "Aizvērt",
    "Close PiP": "Aizvērt PiP",
    Color: "Krāsa",
    "Color spectrum": "Krāsu spektrs",
    "Command server": "Komandu serveris",
    "Command server address, device access code, local HTTP control, and remote text entry settings":
        "Komandu servera adrese, ierīces piekļuves kods, lokālā HTTP vadība un attālinātās teksta ievades iestatījumi",
    "Configure All4you.tv in Settings -> Provider Settings":
        "Konfigurējiet All4you.tv sadaļā Iestatījumi -> Pakalpojuma sniedzēja iestatījumi",
    "Configure BEST LiST IPTV [HLS Playlist] in Settings -> Provider Settings":
        "Konfigurējiet BEST LiST IPTV [HLS Playlist] sadaļā Iestatījumi -> Pakalpojuma sniedzēja iestatījumi",
    "Configure BEST LiST IPTV [Stalker] in Settings -> Provider Settings":
        "Konfigurējiet BEST LiST IPTV [Stalker] sadaļā Iestatījumi -> Pakalpojuma sniedzēja iestatījumi",
    "Configure Diamond TV in Settings -> Provider Settings":
        "Konfigurējiet Diamond TV sadaļā Iestatījumi -> Pakalpojuma sniedzēja iestatījumi",
    "Configure DRVAO in Settings -> Provider Settings":
        "Konfigurējiet DRVAO sadaļā Iestatījumi -> Pakalpojuma sniedzēja iestatījumi",
    "Configure Dragon Media PRO in Settings -> Provider Settings":
        "Konfigurējiet Dragon Media PRO sadaļā Iestatījumi -> Pakalpojuma sniedzēja iestatījumi",
    "Configure Fabryka.TV in Settings -> Provider Settings":
        "Konfigurējiet Fabryka.TV sadaļā Iestatījumi -> Pakalpojuma sniedzēja iestatījumi",
    "Configure Fox-TV in Settings -> Provider Settings":
        "Konfigurējiet Fox-TV sadaļā Iestatījumi -> Pakalpojuma sniedzēja iestatījumi",
    "Configure FXML in Settings -> Provider Settings":
        "Konfigurējiet FXML sadaļā Iestatījumi -> Pakalpojuma sniedzēja iestatījumi",
    "Configure GlanzTV in Settings -> Provider Settings":
        "Konfigurējiet GlanzTV sadaļā Iestatījumi -> Pakalpojuma sniedzēja iestatījumi",
    "Configure GREAT IPTV in Settings -> Provider Settings":
        "Konfigurējiet GREAT IPTV sadaļā Iestatījumi -> Pakalpojuma sniedzēja iestatījumi",
    "Configure IpStream.one in Settings -> Provider Settings":
        "Konfigurējiet IpStream.one sadaļā Iestatījumi -> Pakalpojuma sniedzēja iestatījumi",
    "Configure KORONA TV in Settings -> Provider Settings":
        "Konfigurējiet KORONA TV sadaļā Iestatījumi -> Pakalpojuma sniedzēja iestatījumi",
    "Configure MaxTV in Settings -> Provider Settings":
        "Konfigurējiet MaxTV sadaļā Iestatījumi -> Pakalpojuma sniedzēja iestatījumi",
    "Configure New Look in Settings -> Provider Settings":
        "Konfigurējiet New Look sadaļā Iestatījumi -> Pakalpojuma sniedzēja iestatījumi",
    "Configure OTT Prime ONLINE in Settings -> Provider Settings":
        "Konfigurējiet OTT Prime ONLINE sadaļā Iestatījumi -> Pakalpojuma sniedzēja iestatījumi",
    "Configure POLMEDIA in Settings -> Provider Settings":
        "Konfigurējiet POLMEDIA sadaļā Iestatījumi -> Pakalpojuma sniedzēja iestatījumi",
    "Configure PROST in Settings -> Provider Settings":
        "Konfigurējiet PROST sadaļā Iestatījumi -> Pakalpojuma sniedzēja iestatījumi",
    "Configure RD in Settings -> Provider Settings":
        "Konfigurējiet RD sadaļā Iestatījumi -> Pakalpojuma sniedzēja iestatījumi",
    "Configure RUSSKOETV in Settings -> Provider Settings":
        "Konfigurējiet RUSSKOETV sadaļā Iestatījumi -> Pakalpojuma sniedzēja iestatījumi",
    "Configure Shara.club (ClubTV.pro) in Settings -> Provider Settings":
        "Konfigurējiet Shara.club (ClubTV.pro) sadaļā Iestatījumi -> Pakalpojuma sniedzēja iestatījumi",
    "Configure ShockTv in Settings -> Provider Settings":
        "Konfigurējiet ShockTv sadaļā Iestatījumi -> Pakalpojuma sniedzēja iestatījumi",
    "Configure Tabox in Settings -> Provider Settings":
        "Konfigurējiet Tabox sadaļā Iestatījumi -> Pakalpojuma sniedzēja iestatījumi",
    "Configure TOP-IPTV in Settings -> Provider Settings":
        "Konfigurējiet TOP-IPTV sadaļā Iestatījumi -> Pakalpojuma sniedzēja iestatījumi",
    "Configure Top-Tv in Settings -> Provider Settings":
        "Konfigurējiet Top-Tv sadaļā Iestatījumi -> Pakalpojuma sniedzēja iestatījumi",
    "Configure TV DOSUG in Settings -> Provider Settings":
        "Konfigurējiet TV DOSUG sadaļā Iestatījumi -> Pakalpojuma sniedzēja iestatījumi",
    "Configure TVClub in Settings -> Provider Settings":
        "Konfigurējiet TVClub sadaļā Iestatījumi -> Pakalpojuma sniedzēja iestatījumi",
    "Configure ULTIFL1X in Settings -> Provider Settings":
        "Konfigurējiet ULTIFL1X sadaļā Iestatījumi -> Pakalpojuma sniedzēja iestatījumi",
    "Configure VIP-IP.COM in Settings -> Provider Settings":
        "Konfigurējiet VIP-IP.COM sadaļā Iestatījumi -> Pakalpojuma sniedzēja iestatījumi",
    "Configure Vidok.TV in Settings -> Provider Settings":
        "Konfigurējiet Vidok.TV sadaļā Iestatījumi -> Pakalpojuma sniedzēja iestatījumi",
    "Configure Гомельсат (cbilling) in Settings -> Provider Settings":
        "Konfigurējiet Гомельсат (cbilling) sadaļā Iestatījumi -> Pakalpojuma sniedzēja iestatījumi",
    "Configure МойДом in Settings -> Provider Settings":
        "Konfigurējiet МойДом sadaļā Iestatījumi -> Pakalpojuma sniedzēja iestatījumi",
    "Configure Радуга in Settings -> Provider Settings":
        "Konfigurējiet Радуга sadaļā Iestatījumi -> Pakalpojuma sniedzēja iestatījumi",
    "Configure Шаравоз in Settings -> Provider Settings":
        "Konfigurējiet Шаравоз sadaļā Iestatījumi -> Pakalpojuma sniedzēja iestatījumi",
    Connect: "Savienot",
    Connected: "Savienots",
    "Connected. Waiting for the channel list...":
        "Savienots. Gaida kanālu sarakstu…",
    "Connecting to Stalker portal...": "Savienojas ar Stalker portālu…",
    "Connecting...": "Savienojas…",
    "Continue watching?": "Turpināt skatīties?",
    "Copy category": "Kopēt kategoriju",
    "Copy JSON": "Kopēt JSON",
    "Could not connect to the server.": "Neizdevās savienoties ar serveri.",
    "Could not update HTTP remote control.":
        "Neizdevās atjaunināt HTTP tālvadības iestatījumus.",
    Country: "Valsts",
    "Create category": "Izveidot kategoriju",
    current: "pašreizējais",
    "Debug HUD": "Atkļūdošanas panelis",
    "Debug HUD is not available": "Atkļūdošanas panelis nav pieejams",
    Delete: "Dzēst",
    "Delete category": "Dzēst kategoriju",
    "Delete channel": "Dzēst kanālu",
    "Delete list": "Dzēst sarakstu",
    "Demo — moving test pattern": "Demonstrācija — kustīgs testa attēls",
    Description: "Apraksts",
    "Description of remote control buttons": "Tālvadības pults pogu ceļvedis",
    "Device access code": "Ierīces piekļuves kods",
    "Device info:": "Ierīces informācija:",
    "Device MAC is required for KBC (Kinoboom) playlists":
        "KBC (Kinoboom) sarakstiem nepieciešama ierīces MAC adrese",
    "Diamond TV": "Diamond TV",
    "Diamond TV settings": "Diamond TV iestatījumi",
    Director: "Režisors",
    "Disable HTTP remote": "Izslēgt HTTP tālvadību",
    "Disabled by default. Enabling creates a new device access code.":
        "Pēc noklusējuma izslēgta. Ieslēdzot tiek izveidots jauns ierīces piekļuves kods.",
    Disconnect: "Atvienot",
    Disconnected: "Atvienots",
    "Distance between lines in lists": "Rindstarpa sarakstos",
    "Do you want to exit player?": "Vai vēlaties iziet no atskaņotāja?",
    "Download! Wait ...": "Lejupielādē… lūdzu, uzgaidiet…",
    DRVAO: "DRVAO",
    "DRVAO settings": "DRVAO iestatījumi",
    "Dragon Media PRO": "Dragon Media PRO",
    "Dragon Media PRO settings": "Dragon Media PRO iestatījumi",
    Duration: "Ilgums",
    Edit: "Rediģēt",
    "Edit access key": "Rediģēt piekļuves atslēgu",
    "Edit category name": "Rediģēt kategorijas nosaukumu",
    "Edit channel link": "Rediģēt kanāla saiti",
    "Edit playlist data": "Rediģēt atskaņošanas saraksta datus",
    "Edit VPortal link": "Rediģēt VPortal saiti",
    Editor: "Redaktors",
    "Enable HTTP remote": "Ieslēgt HTTP tālvadību",
    English: "Angļu",
    "Enter a password (8 characters).": "Ievadiet paroli (8 rakstzīmes).",
    "Enter a playlist URL to access this service.":
        "Lai piekļūtu šim pakalpojumam, ievadiet atskaņošanas saraksta URL.",
    "Enter a server address without spaces or a fragment.":
        "Ievadiet servera adresi bez atstarpēm un fragmenta aiz #.",
    "Enter a username (8 characters).":
        "Ievadiet lietotājvārdu (8 rakstzīmes).",
    "Enter a username and password to access this service.":
        "Lai piekļūtu šim pakalpojumam, ievadiet lietotājvārdu un paroli.",
    "Enter a valid server address, for example 192.168.1.20:8081.":
        "Ievadiet derīgu servera adresi, piemēram, 192.168.1.20:8081.",
    "Enter access key for": "Ievadiet piekļuves atslēgu:",
    "Enter an application access key (8 characters).":
        "Ievadiet lietotnes piekļuves atslēgu (8 rakstzīmes).",
    "Enter an ID and PIN to access this service.":
        "Lai piekļūtu šim pakalpojumam, ievadiet ID un PIN.",
    "Enter an IPTV token (10 characters).":
        "Ievadiet IPTV piekļuves pilnvaru (10 rakstzīmes).",
    "Enter category name": "Ievadiet kategorijas nosaukumu",
    "Enter MAC address": "Ievadiet MAC adresi",
    "Enter MAC address (e.g. 00:1A:2B:3C:4D:5E)":
        "Ievadiet MAC adresi (piem., 00:1A:2B:3C:4D:5E)",
    "Enter Media Library URL": "Ievadiet mediotēkas URL",
    "Enter new category name": "Ievadiet jauno kategorijas nosaukumu",
    "Enter Provider Code": "Ievadiet pakalpojuma sniedzēja kodu",
    "Enter Provider Code on PC or Phone":
        "Ievadiet pakalpojuma sniedzēja kodu datorā vai tālrunī",
    "Enter parental code": "Ievadiet vecāku kodu",
    "Enter password": "Ievadiet paroli",
    "Enter playlist archive hours":
        "Ievadiet atskaņošanas saraksta arhīva stundas",
    "Enter playlist Name": "Ievadiet atskaņošanas saraksta nosaukumu",
    "Enter playlist URL": "Ievadiet atskaņošanas saraksta URL",
    "Enter Stalker portal URL": "Ievadiet Stalker portāla URL",
    "Enter Stalker portal URL (e.g. http://your-portal:8800)":
        "Ievadiet Stalker portāla URL (piem., http://your-portal:8800)",
    "Enter Stalker portal URL (e.g. http://your-portal/stalker_portal/c/)":
        "Ievadiet Stalker portāla URL (piem., http://your-portal/stalker_portal/c/)",
    "Enter the access code separately, not in the server address.":
        "Piekļuves kodu ievadiet atsevišķi, nevis servera adresē.",
    "Enter the command server IP or address.":
        "Ievadiet komandu servera IP vai adresi.",
    "Enter the full CDN host from the cabinet stream URL (e.g. subdomain.cdn-domain.tld), not a bare subdomain":
        "Ievadiet pilnu CDN resursdatora nosaukumu no konta straumes URL (piem., subdomain.cdn-domain.tld), nevis tikai apakšdomēnu",
    "Enter the server IP or address and this player's device access code from the server configuration. Saving both starts checking for volume, channel and other commands automatically.":
        "Ievadiet servera IP vai adresi un šī atskaņotāja ierīces piekļuves kodu no servera konfigurācijas. Saglabājot abus, automātiski sākas skaļuma, kanālu un citu komandu pārbaude.",
    "Enter the server's device access code (32–256 letters, digits, _ or -).":
        "Ievadiet servera ierīces piekļuves kodu (32–256 burti, cipari, _ vai -).",
    'Enter the tv.team playlist URL.<br>Playlist type: <b>OTTPlayer</b><br/><br/>The "/playlist.m3u8" suffix is added automatically if omitted.':
        "Ievadiet tv.team atskaņošanas saraksta URL.<br>Saraksta veids: <b>OTTPlayer</b><br/><br/>Ja beigu daļa „/playlist.m3u8” nav norādīta, tā tiek pievienota automātiski.",
    "Enter the VPortal link as shown in the cabinet":
        "Ievadiet VPortal saiti tā, kā tā redzama lietotāja kontā",
    "Enter this link in VPortal link. Playlist URL requires an M3U playlist.":
        "Ievadiet šo saiti VPortal saites laukā. Atskaņošanas saraksta URL jānorāda M3U saraksts.",
    "Enter this player's device access code to connect.":
        "Lai savienotos, ievadiet šī atskaņotāja ierīces piekļuves kodu.",
    "Enter username": "Ievadiet lietotājvārdu",
    "Enter value": "Ievadiet vērtību",
    "Enter Xtream server URL": "Ievadiet Xtream servera URL",
    "Enter Xtream server URL (e.g. https://your-server:8080)":
        "Ievadiet Xtream servera URL (piem., https://your-server:8080)",
    EPG: "Programma",
    "EPG and archive. Channel: ": "EPG un arhīvs. Kanāls: ",
    "ERROR!": "Kļūda!",
    "Error Code!": "Nederīgs kods!",
    Exit: "Iziet",
    "Exit player": "Iziet no atskaņotāja",
    "Export settings": "Eksportēt iestatījumus",
    "epg.one (Ordered)": "epg.one (sakārtots)",
    "epg.one (Standard)": "epg.one (standarta)",
    "epg.one (Thematic)": "epg.one (tematisks)",
    "epgs...": "Programmu ceļveži…",
    "Fabryka.TV": "Fabryka.TV",
    "Fabryka.TV settings": "Fabryka.TV iestatījumi",
    "Failed to connect to Stalker portal":
        "Neizdevās savienoties ar Stalker portālu",
    "Failed to connect to Xtream API server":
        "Neizdevās savienoties ar Xtream API serveri",
    "Failed to get user data!!!": "Neizdevās saņemt lietotāja datus!",
    "Failed to load channel list!": "Neizdevās ielādēt kanālu sarakstu!",
    "Failed to load channels from Stalker portal":
        "Neizdevās ielādēt kanālus no Stalker portāla",
    "Failed to load channels from Xtream API":
        "Neizdevās ielādēt kanālus no Xtream API",
    "Failed to load!": "Ielāde neizdevās!",
    "Favorite lists": "Izlases saraksti",
    Favorites: "Izlase",
    "File selection is not supported on this device":
        "Šajā ierīcē failu izvēle netiek atbalstīta",
    Filters: "Filtri",
    "First Run Setup": "Pirmās palaišanas iestatīšana",
    "Font type": "Fonta veids",
    "For download settings file open":
        "Lai lejupielādētu iestatījumu failu, atveriet",
    "For enter value open": "Lai ievadītu vērtību, atveriet",
    "For upload settings file open":
        "Lai augšupielādētu iestatījumu failu, atveriet",
    "Fox-TV": "Fox-TV",
    "Fox-TV settings": "Fox-TV iestatījumi",
    FXML: "FXML",
    "FXML settings": "FXML iestatījumi",
    Genre: "Žanrs",
    GlanzTV: "GlanzTV",
    "GlanzTV settings": "GlanzTV iestatījumi",
    "Go to": "Doties uz",
    "GREAT IPTV": "GREAT IPTV",
    "GREAT IPTV settings": "GREAT IPTV iestatījumi",
    "Graphical indication": "Grafiskie indikatori",
    Green: "Zaļš",
    "Hide / Return": "Slēpt / rādīt",
    "Hide provider settings?": "Slēpt pakalpojuma sniedzēja iestatījumus?",
    "Hide providers?": "Slēpt pakalpojuma sniedzējus?",
    "History in Media Library": "Vēsture multivides bibliotēkā",
    "History of watched movies": "Skatīšanās vēsture",
    "HTTP port": "HTTP ports",
    "HTTP remote control is unavailable on this device.":
        "HTTP tālvadība šajā ierīcē nav pieejama.",
    ID: "ID",
    "Import settings": "Importēt iestatījumus",
    "In live mode: <br/>": "Tiešraides režīmā:<br/>",
    Info: "Informācija",
    "Infobar display timeout, s": "Informācijas joslas rādīšanas ilgums, s",
    "Infobar settings": "Informācijas joslas iestatījumi",
    Information: "Informācija",
    "Interface credits": "Saskarnes autori",
    "Interface settings": "Saskarnes iestatījumi",
    "Interface theme": "Saskarnes motīvs",
    "Interface transparency": "Saskarnes caurspīdīgums",
    "Invalid channel link! Enter the full host as in the cabinet stream URL (e.g. subdomain.cdn-domain.tld)":
        "Nederīga kanāla saite! Ievadiet pilnu resursdatora nosaukumu kā konta straumes URL (piem., subdomain.cdn-domain.tld)",
    "IPTV token": "IPTV piekļuves pilnvara",
    "IpStream.one": "IpStream.one",
    "IpStream.one settings": "IpStream.one iestatījumi",
    Joystick: "Kursorsvira",
    "KBC (Kinoboom) access data": "KBC (Kinoboom) piekļuves dati",
    "KORONA TV": "KORONA TV",
    "KORONA TV settings": "KORONA TV iestatījumi",
    "List created": "Saraksts izveidots",
    "List deleted": "Saraksts dzēsts",
    "List location": "Saraksta novietojums",
    "List renamed": "Saraksts pārdēvēts",
    "List type": "Saraksta veids",
    "Lists settings": "Sarakstu iestatījumi",
    Live: "Tiešraide",
    Load: "Ielādēt",
    "Load built-in playlist:": "Ielādēt iebūvēto atskaņošanas sarakstu:",
    "Load playlist": "Ielādēt atskaņošanas sarakstu",
    "Load settings": "Load iestatījumi",
    "Load settings from storage": "Ielādēt iestatījumus no krātuves",
    "Load:": "Ielādēt:",
    "Loading channels from Xtream API...": "Ielādē kanālus no Xtream API…",
    "Loading channels...": "Ielādē kanālus…",
    "Loading from API...": "Ielādē no API…",
    "Loading from Edem API...": "Ielādē no Edem API…",
    "Loading M3U playlist...": "Ielādē M3U atskaņošanas sarakstu…",
    "Loading M3U...": "Ielādē M3U…",
    "Loading via proxy...": "Ielādē caur starpniekserveri…",
    "Loading. Please wait...": "Ielādē… lūdzu, uzgaidiet…",
    "Loading...": "Ielādē…",
    "Local HTTP remote control": "Vietējā HTTP tālvadība",
    "Local URL": "Lokālais URL",
    Login: "Pieteikšanās",
    lang: "Latviešu",
    large: "liels",
    left: "pa kreisi",
    "left-bottom": "apakšā pa kreisi",
    "logos...": "Logotipi…",
    M3U: "M3U",
    "M3U URL": "M3U URL",
    "M3U URL (fallback)": "M3U URL (rezerves)",
    "MAC address": "MAC adrese",
    "Manage lists": "Pārvaldīt sarakstus",
    "Manage settings": "Pārvaldīt iestatījumus",
    "Manual setup": "Manuāla iestatīšana",
    MaxTV: "MaxTV",
    "MaxTV settings": "MaxTV iestatījumi",
    Media: "Multivide",
    "Media item is no longer available":
        "Multivides vienums vairs nav pieejams",
    "Media Library": "Multivides bibliotēka",
    "Media Library URL": "Mediotēkas URL",
    Menu: "Izvēlne",
    "Menu items settings": "Izvēlnes vienumu iestatījumi",
    "Move category down": "Pārvietot kategoriju uz leju",
    "Move category up": "Pārvietot kategoriju uz augšu",
    "Move channel down": "Pārvietot kanālu uz leju",
    "Move channel up": "Pārvietot kanālu uz augšu",
    "m3u-m3u8 playlists": "m3u-m3u8 atskaņošanas saraksti",
    medium: "vidējs",
    min: "min",
    "New Look": "New Look",
    "New Look settings": "New Look iestatījumi",
    "New list name": "Jaunā saraksta nosaukums",
    Next: "Nākamā lapa",
    "Next keyboard page": "Nākamā tastatūras lapa",
    "Next TV program": "Nākamais raidījums",
    No: "Nē",
    "No channel name": "Nav kanāla nosaukuma",
    "No saved settings found": "Nav atrasti saglabāti iestatījumi",
    "Not found": "Nav atrasts",
    "Not reduce video when showing the list (bugfix)":
        "Nesamazināt video, rādot sarakstu (kļūdas labojums)",
    Nothing: "Nekas",
    "Number of next TV programs in channel list":
        "Nākamo raidījumu skaits kanālu sarakstā",
    "Number of rows in lists": "Rindu skaits sarakstos",
    native: "vietējais",
    no: "nē",
    "no epg at current time": "Pašlaik nav EPG",
    "not set": "nav iestatīts",
    Off: "Izslēgts",
    Ok: "Labi",
    Open: "Atvērt",
    "Open in PiP": "Atvērt PiP",
    "OTT Prime ONLINE": "OTT Prime ONLINE",
    "OTT Prime ONLINE settings": "OTT Prime ONLINE iestatījumi",
    "OttPlay FOSS %1 is available. Download and install now?":
        "Pieejams OttPlay FOSS %1. Lejupielādēt un instalēt tagad?",
    "Overwrite current settings?": "Pārrakstīt pašreizējos iestatījumus?",
    off: "izslēgts",
    on: "ieslēgta",
    "on ": "ieslēgts ",
    "or scan": "vai skenējiet",
    "Parental control": "Vecāku kontrole",
    Password: "Parole",
    Pause: "Pauze",
    "Pause/Play": "Pauze / atskaņot",
    "Permanent clock on screen": "Vienmēr rādīt pulksteni ekrānā",
    PIN: "PIN",
    "PiP exchange": "Samainīt PiP",
    "PiP window position": "PiP loga novietojums",
    "PiP window size": "PiP loga izmērs",
    Play: "Atskaņot",
    "Player and device info": "Atskaņotāja un ierīces informācija",
    "Player info:": "Atskaņotāja informācija:",
    Playlist: "Atskaņošanas saraksts",
    "Playlist file": "Atskaņošanas saraksta fails",
    "Playlist is not loading directly...Loading via server...":
        "Atskaņošanas saraksts netiek ielādēts tieši...Ielāde caur serveri...",
    "Playlist Name": "Atskaņošanas saraksta nosaukums",
    "Playlist URL": "Atskaņošanas saraksta URL",
    POLMEDIA: "POLMEDIA",
    "POLMEDIA settings": "POLMEDIA iestatījumi",
    "Portal URL": "Portāla URL",
    "Position shift -10 seconds after pause":
        "Pēc pauzes pāriet 10 sekundes atpakaļ",
    PROST: "PROST",
    "PROST settings": "PROST iestatījumi",
    Prev: "Iepriekšējais",
    "Preview in channel list": "Priekšskatījums kanālu sarakstā",
    Previous: "Iepriekšējais",
    "Privacy policy": "Privātuma politika",
    "Protect Adult Channels": "Aizsargāt pieaugušo kanālus",
    "Protect Change Provider": "Aizsargāt pakalpojuma sniedzēja maiņu",
    "Protect Settings": "Aizsargāt iestatījumus",
    "p...": "p...",
    paging: "pa lapām",
    Quality: "Kvalitāte",
    Rating: "Vērtējums",
    RD: "RD",
    "RD settings": "RD iestatījumi",
    "Reconnecting…": "Savienojas atkārtoti…",
    Records: "Ieraksti",
    "Records for channel: ": "Kanāla ieraksti: ",
    "Records library is empty": "Ierakstu bibliotēka ir tukša",
    "Records not supported by provider":
        "Šis pakalpojuma sniedzējs neatbalsta ierakstus",
    "Release date": "Izlaišanas datums",
    "Remember previous channels": "Atcerēties iepriekšējos kanālus",
    "Reminder: %1 — %2 in %3 min": "Atgādinājums: %1 — %2 pēc %3 min.",
    "Remote (color buttons N/A)": "Pults (bez krāsu pogām)",
    "Remote (number buttons N/A)": "Pults (bez ciparu pogām)",
    "Remote control": "Tālvadība",
    "Remote session expired": "Attālinātās sesijas derīgums ir beidzies",
    "Remote text entry denied": "Attālinātā teksta ievade liegta",
    "Remote text entry error": "Attālinātās teksta ievades kļūda",
    "Remote text entry not configured":
        "Attālinātā teksta ievade nav iestatīta",
    "Remote text entry requires a Device ID. Ask the server operator to provision one.":
        "Attālinātai teksta ievadei nepieciešams ierīces ID. Lūdziet servera operatoram to piešķirt.",
    "Remove timer?": "Noņemt taimeri?",
    Rename: "Pārdēvēt",
    "Rename category": "Pārdēvēt kategoriju",
    "Rename to": "Pārdēvēt par",
    "Repeat parental code": "Atkārtoti ievadiet vecāku kodu",
    "Request sended!": "Pieprasījums nosūtīts!",
    "Restart player": "Pārstartēt atskaņotāju",
    "Restart stream": "Pārstartēt straumi",
    "Restart stream / Live": "Pārstartēt straumi / tiešraide",
    "Resume from archive?": "Turpināt no arhīva?",
    "Return to previous channel": "Atgriezties iepriekšējā kanālā",
    Rewind: "Pārtīt",
    "Rewind step by buttons %1/%2": "Attīšanas solis ar pogām %1/%2",
    RUSSKOETV: "RUSSKOETV",
    "RUSSKOETV settings": "RUSSKOETV iestatījumi",
    Russian: "Krievu",
    right: "pa labi",
    Saturation: "Piesātinājums",
    "Save & load channels": "Saglabāt un ielādēt kanālus",
    "Save and load": "Saglabāt un ielādēt",
    "Save and load channels": "Saglabāt un ielādēt kanālus",
    "Save Settings": "Saglabāt iestatījumus",
    "Save settings": "Saglabāt iestatījumus",
    "Save settings and load channel list":
        "Saglabāt iestatījumus un ielādēt kanālu sarakstu",
    "Save settings to storage": "Saglabāt iestatījumus krātuvē",
    Script: "Scenārijs",
    Search: "Meklēt",
    "Search programme": "Meklēt raidījumu",
    "Select a stream type:<br>%1": "Izvēlieties straumes veidu:<br>%1",
    "Select category to add channel":
        "Izvēlieties kategoriju, lai pievienotu kanālu",
    "Select color": "Izvēlēties krāsu",
    "Select menu items": "Izvēlēties izvēlnes vienumus",
    "Select playlist": "Izvēlieties atskaņošanas sarakstu",
    "Select playlist file": "Izvēlieties atskaņošanas saraksta failu",
    "Select playlist template source for EPG and logos":
        "Izvēlieties atskaņošanas saraksta veidnes avotu EPG un logotipiem",
    "Send request": "Nosūtīt pieprasījumu",
    "Send settings": "Nosūtīt iestatījumus",
    "Send this code from your proxy in the Authorization: Bearer header.":
        "Sūtiet šo kodu no starpniekservera galvenē Authorization: Bearer.",
    Server: "Serveris",
    "Server address": "Servera adrese",
    "Server address (for example 192.168.1.20:8081)":
        "Servera adrese (piemēram, 192.168.1.20:8081)",
    "Server device access code": "Servera ierīces piekļuves kods",
    "Server URL": "Servera URL",
    "Server unavailable. Retrying automatically; check its address and network access.":
        "Serveris nav pieejams. Atkārtos automātiski; pārbaudiet adresi un piekļuvi tīklam.",
    Set: "Iestatīt",
    "Set parental code": "Iestatīt vecāku kodu",
    "Set timer?": "Iestatīt taimeri?",
    Settings: "Iestatījumi",
    "Settings could not be saved": "Iestatījumus neizdevās saglabāt",
    "Settings loaded from storage": "Iestatījumi ielādēti no krātuves",
    "Settings STB": "STB iestatījumi",
    "Settings saved": "Iestatījumi saglabāti",
    "Settings saved to storage": "Iestatījumi saglabāti krātuvē",
    "Settings sended!": "Iestatījumi nosūtīti!",
    "Shara.club (ClubTV.pro)": "Shara.club (ClubTV.pro)",
    "Shara.club (ClubTV.pro) settings": "Shara.club (ClubTV.pro) iestatījumi",
    ShockTv: "ShockTv",
    "ShockTv settings": "ShockTv iestatījumi",
    "Show archive availability in list": "Rādīt arhīva pieejamību sarakstā",
    "Show channel name in list": "Rādīt kanāla nosaukumu sarakstā",
    "Show channel number in list": "Rādīt kanāla numuru sarakstā",
    "Show channel selection list": "Rādīt kanālu izvēles sarakstu",
    "Show description": "Rādīt aprakstu",
    "Show EPG and archive for channel": "Rādīt kanāla EPG un arhīvu",
    "Show list of channel archive records": "Rādīt kanāla ierakstus",
    "Show list of channel archive records without duplication":
        "Rādīt kanāla ierakstus bez dublikātiem",
    "Show Media Library": "Rādīt multivides bibliotēku",
    "Show picons in channel list": "Rādīt kanālu ikonas sarakstā",
    "Show player menu": "Rādīt atskaņotāja izvēlni",
    "Show program name": "Rādīt raidījuma nosaukumu",
    "Show progress in channel list": "Rādīt progresu kanālu sarakstā",
    "Show provider settings?": "Rādīt pakalpojuma sniedzēja iestatījumus?",
    "Show providers?": "Rādīt pakalpojuma sniedzējus?",
    "Show rewind window": "Rādīt pārtīšanas logu",
    "Show scrollbar in list": "Rādīt ritjoslu sarakstos",
    "Show thumbnails": "Rādīt sīktēlus",
    "Show when changing program": "Rādīt, mainoties raidījumam",
    "Show when rewind": "Rādīt attīšanas laikā",
    "Show when switching": "Rādīt, pārslēdzot kanālus",
    "Sleep timer": "Miega taimeris",
    "Sort channels": "Kārtot kanālus",
    "Stalker Portal Provider": "Stalker portāla pakalpojuma sniedzējs",
    "Stalker portal settings": "Stalker portāla iestatījumi",
    "Stalker portals": "Stalker portāli",
    Status: "Statuss",
    "Stop playback and return to live":
        "Apturēt atskaņošanu un atgriezties tiešraidē",
    "Stream type: %1": "Straumes veids: %1",
    "String for search": "Meklēšanas vaicājums",
    "Su Mo Tu We Th Fr Sa": "Sv Pr Ot Tr Ce Pk Se",
    Subtitle: "Subtitri",
    Switch: "Pārslēgt",
    "Switch sound track": "Mainīt skaņas celiņu",
    "Switch subtitle": "Mainīt subtitrus",
    "Switch to this list": "Pārslēgties uz šo sarakstu",
    "Swop URL": "Swop URL",
    "saved on this device": "saglabāts šajā ierīcē",
    select: "atlasīt",
    small: "mazs",
    system: "sistēmas",
    Tabox: "Tabox",
    "Tabox settings": "Tabox iestatījumi",
    "The device ID in the address is invalid.": "Ierīces ID adresē nav derīgs.",
    "This HTTPS player cannot connect to an HTTP server. Use an HTTPS server or open the player over HTTP.":
        "Šis HTTPS atskaņotājs nevar savienoties ar HTTP serveri. Izmantojiet HTTPS serveri vai atveriet atskaņotāju ar HTTP.",
    "This Play app requires HTTPS. Ask your provider for an HTTPS playlist or server URL.":
        "Šai Play lietotnei nepieciešams HTTPS. Lūdziet pakalpojuma sniedzējam HTTPS sarakstu vai servera URL.",
    Timer: "Taimeris",
    "Timer: switch to channel?": "Taimeris: pārslēgties uz šo kanālu?",
    "Timeshift: one minute back": "Laika nobīde: vienu minūti atpakaļ",
    "Timeshift: to start of TV program": "Laika nobīde: uz raidījuma sākumu",
    Timezone: "Laika josla",
    TMDb: "TMDb",
    "TOP-IPTV": "TOP-IPTV",
    "TOP-IPTV settings": "TOP-IPTV iestatījumi",
    "To begining": "Uz sākumu",
    "To start of TV program / Previous TV program":
        "Uz raidījuma sākumu / iepriekšējo raidījumu",
    "Toggle Aspect Ratio": "Mainīt attēla proporcijas",
    "Toggle on-screen debug HUD": "Rādīt / slēpt atkļūdošanas paneli",
    "Toggle Zoom Mode": "Mainīt tālummaiņas režīmu",
    "Top-Tv": "Top-Tv",
    "Top-Tv settings": "Top-Tv iestatījumi",
    "Try demo": "Izmēģināt demonstrāciju",
    "TV DOSUG": "TV DOSUG",
    "TV DOSUG settings": "TV DOSUG iestatījumi",
    TVClub: "TVClub",
    "TVClub settings": "TVClub iestatījumi",
    "Type of player for streaming": "Atskaņotāja veids straumēšanai",
    "top-left": "augšā pa kreisi",
    "top-right": "augšā pa labi",
    transparent: "caurspīdīgs",
    ULTIFL1X: "ULTIFL1X",
    "ULTIFL1X settings": "ULTIFL1X iestatījumi",
    "Update installed. Please restart OttPlay FOSS.":
        "Atjauninājums instalēts. Pārstartējiet OttPlay FOSS.",
    "Use an HTTP or HTTPS server address.":
        "Izmantojiet HTTP vai HTTPS servera adresi.",
    "Use HTTP or HTTPS without a username or password in the address.":
        "Izmantojiet HTTP vai HTTPS bez lietotājvārda vai paroles adresē.",
    "Use LEFT/RIGHT to select a control, OK to activate, and UP/DOWN to scroll.":
        "Ar PA KREISI/PA LABI izvēlieties vadīklu, ar OK aktivizējiet to, ar UZ AUGŠU/UZ LEJU ritiniet.",
    Username: "Lietotājvārds",
    "Username or password is missing.": "Trūkst lietotājvārda vai paroles.",
    "VIP-IP.COM": "VIP-IP.COM",
    "VIP-IP.COM settings": "VIP-IP.COM iestatījumi",
    "Vidok.TV": "Vidok.TV",
    "Vidok.TV settings": "Vidok.TV iestatījumi",
    "VOD not supported by provider": "Šis pakalpojuma sniedzējs neatbalsta VOD",
    "Volume step, %": "Skaļuma solis, %",
    "VPortal link": "VPortal saite",
    "VPortal request failed":
        "Neizdevās ielādēt VPortal. Pārbaudiet saiti, piekļuves atslēgu un portāla pieejamību.",
    volume: "skaļums",
    "Wrong parental code !!!": "Nepareizs vecāku kods!!!",
    "Xtream Codes Provider": "Xtream Codes pakalpojuma sniedzējs",
    "Xtream Codes settings": "Xtream Codes iestatījumi",
    Year: "Gads",
    Yellow: "Dzeltens",
    Yes: "Jā",
    yes: "jā",
    "Гомельсат (cbilling)": "Гомельсат (cbilling)",
    "Гомельсат (cbilling) settings": "Гомельсат (cbilling) iestatījumi",
    МойДом: "МойДом",
    "МойДом settings": "МойДом iestatījumi",
    "Ошибка обработки списка каналов! Проверьте правильность данных!!":
        "Neizdevās apstrādāt kanālu sarakstu. Pārbaudiet pakalpojuma sniedzēja datus!",
    Радуга: "Радуга",
    "Радуга settings": "Радуга iestatījumi",
    "Редактирование ID": "Rediģēt ID",
    "Редактирование PIN": "Rediģēt PIN",
    Шаравоз: "Шаравоз",
    "Шаравоз settings": "Шаравоз iestatījumi",
    "↑↓ Scroll": "↑↓ Ritināt",
};
