var keyStrings = {
    " (after changing, load playlist)":
        " (pēc izmaiņām, ielādējiet atskaņošanas sarakstu)",
    " added to category ": " pievienots kategorijai ",
    " added to favorites": " pievienots izlasei",
    "??? No channel name": "??? Nav kanāla nosaukuma",
    Actions: "Darbības",
    "Add channel to category": "Pievienot kanālu kategorijai",
    "Add channel to favorites": "Pievienot kanālu izlasei",
    All: "Visi",
    "Applying HTTP remote settings...":
        "Tiek piemēroti HTTP tālvadības iestatījumi...",
    "Archive hours": "Arhīva stundas",
    alhabet: "aābcčdeēfgģhiījkķlļmnņoprsštuūvzž",
    "Buffer Size, s": "Bufera lielums, s",
    "built-in": "iebūvēts",
    Category: "Kategorija",
    "Channel ": "Kanāls ",
    "Channel is not available!!!": "Kanāls nav pieejams!!!",
    "Channel list": "Kanālu saraksts",
    "Channel list not received !!!": "Kanālu saraksts nav saņemts!!!",
    "Channel list not received !!!<br/><br/>Enter the provider data and restart the player !!!<br/><br/>":
        "Kanālu saraksts nav saņemts!!!<br/><br/>Ievadiet pakalpojumu sniedzēja datus un restartējiet atskaņotāju!!!<br/><br/>",
    "Channel list. Category: ": "Kanālu saraksts. Kategorija: ",
    "Channel parental control": "Kanāla vecāku kontrole",
    Close: "Aizvērt",
    "Could not update HTTP remote control.":
        "Neizdevās atjaunināt HTTP tālvadības iestatījumus.",
    "Delete channel": "Dzēst kanālu",
    Description: "Apraksts",
    "Device access code": "Ierīces piekļuves kods",
    "Disable HTTP remote": "Izslēgt HTTP tālvadību",
    "Disabled by default. Enabling creates a new device access code.":
        "Pēc noklusējuma izslēgta. Ieslēdzot tiek izveidots jauns ierīces piekļuves kods.",
    Edit: "Rediģēt",
    "Edit category name": "Rediģēt kategorijas nosaukumu",
    "Edit playlist data": "Rediģēt atskaņošanas saraksta datus",
    Editor: "Redaktors",
    "Enable HTTP remote": "Ieslēgt HTTP tālvadību",
    "Enter Media Library URL": "Ievadiet mediotēkas URL",
    "Enter parental code": "Ievadiet vecāku kodu",
    "Enter playlist archive hours":
        "Ievadiet atskaņošanas saraksta arhīva stundas",
    "Enter playlist Name": "Ievadiet atskaņošanas saraksta nosaukumu",
    "Enter playlist URL": "Ievadiet atskaņošanas saraksta URL",
    EPG: "Programma",
    Exit: "Iziet",
    "Failed to load channel list!": "Neizdevās ielādēt kanālu sarakstu!",
    Favorites: "Izlase",
    "HTTP port": "HTTP ports",
    "HTTP remote control is unavailable on this device.":
        "HTTP tālvadība šajā ierīcē nav pieejama.",
    Info: "Informācija",
    Load: "Ielādēt",
    "Load playlist": "Ielādēt atskaņošanas sarakstu",
    "Local HTTP remote control": "Vietējā HTTP tālvadība",
    lang: "Latviešu",
    "Media Library URL": "Mediotēkas URL",
    Menu: "Izvēlne",
    "Move channel down": "Pārvietot kanālu uz leju",
    "Move channel up": "Pārvietot kanālu uz augšu",
    "m3u-m3u8 playlists": "m3u-m3u8 atskaņošanas saraksti",
    min: "min",
    "No channel name": "Nav kanāla nosaukuma",
    Nothing: "Nekas",
    native: "vietējais",
    no: "nē",
    "Open in PiP": "Atvērt PiP",
    off: "izslēgts",
    on: "ieslēgta",
    Playlist: "Atskaņošanas saraksts",
    "Playlist file": "Atskaņošanas saraksta fails",
    "Playlist is not loading directly...Loading via server...":
        "Atskaņošanas saraksts netiek ielādēts tieši...Ielāde caur serveri...",
    "Playlist Name": "Atskaņošanas saraksta nosaukums",
    "Playlist URL": "Atskaņošanas saraksta URL",
    "Remote control": "Tālvadība",
    "Save Settings": "Saglabāt iestatījumus",
    Search: "Meklēt",
    "Select category to add channel":
        "Izvēlieties kategoriju, lai pievienotu kanālu",
    "Select playlist": "Izvēlieties atskaņošanas sarakstu",
    "Select playlist file": "Izvēlieties atskaņošanas saraksta failu",
    "Send this code from your proxy in the Authorization: Bearer header.":
        "Sūtiet šo kodu no starpniekservera galvenē Authorization: Bearer.",
    Settings: "Iestatījumi",
    "Settings STB": "STB iestatījumi",
    "Settings saved": "Iestatījumi saglabāti",
    "Stalker portals": "Stalker portāli",
    "Type of player for streaming": "Atskaņotāja veids straumēšanai",
    "Wrong parental code !!!": "Nepareizs vecāku kods!!!",
    yes: "jā",
};
