var keyStrings = {
    " (after changing, load playlist)": " (pakeitus, įkelkite grojaraštį)",
    " added to category ": " pridėta prie kategorijos ",
    " added to favorites": " pridėta prie mėgstamiausių",
    "??? No channel name": "??? Nėra kanalo pavadinimo",
    Actions: "Veiksmai",
    "Add channel to category": "Pridėti kanalą prie kategorijos",
    "Add channel to favorites": "Pridėti kanalą prie mėgstamiausių",
    All: "Visi",
    "Archive hours": "Archyvo valandos",
    alhabet: "aąbcčdeęėfghiįyjklmnoprsštuųūvzž",
    "Buffer Size, s": "Buferio dydis, s",
    "built-in": "įmontuotas",
    Category: "Kategorija",
    "Channel ": "Kanalas ",
    "Channel is not available!!!": "Kanalas nepasiekiamas!!!",
    "Channel list": "Kanalų sąrašas",
    "Channel list not received !!!": "Kanalų sąrašas negautas!!!",
    "Channel list not received !!!<br/><br/>Enter the provider data and restart the player !!!<br/><br/>":
        "Kanalų sąrašas negautas!!!<br/><br/>Įveskite teikėjo duomenis ir iš naujo paleiskite grojytuvą!!!<br/><br/>",
    "Channel list. Category: ": "Kanalų sąrašas. Kategorija: ",
    "Channel parental control": "Kanalo tėvų kontrolė",
    Close: "Uždaryti",
    "Delete channel": "Ištrinti kanalą",
    Description: "Aprašymas",
    Edit: "Redaguoti",
    "Edit category name": "Redaguoti kategorijos pavadinimą",
    "Edit playlist data": "Redaguoti grojaraščio duomenis",
    Editor: "Redaktorius",
    "Enter Media Library URL": "Įveskite mediatekos URL",
    "Enter parental code": "Įveskite tėvų kodą",
    "Enter playlist archive hours": "Įveskite grojaraščio archyvo valandas",
    "Enter playlist Name": "Įveskite grojaraščio pavadinimą",
    "Enter playlist URL": "Įveskite grojaraščio URL",
    EPG: "TV programa",
    Exit: "Išeiti",
    "Failed to load channel list!": "Nepavyko įkelti kanalų sąrašo!",
    Favorites: "Mėgstamiausi",
    Info: "Informacija",
    Load: "Įkelti",
    "Load playlist": "Įkelti grojaraštį",
    lang: "Lietuvių",
    "Media Library URL": "Mediatekos URL",
    Menu: "Meniu",
    "Move channel down": "Perkelti kanalą žemyn",
    "Move channel up": "Perkelti kanalą aukštyn",
    "m3u-m3u8 playlists": "m3u-m3u8 grojaraščiai",
    min: "min",
    "No channel name": "Nėra kanalo pavadinimo",
    Nothing: "Nieko",
    native: "vietinis",
    no: "ne",
    "Open in PiP": "Atidaryti PiP",
    off: "išjungta",
    Playlist: "Grojaraštis",
    "Playlist file": "Grojaraščio failas",
    "Playlist is not loading directly...Loading via server...":
        "Grojaraštis neįkeliamas tiesiogiai...Įkeliama per serverį...",
    "Playlist Name": "Grojaraščio pavadinimas",
    "Playlist URL": "Grojačio sąrašo URL",
    "Save Settings": "Išsaugoti nustatymus",
    Search: "Paieška",
    "Select category to add channel": "Pasirinkite kategoriją kanalui pridėti",
    "Select playlist": "Pasirinkite grojaraštį",
    "Select playlist file": "Pasirinkite grojaraščio failą",
    Settings: "Nustatymai",
    "Settings STB": "STB nustatymai",
    "Settings saved": "Nustatymai išsaugoti",
    "Stalker portals": "Stalker portalai",
    "Type of player for streaming": "Grojojo tipas transliacijai",
    "Wrong parental code !!!": "Neteisingas tėvų kodas!!!",
    yes: "taip",
};
