var keyStrings = {
 "lang": "Lietuvių",
 "alhabet": "aąbcčdeęėfghiįyjklmnoprsštuųūvzž",
 "Channel list. Category: ": "Kanalų sąrašas. Kategorija: ",
 "EPG": "TV programa",
 "Category": "Kategorija",
 "Actions": "Veiksmai",
 "Description": "Aprašymas",
 "Open in PiP": "Atidaryti PiP",
 "Move channel up": "Perkelti kanalą aukštyn",
 "Move channel down": "Perkelti kanalą žemyn",
 "Delete channel": "Ištrinti kanalą",
 "Add channel to category": "Pridėti kanalą prie kategorijos",
 "Add channel to favorites": "Pridėti kanalą prie mėgstamiausių",
 "Channel parental control": "Kanalo tėvų kontrolė",
 "Channel is not available!!!": "Kanalas nepasiekiamas!!!",
 "min": "min",
 "Channel ": "Kanalas ",
 " added to category ": " pridėta prie kategorijos ",
 " added to favorites": " pridėta prie mėgstamiausių",
 "Favorites": "Mėgstamiausi",
 "Select category to add channel": "Pasirinkite kategoriją kanalui pridėti",
 "Enter parental code": "Įveskite tėvų kodą",
 "Wrong parental code !!!": "Neteisingas tėvų kodas!!!",
 "Close": "Uždaryti",
 "Edit category name": "Redaguoti kategorijos pavadinimą",
 "Menu": "Meniu",
 "Channel list": "Kanalų sąrašas",
 "Settings": "Nustatymai",
 "Settings saved": "Nustatymai išsaugoti",
 "no": "ne",
 "yes": "taip",
 "Info": "Informacija",
 "Nothing": "Nieko",
 "Exit": "Išeiti",
 "off": "išjungta",
 "Failed to load channel list!": "Nepavyko įkelti kanalų sąrašo!",
 "??? No channel name": "??? Nėra kanalo pavadinimo",
 "Playlist URL": "Grojačio sąrašo URL",
 "Archive hours": "Archyvo valandos",
 "Enter playlist URL": "Įveskite grojaraščio URL",
 "Playlist Name": "Grojaraščio pavadinimas",
 "Enter playlist Name": "Įveskite grojaraščio pavadinimą",
 "Media Library URL": "Mediatekos URL",
 "Enter Media Library URL": "Įveskite mediatekos URL",
 "Playlist": "Grojaraštis",
 "Playlist is not loading directly...Loading via server...": "Grojaraštis neįkeliamas tiesiogiai...Įkeliama per serverį...",
 "Select playlist": "Pasirinkite grojaraštį",
 "Edit": "Redaguoti",
 "Load": "Įkelti",
 "Edit playlist data": "Redaguoti grojaraščio duomenis",
 "All": "Visi",
 "Search": "Paieška",
 "m3u-m3u8 playlists": "m3u-m3u8 grojaraščiai",
 "Stalker portals": "Stalker portalai",
 "Settings STB": "STB nustatymai",
 "Type of player for streaming": "Grojojo tipas transliacijai",
 "Buffer Size, s": "Buferio dydis, s",
 "Save Settings": "Išsaugoti nustatymus",
 "Editor": "Redaktorius",
 "built-in": "įmontuotas",
 "native": "vietinis",
 "No channel name": "Nėra kanalo pavadinimo",
 " (after changing, load playlist)": " (pakeitus, įkelkite grojaraštį)",
 "Enter playlist archive hours": "Įveskite grojaraščio archyvo valandas",
 "Load playlist": "Įkelti grojaraštį",
 "Playlist file": "Grojaraščio failas",
 "Select playlist file": "Pasirinkite grojaraščio failą",
 "Channel list not received !!!<br/><br/>Enter the provider data and restart the player !!!<br/><br/>": "Kanalų sąrašas negautas!!!<br/><br/>Įveskite teikėjo duomenis ir iš naujo paleiskite grojytuvą!!!<br/><br/>",
 "Channel list not received !!!": "Kanalų sąrašas negautas!!!"
};
