var keyStrings = {
    " (after changing, load playlist)":
        " (muat semula senarai main selepas perubahan)",
    " (after changing, restart player)":
        " (mulakan semula pemain selepas perubahan)",
    " added to category ": " ditambah ke kategori ",
    " added to favorites": " ditambah ke kegemaran",
    " m ": " min ",
    " s": " s",
    "??? No channel name": "??? Saluran tanpa nama",
    '"As Is"': '"Asal"',
    '"Favorites"': '"Kegemaran"',
    '"Sliding" infobar': "Bar maklumat gelongsor",
    "&darr;a": "&darr;a",
    "&uarr;A": "&uarr;A",
    "<br/><br/>In archive mode:<br/>": "<br/><br/>Dalam mod arkib:<br/>",
    "<br/>Loading STB...": "<br/>Memuatkan STB…",
    "<br/>Setup STB...": "<br/>Menyediakan STB…",
    "<br>": "<br>",
    "<br><br>": "<br><br>",
    "<br>Add<br>to category": "<br>Tambah<br>ke kategori",
    "<br>Add<br>to favorites": "<br>Tambah<br>ke kegemaran",
    "<br>Delete": "<br>Padam",
    "<br>Down<br>": "<br>Bawah<br>",
    "<br>Live": "<br>Langsung",
    "<br>Menu": "<br>Menu",
    "<br>Parental<br>Control": "<br>Kawalan<br>ibu bapa",
    "<br>Pause<br>": "<br>Jeda<br>",
    "<br>Previous<br>channel": "<br>Saluran<br>sebelumnya",
    "<br>Rewind<br>": "<br>Undur<br>",
    "<br>Toggle<br>sound track": "<br>Tukar<br>trek audio",
    "<br>Up<br>": "<br>Atas<br>",
    "1 hour": "1 jam",
    "1 minute": "1 minit",
    "2 hours": "2 jam",
    "3 hours": "3 jam",
    "10 Seconds": "10 saat",
    "30 minutes": "30 minit",
    "A command expired while the player was loading channels.":
        "Arahan tamat tempoh semasa pemain memuatkan saluran.",
    "A command was rejected by the player. Check its provider and settings.":
        "Arahan ditolak oleh pemain. Semak penyedia dan tetapannya.",
    About: "Perihal",
    "Access code": "Kod akses",
    "Access denied. Check the server access code.":
        "Akses ditolak. Semak kod akses pelayan.",
    "Access key": "Kunci akses",
    "Access key is required!": "Kunci akses diperlukan!",
    "Access settings": "Tetapan akses",
    Actions: "Tindakan",
    "Active list": "Senarai aktif",
    Actors: "Pelakon",
    "Add / rename / delete…": "Tambah / namakan semula / padam…",
    "Add channel to category": "Tambah saluran ke kategori",
    "Add channel to favorites": "Tambah saluran ke kegemaran",
    "Add new list": "Tambah senarai baharu",
    "Add to favorites": "Tambah ke kegemaran",
    Age: "Umur",
    All: "Semua",
    "All categories": "Semua kategori",
    "All4you.tv": "All4you.tv",
    "All4you.tv settings": "Tetapan All4you.tv",
    "Allowlist this Device ID": "Benarkan ID peranti ini",
    "An IP without a port uses HTTP port 8081. Clear the address or select Disconnect to stop.":
        "IP tanpa port menggunakan port HTTP 8081. Kosongkan alamat atau pilih Putuskan untuk berhenti.",
    "API failed, trying M3U...": "API gagal, mencuba M3U…",
    "API Server": "Pelayan API",
    "API server URL": "URL pelayan API",
    "Applying HTTP remote settings...":
        "Menggunakan tetapan kawalan jauh HTTP…",
    Archive: "Arkib",
    "Archive - begin": "Arkib — mula",
    "Archive hours": "Jam arkib",
    "Archive: ENTER on past programs": "Arkib: ENTER pada rancangan terdahulu",
    "Archive. Channel: ": "Arkib. Saluran: ",
    Aspect: "Nisbah aspek",
    Audio: "Audio",
    alhabet: "abcdefghijklmnopqrstuvwxyz",
    always: "sentiasa",
    "and enter code": "dan masukkan kod",
    Back: "Kembali",
    "Back / Forward for 1 minute": "Undur / maju 1 minit",
    "Background color": "Warna latar",
    "Background color of selected item": "Warna latar item dipilih",
    "BEST LiST IPTV [HLS Playlist]": "BEST LiST IPTV [HLS Playlist]",
    "BEST LiST IPTV [HLS Playlist] settings":
        "Tetapan BEST LiST IPTV [HLS Playlist]",
    "BEST LiST IPTV [Stalker]": "BEST LiST IPTV [Stalker]",
    "BEST LiST IPTV [Stalker] settings": "Tetapan BEST LiST IPTV [Stalker]",
    "Behavior of %1/%2 buttons in lists":
        "Tingkah laku butang %1/%2 dalam senarai",
    "Black screen while switching the channel":
        "Skrin hitam semasa menukar saluran",
    Blue: "Biru",
    "Bookmark age: %1 days": "Usia penanda: %1 hari",
    "Buffer Size, s": "Saiz penimbal, s",
    "Built-in playlist:": "Senarai main terbina dalam:",
    "Built-in playlists": "Senarai main terbina dalam",
    "Button %1 function when viewing": "Fungsi butang %1 semasa menonton",
    "Button function %1 when viewing archive":
        "Fungsi butang %1 semasa menonton arkib",
    "Buttons settings": "Tetapan butang",
    "By alphabet": "Mengikut abjad",
    "By time": "Mengikut masa",
    "begin/end": "mula/akhir",
    "bottom-right": "kanan bawah",
    "built-in": "terbina dalam",
    "Call PiP": "Buka PiP",
    "Call PiP / PiP exchange": "Buka PiP / tukar PiP",
    Cancel: "Batal",
    "Cannot delete the last category": "Tidak boleh memadam kategori terakhir",
    Category: "Kategori",
    "Category selection": "Pilih kategori",
    "Change interface language": "Tukar bahasa antara muka",
    "Change provider": "Tukar penyedia",
    "Change provider - you can change the provider, and it will be remembered at the next start of player!":
        "Tukar penyedia. Pilihan anda akan diingati apabila pemain dimulakan semula.",
    "Change value": "Tukar nilai",
    "Channel ": "Saluran ",
    "Channel has no EPG": "Saluran tiada EPG",
    "Channel is not available!!!": "Saluran tidak tersedia!",
    "Channel link": "Pautan saluran",
    "Channel link is required!": "Pautan saluran diperlukan!",
    "Channel list": "Senarai saluran",
    "Channel list editing style": "Mod penyuntingan senarai saluran",
    "Channel list not received !!!": "Senarai saluran tidak diterima!",
    "Channel list not received !!!<br/><br/>Enter the provider data and restart the player !!!<br/><br/>":
        "Senarai saluran tidak diterima!<br/><br/>Masukkan maklumat penyedia dan mulakan semula pemain.<br/><br/>",
    "Channel list settings": "Tetapan senarai saluran",
    "Channel list. Category: ": "Senarai saluran. Kategori: ",
    "Channel parental control": "Kawalan ibu bapa untuk saluran",
    Channels: "Saluran",
    "Choose from": "Pilih daripada",
    "Choose language": "Pilih bahasa",
    "Choose provider": "Pilih penyedia",
    Classic: "Klasik",
    "Clear all settings?": "Padam semua tetapan?",
    "Clear settings": "Padam tetapan",
    Close: "Tutup",
    "Close PiP": "Tutup PiP",
    Color: "Warna",
    "Color spectrum": "Spektrum warna",
    "Command server": "Pelayan arahan",
    "Command server address, device access code, local HTTP control, and remote text entry settings":
        "Alamat pelayan arahan, kod akses peranti, kawalan HTTP setempat dan tetapan input teks jauh",
    "Configure All4you.tv in Settings -> Provider Settings":
        "Konfigurasikan All4you.tv dalam Tetapan -> Tetapan penyedia",
    "Configure BEST LiST IPTV [HLS Playlist] in Settings -> Provider Settings":
        "Konfigurasikan BEST LiST IPTV [HLS Playlist] dalam Tetapan -> Tetapan penyedia",
    "Configure BEST LiST IPTV [Stalker] in Settings -> Provider Settings":
        "Konfigurasikan BEST LiST IPTV [Stalker] dalam Tetapan -> Tetapan penyedia",
    "Configure Diamond TV in Settings -> Provider Settings":
        "Konfigurasikan Diamond TV dalam Tetapan -> Tetapan penyedia",
    "Configure DRVAO in Settings -> Provider Settings":
        "Konfigurasikan DRVAO dalam Tetapan -> Tetapan penyedia",
    "Configure Dragon Media PRO in Settings -> Provider Settings":
        "Konfigurasikan Dragon Media PRO dalam Tetapan -> Tetapan penyedia",
    "Configure Fabryka.TV in Settings -> Provider Settings":
        "Konfigurasikan Fabryka.TV dalam Tetapan -> Tetapan penyedia",
    "Configure Fox-TV in Settings -> Provider Settings":
        "Konfigurasikan Fox-TV dalam Tetapan -> Tetapan penyedia",
    "Configure FXML in Settings -> Provider Settings":
        "Konfigurasikan FXML dalam Tetapan -> Tetapan penyedia",
    "Configure GlanzTV in Settings -> Provider Settings":
        "Konfigurasikan GlanzTV dalam Tetapan -> Tetapan penyedia",
    "Configure GREAT IPTV in Settings -> Provider Settings":
        "Konfigurasikan GREAT IPTV dalam Tetapan -> Tetapan penyedia",
    "Configure IpStream.one in Settings -> Provider Settings":
        "Konfigurasikan IpStream.one dalam Tetapan -> Tetapan penyedia",
    "Configure KORONA TV in Settings -> Provider Settings":
        "Konfigurasikan KORONA TV dalam Tetapan -> Tetapan penyedia",
    "Configure MaxTV in Settings -> Provider Settings":
        "Konfigurasikan MaxTV dalam Tetapan -> Tetapan penyedia",
    "Configure New Look in Settings -> Provider Settings":
        "Konfigurasikan New Look dalam Tetapan -> Tetapan penyedia",
    "Configure OTT Prime ONLINE in Settings -> Provider Settings":
        "Konfigurasikan OTT Prime ONLINE dalam Tetapan -> Tetapan penyedia",
    "Configure POLMEDIA in Settings -> Provider Settings":
        "Konfigurasikan POLMEDIA dalam Tetapan -> Tetapan penyedia",
    "Configure PROST in Settings -> Provider Settings":
        "Konfigurasikan PROST dalam Tetapan -> Tetapan penyedia",
    "Configure RD in Settings -> Provider Settings":
        "Konfigurasikan RD dalam Tetapan -> Tetapan penyedia",
    "Configure RUSSKOETV in Settings -> Provider Settings":
        "Konfigurasikan RUSSKOETV dalam Tetapan -> Tetapan penyedia",
    "Configure Shara.club (ClubTV.pro) in Settings -> Provider Settings":
        "Konfigurasikan Shara.club (ClubTV.pro) dalam Tetapan -> Tetapan penyedia",
    "Configure ShockTv in Settings -> Provider Settings":
        "Konfigurasikan ShockTv dalam Tetapan -> Tetapan penyedia",
    "Configure Tabox in Settings -> Provider Settings":
        "Konfigurasikan Tabox dalam Tetapan -> Tetapan penyedia",
    "Configure TOP-IPTV in Settings -> Provider Settings":
        "Konfigurasikan TOP-IPTV dalam Tetapan -> Tetapan penyedia",
    "Configure Top-Tv in Settings -> Provider Settings":
        "Konfigurasikan Top-Tv dalam Tetapan -> Tetapan penyedia",
    "Configure TV DOSUG in Settings -> Provider Settings":
        "Konfigurasikan TV DOSUG dalam Tetapan -> Tetapan penyedia",
    "Configure TVClub in Settings -> Provider Settings":
        "Konfigurasikan TVClub dalam Tetapan -> Tetapan penyedia",
    "Configure ULTIFL1X in Settings -> Provider Settings":
        "Konfigurasikan ULTIFL1X dalam Tetapan -> Tetapan penyedia",
    "Configure VIP-IP.COM in Settings -> Provider Settings":
        "Konfigurasikan VIP-IP.COM dalam Tetapan -> Tetapan penyedia",
    "Configure Vidok.TV in Settings -> Provider Settings":
        "Konfigurasikan Vidok.TV dalam Tetapan -> Tetapan penyedia",
    "Configure Гомельсат (cbilling) in Settings -> Provider Settings":
        "Konfigurasikan Гомельсат (cbilling) dalam Tetapan -> Tetapan penyedia",
    "Configure МойДом in Settings -> Provider Settings":
        "Konfigurasikan МойДом dalam Tetapan -> Tetapan penyedia",
    "Configure Радуга in Settings -> Provider Settings":
        "Konfigurasikan Радуга dalam Tetapan -> Tetapan penyedia",
    "Configure Шаравоз in Settings -> Provider Settings":
        "Konfigurasikan Шаравоз dalam Tetapan -> Tetapan penyedia",
    Connect: "Sambung",
    Connected: "Disambungkan",
    "Connected. Waiting for the channel list...":
        "Disambungkan. Menunggu senarai saluran…",
    "Connecting to Stalker portal...": "Menyambung ke portal Stalker…",
    "Connecting...": "Menyambung…",
    "Continue watching?": "Teruskan menonton?",
    "Copy category": "Salin kategori",
    "Copy JSON": "Salin JSON",
    "Could not connect to the server.": "Tidak dapat menyambung ke pelayan.",
    "Could not update HTTP remote control.":
        "Tidak dapat mengemas kini kawalan jauh HTTP.",
    Country: "Negara",
    "Create category": "Cipta kategori",
    current: "semasa",
    "Debug HUD": "Panel nyahpepijat",
    "Debug HUD is not available": "Panel nyahpepijat tidak tersedia",
    Delete: "Padam",
    "Delete category": "Padam kategori",
    "Delete channel": "Padam saluran",
    "Delete list": "Padam senarai",
    "Demo — moving test pattern": "Demo — corak ujian bergerak",
    Description: "Penerangan",
    "Description of remote control buttons": "Panduan butang kawalan jauh",
    "Device access code": "Kod akses peranti",
    "Device info:": "Maklumat peranti:",
    "Device MAC is required for KBC (Kinoboom) playlists":
        "MAC peranti diperlukan untuk senarai main KBC (Kinoboom)",
    "Diamond TV": "Diamond TV",
    "Diamond TV settings": "Tetapan Diamond TV",
    Director: "Pengarah",
    "Disable HTTP remote": "Nyahdayakan kawalan HTTP",
    "Disabled by default. Enabling creates a new device access code.":
        "Dinyahdayakan secara lalai. Pengaktifan akan mencipta kod akses peranti baharu.",
    Disconnect: "Putuskan",
    Disconnected: "Terputus",
    "Distance between lines in lists": "Jarak baris dalam senarai",
    "Do you want to exit player?": "Keluar daripada pemain?",
    "Download! Wait ...": "Memuat turun… sila tunggu…",
    DRVAO: "DRVAO",
    "DRVAO settings": "Tetapan DRVAO",
    "Dragon Media PRO": "Dragon Media PRO",
    "Dragon Media PRO settings": "Tetapan Dragon Media PRO",
    Duration: "Tempoh",
    Edit: "Sunting",
    "Edit access key": "Sunting kunci akses",
    "Edit category name": "Sunting nama kategori",
    "Edit channel link": "Sunting pautan saluran",
    "Edit playlist data": "Sunting maklumat senarai main",
    "Edit VPortal link": "Sunting pautan VPortal",
    Editor: "Penyunting",
    "Enable HTTP remote": "Dayakan kawalan HTTP",
    English: "Bahasa Inggeris",
    "Enter a password (8 characters).": "Masukkan kata laluan (8 aksara).",
    "Enter a playlist URL to access this service.":
        "Masukkan URL senarai main untuk mengakses perkhidmatan ini.",
    "Enter a server address without spaces or a fragment.":
        "Masukkan alamat pelayan tanpa ruang atau fragmen.",
    "Enter a username (8 characters).": "Masukkan nama pengguna (8 aksara).",
    "Enter a username and password to access this service.":
        "Masukkan nama pengguna dan kata laluan untuk mengakses perkhidmatan ini.",
    "Enter a valid server address, for example 192.168.1.20:8081.":
        "Masukkan alamat pelayan yang sah, contohnya 192.168.1.20:8081.",
    "Enter access key for": "Masukkan kunci akses untuk",
    "Enter an application access key (8 characters).":
        "Masukkan kunci akses aplikasi (8 aksara).",
    "Enter an ID and PIN to access this service.":
        "Masukkan ID dan PIN untuk mengakses perkhidmatan ini.",
    "Enter an IPTV token (10 characters).": "Masukkan token IPTV (10 aksara).",
    "Enter category name": "Masukkan nama kategori",
    "Enter MAC address": "Masukkan alamat MAC",
    "Enter MAC address (e.g. 00:1A:2B:3C:4D:5E)":
        "Masukkan alamat MAC (cth. 00:1A:2B:3C:4D:5E)",
    "Enter Media Library URL": "Masukkan URL pustaka media",
    "Enter new category name": "Masukkan nama kategori baharu",
    "Enter Provider Code": "Masukkan kod penyedia",
    "Enter Provider Code on PC or Phone":
        "Masukkan kod penyedia pada PC atau telefon",
    "Enter parental code": "Masukkan kod ibu bapa",
    "Enter password": "Masukkan kata laluan",
    "Enter playlist archive hours": "Masukkan jumlah jam arkib senarai main",
    "Enter playlist Name": "Masukkan nama senarai main",
    "Enter playlist URL": "Masukkan URL senarai main",
    "Enter Stalker portal URL": "Masukkan URL portal Stalker",
    "Enter Stalker portal URL (e.g. http://your-portal:8800)":
        "Masukkan URL portal Stalker (cth. http://your-portal:8800)",
    "Enter Stalker portal URL (e.g. http://your-portal/stalker_portal/c/)":
        "Masukkan URL portal Stalker (cth. http://your-portal/stalker_portal/c/)",
    "Enter the access code separately, not in the server address.":
        "Masukkan kod akses secara berasingan, bukan dalam alamat pelayan.",
    "Enter the command server IP or address.":
        "Masukkan IP atau alamat pelayan arahan.",
    "Enter the full CDN host from the cabinet stream URL (e.g. subdomain.cdn-domain.tld), not a bare subdomain":
        "Masukkan hos CDN penuh daripada URL strim dalam akaun pelanggan (cth. subdomain.cdn-domain.tld), bukan subdomain sahaja",
    "Enter the server IP or address and this player's device access code from the server configuration. Saving both starts checking for volume, channel and other commands automatically.":
        "Masukkan IP atau alamat pelayan serta kod akses peranti pemain ini daripada konfigurasi pelayan. Menyimpan kedua-duanya memulakan semakan arahan kelantangan, saluran dan lain-lain secara automatik.",
    "Enter the server's device access code (32–256 letters, digits, _ or -).":
        "Masukkan kod akses peranti pelayan (32–256 huruf, digit, _ atau -).",
    'Enter the tv.team playlist URL.<br>Playlist type: <b>OTTPlayer</b><br/><br/>The "/playlist.m3u8" suffix is added automatically if omitted.':
        'Masukkan URL senarai main tv.team.<br>Jenis senarai main: <b>OTTPlayer</b><br/><br/>Akhiran "/playlist.m3u8" ditambah secara automatik jika ditinggalkan.',
    "Enter the VPortal link as shown in the cabinet":
        "Masukkan pautan VPortal seperti yang tertera dalam akaun pelanggan",
    "Enter this link in VPortal link. Playlist URL requires an M3U playlist.":
        "Masukkan pautan ini dalam Pautan VPortal. URL senarai main memerlukan senarai main M3U.",
    "Enter this player's device access code to connect.":
        "Masukkan kod akses peranti pemain ini untuk menyambung.",
    "Enter username": "Masukkan nama pengguna",
    "Enter value": "Masukkan nilai",
    "Enter Xtream server URL": "Masukkan URL pelayan Xtream",
    "Enter Xtream server URL (e.g. https://your-server:8080)":
        "Masukkan URL pelayan Xtream (cth. https://your-server:8080)",
    EPG: "EPG",
    "EPG and archive. Channel: ": "EPG dan arkib. Saluran: ",
    "ERROR!": "Ralat!",
    "Error Code!": "Kod tidak sah!",
    Exit: "Keluar",
    "Exit player": "Keluar daripada pemain",
    "Export settings": "Eksport tetapan",
    "epg.one (Ordered)": "epg.one (Tersusun)",
    "epg.one (Standard)": "epg.one (Piawai)",
    "epg.one (Thematic)": "epg.one (Bertema)",
    "epgs...": "Panduan EPG…",
    "Fabryka.TV": "Fabryka.TV",
    "Fabryka.TV settings": "Tetapan Fabryka.TV",
    "Failed to connect to Stalker portal": "Gagal menyambung ke portal Stalker",
    "Failed to connect to Xtream API server":
        "Gagal menyambung ke pelayan API Xtream",
    "Failed to get user data!!!": "Gagal mendapatkan maklumat pengguna!",
    "Failed to load channel list!": "Gagal memuatkan senarai saluran!",
    "Failed to load channels from Stalker portal":
        "Gagal memuatkan saluran daripada portal Stalker",
    "Failed to load channels from Xtream API":
        "Gagal memuatkan saluran daripada API Xtream",
    "Failed to load!": "Gagal memuatkan!",
    "Favorite lists": "Senarai kegemaran",
    Favorites: "Kegemaran",
    "File selection is not supported on this device":
        "Pemilihan fail tidak disokong pada peranti ini",
    Filters: "Penapis",
    "First Run Setup": "Persediaan kali pertama",
    "Font type": "Jenis fon",
    "For download settings file open": "Untuk memuat turun fail tetapan, buka",
    "For enter value open": "Untuk memasukkan nilai, buka",
    "For upload settings file open": "Untuk memuat naik fail tetapan, buka",
    "Fox-TV": "Fox-TV",
    "Fox-TV settings": "Tetapan Fox-TV",
    FXML: "FXML",
    "FXML settings": "Tetapan FXML",
    Genre: "Genre",
    GlanzTV: "GlanzTV",
    "GlanzTV settings": "Tetapan GlanzTV",
    "Go to": "Pergi ke",
    "GREAT IPTV": "GREAT IPTV",
    "GREAT IPTV settings": "Tetapan GREAT IPTV",
    "Graphical indication": "Penunjuk grafik",
    Green: "Hijau",
    "Hide / Return": "Sembunyikan / tunjukkan",
    "Hide provider settings?": "Sembunyikan tetapan penyedia?",
    "Hide providers?": "Sembunyikan penyedia?",
    "History in Media Library": "Sejarah dalam pustaka media",
    "History of watched movies": "Sejarah tontonan",
    "HTTP port": "Port HTTP",
    "HTTP remote control is unavailable on this device.":
        "Kawalan jauh HTTP tidak tersedia pada peranti ini.",
    ID: "ID",
    "Import settings": "Import tetapan",
    "In live mode: <br/>": "Dalam mod langsung:<br/>",
    Info: "Maklumat",
    "Infobar display timeout, s": "Tempoh paparan bar maklumat, s",
    "Infobar settings": "Tetapan bar maklumat",
    Information: "Maklumat",
    "Interface credits": "Penghargaan antara muka",
    "Interface settings": "Tetapan antara muka",
    "Interface theme": "Tema antara muka",
    "Interface transparency": "Ketelusan antara muka",
    "Invalid channel link! Enter the full host as in the cabinet stream URL (e.g. subdomain.cdn-domain.tld)":
        "Pautan saluran tidak sah! Masukkan hos penuh seperti dalam URL strim akaun pelanggan (cth. subdomain.cdn-domain.tld)",
    "IPTV token": "Token IPTV",
    "IpStream.one": "IpStream.one",
    "IpStream.one settings": "Tetapan IpStream.one",
    Joystick: "Kayu ria",
    "KBC (Kinoboom) access data": "Maklumat akses KBC (Kinoboom)",
    "KORONA TV": "KORONA TV",
    "KORONA TV settings": "Tetapan KORONA TV",
    "List created": "Senarai dicipta",
    "List deleted": "Senarai dipadam",
    "List location": "Kedudukan senarai",
    "List renamed": "Senarai dinamakan semula",
    "List type": "Jenis senarai",
    "Lists settings": "Tetapan senarai",
    Live: "Langsung",
    Load: "Muatkan",
    "Load built-in playlist:": "Muatkan senarai main terbina dalam:",
    "Load playlist": "Muatkan senarai main",
    "Load settings": "Muatkan tetapan",
    "Load settings from storage": "Muatkan tetapan daripada storan",
    "Load:": "Muatkan:",
    "Loading channels from Xtream API...":
        "Memuatkan saluran daripada API Xtream…",
    "Loading channels...": "Memuatkan saluran…",
    "Loading from API...": "Memuatkan daripada API…",
    "Loading from Edem API...": "Memuatkan daripada API Edem…",
    "Loading M3U playlist...": "Memuatkan senarai main M3U…",
    "Loading M3U...": "Memuatkan M3U…",
    "Loading via proxy...": "Memuatkan melalui proksi…",
    "Loading. Please wait...": "Memuatkan… sila tunggu…",
    "Loading...": "Memuatkan…",
    "Local HTTP remote control": "Kawalan jauh HTTP setempat",
    "Local URL": "URL setempat",
    Login: "Log masuk",
    lang: "Bahasa Melayu",
    large: "besar",
    left: "kiri",
    "left-bottom": "kiri bawah",
    "logos...": "Logo…",
    M3U: "M3U",
    "M3U URL": "URL M3U",
    "M3U URL (fallback)": "URL M3U (sandaran)",
    "MAC address": "Alamat MAC",
    "Manage lists": "Urus senarai",
    "Manage settings": "Urus tetapan",
    "Manual setup": "Persediaan manual",
    MaxTV: "MaxTV",
    "MaxTV settings": "Tetapan MaxTV",
    Media: "Media",
    "Media item is no longer available": "Item media tidak lagi tersedia",
    "Media Library": "Pustaka media",
    "Media Library URL": "URL pustaka media",
    Menu: "Menu",
    "Menu items settings": "Tetapan item menu",
    "Move category down": "Alih kategori ke bawah",
    "Move category up": "Alih kategori ke atas",
    "Move channel down": "Alih saluran ke bawah",
    "Move channel up": "Alih saluran ke atas",
    "m3u-m3u8 playlists": "Senarai main M3U / M3U8",
    medium: "sederhana",
    min: "min",
    "New Look": "New Look",
    "New Look settings": "Tetapan New Look",
    "New list name": "Nama senarai baharu",
    Next: "Halaman seterusnya",
    "Next keyboard page": "Halaman papan kekunci seterusnya",
    "Next TV program": "Rancangan seterusnya",
    No: "Tidak",
    "No channel name": "Saluran tanpa nama",
    "No saved settings found": "Tiada tetapan tersimpan ditemukan",
    "Not found": "Tidak ditemukan",
    "Not reduce video when showing the list (bugfix)":
        "Jangan kecilkan video apabila memaparkan senarai (pembaikan pepijat)",
    Nothing: "Tiada",
    "Number of next TV programs in channel list":
        "Bilangan rancangan seterusnya dalam senarai saluran",
    "Number of rows in lists": "Bilangan baris dalam senarai",
    native: "natif",
    no: "tidak",
    "no epg at current time": "Tiada EPG pada masa ini",
    "not set": "belum ditetapkan",
    Off: "Mati",
    Ok: "OK",
    Open: "Buka",
    "Open in PiP": "Buka dalam PiP",
    "OTT Prime ONLINE": "OTT Prime ONLINE",
    "OTT Prime ONLINE settings": "Tetapan OTT Prime ONLINE",
    "OttPlay FOSS %1 is available. Download and install now?":
        "OttPlay FOSS %1 tersedia. Muat turun dan pasang sekarang?",
    "Overwrite current settings?": "Tulis ganti tetapan semasa?",
    off: "mati",
    on: "hidup",
    "on ": "hidup ",
    "or scan": "atau imbas",
    "Parental control": "Kawalan ibu bapa",
    Password: "Kata laluan",
    Pause: "Jeda",
    "Pause/Play": "Jeda / main",
    "Permanent clock on screen": "Sentiasa tunjukkan jam pada skrin",
    PIN: "PIN",
    "PiP exchange": "Tukar PiP",
    "PiP window position": "Kedudukan tetingkap PiP",
    "PiP window size": "Saiz tetingkap PiP",
    Play: "Main",
    "Player and device info": "Maklumat pemain dan peranti",
    "Player info:": "Maklumat pemain:",
    Playlist: "Senarai main",
    "Playlist file": "Fail senarai main",
    "Playlist is not loading directly...Loading via server...":
        "Senarai main tidak dapat dimuatkan terus. Memuatkan melalui pelayan…",
    "Playlist Name": "Nama senarai main",
    "Playlist URL": "URL senarai main",
    POLMEDIA: "POLMEDIA",
    "POLMEDIA settings": "Tetapan POLMEDIA",
    "Portal URL": "URL portal",
    "Position shift -10 seconds after pause": "Undur 10 saat selepas jeda",
    PROST: "PROST",
    "PROST settings": "Tetapan PROST",
    Prev: "Sebelumnya",
    "Preview in channel list": "Pratonton dalam senarai saluran",
    Previous: "Sebelumnya",
    "Privacy policy": "Dasar privasi",
    "Protect Adult Channels": "Lindungi saluran dewasa",
    "Protect Change Provider": "Lindungi pertukaran penyedia",
    "Protect Settings": "Lindungi tetapan",
    "p...": "p...",
    paging: "mengikut halaman",
    Quality: "Kualiti",
    Rating: "Penilaian",
    RD: "RD",
    "RD settings": "Tetapan RD",
    "Reconnecting…": "Menyambung semula…",
    Records: "Rakaman",
    "Records for channel: ": "Rakaman untuk saluran: ",
    "Records library is empty": "Pustaka rakaman kosong",
    "Records not supported by provider":
        "Rakaman tidak disokong oleh penyedia ini",
    "Release date": "Tarikh keluaran",
    "Remember previous channels": "Ingat saluran sebelumnya",
    "Reminder: %1 — %2 in %3 min": "Peringatan: %1 — %2 dalam %3 min",
    "Remote (color buttons N/A)": "Kawalan jauh tanpa butang warna",
    "Remote (number buttons N/A)": "Kawalan jauh tanpa butang nombor",
    "Remote control": "Kawalan jauh",
    "Remote session expired": "Sesi jauh tamat tempoh",
    "Remote text entry denied": "Input teks jauh ditolak",
    "Remote text entry error": "Ralat input teks jauh",
    "Remote text entry not configured":
        "Input teks jauh belum dikonfigurasikan",
    "Remote text entry requires a Device ID. Ask the server operator to provision one.":
        "Input teks jauh memerlukan ID peranti. Minta pengendali pelayan menyediakannya.",
    "Remove timer?": "Padam pemasa?",
    Rename: "Namakan semula",
    "Rename category": "Namakan semula kategori",
    "Rename to": "Namakan semula kepada",
    "Repeat parental code": "Masukkan semula kod ibu bapa",
    "Request sended!": "Permintaan dihantar!",
    "Restart player": "Mulakan semula pemain",
    "Restart stream": "Mulakan semula strim",
    "Restart stream / Live": "Mulakan semula strim / langsung",
    "Resume from archive?": "Sambung daripada arkib?",
    "Return to previous channel": "Kembali ke saluran sebelumnya",
    Rewind: "Cari kedudukan",
    "Rewind step by buttons %1/%2": "Langkah undur butang %1/%2",
    RUSSKOETV: "RUSSKOETV",
    "RUSSKOETV settings": "Tetapan RUSSKOETV",
    Russian: "Bahasa Rusia",
    right: "kanan",
    Saturation: "Ketepuan",
    "Save & load channels": "Simpan dan muatkan saluran",
    "Save and load": "Simpan dan muatkan",
    "Save and load channels": "Simpan dan muatkan saluran",
    "Save Settings": "Simpan tetapan",
    "Save settings": "Simpan tetapan",
    "Save settings and load channel list":
        "Simpan tetapan dan muatkan senarai saluran",
    "Save settings to storage": "Simpan tetapan ke storan",
    Script: "Lakon layar",
    Search: "Cari",
    "Search programme": "Cari rancangan",
    "Select a stream type:<br>%1": "Pilih jenis strim:<br>%1",
    "Select category to add channel": "Pilih kategori untuk menambah saluran",
    "Select color": "Pilih warna",
    "Select menu items": "Pilih item menu",
    "Select playlist": "Pilih senarai main",
    "Select playlist file": "Pilih fail senarai main",
    "Select playlist template source for EPG and logos":
        "Pilih sumber templat senarai main untuk EPG dan logo",
    "Send request": "Hantar permintaan",
    "Send settings": "Hantar tetapan",
    "Send this code from your proxy in the Authorization: Bearer header.":
        "Hantar kod ini daripada proksi anda dalam pengepala Authorization: Bearer.",
    Server: "Pelayan",
    "Server address": "Alamat pelayan",
    "Server address (for example 192.168.1.20:8081)":
        "Alamat pelayan (contohnya 192.168.1.20:8081)",
    "Server device access code": "Kod akses peranti pada pelayan",
    "Server URL": "URL pelayan",
    "Server unavailable. Retrying automatically; check its address and network access.":
        "Pelayan tidak tersedia. Mencuba semula secara automatik; semak alamat dan akses rangkaiannya.",
    Set: "Tetapkan",
    "Set parental code": "Tetapkan kod ibu bapa",
    "Set timer?": "Tetapkan pemasa?",
    Settings: "Tetapan",
    "Settings could not be saved": "Tetapan tidak dapat disimpan",
    "Settings loaded from storage": "Tetapan dimuatkan daripada storan",
    "Settings STB": "Tetapan STB",
    "Settings saved": "Tetapan disimpan",
    "Settings saved to storage": "Tetapan disimpan ke storan",
    "Settings sended!": "Tetapan dihantar!",
    "Shara.club (ClubTV.pro)": "Shara.club (ClubTV.pro)",
    "Shara.club (ClubTV.pro) settings": "Tetapan Shara.club (ClubTV.pro)",
    ShockTv: "ShockTv",
    "ShockTv settings": "Tetapan ShockTv",
    "Show archive availability in list":
        "Tunjukkan ketersediaan arkib dalam senarai",
    "Show channel name in list": "Tunjukkan nama saluran dalam senarai",
    "Show channel number in list": "Tunjukkan nombor saluran dalam senarai",
    "Show channel selection list": "Tunjukkan senarai pemilihan saluran",
    "Show description": "Tunjukkan penerangan",
    "Show EPG and archive for channel": "Tunjukkan EPG dan arkib saluran",
    "Show list of channel archive records": "Tunjukkan rakaman saluran",
    "Show list of channel archive records without duplication":
        "Tunjukkan rakaman saluran tanpa pendua",
    "Show Media Library": "Tunjukkan pustaka media",
    "Show picons in channel list": "Tunjukkan ikon saluran dalam senarai",
    "Show player menu": "Tunjukkan menu pemain",
    "Show program name": "Tunjukkan nama rancangan",
    "Show progress in channel list": "Tunjukkan kemajuan dalam senarai saluran",
    "Show provider settings?": "Tunjukkan tetapan penyedia?",
    "Show providers?": "Tunjukkan penyedia?",
    "Show rewind window": "Tunjukkan tetingkap cari kedudukan",
    "Show scrollbar in list": "Tunjukkan bar tatal dalam senarai",
    "Show thumbnails": "Tunjukkan imej kecil",
    "Show when changing program": "Tunjukkan apabila rancangan berubah",
    "Show when rewind": "Tunjukkan semasa mengundur",
    "Show when switching": "Tunjukkan apabila menukar saluran",
    "Sleep timer": "Pemasa tidur",
    "Sort channels": "Isih saluran",
    "Stalker Portal Provider": "Penyedia portal Stalker",
    "Stalker portal settings": "Tetapan portal Stalker",
    "Stalker portals": "Portal Stalker",
    Status: "Status",
    "Stop playback and return to live":
        "Hentikan main balik dan kembali ke siaran langsung",
    "Stream type: %1": "Jenis strim: %1",
    "String for search": "Teks carian",
    "Su Mo Tu We Th Fr Sa": "Ahd Isn Sel Rab Kha Jum Sab",
    Subtitle: "Sari kata",
    Switch: "Tukar",
    "Switch sound track": "Tukar trek audio",
    "Switch subtitle": "Tukar sari kata",
    "Switch to this list": "Tukar ke senarai ini",
    "Swop URL": "Swop URL",
    "saved on this device": "disimpan pada peranti ini",
    select: "pilih",
    small: "kecil",
    system: "sistem",
    Tabox: "Tabox",
    "Tabox settings": "Tetapan Tabox",
    "The device ID in the address is invalid.":
        "ID peranti dalam alamat tidak sah.",
    "This HTTPS player cannot connect to an HTTP server. Use an HTTPS server or open the player over HTTP.":
        "Pemain HTTPS ini tidak dapat menyambung ke pelayan HTTP. Gunakan pelayan HTTPS atau buka pemain melalui HTTP.",
    "This Play app requires HTTPS. Ask your provider for an HTTPS playlist or server URL.":
        "Aplikasi Play ini memerlukan HTTPS. Minta URL senarai main atau pelayan HTTPS daripada penyedia anda.",
    Timer: "Pemasa",
    "Timer: switch to channel?": "Pemasa: tukar ke saluran ini?",
    "Timeshift: one minute back": "Timeshift: undur satu minit",
    "Timeshift: to start of TV program": "Timeshift: ke permulaan rancangan",
    Timezone: "Zon waktu",
    TMDb: "TMDb",
    "TOP-IPTV": "TOP-IPTV",
    "TOP-IPTV settings": "Tetapan TOP-IPTV",
    "To begining": "Ke permulaan",
    "To start of TV program / Previous TV program":
        "Ke permulaan rancangan / rancangan sebelumnya",
    "Toggle Aspect Ratio": "Tukar nisbah aspek",
    "Toggle on-screen debug HUD":
        "Hidupkan atau matikan panel nyahpepijat pada skrin",
    "Toggle Zoom Mode": "Tukar mod zum",
    "Top-Tv": "Top-Tv",
    "Top-Tv settings": "Tetapan Top-Tv",
    "Try demo": "Cuba demo",
    "TV DOSUG": "TV DOSUG",
    "TV DOSUG settings": "Tetapan TV DOSUG",
    TVClub: "TVClub",
    "TVClub settings": "Tetapan TVClub",
    "Type of player for streaming": "Jenis pemain penstriman",
    "top-left": "kiri atas",
    "top-right": "kanan atas",
    transparent: "lutsinar",
    ULTIFL1X: "ULTIFL1X",
    "ULTIFL1X settings": "Tetapan ULTIFL1X",
    "Update installed. Please restart OttPlay FOSS.":
        "Kemas kini dipasang. Sila mulakan semula OttPlay FOSS.",
    "Use an HTTP or HTTPS server address.":
        "Gunakan alamat pelayan HTTP atau HTTPS.",
    "Use HTTP or HTTPS without a username or password in the address.":
        "Gunakan HTTP atau HTTPS tanpa nama pengguna atau kata laluan dalam alamat.",
    "Use LEFT/RIGHT to select a control, OK to activate, and UP/DOWN to scroll.":
        "Gunakan KIRI/KANAN untuk memilih kawalan, OK untuk mengaktifkannya dan ATAS/BAWAH untuk menatal.",
    Username: "Nama pengguna",
    "Username or password is missing.": "Nama pengguna atau kata laluan tiada.",
    "VIP-IP.COM": "VIP-IP.COM",
    "VIP-IP.COM settings": "Tetapan VIP-IP.COM",
    "Vidok.TV": "Vidok.TV",
    "Vidok.TV settings": "Tetapan Vidok.TV",
    "VOD not supported by provider": "VOD tidak disokong oleh penyedia ini",
    "Volume step, %": "Langkah kelantangan, %",
    "VPortal link": "Pautan VPortal",
    "VPortal request failed":
        "Tidak dapat memuatkan VPortal. Semak pautan, kunci akses dan ketersediaan portal.",
    volume: "kelantangan",
    "Wrong parental code !!!": "Kod ibu bapa salah!",
    "Xtream Codes Provider": "Penyedia Xtream Codes",
    "Xtream Codes settings": "Tetapan Xtream Codes",
    Year: "Tahun",
    Yellow: "Kuning",
    Yes: "Ya",
    yes: "ya",
    "Гомельсат (cbilling)": "Гомельсат (cbilling)",
    "Гомельсат (cbilling) settings": "Tetapan Гомельсат (cbilling)",
    МойДом: "МойДом",
    "МойДом settings": "Tetapan МойДом",
    "Ошибка обработки списка каналов! Проверьте правильность данных!!":
        "Tidak dapat memproses senarai saluran. Semak maklumat penyedia anda!",
    Радуга: "Радуга",
    "Радуга settings": "Tetapan Радуга",
    "Редактирование ID": "Sunting ID",
    "Редактирование PIN": "Sunting PIN",
    Шаравоз: "Шаравоз",
    "Шаравоз settings": "Tetapan Шаравоз",
    "↑↓ Scroll": "↑↓ Tatal",
};
