var keyStrings = {
    " (after changing, load playlist)": " (po zmianie, załaduj playlistę)",
    " added to category ": " dodany do kategorii ",
    " added to favorites": " dodany do ulubionych",
    "??? No channel name": "??? Brak nazwy kanału",
    Actions: "Akcje",
    "Add channel to category": "Dodaj kanał do kategorii",
    "Add channel to favorites": "Dodaj kanał do ulubionych",
    All: "Wszystkie",
    "Applying HTTP remote settings...":
        "Stosowanie ustawień sterowania HTTP...",
    "Archive hours": "Godziny archiwum",
    alhabet: "aąbcćdeęfghijklłmnńoópqrsśtuvwxyzźż",
    "Buffer Size, s": "Rozmiar bufora, s",
    "built-in": "wbudowany",
    Category: "Kategoria",
    "Channel ": "Kanał ",
    "Channel is not available!!!": "Kanał niedostępny!!!",
    "Channel list": "Lista kanałów",
    "Channel list not received !!!": "Nie otrzymano listy kanałów!!!",
    "Channel list not received !!!<br/><br/>Enter the provider data and restart the player !!!<br/><br/>":
        "Nie otrzymano listy kanałów!!!<br/><br/>Wprowadź dane dostawcy i uruchom ponownie odtwarzacz!!!<br/><br/>",
    "Channel list. Category: ": "Lista kanałów. Kategoria: ",
    "Channel parental control": "Kontrola rodzicielska kanału",
    Close: "Zamknij",
    "Could not update HTTP remote control.":
        "Nie udało się zmienić ustawień sterowania HTTP.",
    "Delete channel": "Usuń kanał",
    Description: "Opis",
    "Device access code": "Kod dostępu do urządzenia",
    "Disable HTTP remote": "Wyłącz sterowanie HTTP",
    "Disabled by default. Enabling creates a new device access code.":
        "Domyślnie wyłączone. Włączenie tworzy nowy kod dostępu do urządzenia.",
    Edit: "Edytuj",
    "Edit category name": "Edytuj nazwę kategorii",
    "Edit playlist data": "Edytuj dane playlisty",
    Editor: "Edytor",
    "Enable HTTP remote": "Włącz sterowanie HTTP",
    "Enter Media Library URL": "Wprowadź URL biblioteki multimediów",
    "Enter parental code": "Wprowadź kod rodzicielski",
    "Enter playlist archive hours": "Wprowadź godziny archiwum playlisty",
    "Enter playlist Name": "Wprowadź nazwę playlisty",
    "Enter playlist URL": "Wprowadź URL playlisty",
    EPG: "Program TV",
    Exit: "Wyjście",
    "Failed to load channel list!": "Nie udało się załadować listy kanałów!",
    Favorites: "Ulubione",
    "HTTP port": "Port HTTP",
    "HTTP remote control is unavailable on this device.":
        "Sterowanie HTTP jest niedostępne na tym urządzeniu.",
    Info: "Informacje",
    Load: "Załaduj",
    "Load playlist": "Załaduj playlistę",
    "Local HTTP remote control": "Lokalne sterowanie HTTP",
    lang: "Polski",
    "Media Library URL": "URL biblioteki multimediów",
    Menu: "Menu",
    "Move channel down": "Przesuń kanał w dół",
    "Move channel up": "Przesuń kanał w górę",
    "m3u-m3u8 playlists": "Playlisty m3u-m3u8",
    min: "min",
    "No channel name": "Brak nazwy kanału",
    Nothing: "Nic",
    native: "natywny",
    no: "nie",
    "Open in PiP": "Otwórz w PiP",
    off: "wyłączony",
    on: "włączone",
    Playlist: "Playlista",
    "Playlist file": "Plik playlisty",
    "Playlist is not loading directly...Loading via server...":
        "Playlista nie ładuje się bezpośrednio...Ładowanie przez serwer...",
    "Playlist Name": "Nazwa playlisty",
    "Playlist URL": "URL playlisty",
    "Remote control": "Zdalne sterowanie",
    "Save Settings": "Zapisz ustawienia",
    Search: "Szukaj",
    "Select category to add channel": "Wybierz kategorię, aby dodać kanał",
    "Select playlist": "Wybierz playlistę",
    "Select playlist file": "Wybierz plik playlisty",
    "Send this code from your proxy in the Authorization: Bearer header.":
        "Wysyłaj ten kod z serwera proxy w nagłówku Authorization: Bearer.",
    Settings: "Ustawienia",
    "Settings STB": "Ustawienia STB",
    "Settings saved": "Ustawienia zapisane",
    "Stalker portals": "Portale Stalker",
    "Type of player for streaming": "Typ odtwarzacza do streamingu",
    "Wrong parental code !!!": "Nieprawidłowy kod rodzicielski!!!",
    yes: "tak",
};
