var keyStrings = {
    " (after changing, load playlist)": " (após alteração, carregar lista)",
    " added to category ": " adicionado à categoria ",
    " added to favorites": " adicionado aos favoritos",
    "??? No channel name": "??? Sem nome de canal",
    Actions: "Ações",
    "Add channel to category": "Adicionar canal à categoria",
    "Add channel to favorites": "Adicionar canal aos favoritos",
    All: "Todos",
    "Archive hours": "Horas de arquivo",
    alhabet: "aàáâãbcçdeéêfghiíîjklmnoóôõpqrstuúvwxyz",
    "Buffer Size, s": "Tamanho do buffer, s",
    "built-in": "integrado",
    Category: "Categoria",
    "Channel ": "Canal ",
    "Channel is not available!!!": "Canal não disponível!!!",
    "Channel list": "Lista de canais",
    "Channel list not received !!!": "Lista de canais não recebida!!!",
    "Channel list not received !!!<br/><br/>Enter the provider data and restart the player !!!<br/><br/>":
        "Lista de canais não recebida!!!<br/><br/>Introduza os dados do fornecedor e reinicie o leitor!!!<br/><br/>",
    "Channel list. Category: ": "Lista de canais. Categoria: ",
    "Channel parental control": "Controlo parental do canal",
    Close: "Fechar",
    "Delete channel": "Eliminar canal",
    Description: "Descrição",
    Edit: "Editar",
    "Edit category name": "Editar nome da categoria",
    "Edit playlist data": "Editar dados da lista",
    Editor: "Editor",
    "Enter Media Library URL": "Introduzir URL da mediateca",
    "Enter parental code": "Introduzir código parental",
    "Enter playlist archive hours": "Introduzir horas de arquivo da lista",
    "Enter playlist Name": "Introduzir nome da lista",
    "Enter playlist URL": "Introduzir URL da lista",
    EPG: "Guia TV",
    Exit: "Sair",
    "Failed to load channel list!": "Falha ao carregar a lista de canais!",
    Favorites: "Favoritos",
    Info: "Informação",
    Load: "Carregar",
    "Load playlist": "Carregar lista",
    lang: "Português",
    "Media Library URL": "URL da mediateca",
    Menu: "Menu",
    "Move channel down": "Mover canal para baixo",
    "Move channel up": "Mover canal para cima",
    "m3u-m3u8 playlists": "Listas m3u-m3u8",
    min: "min",
    "No channel name": "Sem nome de canal",
    Nothing: "Nada",
    native: "nativo",
    no: "não",
    "Open in PiP": "Abrir em PiP",
    off: "desligado",
    Playlist: "Lista de reprodução",
    "Playlist file": "Ficheiro da lista",
    "Playlist is not loading directly...Loading via server...":
        "A lista não está a carregar diretamente...A carregar através do servidor...",
    "Playlist Name": "Nome da lista",
    "Playlist URL": "URL da lista",
    "Save Settings": "Guardar configurações",
    Search: "Pesquisar",
    "Select category to add channel":
        "Selecionar categoria para adicionar canal",
    "Select playlist": "Selecionar lista",
    "Select playlist file": "Selecionar ficheiro da lista",
    Settings: "Configurações",
    "Settings STB": "Configurações STB",
    "Settings saved": "Configurações guardadas",
    "Stalker portals": "Portais Stalker",
    "Type of player for streaming": "Tipo de leitor para streaming",
    "Wrong parental code !!!": "Código parental errado!!!",
    yes: "sim",
};
