var keyStrings = {
    " (after changing, load playlist)": " (após alteração, carregar lista)",
    " (after changing, restart player)": " (reinicie o leitor após alterar)",
    " added to category ": " adicionado à categoria ",
    " added to favorites": " adicionado aos favoritos",
    " m ": " min ",
    " s": " s",
    "??? No channel name": "??? Sem nome de canal",
    '"As Is"': '"Original"',
    '"Favorites"': '"Favoritos"',
    '"Sliding" infobar': "Barra de informações deslizante",
    "&darr;a": "&darr;a",
    "&uarr;A": "&uarr;A",
    "<br/><br/>In archive mode:<br/>": "<br/><br/>No modo de arquivo:<br/>",
    "<br/>Loading STB...": "<br/>A carregar o descodificador…",
    "<br/>Setup STB...": "<br/>A configurar o descodificador…",
    "<br>": "<br>",
    "<br><br>": "<br><br>",
    "<br>Add<br>to category": "<br>Adicionar<br>à categoria",
    "<br>Add<br>to favorites": "<br>Adicionar<br>aos favoritos",
    "<br>Delete": "<br>Eliminar",
    "<br>Down<br>": "<br>Baixo<br>",
    "<br>Live": "<br>Em direto",
    "<br>Menu": "<br>Menu",
    "<br>Parental<br>Control": "<br>Controlo<br>parental",
    "<br>Pause<br>": "<br>Pausa<br>",
    "<br>Previous<br>channel": "<br>Canal<br>anterior",
    "<br>Rewind<br>": "<br>Recuar<br>",
    "<br>Toggle<br>sound track": "<br>Mudar<br>faixa de áudio",
    "<br>Up<br>": "<br>Cima<br>",
    "1 hour": "1 hora",
    "1 minute": "1 minuto",
    "2 hours": "2 horas",
    "3 hours": "3 horas",
    "10 Seconds": "10 segundos",
    "30 minutes": "30 minutos",
    "A command expired while the player was loading channels.":
        "Um comando expirou durante o carregamento dos canais.",
    "A command was rejected by the player. Check its provider and settings.":
        "O leitor rejeitou um comando. Verifique o fornecedor e as configurações.",
    About: "Acerca de",
    "Access code": "Código de acesso",
    "Access denied. Check the server access code.":
        "Acesso negado. Verifique o código de acesso do servidor.",
    "Access key": "Chave de acesso",
    "Access key is required!": "É necessária uma chave de acesso!",
    "Access settings": "Configurações de acesso",
    Actions: "Ações",
    "Active list": "Lista ativa",
    Actors: "Elenco",
    "Add / rename / delete…": "Adicionar / mudar nome / eliminar…",
    "Add channel to category": "Adicionar canal à categoria",
    "Add channel to favorites": "Adicionar canal aos favoritos",
    "Add new list": "Adicionar nova lista",
    "Add to favorites": "Adicionar aos favoritos",
    Age: "Idade",
    All: "Todos",
    "All categories": "Todas as categorias",
    "All4you.tv": "All4you.tv",
    "All4you.tv settings": "Configurações de All4you.tv",
    "Allowlist this Device ID": "Autorizar este ID de dispositivo",
    "An IP without a port uses HTTP port 8081. Clear the address or select Disconnect to stop.":
        "Um IP sem porta usa a porta HTTP 8081. Apague o endereço ou selecione Desligar para parar.",
    "API failed, trying M3U...": "A API falhou, a tentar M3U…",
    "API Server": "Servidor API",
    "API server URL": "URL do servidor API",
    "Applying HTTP remote settings...":
        "A aplicar as definições do controlo remoto HTTP...",
    Archive: "Arquivo",
    "Archive - begin": "Arquivo — início",
    "Archive hours": "Horas de arquivo",
    "Archive: ENTER on past programs":
        "Arquivo: ENTER nos programas anteriores",
    "Archive. Channel: ": "Arquivo. Canal: ",
    Aspect: "Proporção da imagem",
    Audio: "Áudio",
    alhabet: "aàáâãbcçdeéêfghiíîjklmnoòóôõpqrstuúvwxyz",
    always: "sempre",
    "and enter code": "e introduza o código",
    Back: "Voltar",
    "Back / Forward for 1 minute": "Recuar / avançar 1 minuto",
    "Background color": "Cor de fundo",
    "Background color of selected item": "Cor de fundo do item selecionado",
    "BEST LiST IPTV [HLS Playlist]": "BEST LiST IPTV [HLS Playlist]",
    "BEST LiST IPTV [HLS Playlist] settings":
        "Configurações de BEST LiST IPTV [HLS Playlist]",
    "BEST LiST IPTV [Stalker]": "BEST LiST IPTV [Stalker]",
    "BEST LiST IPTV [Stalker] settings":
        "Configurações de BEST LiST IPTV [Stalker]",
    "Behavior of %1/%2 buttons in lists":
        "Comportamento dos botões %1/%2 nas listas",
    "Black screen while switching the channel": "Ecrã preto ao mudar de canal",
    Blue: "Azul",
    "Bookmark age: %1 days": "Idade do marcador: %1 dias",
    "Buffer Size, s": "Tamanho do buffer, s",
    "Built-in playlist:": "Lista integrada:",
    "Built-in playlists": "Listas integradas",
    "Button %1 function when viewing":
        "Função do botão %1 durante a reprodução",
    "Button function %1 when viewing archive":
        "Função do botão %1 durante a reprodução do arquivo",
    "Buttons settings": "Configurações dos botões",
    "By alphabet": "Por ordem alfabética",
    "By time": "Por ordem cronológica",
    "begin/end": "início/fim",
    "bottom-right": "canto inferior direito",
    "built-in": "integrado",
    "Call PiP": "Abrir PiP",
    "Call PiP / PiP exchange": "Abrir PiP / trocar PiP",
    Cancel: "Cancelar",
    "Cannot delete the last category":
        "Não é possível eliminar a última categoria",
    Category: "Categoria",
    "Category selection": "Seleção de categoria",
    "Change interface language": "Mudar o idioma da interface",
    "Change provider": "Mudar fornecedor",
    "Change provider - you can change the provider, and it will be remembered at the next start of player!":
        "Mude o fornecedor. A seleção será mantida no próximo arranque do leitor.",
    "Change value": "Alterar valor",
    "Channel ": "Canal ",
    "Channel has no EPG": "O canal não tem EPG",
    "Channel is not available!!!": "Canal não disponível!!!",
    "Channel link": "Ligação do canal",
    "Channel link is required!": "É necessária a ligação do canal!",
    "Channel list": "Lista de canais",
    "Channel list editing style": "Modo de edição da lista de canais",
    "Channel list not received !!!": "Lista de canais não recebida!!!",
    "Channel list not received !!!<br/><br/>Enter the provider data and restart the player !!!<br/><br/>":
        "Lista de canais não recebida!!!<br/><br/>Introduza os dados do fornecedor e reinicie o leitor!!!<br/><br/>",
    "Channel list settings": "Configurações da lista de canais",
    "Channel list. Category: ": "Lista de canais. Categoria: ",
    "Channel parental control": "Controlo parental do canal",
    Channels: "Canais",
    "Choose from": "Escolher entre",
    "Choose language": "Escolher idioma",
    "Choose provider": "Escolher fornecedor",
    Classic: "Clássico",
    "Clear all settings?": "Apagar todas as configurações?",
    "Clear settings": "Apagar configurações",
    Close: "Fechar",
    "Close PiP": "Fechar PiP",
    Color: "Cor",
    "Color spectrum": "Espetro de cores",
    "Command server": "Servidor de comandos",
    "Command server address, device access code, local HTTP control, and remote text entry settings":
        "Endereço do servidor de comandos, código de acesso do dispositivo, controlo HTTP local e entrada de texto remota",
    "Configure All4you.tv in Settings -> Provider Settings":
        "Configure All4you.tv em Configurações -> Configurações do fornecedor",
    "Configure BEST LiST IPTV [HLS Playlist] in Settings -> Provider Settings":
        "Configure BEST LiST IPTV [HLS Playlist] em Configurações -> Configurações do fornecedor",
    "Configure BEST LiST IPTV [Stalker] in Settings -> Provider Settings":
        "Configure BEST LiST IPTV [Stalker] em Configurações -> Configurações do fornecedor",
    "Configure Diamond TV in Settings -> Provider Settings":
        "Configure Diamond TV em Configurações -> Configurações do fornecedor",
    "Configure DRVAO in Settings -> Provider Settings":
        "Configure DRVAO em Configurações -> Configurações do fornecedor",
    "Configure Dragon Media PRO in Settings -> Provider Settings":
        "Configure Dragon Media PRO em Configurações -> Configurações do fornecedor",
    "Configure Fabryka.TV in Settings -> Provider Settings":
        "Configure Fabryka.TV em Configurações -> Configurações do fornecedor",
    "Configure Fox-TV in Settings -> Provider Settings":
        "Configure Fox-TV em Configurações -> Configurações do fornecedor",
    "Configure FXML in Settings -> Provider Settings":
        "Configure FXML em Configurações -> Configurações do fornecedor",
    "Configure GlanzTV in Settings -> Provider Settings":
        "Configure GlanzTV em Configurações -> Configurações do fornecedor",
    "Configure GREAT IPTV in Settings -> Provider Settings":
        "Configure GREAT IPTV em Configurações -> Configurações do fornecedor",
    "Configure IpStream.one in Settings -> Provider Settings":
        "Configure IpStream.one em Configurações -> Configurações do fornecedor",
    "Configure KORONA TV in Settings -> Provider Settings":
        "Configure KORONA TV em Configurações -> Configurações do fornecedor",
    "Configure MaxTV in Settings -> Provider Settings":
        "Configure MaxTV em Configurações -> Configurações do fornecedor",
    "Configure New Look in Settings -> Provider Settings":
        "Configure New Look em Configurações -> Configurações do fornecedor",
    "Configure OTT Prime ONLINE in Settings -> Provider Settings":
        "Configure OTT Prime ONLINE em Configurações -> Configurações do fornecedor",
    "Configure POLMEDIA in Settings -> Provider Settings":
        "Configure POLMEDIA em Configurações -> Configurações do fornecedor",
    "Configure PROST in Settings -> Provider Settings":
        "Configure PROST em Configurações -> Configurações do fornecedor",
    "Configure RD in Settings -> Provider Settings":
        "Configure RD em Configurações -> Configurações do fornecedor",
    "Configure RUSSKOETV in Settings -> Provider Settings":
        "Configure RUSSKOETV em Configurações -> Configurações do fornecedor",
    "Configure Shara.club (ClubTV.pro) in Settings -> Provider Settings":
        "Configure Shara.club (ClubTV.pro) em Configurações -> Configurações do fornecedor",
    "Configure ShockTv in Settings -> Provider Settings":
        "Configure ShockTv em Configurações -> Configurações do fornecedor",
    "Configure Tabox in Settings -> Provider Settings":
        "Configure Tabox em Configurações -> Configurações do fornecedor",
    "Configure TOP-IPTV in Settings -> Provider Settings":
        "Configure TOP-IPTV em Configurações -> Configurações do fornecedor",
    "Configure Top-Tv in Settings -> Provider Settings":
        "Configure Top-Tv em Configurações -> Configurações do fornecedor",
    "Configure TV DOSUG in Settings -> Provider Settings":
        "Configure TV DOSUG em Configurações -> Configurações do fornecedor",
    "Configure TVClub in Settings -> Provider Settings":
        "Configure TVClub em Configurações -> Configurações do fornecedor",
    "Configure ULTIFL1X in Settings -> Provider Settings":
        "Configure ULTIFL1X em Configurações -> Configurações do fornecedor",
    "Configure VIP-IP.COM in Settings -> Provider Settings":
        "Configure VIP-IP.COM em Configurações -> Configurações do fornecedor",
    "Configure Vidok.TV in Settings -> Provider Settings":
        "Configure Vidok.TV em Configurações -> Configurações do fornecedor",
    "Configure Гомельсат (cbilling) in Settings -> Provider Settings":
        "Configure Гомельсат (cbilling) em Configurações -> Configurações do fornecedor",
    "Configure МойДом in Settings -> Provider Settings":
        "Configure МойДом em Configurações -> Configurações do fornecedor",
    "Configure Радуга in Settings -> Provider Settings":
        "Configure Радуга em Configurações -> Configurações do fornecedor",
    "Configure Шаравоз in Settings -> Provider Settings":
        "Configure Шаравоз em Configurações -> Configurações do fornecedor",
    Connect: "Ligar",
    Connected: "Ligado",
    "Connected. Waiting for the channel list...":
        "Ligado. A aguardar a lista de canais…",
    "Connecting to Stalker portal...": "A ligar ao portal Stalker…",
    "Connecting...": "A ligar…",
    "Continue watching?": "Continuar a ver?",
    "Copy category": "Copiar categoria",
    "Copy JSON": "Copiar JSON",
    "Could not connect to the server.": "Não foi possível ligar ao servidor.",
    "Could not update HTTP remote control.":
        "Não foi possível atualizar o controlo remoto HTTP.",
    Country: "País",
    "Create category": "Criar categoria",
    current: "atual",
    "Debug HUD": "Painel de depuração",
    "Debug HUD is not available": "Painel de depuração indisponível",
    Delete: "Eliminar",
    "Delete category": "Eliminar categoria",
    "Delete channel": "Eliminar canal",
    "Delete list": "Eliminar lista",
    "Demo — moving test pattern": "Demonstração — padrão de teste em movimento",
    Description: "Descrição",
    "Description of remote control buttons": "Guia dos botões do comando",
    "Device access code": "Código de acesso ao dispositivo",
    "Device info:": "Informações do dispositivo:",
    "Device MAC is required for KBC (Kinoboom) playlists":
        "As listas KBC (Kinoboom) exigem o MAC do dispositivo",
    "Diamond TV": "Diamond TV",
    "Diamond TV settings": "Configurações de Diamond TV",
    Director: "Realização",
    "Disable HTTP remote": "Desativar controlo HTTP",
    "Disabled by default. Enabling creates a new device access code.":
        "Desativado por predefinição. A ativação cria um novo código de acesso ao dispositivo.",
    Disconnect: "Desligar",
    Disconnected: "Desligado",
    "Distance between lines in lists": "Espaçamento entre linhas nas listas",
    "Do you want to exit player?": "Pretende sair do leitor?",
    "Download! Wait ...": "A transferir… aguarde…",
    DRVAO: "DRVAO",
    "DRVAO settings": "Configurações de DRVAO",
    "Dragon Media PRO": "Dragon Media PRO",
    "Dragon Media PRO settings": "Configurações de Dragon Media PRO",
    Duration: "Duração",
    Edit: "Editar",
    "Edit access key": "Editar chave de acesso",
    "Edit category name": "Editar nome da categoria",
    "Edit channel link": "Editar ligação do canal",
    "Edit playlist data": "Editar dados da lista",
    "Edit VPortal link": "Editar ligação VPortal",
    Editor: "Editor",
    "Enable HTTP remote": "Ativar controlo HTTP",
    English: "Inglês",
    "Enter a password (8 characters).":
        "Introduza uma palavra-passe (8 caracteres).",
    "Enter a playlist URL to access this service.":
        "Introduza o URL de uma lista de reprodução para aceder a este serviço.",
    "Enter a server address without spaces or a fragment.":
        "Introduza um endereço de servidor sem espaços nem fragmento.",
    "Enter a username (8 characters).":
        "Introduza um nome de utilizador (8 caracteres).",
    "Enter a username and password to access this service.":
        "Introduza o nome de utilizador e a palavra-passe para aceder a este serviço.",
    "Enter a valid server address, for example 192.168.1.20:8081.":
        "Introduza um endereço de servidor válido, por exemplo 192.168.1.20:8081.",
    "Enter access key for": "Introduzir chave de acesso para",
    "Enter an application access key (8 characters).":
        "Introduza uma chave de acesso para aplicações (8 caracteres).",
    "Enter an ID and PIN to access this service.":
        "Introduza ID e PIN para aceder a este serviço.",
    "Enter an IPTV token (10 characters).":
        "Introduza um token IPTV (10 caracteres).",
    "Enter category name": "Introduzir nome da categoria",
    "Enter MAC address": "Introduzir endereço MAC",
    "Enter MAC address (e.g. 00:1A:2B:3C:4D:5E)":
        "Introduzir endereço MAC (ex.: 00:1A:2B:3C:4D:5E)",
    "Enter Media Library URL": "Introduzir URL da mediateca",
    "Enter new category name": "Introduzir novo nome da categoria",
    "Enter Provider Code": "Introduzir código do fornecedor",
    "Enter Provider Code on PC or Phone":
        "Introduzir código do fornecedor no PC ou telefone",
    "Enter parental code": "Introduzir código parental",
    "Enter password": "Introduzir palavra-passe",
    "Enter playlist archive hours": "Introduzir horas de arquivo da lista",
    "Enter playlist Name": "Introduzir nome da lista",
    "Enter playlist URL": "Introduzir URL da lista",
    "Enter Stalker portal URL": "Introduzir URL do portal Stalker",
    "Enter Stalker portal URL (e.g. http://your-portal:8800)":
        "Introduzir URL do portal Stalker (ex.: http://your-portal:8800)",
    "Enter Stalker portal URL (e.g. http://your-portal/stalker_portal/c/)":
        "Introduzir URL do portal Stalker (ex.: http://your-portal/stalker_portal/c/)",
    "Enter the access code separately, not in the server address.":
        "Introduza o código de acesso separadamente, não no endereço do servidor.",
    "Enter the command server IP or address.":
        "Introduza o IP ou endereço do servidor de comandos.",
    "Enter the full CDN host from the cabinet stream URL (e.g. subdomain.cdn-domain.tld), not a bare subdomain":
        "Introduza o nome completo do servidor CDN do URL do fluxo na área de cliente (ex.: subdomain.cdn-domain.tld), não apenas o subdomínio",
    "Enter the server IP or address and this player's device access code from the server configuration. Saving both starts checking for volume, channel and other commands automatically.":
        "Introduza o IP ou endereço do servidor e o código de acesso deste leitor indicado na configuração do servidor. Ao guardar ambos, a verificação de comandos de volume, canal e outros inicia-se automaticamente.",
    "Enter the server's device access code (32–256 letters, digits, _ or -).":
        "Introduza o código de acesso do dispositivo no servidor (32–256 letras, algarismos, _ ou -).",
    'Enter the tv.team playlist URL.<br>Playlist type: <b>OTTPlayer</b><br/><br/>The "/playlist.m3u8" suffix is added automatically if omitted.':
        'Introduza o URL da lista tv.team.<br>Tipo de lista: <b>OTTPlayer</b><br/><br/>O sufixo "/playlist.m3u8" é adicionado automaticamente se for omitido.',
    "Enter the VPortal link as shown in the cabinet":
        "Introduza a ligação VPortal tal como aparece na área de cliente",
    "Enter this link in VPortal link. Playlist URL requires an M3U playlist.":
        "Introduza esta ligação em Ligação VPortal. O URL da lista exige uma lista M3U.",
    "Enter this player's device access code to connect.":
        "Introduza o código de acesso deste leitor para ligar.",
    "Enter username": "Introduzir nome de utilizador",
    "Enter value": "Introduzir valor",
    "Enter Xtream server URL": "Introduzir URL do servidor Xtream",
    "Enter Xtream server URL (e.g. https://your-server:8080)":
        "Introduzir URL do servidor Xtream (ex.: https://your-server:8080)",
    EPG: "Guia TV",
    "EPG and archive. Channel: ": "EPG e arquivo. Canal: ",
    "ERROR!": "Erro!",
    "Error Code!": "Código inválido!",
    Exit: "Sair",
    "Exit player": "Sair do leitor",
    "Export settings": "Exportar configurações",
    "epg.one (Ordered)": "epg.one (ordenado)",
    "epg.one (Standard)": "epg.one (padrão)",
    "epg.one (Thematic)": "epg.one (temático)",
    "epgs...": "Guias EPG…",
    "Fabryka.TV": "Fabryka.TV",
    "Fabryka.TV settings": "Configurações de Fabryka.TV",
    "Failed to connect to Stalker portal":
        "Não foi possível ligar ao portal Stalker",
    "Failed to connect to Xtream API server":
        "Não foi possível ligar ao servidor API Xtream",
    "Failed to get user data!!!":
        "Não foi possível obter os dados do utilizador!",
    "Failed to load channel list!": "Falha ao carregar a lista de canais!",
    "Failed to load channels from Stalker portal":
        "Não foi possível carregar os canais do portal Stalker",
    "Failed to load channels from Xtream API":
        "Não foi possível carregar os canais da API Xtream",
    "Failed to load!": "Falha ao carregar!",
    "Favorite lists": "Listas de favoritos",
    Favorites: "Favoritos",
    "File selection is not supported on this device":
        "A seleção de ficheiros não é suportada neste dispositivo",
    Filters: "Filtros",
    "First Run Setup": "Configuração inicial",
    "Font type": "Tipo de letra",
    "For download settings file open":
        "Para transferir o ficheiro de configurações, abra",
    "For enter value open": "Para introduzir um valor, abra",
    "For upload settings file open":
        "Para enviar o ficheiro de configurações, abra",
    "Fox-TV": "Fox-TV",
    "Fox-TV settings": "Configurações de Fox-TV",
    FXML: "FXML",
    "FXML settings": "Configurações de FXML",
    Genre: "Género",
    GlanzTV: "GlanzTV",
    "GlanzTV settings": "Configurações de GlanzTV",
    "Go to": "Ir para",
    "GREAT IPTV": "GREAT IPTV",
    "GREAT IPTV settings": "Configurações de GREAT IPTV",
    "Graphical indication": "Indicadores gráficos",
    Green: "Verde",
    "Hide / Return": "Ocultar / mostrar",
    "Hide provider settings?": "Ocultar as configurações do fornecedor?",
    "Hide providers?": "Ocultar fornecedores?",
    "History in Media Library": "Histórico na mediateca",
    "History of watched movies": "Histórico de visualização",
    "HTTP port": "Porta HTTP",
    "HTTP remote control is unavailable on this device.":
        "O controlo remoto HTTP não está disponível neste dispositivo.",
    ID: "ID",
    "Import settings": "Importar configurações",
    "In live mode: <br/>": "No modo em direto:<br/>",
    Info: "Informação",
    "Infobar display timeout, s": "Duração da barra de informações, s",
    "Infobar settings": "Configurações da barra de informações",
    Information: "Informações",
    "Interface credits": "Créditos da interface",
    "Interface settings": "Configurações da interface",
    "Interface theme": "Tema da interface",
    "Interface transparency": "Transparência da interface",
    "Invalid channel link! Enter the full host as in the cabinet stream URL (e.g. subdomain.cdn-domain.tld)":
        "Ligação do canal inválida! Introduza o nome completo do servidor como no URL do fluxo da área de cliente (ex.: subdomain.cdn-domain.tld)",
    "IPTV token": "Token IPTV",
    "IpStream.one": "IpStream.one",
    "IpStream.one settings": "Configurações de IpStream.one",
    Joystick: "Joystick",
    "KBC (Kinoboom) access data": "Dados de acesso KBC (Kinoboom)",
    "KORONA TV": "KORONA TV",
    "KORONA TV settings": "Configurações de KORONA TV",
    "List created": "Lista criada",
    "List deleted": "Lista eliminada",
    "List location": "Posição da lista",
    "List renamed": "Nome da lista alterado",
    "List type": "Tipo de lista",
    "Lists settings": "Configurações das listas",
    Live: "Em direto",
    Load: "Carregar",
    "Load built-in playlist:": "Carregar lista integrada:",
    "Load playlist": "Carregar lista",
    "Load settings": "Carregar configurações",
    "Load settings from storage": "Carregar configurações do armazenamento",
    "Load:": "Carregar:",
    "Loading channels from Xtream API...": "A carregar canais da API Xtream…",
    "Loading channels...": "A carregar canais…",
    "Loading from API...": "A carregar da API…",
    "Loading from Edem API...": "A carregar da API Edem…",
    "Loading M3U playlist...": "A carregar a lista M3U…",
    "Loading M3U...": "A carregar M3U…",
    "Loading via proxy...": "A carregar através do proxy…",
    "Loading. Please wait...": "A carregar… aguarde…",
    "Loading...": "A carregar…",
    "Local HTTP remote control": "Controlo remoto HTTP local",
    "Local URL": "URL local",
    Login: "Início de sessão",
    lang: "Português",
    large: "grande",
    left: "esquerda",
    "left-bottom": "canto inferior esquerdo",
    "logos...": "Logótipos…",
    M3U: "M3U",
    "M3U URL": "URL M3U",
    "M3U URL (fallback)": "URL M3U (alternativo)",
    "MAC address": "Endereço MAC",
    "Manage lists": "Gerir listas",
    "Manage settings": "Gerir configurações",
    "Manual setup": "Configuração manual",
    MaxTV: "MaxTV",
    "MaxTV settings": "Configurações de MaxTV",
    Media: "Multimédia",
    "Media item is no longer available":
        "O conteúdo multimédia já não está disponível",
    "Media Library": "Mediateca",
    "Media Library URL": "URL da mediateca",
    Menu: "Menu",
    "Menu items settings": "Configurações dos itens do menu",
    "Move category down": "Mover categoria para baixo",
    "Move category up": "Mover categoria para cima",
    "Move channel down": "Mover canal para baixo",
    "Move channel up": "Mover canal para cima",
    "m3u-m3u8 playlists": "Listas m3u-m3u8",
    medium: "médio",
    min: "min",
    "New Look": "New Look",
    "New Look settings": "Configurações de New Look",
    "New list name": "Nome da nova lista",
    Next: "Página seguinte",
    "Next keyboard page": "Página seguinte do teclado",
    "Next TV program": "Programa seguinte",
    No: "Não",
    "No channel name": "Sem nome de canal",
    "No saved settings found": "Não foram encontradas configurações guardadas",
    "Not found": "Não encontrado",
    "Not reduce video when showing the list (bugfix)":
        "Não reduzir o vídeo ao mostrar a lista (correção)",
    Nothing: "Nada",
    "Number of next TV programs in channel list":
        "Número de programas seguintes na lista de canais",
    "Number of rows in lists": "Número de linhas nas listas",
    native: "nativo",
    no: "não",
    "no epg at current time": "Sem EPG neste momento",
    "not set": "não definido",
    Off: "Desativado",
    Ok: "OK",
    Open: "Abrir",
    "Open in PiP": "Abrir em PiP",
    "OTT Prime ONLINE": "OTT Prime ONLINE",
    "OTT Prime ONLINE settings": "Configurações de OTT Prime ONLINE",
    "OttPlay FOSS %1 is available. Download and install now?":
        "OttPlay FOSS %1 está disponível. Transferir e instalar agora?",
    "Overwrite current settings?": "Substituir as configurações atuais?",
    off: "desligado",
    on: "ativado",
    "on ": "ativado ",
    "or scan": "ou leia o código",
    "Parental control": "Controlo parental",
    Password: "Palavra-passe",
    Pause: "Pausa",
    "Pause/Play": "Pausa / reproduzir",
    "Permanent clock on screen": "Mostrar sempre o relógio no ecrã",
    PIN: "PIN",
    "PiP exchange": "Trocar PiP",
    "PiP window position": "Posição da janela PiP",
    "PiP window size": "Tamanho da janela PiP",
    Play: "Reproduzir",
    "Player and device info": "Informações do leitor e dispositivo",
    "Player info:": "Informações do leitor:",
    Playlist: "Lista de reprodução",
    "Playlist file": "Ficheiro da lista",
    "Playlist is not loading directly...Loading via server...":
        "A lista não está a carregar diretamente...A carregar através do servidor...",
    "Playlist Name": "Nome da lista",
    "Playlist URL": "URL da lista",
    POLMEDIA: "POLMEDIA",
    "POLMEDIA settings": "Configurações de POLMEDIA",
    "Portal URL": "URL do portal",
    "Position shift -10 seconds after pause":
        "Recuar 10 segundos após uma pausa",
    PROST: "PROST",
    "PROST settings": "Configurações de PROST",
    Prev: "Anterior",
    "Preview in channel list": "Pré-visualização na lista de canais",
    Previous: "Anterior",
    "Privacy policy": "Política de privacidade",
    "Protect Adult Channels": "Proteger canais para adultos",
    "Protect Change Provider": "Proteger mudança de fornecedor",
    "Protect Settings": "Proteger configurações",
    "p...": "p...",
    paging: "por páginas",
    Quality: "Qualidade",
    Rating: "Classificação",
    RD: "RD",
    "RD settings": "Configurações de RD",
    "Reconnecting…": "A voltar a ligar…",
    Records: "Gravações",
    "Records for channel: ": "Gravações do canal: ",
    "Records library is empty": "A biblioteca de gravações está vazia",
    "Records not supported by provider": "O fornecedor não suporta gravações",
    "Release date": "Data de lançamento",
    "Remember previous channels": "Memorizar canais anteriores",
    "Reminder: %1 — %2 in %3 min": "Lembrete: %1 — %2 em %3 min",
    "Remote (color buttons N/A)": "Comando sem botões coloridos",
    "Remote (number buttons N/A)": "Comando sem botões numéricos",
    "Remote control": "Controlo remoto",
    "Remote session expired": "Sessão remota expirada",
    "Remote text entry denied": "Entrada de texto remota negada",
    "Remote text entry error": "Erro na entrada de texto remota",
    "Remote text entry not configured":
        "Entrada de texto remota não configurada",
    "Remote text entry requires a Device ID. Ask the server operator to provision one.":
        "A entrada de texto remota exige um ID de dispositivo. Peça um ao administrador do servidor.",
    "Remove timer?": "Remover temporizador?",
    Rename: "Mudar nome",
    "Rename category": "Mudar nome da categoria",
    "Rename to": "Mudar nome para",
    "Repeat parental code": "Repetir código parental",
    "Request sended!": "Pedido enviado!",
    "Restart player": "Reiniciar leitor",
    "Restart stream": "Reiniciar fluxo",
    "Restart stream / Live": "Reiniciar fluxo / direto",
    "Resume from archive?": "Retomar a partir do arquivo?",
    "Return to previous channel": "Voltar ao canal anterior",
    Rewind: "Deslocar reprodução",
    "Rewind step by buttons %1/%2": "Intervalo de recuo dos botões %1/%2",
    RUSSKOETV: "RUSSKOETV",
    "RUSSKOETV settings": "Configurações de RUSSKOETV",
    Russian: "Russo",
    right: "direita",
    Saturation: "Saturação",
    "Save & load channels": "Guardar e carregar canais",
    "Save and load": "Guardar e carregar",
    "Save and load channels": "Guardar e carregar canais",
    "Save Settings": "Guardar configurações",
    "Save settings": "Guardar configurações",
    "Save settings and load channel list":
        "Guardar configurações e carregar lista de canais",
    "Save settings to storage": "Guardar configurações no armazenamento",
    Script: "Argumento",
    Search: "Pesquisar",
    "Search programme": "Pesquisar programa",
    "Select a stream type:<br>%1": "Selecione um tipo de fluxo:<br>%1",
    "Select category to add channel":
        "Selecionar categoria para adicionar canal",
    "Select color": "Selecionar cor",
    "Select menu items": "Selecionar itens do menu",
    "Select playlist": "Selecionar lista",
    "Select playlist file": "Selecionar ficheiro da lista",
    "Select playlist template source for EPG and logos":
        "Selecionar origem do modelo de lista para EPG e logótipos",
    "Send request": "Enviar pedido",
    "Send settings": "Enviar configurações",
    "Send this code from your proxy in the Authorization: Bearer header.":
        "Envie este código a partir do proxy no cabeçalho Authorization: Bearer.",
    Server: "Servidor",
    "Server address": "Endereço do servidor",
    "Server address (for example 192.168.1.20:8081)":
        "Endereço do servidor (por exemplo 192.168.1.20:8081)",
    "Server device access code": "Código de acesso do dispositivo no servidor",
    "Server URL": "URL do servidor",
    "Server unavailable. Retrying automatically; check its address and network access.":
        "Servidor indisponível. Nova tentativa automática; verifique o endereço e o acesso à rede.",
    Set: "Definir",
    "Set parental code": "Definir código parental",
    "Set timer?": "Definir temporizador?",
    Settings: "Configurações",
    "Settings could not be saved": "Não foi possível guardar as configurações",
    "Settings loaded from storage": "Configurações carregadas do armazenamento",
    "Settings STB": "Configurações STB",
    "Settings saved": "Configurações guardadas",
    "Settings saved to storage": "Configurações guardadas no armazenamento",
    "Settings sended!": "Configurações enviadas!",
    "Shara.club (ClubTV.pro)": "Shara.club (ClubTV.pro)",
    "Shara.club (ClubTV.pro) settings":
        "Configurações de Shara.club (ClubTV.pro)",
    ShockTv: "ShockTv",
    "ShockTv settings": "Configurações de ShockTv",
    "Show archive availability in list":
        "Mostrar disponibilidade do arquivo na lista",
    "Show channel name in list": "Mostrar nome do canal na lista",
    "Show channel number in list": "Mostrar número do canal na lista",
    "Show channel selection list": "Mostrar lista de seleção de canais",
    "Show description": "Mostrar descrição",
    "Show EPG and archive for channel": "Mostrar EPG e arquivo do canal",
    "Show list of channel archive records": "Mostrar gravações do canal",
    "Show list of channel archive records without duplication":
        "Mostrar gravações do canal sem duplicados",
    "Show Media Library": "Mostrar mediateca",
    "Show picons in channel list": "Mostrar ícones dos canais na lista",
    "Show player menu": "Mostrar menu do leitor",
    "Show program name": "Mostrar nome do programa",
    "Show progress in channel list": "Mostrar progresso na lista de canais",
    "Show provider settings?": "Mostrar configurações do fornecedor?",
    "Show providers?": "Mostrar fornecedores?",
    "Show rewind window": "Mostrar janela de deslocamento",
    "Show scrollbar in list": "Mostrar barra de deslocamento nas listas",
    "Show thumbnails": "Mostrar miniaturas",
    "Show when changing program": "Mostrar ao mudar de programa",
    "Show when rewind": "Mostrar ao recuar",
    "Show when switching": "Mostrar ao mudar de canal",
    "Sleep timer": "Temporizador de suspensão",
    "Sort channels": "Ordenar canais",
    "Stalker Portal Provider": "Fornecedor do portal Stalker",
    "Stalker portal settings": "Configurações do portal Stalker",
    "Stalker portals": "Portais Stalker",
    Status: "Estado",
    "Stop playback and return to live": "Parar reprodução e voltar ao direto",
    "Stream type: %1": "Tipo de fluxo: %1",
    "String for search": "Texto de pesquisa",
    "Su Mo Tu We Th Fr Sa": "Do Se Te Qu Qu Se Sá",
    Subtitle: "Legendas",
    Switch: "Mudar",
    "Switch sound track": "Mudar faixa de áudio",
    "Switch subtitle": "Mudar legendas",
    "Switch to this list": "Mudar para esta lista",
    "Swop URL": "Swop URL",
    "saved on this device": "guardado neste dispositivo",
    select: "selecionar",
    small: "pequeno",
    system: "sistema",
    Tabox: "Tabox",
    "Tabox settings": "Configurações de Tabox",
    "The device ID in the address is invalid.":
        "O ID do dispositivo no endereço é inválido.",
    "This HTTPS player cannot connect to an HTTP server. Use an HTTPS server or open the player over HTTP.":
        "Este leitor HTTPS não pode ligar a um servidor HTTP. Use um servidor HTTPS ou abra o leitor por HTTP.",
    "This Play app requires HTTPS. Ask your provider for an HTTPS playlist or server URL.":
        "Esta aplicação Play exige HTTPS. Peça ao fornecedor uma lista ou URL de servidor HTTPS.",
    Timer: "Temporizador",
    "Timer: switch to channel?": "Temporizador: mudar para este canal?",
    "Timeshift: one minute back": "Timeshift: recuar um minuto",
    "Timeshift: to start of TV program": "Timeshift: início do programa",
    Timezone: "Fuso horário",
    TMDb: "TMDb",
    "TOP-IPTV": "TOP-IPTV",
    "TOP-IPTV settings": "Configurações de TOP-IPTV",
    "To begining": "Para o início",
    "To start of TV program / Previous TV program":
        "Início do programa / programa anterior",
    "Toggle Aspect Ratio": "Mudar proporção da imagem",
    "Toggle on-screen debug HUD": "Ativar ou desativar o painel de depuração",
    "Toggle Zoom Mode": "Mudar modo de zoom",
    "Top-Tv": "Top-Tv",
    "Top-Tv settings": "Configurações de Top-Tv",
    "Try demo": "Experimentar demonstração",
    "TV DOSUG": "TV DOSUG",
    "TV DOSUG settings": "Configurações de TV DOSUG",
    TVClub: "TVClub",
    "TVClub settings": "Configurações de TVClub",
    "Type of player for streaming": "Tipo de leitor para streaming",
    "top-left": "canto superior esquerdo",
    "top-right": "canto superior direito",
    transparent: "transparente",
    ULTIFL1X: "ULTIFL1X",
    "ULTIFL1X settings": "Configurações de ULTIFL1X",
    "Update installed. Please restart OttPlay FOSS.":
        "Atualização instalada. Reinicie o OttPlay FOSS.",
    "Use an HTTP or HTTPS server address.":
        "Use um endereço de servidor HTTP ou HTTPS.",
    "Use HTTP or HTTPS without a username or password in the address.":
        "Use HTTP ou HTTPS sem nome de utilizador nem palavra-passe no endereço.",
    "Use LEFT/RIGHT to select a control, OK to activate, and UP/DOWN to scroll.":
        "Use ESQUERDA/DIREITA para selecionar um controlo, OK para o ativar e CIMA/BAIXO para deslocar.",
    Username: "Nome de utilizador",
    "Username or password is missing.":
        "Falta o nome de utilizador ou a palavra-passe.",
    "VIP-IP.COM": "VIP-IP.COM",
    "VIP-IP.COM settings": "Configurações de VIP-IP.COM",
    "Vidok.TV": "Vidok.TV",
    "Vidok.TV settings": "Configurações de Vidok.TV",
    "VOD not supported by provider": "O fornecedor não suporta VOD",
    "Volume step, %": "Incremento de volume, %",
    "VPortal link": "Ligação VPortal",
    "VPortal request failed":
        "Não foi possível carregar o VPortal. Verifique a ligação, a chave de acesso e a disponibilidade do portal.",
    volume: "volume",
    "Wrong parental code !!!": "Código parental errado!!!",
    "Xtream Codes Provider": "Fornecedor Xtream Codes",
    "Xtream Codes settings": "Configurações Xtream Codes",
    Year: "Ano",
    Yellow: "Amarelo",
    Yes: "Sim",
    yes: "sim",
    "Гомельсат (cbilling)": "Гомельсат (cbilling)",
    "Гомельсат (cbilling) settings": "Configurações de Гомельсат (cbilling)",
    МойДом: "МойДом",
    "МойДом settings": "Configurações de МойДом",
    "Ошибка обработки списка каналов! Проверьте правильность данных!!":
        "Não foi possível processar a lista de canais. Verifique os dados do fornecedor!",
    Радуга: "Радуга",
    "Радуга settings": "Configurações de Радуга",
    "Редактирование ID": "Editar ID",
    "Редактирование PIN": "Editar PIN",
    Шаравоз: "Шаравоз",
    "Шаравоз settings": "Configurações de Шаравоз",
    "↑↓ Scroll": "↑↓ Deslocar",
};
