var keyStrings = {
    " (after changing, load playlist)":
        " (după modificare, încărcați playlistul)",
    " added to category ": " adăugat la categoria ",
    " added to favorites": " adăugat la favorite",
    "??? No channel name": "??? Fără nume de canal",
    Actions: "Acțiuni",
    "Add channel to category": "Adaugă canalul la categorie",
    "Add channel to favorites": "Adaugă canalul la favorite",
    All: "Toate",
    "Archive hours": "Ore de arhivă",
    alhabet: "aăâbcdefghiîjklmnopqrsștțuvwxyz",
    "Buffer Size, s": "Dimensiune buffer, s",
    "built-in": "încorporat",
    Category: "Categorie",
    "Channel ": "Canalul ",
    "Channel is not available!!!": "Canalul nu este disponibil!!!",
    "Channel list": "Lista canalelor",
    "Channel list not received !!!": "Lista de canale nu a fost primită!!!",
    "Channel list not received !!!<br/><br/>Enter the provider data and restart the player !!!<br/><br/>":
        "Lista de canale nu a fost primită!!!<br/><br/>Introduceți datele furnizorului și reporniți playerul!!!<br/><br/>",
    "Channel list. Category: ": "Lista canalelor. Categorie: ",
    "Channel parental control": "Control parental al canalului",
    Close: "Închide",
    "Delete channel": "Șterge canalul",
    Description: "Descriere",
    Edit: "Editează",
    "Edit category name": "Editează numele categoriei",
    "Edit playlist data": "Editează datele playlistului",
    Editor: "Editor",
    "Enter Media Library URL": "Introduceți URL-ul mediatecii",
    "Enter parental code": "Introduceți codul parental",
    "Enter playlist archive hours":
        "Introduceți orele de arhivă pentru playlist",
    "Enter playlist Name": "Introduceți numele playlistului",
    "Enter playlist URL": "Introduceți URL-ul playlistului",
    EPG: "Ghid TV",
    Exit: "Ieșire",
    "Failed to load channel list!": "Eșec la încărcarea listei de canale!",
    Favorites: "Favorite",
    Info: "Informații",
    Load: "Încarcă",
    "Load playlist": "Încarcă playlistul",
    lang: "Română",
    "Media Library URL": "URL mediatecă",
    Menu: "Meniu",
    "Move channel down": "Mută canalul în jos",
    "Move channel up": "Mută canalul în sus",
    "m3u-m3u8 playlists": "Playlisturi m3u-m3u8",
    min: "min",
    "No channel name": "Fără nume de canal",
    Nothing: "Nimic",
    native: "nativ",
    no: "nu",
    "Open in PiP": "Deschide în PiP",
    off: "dezactivat",
    Playlist: "Playlist",
    "Playlist file": "Fișier playlist",
    "Playlist is not loading directly...Loading via server...":
        "Playlistul nu se încarcă direct...Se încarcă prin server...",
    "Playlist Name": "Nume playlist",
    "Playlist URL": "URL playlist",
    "Save Settings": "Salvează setările",
    Search: "Căutare",
    "Select category to add channel":
        "Selectați categoria pentru a adăuga canalul",
    "Select playlist": "Selectați playlistul",
    "Select playlist file": "Selectați fișierul playlistului",
    Settings: "Setări",
    "Settings STB": "Setări STB",
    "Settings saved": "Setări salvate",
    "Stalker portals": "Portaluri Stalker",
    "Type of player for streaming": "Tipul de player pentru streaming",
    "Wrong parental code !!!": "Cod parental greșit!!!",
    yes: "da",
};
