var keyStrings = {
 "lang": "Română",
 "alhabet": "aăâbcdefghiîjklmnopqrsștțuvwxyz",
 "Channel list. Category: ": "Lista canalelor. Categorie: ",
 "EPG": "Ghid TV",
 "Category": "Categorie",
 "Actions": "Acțiuni",
 "Description": "Descriere",
 "Open in PiP": "Deschide în PiP",
 "Move channel up": "Mută canalul în sus",
 "Move channel down": "Mută canalul în jos",
 "Delete channel": "Șterge canalul",
 "Add channel to category": "Adaugă canalul la categorie",
 "Add channel to favorites": "Adaugă canalul la favorite",
 "Channel parental control": "Control parental al canalului",
 "Channel is not available!!!": "Canalul nu este disponibil!!!",
 "min": "min",
 "Channel ": "Canalul ",
 " added to category ": " adăugat la categoria ",
 " added to favorites": " adăugat la favorite",
 "Favorites": "Favorite",
 "Select category to add channel": "Selectați categoria pentru a adăuga canalul",
 "Enter parental code": "Introduceți codul parental",
 "Wrong parental code !!!": "Cod parental greșit!!!",
 "Close": "Închide",
 "Edit category name": "Editează numele categoriei",
 "Menu": "Meniu",
 "Channel list": "Lista canalelor",
 "Settings": "Setări",
 "Settings saved": "Setări salvate",
 "no": "nu",
 "yes": "da",
 "Info": "Informații",
 "Nothing": "Nimic",
 "Exit": "Ieșire",
 "off": "dezactivat",
 "Failed to load channel list!": "Eșec la încărcarea listei de canale!",
 "??? No channel name": "??? Fără nume de canal",
 "Playlist URL": "URL playlist",
 "Archive hours": "Ore de arhivă",
 "Enter playlist URL": "Introduceți URL-ul playlistului",
 "Playlist Name": "Nume playlist",
 "Enter playlist Name": "Introduceți numele playlistului",
 "Media Library URL": "URL mediatecă",
 "Enter Media Library URL": "Introduceți URL-ul mediatecii",
 "Playlist": "Playlist",
 "Playlist is not loading directly...Loading via server...": "Playlistul nu se încarcă direct...Se încarcă prin server...",
 "Select playlist": "Selectați playlistul",
 "Edit": "Editează",
 "Load": "Încarcă",
 "Edit playlist data": "Editează datele playlistului",
 "All": "Toate",
 "Search": "Căutare",
 "m3u-m3u8 playlists": "Playlisturi m3u-m3u8",
 "Stalker portals": "Portaluri Stalker",
 "Settings STB": "Setări STB",
 "Type of player for streaming": "Tipul de player pentru streaming",
 "Buffer Size, s": "Dimensiune buffer, s",
 "Save Settings": "Salvează setările",
 "Editor": "Editor",
 "built-in": "încorporat",
 "native": "nativ",
 "No channel name": "Fără nume de canal",
 " (after changing, load playlist)": " (după modificare, încărcați playlistul)",
 "Enter playlist archive hours": "Introduceți orele de arhivă pentru playlist",
 "Load playlist": "Încarcă playlistul",
 "Playlist file": "Fișier playlist",
 "Select playlist file": "Selectați fișierul playlistului",
 "Channel list not received !!!<br/><br/>Enter the provider data and restart the player !!!<br/><br/>": "Lista de canale nu a fost primită!!!<br/><br/>Introduceți datele furnizorului și reporniți playerul!!!<br/><br/>",
 "Channel list not received !!!": "Lista de canale nu a fost primită!!!"
};
