var keyStrings = {
    " (after changing, load playlist)":
        " (после изменения, загрузить плейлист)",
    " added to category ": " добавлен в категорию ",
    " added to favorites": " добавлен в избранные",
    "??? No channel name": "??? Нет названия канала",
    Actions: "Действия",
    "Active list": "Активный список",
    "Add / rename / delete…": "Добавить / переименовать / удалить…",
    "Add channel to category": "Добавить канал в категорию",
    "Add channel to favorites": "Добавить канал в избранные",
    "Add new list": "Новый список",
    All: "Все",
    "Archive hours": "Количество часов архива",
    alhabet: "абвгдеёжзийклмнопрстуфхцчшщъыьэюя",
    "Buffer Size, s": "Размер буфера, с",
    "built-in": "встроенный",
    Category: "Категории",
    "Channel ": "Канал ",
    "Channel is not available!!!": "Канал не доступен!!!",
    "Channel list": "Список каналов",
    "Channel list not received !!!": "Не получен список каналов!!!",
    "Channel list not received !!!<br/><br/>Enter the provider data and restart the player !!!<br/><br/>":
        "Не получен список каналов!!!<br/><br/>Введите данные провайдера и перезапустите плеер!!!<br/><br/>",
    "Channel list. Category: ": "Список каналов. Категория: ",
    "Channel parental control": "Родительский контроль канала",
    Close: "Закрыть",
    current: "текущий",
    "Delete channel": "Удалить канал",
    "Delete list": "Удалить список",
    Description: "Описание",
    Edit: "Редактировать",
    "Edit category name": "Редактирование названия категории",
    "Edit playlist data": "Редактирование данных плейлиста",
    Editor: "Редактор",
    English: "Английский",
    "Enter Media Library URL": "Ввод адреса медиатеки",
    "Enter parental code": "Введите родительский код",
    "Enter playlist archive hours":
        "Ввод количества часов архива для плейлиста",
    "Enter playlist Name": "Ввод названия плейлиста",
    "Enter playlist URL": "Ввод адреса плейлиста",
    EPG: "Программа",
    Exit: "Выход",
    "Failed to load channel list!": "Не удалось загрузить список каналов!",
    "Favorite lists": "Списки избранного",
    Favorites: "Избранные",
    Info: "Инфо",
    "List created": "Список создан",
    "List deleted": "Список удалён",
    "List renamed": "Список переименован",
    Load: "Загрузить",
    "Load playlist": "Загрузить плейлист",
    lang: "Русский",
    "Manage lists": "Управление списками",
    "Media Library URL": "Адрес медиатеки",
    Menu: "Меню",
    "Move channel down": "Передвинуть канал вниз",
    "Move channel up": "Передвинуть канал вверх",
    "m3u-m3u8 playlists": "m3u-m3u8 плейлисты",
    min: "минут",
    "New list name": "Имя нового списка",
    "No channel name": "Нет названия канала",
    Nothing: "Ничего",
    native: "родной",
    no: "нет",
    "Open in PiP": "Открыть в PiP",
    off: "отключен",
    Playlist: "Плейлист",
    "Playlist file": "Файл плейлиста",
    "Playlist is not loading directly...Loading via server...":
        "Плейлист не грузится напрямую...Загрузка через сервер...",
    "Playlist Name": "Название плейлиста",
    "Playlist URL": "Адрес плейлиста",
    "Rename to": "Переименовать в",
    Russian: "Русский",
    "Save Settings": "Сохранить настройки",
    Search: "Поиск",
    "Select category to add channel": "Выбор категории для добавления канала",
    "Select playlist": "Выберите плейлист",
    "Select playlist file": "Выбор файла плейлиста",
    Settings: "Настройки",
    "Settings STB": "Настройки устройства",
    "Settings saved": "Настройки сохранены",
    "Stalker portals": "Сталкер порталы",
    Switch: "Переключить",
    "Switch to this list": "Переключиться на этот список",
    "Type of player for streaming": "Тип плеера для воспроизведения",
    "Wrong parental code !!!": "Неверный родительский код !!!",
    yes: "да",
};
