var keyStrings = {
    " (after changing, load playlist)":
        " (после изменения, загрузить плейлист)",
    " added to category ": " добавлен в категорию ",
    " added to favorites": " добавлен в избранные",
    "??? No channel name": "??? Нет названия канала",
    "Access key": "Ключ доступа",
    "Access key is required!": "Необходимо ввести ключ доступа!",
    "Access settings": "Настройки доступа",
    Actions: "Действия",
    "Active list": "Активный список",
    "Add / rename / delete…": "Добавить / переименовать / удалить…",
    "Add channel to category": "Добавить канал в категорию",
    "Add channel to favorites": "Добавить канал в избранные",
    "Add new list": "Новый список",
    All: "Все",
    "Applying HTTP remote settings...": "Применение настроек HTTP-пульта...",
    "Archive hours": "Количество часов архива",
    alhabet: "абвгдеёжзийклмнопрстуфхцчшщъыьэюя",
    "and enter code": "и введите код",
    "Buffer Size, s": "Размер буфера, с",
    "built-in": "встроенный",
    Category: "Категории",
    "Channel ": "Канал ",
    "Channel is not available!!!": "Канал не доступен!!!",
    "Channel link": "Ссылка на канал",
    "Channel link is required!": "Необходимо ввести ссылку на канал!",
    "Channel list": "Список каналов",
    "Channel list not received !!!": "Не получен список каналов!!!",
    "Channel list not received !!!<br/><br/>Enter the provider data and restart the player !!!<br/><br/>":
        "Не получен список каналов!!!<br/><br/>Введите данные провайдера и перезапустите плеер!!!<br/><br/>",
    "Channel list. Category: ": "Список каналов. Категория: ",
    "Channel parental control": "Родительский контроль канала",
    Close: "Закрыть",
    "Could not update HTTP remote control.":
        "Не удалось изменить настройки HTTP-пульта.",
    current: "текущий",
    "Delete channel": "Удалить канал",
    "Delete list": "Удалить список",
    Description: "Описание",
    "Device access code": "Код доступа к устройству",
    "Disable HTTP remote": "Выключить HTTP-пульт",
    "Disabled by default. Enabling creates a new device access code.":
        "По умолчанию выключен. При включении создаётся новый код доступа к устройству.",
    Edit: "Редактировать",
    "Edit access key": "Редактирование ключа доступа",
    "Edit category name": "Редактирование названия категории",
    "Edit channel link": "Редактирование ссылки на канал",
    "Edit playlist data": "Редактирование данных плейлиста",
    "Edit VPortal link": "Редактирование ссылки VPortal",
    Editor: "Редактор",
    "Enable HTTP remote": "Включить HTTP-пульт",
    English: "Английский",
    "Enter access key for": "Ввод ключа доступа",
    "Enter Media Library URL": "Ввод адреса медиатеки",
    "Enter parental code": "Введите родительский код",
    "Enter playlist archive hours":
        "Ввод количества часов архива для плейлиста",
    "Enter playlist Name": "Ввод названия плейлиста",
    "Enter playlist URL": "Ввод адреса плейлиста",
    "Enter the full CDN host from the cabinet stream URL (e.g. subdomain.cdn-domain.tld), not a bare subdomain":
        "Введите полный хост CDN из URL потока в личном кабинете (например subdomain.cdn-domain.tld), не один поддомен",
    "Enter the VPortal link as shown in the cabinet":
        "Введите ссылку VPortal так как она выглядит в кабинете",
    EPG: "Программа",
    Exit: "Выход",
    "epg.one (Ordered)": "epg.one (Упорядоченный)",
    "epg.one (Standard)": "epg.one (Стандартный)",
    "epg.one (Thematic)": "epg.one (Тематический)",
    "Failed to load channel list!": "Не удалось загрузить список каналов!",
    "Favorite lists": "Списки избранного",
    Favorites: "Избранные",
    "For enter value open": "Для ввода значения откройте",
    "HTTP port": "HTTP-порт",
    "HTTP remote control is unavailable on this device.":
        "HTTP-пульт недоступен на этом устройстве.",
    Info: "Инфо",
    "Invalid channel link! Enter the full host as in the cabinet stream URL (e.g. subdomain.cdn-domain.tld)":
        "Некорректная ссылка на канал! Укажите полный хост как в URL потока в кабинете (например subdomain.cdn-domain.tld)",
    "List created": "Список создан",
    "List deleted": "Список удалён",
    "List renamed": "Список переименован",
    "List type": "Тип листа",
    Load: "Загрузить",
    "Load playlist": "Загрузить плейлист",
    "Local HTTP remote control": "Локальный HTTP-пульт",
    lang: "Русский",
    "Manage lists": "Управление списками",
    "Media Library URL": "Адрес медиатеки",
    Menu: "Меню",
    "Move channel down": "Передвинуть канал вниз",
    "Move channel up": "Передвинуть канал вверх",
    "m3u-m3u8 playlists": "m3u-m3u8 плейлисты",
    min: "минут",
    "New list name": "Имя нового списка",
    "No channel name": "Нет названия канала",
    Nothing: "Ничего",
    native: "родной",
    no: "нет",
    "Open in PiP": "Открыть в PiP",
    off: "отключен",
    on: "включен",
    Playlist: "Плейлист",
    "Playlist file": "Файл плейлиста",
    "Playlist is not loading directly...Loading via server...":
        "Плейлист не грузится напрямую...Загрузка через сервер...",
    "Playlist Name": "Название плейлиста",
    "Playlist URL": "Адрес плейлиста",
    "Remote control": "Удалённое управление",
    "Rename to": "Переименовать в",
    "Request sended!": "Запрос отправлен!",
    Russian: "Русский",
    "Save Settings": "Сохранить настройки",
    Search: "Поиск",
    "Select category to add channel": "Выбор категории для добавления канала",
    "Select playlist": "Выберите плейлист",
    "Select playlist file": "Выбор файла плейлиста",
    "Select playlist template source for EPG and logos":
        "Выберите источник шаблона плейлиста, EPG и логотипов",
    "Send this code from your proxy in the Authorization: Bearer header.":
        "Передавайте этот код из прокси в заголовке Authorization: Bearer.",
    Settings: "Настройки",
    "Settings STB": "Настройки устройства",
    "Settings saved": "Настройки сохранены",
    "Stalker portals": "Сталкер порталы",
    Switch: "Переключить",
    "Switch to this list": "Переключиться на этот список",
    "Type of player for streaming": "Тип плеера для воспроизведения",
    "VPortal link": "Ссылка VPortal",
    "Wrong parental code !!!": "Неверный родительский код !!!",
    yes: "да",
};
