var keyStrings = {
    " (after changing, load playlist)":
        " (después de cambiar, cargar la lista)",
    " added to category ": " añadido a la categoría ",
    " added to favorites": " añadido a favoritos",
    "??? No channel name": "??? Sin nombre de canal",
    Actions: "Acciones",
    "Add channel to category": "Añadir canal a categoría",
    "Add channel to favorites": "Añadir canal a favoritos",
    All: "Todos",
    "Applying HTTP remote settings...":
        "Aplicando los ajustes del control remoto HTTP...",
    "Archive hours": "Horas de archivo",
    alhabet: "aábcdeéfghiíjklmnñoópqrstuúüvwxyz",
    "Buffer Size, s": "Tamaño de búfer, s",
    "built-in": "integrado",
    Category: "Categoría",
    "Channel ": "Canal ",
    "Channel is not available!!!": "¡¡¡Canal no disponible!!!",
    "Channel list": "Lista de canales",
    "Channel list not received !!!": "¡¡¡Lista de canales no recibida!!!",
    "Channel list not received !!!<br/><br/>Enter the provider data and restart the player !!!<br/><br/>":
        "¡¡¡Lista de canales no recibida!!!<br/><br/>Introduzca los datos del proveedor y reinicie el reproductor!!!<br/><br/>",
    "Channel list. Category: ": "Lista de canales. Categoría: ",
    "Channel parental control": "Control parental del canal",
    Close: "Cerrar",
    "Could not update HTTP remote control.":
        "No se pudo actualizar el control remoto HTTP.",
    "Delete channel": "Eliminar canal",
    Description: "Descripción",
    "Device access code": "Código de acceso al dispositivo",
    "Disable HTTP remote": "Desactivar control HTTP",
    "Disabled by default. Enabling creates a new device access code.":
        "Desactivado de forma predeterminada. Al activarlo se genera un nuevo código de acceso al dispositivo.",
    Edit: "Editar",
    "Edit category name": "Editar nombre de categoría",
    "Edit playlist data": "Editar datos de la lista",
    Editor: "Editor",
    "Enable HTTP remote": "Activar control HTTP",
    "Enter Media Library URL": "Introducir URL de la mediateca",
    "Enter parental code": "Introducir código parental",
    "Enter playlist archive hours": "Introducir horas de archivo de la lista",
    "Enter playlist Name": "Introducir nombre de la lista",
    "Enter playlist URL": "Introducir URL de la lista",
    EPG: "Guía TV",
    Exit: "Salir",
    "Failed to load channel list!": "¡Error al cargar la lista de canales!",
    Favorites: "Favoritos",
    "HTTP port": "Puerto HTTP",
    "HTTP remote control is unavailable on this device.":
        "El control remoto HTTP no está disponible en este dispositivo.",
    Info: "Información",
    Load: "Cargar",
    "Load playlist": "Cargar lista",
    "Local HTTP remote control": "Control remoto HTTP local",
    lang: "Español",
    "Media Library URL": "URL de la mediateca",
    Menu: "Menú",
    "Move channel down": "Mover canal abajo",
    "Move channel up": "Mover canal arriba",
    "m3u-m3u8 playlists": "Listas m3u-m3u8",
    min: "min",
    "No channel name": "Sin nombre de canal",
    Nothing: "Nada",
    native: "nativo",
    no: "no",
    "Open in PiP": "Abrir en PiP",
    off: "desactivado",
    on: "activado",
    Playlist: "Lista de reproducción",
    "Playlist file": "Archivo de lista",
    "Playlist is not loading directly...Loading via server...":
        "La lista no se carga directamente...Cargando a través del servidor...",
    "Playlist Name": "Nombre de la lista",
    "Playlist URL": "URL de la lista",
    "Remote control": "Control remoto",
    "Save Settings": "Guardar ajustes",
    Search: "Buscar",
    "Select category to add channel": "Seleccionar categoría para añadir canal",
    "Select playlist": "Seleccionar lista",
    "Select playlist file": "Seleccionar archivo de lista",
    "Send this code from your proxy in the Authorization: Bearer header.":
        "Envía este código desde tu proxy en la cabecera Authorization: Bearer.",
    Settings: "Ajustes",
    "Settings STB": "Ajustes del STB",
    "Settings saved": "Ajustes guardados",
    "Stalker portals": "Portales Stalker",
    "Type of player for streaming": "Tipo de reproductor para streaming",
    "Wrong parental code !!!": "¡¡¡Código parental incorrecto!!!",
    yes: "sí",
};
