var keyStrings = {
    lang: "Español",
    alhabet: "aábcdeéfghiíjklmnñoópqrstuúüvwxyz",
    "Channel list. Category: ": "Lista de canales. Categoría: ",
    EPG: "Guía TV",
    Category: "Categoría",
    Actions: "Acciones",
    Description: "Descripción",
    "Open in PiP": "Abrir en PiP",
    "Move channel up": "Mover canal arriba",
    "Move channel down": "Mover canal abajo",
    "Delete channel": "Eliminar canal",
    "Add channel to category": "Añadir canal a categoría",
    "Add channel to favorites": "Añadir canal a favoritos",
    "Channel parental control": "Control parental del canal",
    "Channel is not available!!!": "¡¡¡Canal no disponible!!!",
    min: "min",
    "Channel ": "Canal ",
    " added to category ": " añadido a la categoría ",
    " added to favorites": " añadido a favoritos",
    Favorites: "Favoritos",
    "Select category to add channel": "Seleccionar categoría para añadir canal",
    "Enter parental code": "Introducir código parental",
    "Wrong parental code !!!": "¡¡¡Código parental incorrecto!!!",
    Close: "Cerrar",
    "Edit category name": "Editar nombre de categoría",
    Menu: "Menú",
    "Channel list": "Lista de canales",
    Settings: "Ajustes",
    "Settings saved": "Ajustes guardados",
    no: "no",
    yes: "sí",
    Info: "Información",
    Nothing: "Nada",
    Exit: "Salir",
    off: "desactivado",
    "Failed to load channel list!": "¡Error al cargar la lista de canales!",
    "??? No channel name": "??? Sin nombre de canal",
    "Playlist URL": "URL de la lista",
    "Archive hours": "Horas de archivo",
    "Enter playlist URL": "Introducir URL de la lista",
    "Playlist Name": "Nombre de la lista",
    "Enter playlist Name": "Introducir nombre de la lista",
    "Media Library URL": "URL de la mediateca",
    "Enter Media Library URL": "Introducir URL de la mediateca",
    Playlist: "Lista de reproducción",
    "Playlist is not loading directly...Loading via server...":
        "La lista no se carga directamente...Cargando a través del servidor...",
    "Select playlist": "Seleccionar lista",
    Edit: "Editar",
    Load: "Cargar",
    "Edit playlist data": "Editar datos de la lista",
    All: "Todos",
    Search: "Buscar",
    "m3u-m3u8 playlists": "Listas m3u-m3u8",
    "Stalker portals": "Portales Stalker",
    "Settings STB": "Ajustes del STB",
    "Type of player for streaming": "Tipo de reproductor para streaming",
    "Buffer Size, s": "Tamaño de búfer, s",
    "Save Settings": "Guardar ajustes",
    Editor: "Editor",
    "built-in": "integrado",
    native: "nativo",
    "No channel name": "Sin nombre de canal",
    " (after changing, load playlist)":
        " (después de cambiar, cargar la lista)",
    "Enter playlist archive hours": "Introducir horas de archivo de la lista",
    "Load playlist": "Cargar lista",
    "Playlist file": "Archivo de lista",
    "Select playlist file": "Seleccionar archivo de lista",
    "Channel list not received !!!<br/><br/>Enter the provider data and restart the player !!!<br/><br/>":
        "¡¡¡Lista de canales no recibida!!!<br/><br/>Introduzca los datos del proveedor y reinicie el reproductor!!!<br/><br/>",
    "Channel list not received !!!": "¡¡¡Lista de canales no recibida!!!",
};
