var keyStrings = {
    " (after changing, load playlist)":
        " (läs in spellistan igen efter ändring)",
    " (after changing, restart player)": " (starta om spelaren efter ändring)",
    " added to category ": " lades till i kategorin ",
    " added to favorites": " lades till i favoriter",
    " m ": " min ",
    " s": " s",
    "??? No channel name": "??? Kanalnamn saknas",
    '"As Is"': "”Oförändrat”",
    '"Favorites"': "”Favoriter”",
    '"Sliding" infobar': "Glidande informationsfält",
    "&darr;a": "&darr;a",
    "&uarr;A": "&uarr;A",
    "<br/><br/>In archive mode:<br/>": "<br/><br/>I arkivläge:<br/>",
    "<br/>Loading STB...": "<br/>Läser in enheten…",
    "<br/>Setup STB...": "<br/>Konfigurerar enheten…",
    "<br>": "<br>",
    "<br><br>": "<br><br>",
    "<br>Add<br>to category": "<br>Lägg till<br>i kategori",
    "<br>Add<br>to favorites": "<br>Lägg till<br>i favoriter",
    "<br>Delete": "<br>Ta bort",
    "<br>Down<br>": "<br>Ned<br>",
    "<br>Live": "<br>Direktsändning",
    "<br>Menu": "<br>Meny",
    "<br>Parental<br>Control": "<br>Föräldra-<br>kontroll",
    "<br>Pause<br>": "<br>Paus<br>",
    "<br>Previous<br>channel": "<br>Föregående<br>kanal",
    "<br>Rewind<br>": "<br>Spola<br>",
    "<br>Toggle<br>sound track": "<br>Byt<br>ljudspår",
    "<br>Up<br>": "<br>Upp<br>",
    "1 hour": "1 timme",
    "1 minute": "1 minut",
    "2 hours": "2 timmar",
    "3 hours": "3 timmar",
    "10 Seconds": "10 sekunder",
    "30 minutes": "30 minuter",
    "A command expired while the player was loading channels.":
        "Ett kommando gick ut medan spelaren läste in kanaler.",
    "A command was rejected by the player. Check its provider and settings.":
        "Spelaren avvisade ett kommando. Kontrollera leverantör och inställningar.",
    About: "Om",
    "Access code": "Åtkomstkod",
    "Access denied. Check the server access code.":
        "Åtkomst nekad. Kontrollera serverns åtkomstkod.",
    "Access key": "Åtkomstnyckel",
    "Access key is required!": "Åtkomstnyckel krävs!",
    "Access settings": "Åtkomstinställningar",
    Actions: "Åtgärder",
    "Active list": "Aktiv lista",
    Actors: "Skådespelare",
    "Add / rename / delete…": "Lägg till / byt namn / ta bort…",
    "Add channel to category": "Lägg till kanal i kategori",
    "Add channel to favorites": "Lägg till kanal i favoriter",
    "Add new list": "Lägg till ny lista",
    "Add to favorites": "Lägg till i favoriter",
    Age: "Ålder",
    All: "Alla",
    "All categories": "Alla kategorier",
    "All4you.tv": "All4you.tv",
    "All4you.tv settings": "All4you.tv-inställningar",
    "Allowlist this Device ID": "Tillåt detta enhets-ID",
    "An IP without a port uses HTTP port 8081. Clear the address or select Disconnect to stop.":
        "En IP-adress utan port använder HTTP-port 8081. Rensa adressen eller välj Koppla från för att stoppa.",
    "API failed, trying M3U...": "API misslyckades, försöker med M3U…",
    "API Server": "API-server",
    "API server URL": "API-serverns URL",
    "Applying HTTP remote settings...":
        "Tillämpar inställningar för HTTP-fjärrkontroll…",
    Archive: "Arkiv",
    "Archive - begin": "Arkiv — början",
    "Archive hours": "Arkivtimmar",
    "Archive: ENTER on past programs": "Arkiv: ENTER på tidigare program",
    "Archive. Channel: ": "Arkiv. Kanal: ",
    Aspect: "Bildförhållande",
    Audio: "Ljud",
    alhabet: "aàbcdeéfghijklmnopqrstuvwxyzåäö",
    always: "alltid",
    "and enter code": "och ange koden",
    Back: "Tillbaka",
    "Back / Forward for 1 minute": "Bakåt / framåt 1 minut",
    "Background color": "Bakgrundsfärg",
    "Background color of selected item": "Bakgrundsfärg för valt objekt",
    "BEST LiST IPTV [HLS Playlist]": "BEST LiST IPTV [HLS Playlist]",
    "BEST LiST IPTV [HLS Playlist] settings":
        "BEST LiST IPTV [HLS Playlist]-inställningar",
    "BEST LiST IPTV [Stalker]": "BEST LiST IPTV [Stalker]",
    "BEST LiST IPTV [Stalker] settings":
        "BEST LiST IPTV [Stalker]-inställningar",
    "Behavior of %1/%2 buttons in lists":
        "Funktion för knapparna %1/%2 i listor",
    "Black screen while switching the channel": "Svart skärm vid kanalbyte",
    Blue: "Blå",
    "Bookmark age: %1 days": "Bokmärkets ålder: %1 dagar",
    "Buffer Size, s": "Buffertstorlek, s",
    "Built-in playlist:": "Inbyggd spellista:",
    "Built-in playlists": "Inbyggda spellistor",
    "Button %1 function when viewing": "Funktion för knapp %1 vid visning",
    "Button function %1 when viewing archive":
        "Funktion för knapp %1 vid arkivvisning",
    "Buttons settings": "Knappinställningar",
    "By alphabet": "Alfabetiskt",
    "By time": "Efter tid",
    "begin/end": "början/slut",
    "bottom-right": "nedre höger",
    "built-in": "inbyggd",
    "Call PiP": "Öppna PiP",
    "Call PiP / PiP exchange": "Öppna PiP / växla PiP",
    Cancel: "Avbryt",
    "Cannot delete the last category": "Den sista kategorin kan inte tas bort",
    Category: "Kategori",
    "Category selection": "Välj kategori",
    "Change interface language": "Byt gränssnittsspråk",
    "Change provider": "Byt leverantör",
    "Change provider - you can change the provider, and it will be remembered at the next start of player!":
        "Byt leverantör. Ditt val sparas till nästa gång spelaren startas.",
    "Change value": "Ändra värde",
    "Channel ": "Kanal ",
    "Channel has no EPG": "Kanalen saknar programguide",
    "Channel is not available!!!": "Kanalen är inte tillgänglig!",
    "Channel link": "Kanallänk",
    "Channel link is required!": "Kanallänk krävs!",
    "Channel list": "Kanallista",
    "Channel list editing style": "Redigeringsläge för kanallista",
    "Channel list not received !!!": "Kanallistan kunde inte hämtas!",
    "Channel list not received !!!<br/><br/>Enter the provider data and restart the player !!!<br/><br/>":
        "Kanallistan kunde inte hämtas!<br/><br/>Ange leverantörens uppgifter och starta om spelaren.<br/><br/>",
    "Channel list settings": "Inställningar för kanallista",
    "Channel list. Category: ": "Kanallista. Kategori: ",
    "Channel parental control": "Föräldrakontroll för kanal",
    Channels: "Kanaler",
    "Choose from": "Välj från",
    "Choose language": "Välj språk",
    "Choose provider": "Välj leverantör",
    Classic: "Klassisk",
    "Clear all settings?": "Rensa alla inställningar?",
    "Clear settings": "Rensa inställningar",
    Close: "Stäng",
    "Close PiP": "Stäng PiP",
    Color: "Färg",
    "Color spectrum": "Färgpalett",
    "Command server": "Kommandoserver",
    "Command server address, device access code, local HTTP control, and remote text entry settings":
        "Kommandoserverns adress, enhetens åtkomstkod, lokal HTTP-styrning och fjärrinmatning av text",
    "Configure All4you.tv in Settings -> Provider Settings":
        "Konfigurera All4you.tv under Inställningar -> Leverantörsinställningar",
    "Configure BEST LiST IPTV [HLS Playlist] in Settings -> Provider Settings":
        "Konfigurera BEST LiST IPTV [HLS Playlist] under Inställningar -> Leverantörsinställningar",
    "Configure BEST LiST IPTV [Stalker] in Settings -> Provider Settings":
        "Konfigurera BEST LiST IPTV [Stalker] under Inställningar -> Leverantörsinställningar",
    "Configure Diamond TV in Settings -> Provider Settings":
        "Konfigurera Diamond TV under Inställningar -> Leverantörsinställningar",
    "Configure DRVAO in Settings -> Provider Settings":
        "Konfigurera DRVAO under Inställningar -> Leverantörsinställningar",
    "Configure Dragon Media PRO in Settings -> Provider Settings":
        "Konfigurera Dragon Media PRO under Inställningar -> Leverantörsinställningar",
    "Configure Fabryka.TV in Settings -> Provider Settings":
        "Konfigurera Fabryka.TV under Inställningar -> Leverantörsinställningar",
    "Configure Fox-TV in Settings -> Provider Settings":
        "Konfigurera Fox-TV under Inställningar -> Leverantörsinställningar",
    "Configure FXML in Settings -> Provider Settings":
        "Konfigurera FXML under Inställningar -> Leverantörsinställningar",
    "Configure GlanzTV in Settings -> Provider Settings":
        "Konfigurera GlanzTV under Inställningar -> Leverantörsinställningar",
    "Configure GREAT IPTV in Settings -> Provider Settings":
        "Konfigurera GREAT IPTV under Inställningar -> Leverantörsinställningar",
    "Configure IpStream.one in Settings -> Provider Settings":
        "Konfigurera IpStream.one under Inställningar -> Leverantörsinställningar",
    "Configure KORONA TV in Settings -> Provider Settings":
        "Konfigurera KORONA TV under Inställningar -> Leverantörsinställningar",
    "Configure MaxTV in Settings -> Provider Settings":
        "Konfigurera MaxTV under Inställningar -> Leverantörsinställningar",
    "Configure New Look in Settings -> Provider Settings":
        "Konfigurera New Look under Inställningar -> Leverantörsinställningar",
    "Configure OTT Prime ONLINE in Settings -> Provider Settings":
        "Konfigurera OTT Prime ONLINE under Inställningar -> Leverantörsinställningar",
    "Configure POLMEDIA in Settings -> Provider Settings":
        "Konfigurera POLMEDIA under Inställningar -> Leverantörsinställningar",
    "Configure PROST in Settings -> Provider Settings":
        "Konfigurera PROST under Inställningar -> Leverantörsinställningar",
    "Configure RD in Settings -> Provider Settings":
        "Konfigurera RD under Inställningar -> Leverantörsinställningar",
    "Configure RUSSKOETV in Settings -> Provider Settings":
        "Konfigurera RUSSKOETV under Inställningar -> Leverantörsinställningar",
    "Configure Shara.club (ClubTV.pro) in Settings -> Provider Settings":
        "Konfigurera Shara.club (ClubTV.pro) under Inställningar -> Leverantörsinställningar",
    "Configure ShockTv in Settings -> Provider Settings":
        "Konfigurera ShockTv under Inställningar -> Leverantörsinställningar",
    "Configure Tabox in Settings -> Provider Settings":
        "Konfigurera Tabox under Inställningar -> Leverantörsinställningar",
    "Configure TOP-IPTV in Settings -> Provider Settings":
        "Konfigurera TOP-IPTV under Inställningar -> Leverantörsinställningar",
    "Configure Top-Tv in Settings -> Provider Settings":
        "Konfigurera Top-Tv under Inställningar -> Leverantörsinställningar",
    "Configure TV DOSUG in Settings -> Provider Settings":
        "Konfigurera TV DOSUG under Inställningar -> Leverantörsinställningar",
    "Configure TVClub in Settings -> Provider Settings":
        "Konfigurera TVClub under Inställningar -> Leverantörsinställningar",
    "Configure ULTIFL1X in Settings -> Provider Settings":
        "Konfigurera ULTIFL1X under Inställningar -> Leverantörsinställningar",
    "Configure VIP-IP.COM in Settings -> Provider Settings":
        "Konfigurera VIP-IP.COM under Inställningar -> Leverantörsinställningar",
    "Configure Vidok.TV in Settings -> Provider Settings":
        "Konfigurera Vidok.TV under Inställningar -> Leverantörsinställningar",
    "Configure Гомельсат (cbilling) in Settings -> Provider Settings":
        "Konfigurera Гомельсат (cbilling) under Inställningar -> Leverantörsinställningar",
    "Configure МойДом in Settings -> Provider Settings":
        "Konfigurera МойДом under Inställningar -> Leverantörsinställningar",
    "Configure Радуга in Settings -> Provider Settings":
        "Konfigurera Радуга under Inställningar -> Leverantörsinställningar",
    "Configure Шаравоз in Settings -> Provider Settings":
        "Konfigurera Шаравоз under Inställningar -> Leverantörsinställningar",
    Connect: "Anslut",
    Connected: "Ansluten",
    "Connected. Waiting for the channel list...":
        "Ansluten. Väntar på kanallistan…",
    "Connecting to Stalker portal...": "Ansluter till Stalker-portalen…",
    "Connecting...": "Ansluter…",
    "Continue watching?": "Fortsätta titta?",
    "Copy category": "Kopiera kategori",
    "Copy JSON": "Kopiera JSON",
    "Could not connect to the server.": "Kunde inte ansluta till servern.",
    "Could not update HTTP remote control.":
        "Kunde inte uppdatera HTTP-fjärrkontrollen.",
    Country: "Land",
    "Create category": "Skapa kategori",
    current: "aktuell",
    "Debug HUD": "Felsökningspanel",
    "Debug HUD is not available": "Felsökningspanelen är inte tillgänglig",
    Delete: "Ta bort",
    "Delete category": "Ta bort kategori",
    "Delete channel": "Ta bort kanal",
    "Delete list": "Ta bort lista",
    "Demo — moving test pattern": "Demo — rörlig testbild",
    Description: "Beskrivning",
    "Description of remote control buttons":
        "Guide till fjärrkontrollens knappar",
    "Device access code": "Enhetens åtkomstkod",
    "Device info:": "Enhetsinformation:",
    "Device MAC is required for KBC (Kinoboom) playlists":
        "Enhetens MAC-adress krävs för KBC-spellistor (Kinoboom)",
    "Diamond TV": "Diamond TV",
    "Diamond TV settings": "Diamond TV-inställningar",
    Director: "Regissör",
    "Disable HTTP remote": "Inaktivera HTTP-fjärrkontroll",
    "Disabled by default. Enabling creates a new device access code.":
        "Inaktiverat som standard. Aktivering skapar en ny åtkomstkod för enheten.",
    Disconnect: "Koppla från",
    Disconnected: "Frånkopplad",
    "Distance between lines in lists": "Radavstånd i listor",
    "Do you want to exit player?": "Vill du avsluta spelaren?",
    "Download! Wait ...": "Laddar ned… vänta…",
    DRVAO: "DRVAO",
    "DRVAO settings": "DRVAO-inställningar",
    "Dragon Media PRO": "Dragon Media PRO",
    "Dragon Media PRO settings": "Dragon Media PRO-inställningar",
    Duration: "Längd",
    Edit: "Redigera",
    "Edit access key": "Redigera åtkomstnyckel",
    "Edit category name": "Redigera kategorinamn",
    "Edit channel link": "Redigera kanallänk",
    "Edit playlist data": "Redigera spellistans uppgifter",
    "Edit VPortal link": "Redigera VPortal-länk",
    Editor: "Redigerare",
    "Enable HTTP remote": "Aktivera HTTP-fjärrkontroll",
    English: "Engelska",
    "Enter a password (8 characters).": "Ange ett lösenord (8 tecken).",
    "Enter a playlist URL to access this service.":
        "Ange en spelliste-URL för att använda tjänsten.",
    "Enter a server address without spaces or a fragment.":
        "Ange en serveradress utan blanksteg eller fragment efter #.",
    "Enter a username (8 characters).": "Ange ett användarnamn (8 tecken).",
    "Enter a username and password to access this service.":
        "Ange användarnamn och lösenord för att använda tjänsten.",
    "Enter a valid server address, for example 192.168.1.20:8081.":
        "Ange en giltig serveradress, t.ex. 192.168.1.20:8081.",
    "Enter access key for": "Ange åtkomstnyckel för",
    "Enter an application access key (8 characters).":
        "Ange programmets åtkomstnyckel (8 tecken).",
    "Enter an ID and PIN to access this service.":
        "Ange ID och PIN för att använda tjänsten.",
    "Enter an IPTV token (10 characters).": "Ange en IPTV-token (10 tecken).",
    "Enter category name": "Ange kategorinamn",
    "Enter MAC address": "Ange MAC-adress",
    "Enter MAC address (e.g. 00:1A:2B:3C:4D:5E)":
        "Ange MAC-adress (t.ex. 00:1A:2B:3C:4D:5E)",
    "Enter Media Library URL": "Ange mediebibliotekets URL",
    "Enter new category name": "Ange nytt kategorinamn",
    "Enter Provider Code": "Ange leverantörskod",
    "Enter Provider Code on PC or Phone":
        "Ange leverantörskod på dator eller telefon",
    "Enter parental code": "Ange föräldrakod",
    "Enter password": "Ange lösenord",
    "Enter playlist archive hours": "Ange antal arkivtimmar för spellistan",
    "Enter playlist Name": "Ange spellistans namn",
    "Enter playlist URL": "Ange spellistans URL",
    "Enter Stalker portal URL": "Ange Stalker-portalens URL",
    "Enter Stalker portal URL (e.g. http://your-portal:8800)":
        "Ange Stalker-portalens URL (t.ex. http://your-portal:8800)",
    "Enter Stalker portal URL (e.g. http://your-portal/stalker_portal/c/)":
        "Ange Stalker-portalens URL (t.ex. http://your-portal/stalker_portal/c/)",
    "Enter the access code separately, not in the server address.":
        "Ange åtkomstkoden separat från serveradressen.",
    "Enter the command server IP or address.":
        "Ange kommandoserverns IP-adress eller adress.",
    "Enter the full CDN host from the cabinet stream URL (e.g. subdomain.cdn-domain.tld), not a bare subdomain":
        "Ange det fullständiga CDN-värdnamnet från strömmens URL på kundkontot (t.ex. subdomain.cdn-domain.tld), inte bara underdomänen",
    "Enter the server IP or address and this player's device access code from the server configuration. Saving both starts checking for volume, channel and other commands automatically.":
        "Ange serverns IP-adress eller adress och spelarens åtkomstkod från serverkonfigurationen. När båda sparas börjar spelaren automatiskt söka efter volym-, kanal- och andra kommandon.",
    "Enter the server's device access code (32–256 letters, digits, _ or -).":
        "Ange enhetens åtkomstkod från servern (32–256 bokstäver, siffror, _ eller -).",
    'Enter the tv.team playlist URL.<br>Playlist type: <b>OTTPlayer</b><br/><br/>The "/playlist.m3u8" suffix is added automatically if omitted.':
        'Ange tv.team-spellistans URL.<br>Spellistetyp: <b>OTTPlayer</b><br/><br/>Ändelsen "/playlist.m3u8" läggs till automatiskt om den saknas.',
    "Enter the VPortal link as shown in the cabinet":
        "Ange VPortal-länken som visas på ditt kundkonto",
    "Enter this link in VPortal link. Playlist URL requires an M3U playlist.":
        "Ange denna länk i VPortal-fältet. Spellistans URL måste leda till en M3U-spellista.",
    "Enter this player's device access code to connect.":
        "Ange spelarens åtkomstkod för att ansluta.",
    "Enter username": "Ange användarnamn",
    "Enter value": "Ange värde",
    "Enter Xtream server URL": "Ange Xtream-serverns URL",
    "Enter Xtream server URL (e.g. https://your-server:8080)":
        "Ange Xtream-serverns URL (t.ex. https://your-server:8080)",
    EPG: "Programguide",
    "EPG and archive. Channel: ": "Programguide och arkiv. Kanal: ",
    "ERROR!": "Fel!",
    "Error Code!": "Ogiltig kod!",
    Exit: "Avsluta",
    "Exit player": "Avsluta spelaren",
    "Export settings": "Exportera inställningar",
    "epg.one (Ordered)": "epg.one (Ordnad)",
    "epg.one (Standard)": "epg.one (Standard)",
    "epg.one (Thematic)": "epg.one (Tematisk)",
    "epgs...": "Programguider…",
    "Fabryka.TV": "Fabryka.TV",
    "Fabryka.TV settings": "Fabryka.TV-inställningar",
    "Failed to connect to Stalker portal":
        "Kunde inte ansluta till Stalker-portalen",
    "Failed to connect to Xtream API server":
        "Kunde inte ansluta till Xtream API-servern",
    "Failed to get user data!!!": "Kunde inte hämta användaruppgifter!",
    "Failed to load channel list!": "Kunde inte läsa in kanallistan!",
    "Failed to load channels from Stalker portal":
        "Kunde inte läsa in kanaler från Stalker-portalen",
    "Failed to load channels from Xtream API":
        "Kunde inte läsa in kanaler från Xtream API",
    "Failed to load!": "Kunde inte läsa in!",
    "Favorite lists": "Favoritlistor",
    Favorites: "Favoriter",
    "File selection is not supported on this device":
        "Filval stöds inte på den här enheten",
    Filters: "Filter",
    "First Run Setup": "Förstagångsinställning",
    "Font type": "Typsnitt",
    "For download settings file open":
        "För att ladda ned inställningsfilen, öppna",
    "For enter value open": "För att ange ett värde, öppna",
    "For upload settings file open":
        "För att ladda upp inställningsfilen, öppna",
    "Fox-TV": "Fox-TV",
    "Fox-TV settings": "Fox-TV-inställningar",
    FXML: "FXML",
    "FXML settings": "FXML-inställningar",
    Genre: "Genre",
    GlanzTV: "GlanzTV",
    "GlanzTV settings": "GlanzTV-inställningar",
    "Go to": "Gå till",
    "GREAT IPTV": "GREAT IPTV",
    "GREAT IPTV settings": "GREAT IPTV-inställningar",
    "Graphical indication": "Grafiska indikatorer",
    Green: "Grön",
    "Hide / Return": "Dölj / visa",
    "Hide provider settings?": "Dölja leverantörsinställningar?",
    "Hide providers?": "Dölja leverantörer?",
    "History in Media Library": "Historik i mediebiblioteket",
    "History of watched movies": "Visningshistorik",
    "HTTP port": "HTTP-port",
    "HTTP remote control is unavailable on this device.":
        "HTTP-fjärrkontroll är inte tillgänglig på den här enheten.",
    ID: "ID",
    "Import settings": "Importera inställningar",
    "In live mode: <br/>": "Vid direktsändning:<br/>",
    Info: "Info",
    "Infobar display timeout, s": "Visningstid för informationsfält, s",
    "Infobar settings": "Inställningar för informationsfält",
    Information: "Information",
    "Interface credits": "Gränssnittets upphovspersoner",
    "Interface settings": "Gränssnittsinställningar",
    "Interface theme": "Gränssnittstema",
    "Interface transparency": "Gränssnittets genomskinlighet",
    "Invalid channel link! Enter the full host as in the cabinet stream URL (e.g. subdomain.cdn-domain.tld)":
        "Ogiltig kanallänk! Ange hela värdnamnet från strömmens URL på kundkontot (t.ex. subdomain.cdn-domain.tld)",
    "IPTV token": "IPTV-token",
    "IpStream.one": "IpStream.one",
    "IpStream.one settings": "IpStream.one-inställningar",
    Joystick: "Styrspak",
    "KBC (Kinoboom) access data": "Åtkomstuppgifter för KBC (Kinoboom)",
    "KORONA TV": "KORONA TV",
    "KORONA TV settings": "KORONA TV-inställningar",
    "List created": "Listan skapades",
    "List deleted": "Listan togs bort",
    "List location": "Listans placering",
    "List renamed": "Listans namn ändrades",
    "List type": "Listtyp",
    "Lists settings": "Listinställningar",
    Live: "Direktsändning",
    Load: "Läs in",
    "Load built-in playlist:": "Läs in inbyggd spellista:",
    "Load playlist": "Läs in spellista",
    "Load settings": "Läs in inställningar",
    "Load settings from storage": "Läs in inställningar från lagring",
    "Load:": "Läs in:",
    "Loading channels from Xtream API...": "Läser in kanaler från Xtream API…",
    "Loading channels...": "Läser in kanaler…",
    "Loading from API...": "Läser in via API…",
    "Loading from Edem API...": "Läser in från Edem API…",
    "Loading M3U playlist...": "Läser in M3U-spellista…",
    "Loading M3U...": "Läser in M3U…",
    "Loading via proxy...": "Läser in via proxy…",
    "Loading. Please wait...": "Läser in. Vänta…",
    "Loading...": "Läser in…",
    "Local HTTP remote control": "Lokal HTTP-fjärrkontroll",
    "Local URL": "Lokal URL",
    Login: "Inloggningsnamn",
    lang: "Svenska",
    large: "stor",
    left: "vänster",
    "left-bottom": "nedre vänster",
    "logos...": "Logotyper…",
    M3U: "M3U",
    "M3U URL": "M3U-URL",
    "M3U URL (fallback)": "M3U-URL (reserv)",
    "MAC address": "MAC-adress",
    "Manage lists": "Hantera listor",
    "Manage settings": "Hantera inställningar",
    "Manual setup": "Manuell inställning",
    MaxTV: "MaxTV",
    "MaxTV settings": "MaxTV-inställningar",
    Media: "Media",
    "Media item is no longer available":
        "Det här medieinnehållet är inte längre tillgängligt",
    "Media Library": "Mediebibliotek",
    "Media Library URL": "Mediebibliotekets URL",
    Menu: "Meny",
    "Menu items settings": "Inställningar för menyalternativ",
    "Move category down": "Flytta kategori nedåt",
    "Move category up": "Flytta kategori uppåt",
    "Move channel down": "Flytta kanal nedåt",
    "Move channel up": "Flytta kanal uppåt",
    "m3u-m3u8 playlists": "M3U- / M3U8-spellistor",
    medium: "mellan",
    min: "min",
    "New Look": "New Look",
    "New Look settings": "New Look-inställningar",
    "New list name": "Namn på ny lista",
    Next: "Nästa sida",
    "Next keyboard page": "Nästa tangentbordssida",
    "Next TV program": "Nästa program",
    No: "Nej",
    "No channel name": "Kanalnamn saknas",
    "No saved settings found": "Inga sparade inställningar hittades",
    "Not found": "Hittades inte",
    "Not reduce video when showing the list (bugfix)":
        "Förminska inte videon när listan visas (felkorrigering)",
    Nothing: "Ingenting",
    "Number of next TV programs in channel list":
        "Antal kommande program i kanallistan",
    "Number of rows in lists": "Antal rader i listor",
    native: "systemets",
    no: "nej",
    "no epg at current time": "Ingen programguide för aktuell tid",
    "not set": "inte inställt",
    Off: "Av",
    Ok: "OK",
    Open: "Öppna",
    "Open in PiP": "Öppna i PiP",
    "OTT Prime ONLINE": "OTT Prime ONLINE",
    "OTT Prime ONLINE settings": "OTT Prime ONLINE-inställningar",
    "OttPlay FOSS %1 is available. Download and install now?":
        "OttPlay FOSS %1 är tillgängligt. Ladda ned och installera nu?",
    "Overwrite current settings?": "Skriva över aktuella inställningar?",
    off: "av",
    on: "på",
    "on ": "vid ",
    "or scan": "eller skanna",
    "Parental control": "Föräldrakontroll",
    Password: "Lösenord",
    Pause: "Paus",
    "Pause/Play": "Paus / spela",
    "Permanent clock on screen": "Visa alltid klocka på skärmen",
    PIN: "PIN",
    "PiP exchange": "Växla PiP-fönster",
    "PiP window position": "PiP-fönstrets placering",
    "PiP window size": "PiP-fönstrets storlek",
    Play: "Spela",
    "Player and device info": "Spelar- och enhetsinformation",
    "Player info:": "Spelarinformation:",
    Playlist: "Spellista",
    "Playlist file": "Spellistefil",
    "Playlist is not loading directly...Loading via server...":
        "Spellistan kunde inte läsas in direkt. Läser in via server…",
    "Playlist Name": "Spellistans namn",
    "Playlist URL": "Spellistans URL",
    POLMEDIA: "POLMEDIA",
    "POLMEDIA settings": "POLMEDIA-inställningar",
    "Portal URL": "Portalens URL",
    "Position shift -10 seconds after pause":
        "Hoppa tillbaka 10 sekunder efter paus",
    PROST: "PROST",
    "PROST settings": "PROST-inställningar",
    Prev: "Föregående",
    "Preview in channel list": "Förhandsvisning i kanallistan",
    Previous: "Föregående kanal",
    "Privacy policy": "Integritetspolicy",
    "Protect Adult Channels": "Skydda vuxenkanaler",
    "Protect Change Provider": "Skydda leverantörsbyte",
    "Protect Settings": "Skydda inställningar",
    "p...": "p…",
    paging: "sidbläddring",
    Quality: "Kvalitet",
    Rating: "Betyg",
    RD: "RD",
    "RD settings": "RD-inställningar",
    "Reconnecting…": "Återansluter…",
    Records: "Inspelningar",
    "Records for channel: ": "Inspelningar för kanal: ",
    "Records library is empty": "Inspelningsbiblioteket är tomt",
    "Records not supported by provider":
        "Leverantören stöder inte inspelningar",
    "Release date": "Utgivningsdatum",
    "Remember previous channels": "Kom ihåg tidigare kanaler",
    "Reminder: %1 — %2 in %3 min": "Påminnelse: %1 — %2 om %3 min",
    "Remote (color buttons N/A)": "Fjärrkontroll utan färgknappar",
    "Remote (number buttons N/A)": "Fjärrkontroll utan sifferknappar",
    "Remote control": "Fjärrkontroll",
    "Remote session expired": "Fjärrsessionen har gått ut",
    "Remote text entry denied": "Fjärrinmatning av text nekades",
    "Remote text entry error": "Fel vid fjärrinmatning av text",
    "Remote text entry not configured":
        "Fjärrinmatning av text är inte konfigurerad",
    "Remote text entry requires a Device ID. Ask the server operator to provision one.":
        "Fjärrinmatning av text kräver ett enhets-ID. Be serveradministratören tilldela ett.",
    "Remove timer?": "Ta bort timer?",
    Rename: "Byt namn",
    "Rename category": "Byt namn på kategori",
    "Rename to": "Byt namn till",
    "Repeat parental code": "Ange föräldrakoden igen",
    "Request sended!": "Begäran skickad!",
    "Restart player": "Starta om spelaren",
    "Restart stream": "Starta om strömmen",
    "Restart stream / Live": "Starta om strömmen / direktsändning",
    "Resume from archive?": "Fortsätta från arkivet?",
    "Return to previous channel": "Återgå till föregående kanal",
    Rewind: "Spola",
    "Rewind step by buttons %1/%2": "Spolningssteg för knapparna %1/%2",
    RUSSKOETV: "RUSSKOETV",
    "RUSSKOETV settings": "RUSSKOETV-inställningar",
    Russian: "Ryska",
    right: "höger",
    Saturation: "Mättnad",
    "Save & load channels": "Spara och läs in kanaler",
    "Save and load": "Spara och läs in",
    "Save and load channels": "Spara och läs in kanaler",
    "Save Settings": "Spara inställningar",
    "Save settings": "Spara inställningar",
    "Save settings and load channel list":
        "Spara inställningar och läs in kanallistan",
    "Save settings to storage": "Spara inställningar i lagring",
    Script: "Manus",
    Search: "Sök",
    "Search programme": "Sök program",
    "Select a stream type:<br>%1": "Välj strömtyp:<br>%1",
    "Select category to add channel": "Välj kategori att lägga till kanalen i",
    "Select color": "Välj färg",
    "Select menu items": "Välj menyalternativ",
    "Select playlist": "Välj spellista",
    "Select playlist file": "Välj spellistefil",
    "Select playlist template source for EPG and logos":
        "Välj spellistemall för programguide och logotyper",
    "Send request": "Skicka begäran",
    "Send settings": "Skicka inställningar",
    "Send this code from your proxy in the Authorization: Bearer header.":
        "Skicka koden från din proxy i rubriken Authorization: Bearer.",
    Server: "Server",
    "Server address": "Serveradress",
    "Server address (for example 192.168.1.20:8081)":
        "Serveradress (t.ex. 192.168.1.20:8081)",
    "Server device access code": "Enhetens åtkomstkod från servern",
    "Server URL": "Serverns URL",
    "Server unavailable. Retrying automatically; check its address and network access.":
        "Servern är inte tillgänglig. Försöker igen automatiskt; kontrollera adressen och nätverksåtkomsten.",
    Set: "Ställ in",
    "Set parental code": "Ställ in föräldrakod",
    "Set timer?": "Ställa in timer?",
    Settings: "Inställningar",
    "Settings could not be saved": "Inställningarna kunde inte sparas",
    "Settings loaded from storage": "Inställningar inlästa från lagring",
    "Settings STB": "Enhetsinställningar",
    "Settings saved": "Inställningarna sparades",
    "Settings saved to storage": "Inställningar sparade i lagring",
    "Settings sended!": "Inställningarna skickades!",
    "Shara.club (ClubTV.pro)": "Shara.club (ClubTV.pro)",
    "Shara.club (ClubTV.pro) settings": "Shara.club (ClubTV.pro)-inställningar",
    ShockTv: "ShockTv",
    "ShockTv settings": "ShockTv-inställningar",
    "Show archive availability in list": "Visa arkivtillgänglighet i listan",
    "Show channel name in list": "Visa kanalnamn i listan",
    "Show channel number in list": "Visa kanalnummer i listan",
    "Show channel selection list": "Visa kanalvalslista",
    "Show description": "Visa beskrivning",
    "Show EPG and archive for channel": "Visa kanalens programguide och arkiv",
    "Show list of channel archive records": "Visa kanalens inspelningar",
    "Show list of channel archive records without duplication":
        "Visa kanalens inspelningar utan dubbletter",
    "Show Media Library": "Visa mediebibliotek",
    "Show picons in channel list": "Visa kanalikoner i listan",
    "Show player menu": "Visa spelarmeny",
    "Show program name": "Visa programnamn",
    "Show progress in channel list": "Visa förlopp i kanallistan",
    "Show provider settings?": "Visa leverantörsinställningar?",
    "Show providers?": "Visa leverantörer?",
    "Show rewind window": "Visa spolningsfönster",
    "Show scrollbar in list": "Visa rullningslist i listor",
    "Show thumbnails": "Visa miniatyrer",
    "Show when changing program": "Visa vid programbyte",
    "Show when rewind": "Visa vid spolning",
    "Show when switching": "Visa vid kanalbyte",
    "Sleep timer": "Insomningstimer",
    "Sort channels": "Sortera kanaler",
    "Stalker Portal Provider": "Stalker-portalleverantör",
    "Stalker portal settings": "Inställningar för Stalker-portal",
    "Stalker portals": "Stalker-portaler",
    Status: "Status",
    "Stop playback and return to live":
        "Stoppa uppspelning och återgå till direktsändning",
    "Stream type: %1": "Strömtyp: %1",
    "String for search": "Söktext",
    "Su Mo Tu We Th Fr Sa": "Sö Må Ti On To Fr Lö",
    Subtitle: "Undertexter",
    Switch: "Byt",
    "Switch sound track": "Byt ljudspår",
    "Switch subtitle": "Byt undertext",
    "Switch to this list": "Byt till den här listan",
    "Swop URL": "Swop-URL",
    "saved on this device": "sparat på den här enheten",
    select: "välj",
    small: "liten",
    system: "systemets",
    Tabox: "Tabox",
    "Tabox settings": "Tabox-inställningar",
    "The device ID in the address is invalid.":
        "Enhets-ID:t i adressen är ogiltigt.",
    "This HTTPS player cannot connect to an HTTP server. Use an HTTPS server or open the player over HTTP.":
        "Denna HTTPS-spelare kan inte ansluta till en HTTP-server. Använd en HTTPS-server eller öppna spelaren via HTTP.",
    "This Play app requires HTTPS. Ask your provider for an HTTPS playlist or server URL.":
        "Denna Play-app kräver HTTPS. Be leverantören om en HTTPS-adress till spellistan eller servern.",
    Timer: "Timer",
    "Timer: switch to channel?": "Timer: byta kanal?",
    "Timeshift: one minute back": "Tidsförskjutning: en minut bakåt",
    "Timeshift: to start of TV program":
        "Tidsförskjutning: till programmets början",
    Timezone: "Tidszon",
    TMDb: "TMDb",
    "TOP-IPTV": "TOP-IPTV",
    "TOP-IPTV settings": "TOP-IPTV-inställningar",
    "To begining": "Till början",
    "To start of TV program / Previous TV program":
        "Till programmets början / föregående program",
    "Toggle Aspect Ratio": "Byt bildförhållande",
    "Toggle on-screen debug HUD": "Visa eller dölj felsökningspanelen",
    "Toggle Zoom Mode": "Byt zoomläge",
    "Top-Tv": "Top-Tv",
    "Top-Tv settings": "Top-Tv-inställningar",
    "Try demo": "Prova demo",
    "TV DOSUG": "TV DOSUG",
    "TV DOSUG settings": "TV DOSUG-inställningar",
    TVClub: "TVClub",
    "TVClub settings": "TVClub-inställningar",
    "Type of player for streaming": "Spelartyp för strömning",
    "top-left": "övre vänster",
    "top-right": "övre höger",
    transparent: "genomskinlig",
    ULTIFL1X: "ULTIFL1X",
    "ULTIFL1X settings": "ULTIFL1X-inställningar",
    "Update installed. Please restart OttPlay FOSS.":
        "Uppdateringen är installerad. Starta om OttPlay FOSS.",
    "Use an HTTP or HTTPS server address.":
        "Använd en HTTP- eller HTTPS-serveradress.",
    "Use HTTP or HTTPS without a username or password in the address.":
        "Använd HTTP eller HTTPS utan användarnamn eller lösenord i adressen.",
    "Use LEFT/RIGHT to select a control, OK to activate, and UP/DOWN to scroll.":
        "Använd VÄNSTER/HÖGER för att välja, OK för att aktivera och UPP/NED för att rulla.",
    Username: "Användarnamn",
    "Username or password is missing.": "Användarnamn eller lösenord saknas.",
    "VIP-IP.COM": "VIP-IP.COM",
    "VIP-IP.COM settings": "VIP-IP.COM-inställningar",
    "Vidok.TV": "Vidok.TV",
    "Vidok.TV settings": "Vidok.TV-inställningar",
    "VOD not supported by provider": "Leverantören stöder inte beställvideo",
    "Volume step, %": "Volymsteg, %",
    "VPortal link": "VPortal-länk",
    "VPortal request failed":
        "Kunde inte läsa in VPortal. Kontrollera länken, åtkomstnyckeln och portalens tillgänglighet.",
    volume: "volym",
    "Wrong parental code !!!": "Fel föräldrakod!",
    "Xtream Codes Provider": "Xtream Codes-leverantör",
    "Xtream Codes settings": "Xtream Codes-inställningar",
    Year: "År",
    Yellow: "Gul",
    Yes: "Ja",
    yes: "ja",
    "Гомельсат (cbilling)": "Гомельсат (cbilling)",
    "Гомельсат (cbilling) settings": "Гомельсат (cbilling)-inställningar",
    МойДом: "МойДом",
    "МойДом settings": "МойДом-inställningar",
    "Ошибка обработки списка каналов! Проверьте правильность данных!!":
        "Kunde inte bearbeta kanallistan. Kontrollera leverantörsuppgifterna!",
    Радуга: "Радуга",
    "Радуга settings": "Радуга-inställningar",
    "Редактирование ID": "Redigera ID",
    "Редактирование PIN": "Redigera PIN",
    Шаравоз: "Шаравоз",
    "Шаравоз settings": "Шаравоз-inställningar",
    "↑↓ Scroll": "↑↓ Rulla",
};
