var keyStrings = {
    " (after changing, load playlist)":
        " (değişiklikten sonra, oynatma listesini yükleyin)",
    " (after changing, restart player)":
        " (değişiklikten sonra oynatıcıyı yeniden başlatın)",
    " added to category ": " kategorisine eklendi ",
    " added to favorites": " favorilere eklendi",
    " m ": " dk ",
    " s": " sn",
    "??? No channel name": "??? Kanal adı yok",
    '"As Is"': "“Olduğu gibi”",
    '"Favorites"': "“Favoriler”",
    '"Sliding" infobar': "Kayan bilgi çubuğu",
    "&darr;a": "&darr;a",
    "&uarr;A": "&uarr;A",
    "<br/><br/>In archive mode:<br/>": "<br/><br/>Arşiv modunda:<br/>",
    "<br/>Loading STB...": "<br/>STB yükleniyor…",
    "<br/>Setup STB...": "<br/>STB ayarlanıyor…",
    "<br>": "<br>",
    "<br><br>": "<br><br>",
    "<br>Add<br>to category": "<br>Kategoriye<br>ekle",
    "<br>Add<br>to favorites": "<br>Favorilere<br>ekle",
    "<br>Delete": "<br>Sil",
    "<br>Down<br>": "<br>Aşağı<br>",
    "<br>Live": "<br>Canlı",
    "<br>Menu": "<br>Menü",
    "<br>Parental<br>Control": "<br>Ebeveyn<br>denetimi",
    "<br>Pause<br>": "<br>Duraklat<br>",
    "<br>Previous<br>channel": "<br>Önceki<br>kanal",
    "<br>Rewind<br>": "<br>Geri sar<br>",
    "<br>Toggle<br>sound track": "<br>Ses parçasını<br>değiştir",
    "<br>Up<br>": "<br>Yukarı<br>",
    "1 hour": "1 saat",
    "1 minute": "1 dakika",
    "2 hours": "2 saat",
    "3 hours": "3 saat",
    "10 Seconds": "10 saniye",
    "30 minutes": "30 dakika",
    "A command expired while the player was loading channels.":
        "Kanallar yüklenirken bir komutun süresi doldu.",
    "A command was rejected by the player. Check its provider and settings.":
        "Oynatıcı bir komutu reddetti. Sağlayıcısını ve ayarlarını kontrol edin.",
    About: "Hakkında",
    "Access code": "Erişim kodu",
    "Access denied. Check the server access code.":
        "Erişim reddedildi. Sunucunun erişim kodunu kontrol edin.",
    "Access key": "Erişim anahtarı",
    "Access key is required!": "Erişim anahtarı gerekli!",
    "Access settings": "Erişim ayarları",
    Actions: "İşlemler",
    "Active list": "Etkin liste",
    Actors: "Oyuncular",
    "Add / rename / delete…": "Ekle / yeniden adlandır / sil…",
    "Add channel to category": "Kanala kategori ekle",
    "Add channel to favorites": "Kanala favorilere ekle",
    "Add new list": "Yeni liste ekle",
    "Add to favorites": "Favorilere ekle",
    Age: "Yaş",
    All: "Tümü",
    "All categories": "Tüm kategoriler",
    "All4you.tv": "All4you.tv",
    "All4you.tv settings": "All4you.tv ayarları",
    "Allowlist this Device ID": "Bu cihaz kimliğine izin ver",
    "An IP without a port uses HTTP port 8081. Clear the address or select Disconnect to stop.":
        "Port belirtilmeyen IP adreslerinde HTTP portu 8081 kullanılır. Durdurmak için adresi silin veya Bağlantıyı kes'i seçin.",
    "API failed, trying M3U...": "API başarısız, M3U deneniyor…",
    "API Server": "API sunucusu",
    "API server URL": "API sunucusu URL'si",
    "Applying HTTP remote settings...":
        "HTTP uzaktan kumanda ayarları uygulanıyor...",
    Archive: "Arşiv",
    "Archive - begin": "Arşiv — başlangıç",
    "Archive hours": "Arşiv saatleri",
    "Archive: ENTER on past programs": "Arşiv: geçmiş programlarda ENTER",
    "Archive. Channel: ": "Arşiv. Kanal: ",
    Aspect: "En boy oranı",
    Audio: "Ses",
    alhabet: "abcçdefgğhıijklmnoöprsştuüvyz",
    always: "her zaman",
    "and enter code": "ve kodu girin",
    Back: "Geri",
    "Back / Forward for 1 minute": "1 dakika geri / ileri atla",
    "Background color": "Arka plan rengi",
    "Background color of selected item": "Seçili öğenin arka plan rengi",
    "BEST LiST IPTV [HLS Playlist]": "BEST LiST IPTV [HLS Playlist]",
    "BEST LiST IPTV [HLS Playlist] settings":
        "BEST LiST IPTV [HLS Playlist] ayarları",
    "BEST LiST IPTV [Stalker]": "BEST LiST IPTV [Stalker]",
    "BEST LiST IPTV [Stalker] settings": "BEST LiST IPTV [Stalker] ayarları",
    "Behavior of %1/%2 buttons in lists":
        "Listelerde %1/%2 düğmelerinin davranışı",
    "Black screen while switching the channel":
        "Kanal değiştirirken siyah ekran",
    Blue: "Mavi",
    "Bookmark age: %1 days": "Yer işareti yaşı: %1 gün",
    "Buffer Size, s": "Arabellek boyutu, s",
    "Built-in playlist:": "Yerleşik oynatma listesi:",
    "Built-in playlists": "Yerleşik oynatma listeleri",
    "Button %1 function when viewing": "İzlerken %1 düğmesinin işlevi",
    "Button function %1 when viewing archive":
        "Arşiv izlerken %1 düğmesinin işlevi",
    "Buttons settings": "Düğme ayarları",
    "By alphabet": "Alfabetik",
    "By time": "Kronolojik",
    "begin/end": "başlangıç/bitiş",
    "bottom-right": "sağ alt",
    "built-in": "dahili",
    "Call PiP": "PiP aç",
    "Call PiP / PiP exchange": "PiP aç / PiP yer değiştir",
    Cancel: "İptal",
    "Cannot delete the last category": "Son kategori silinemez",
    Category: "Kategori",
    "Category selection": "Kategori seçimi",
    "Change interface language": "Arayüz dilini değiştir",
    "Change provider": "Sağlayıcıyı değiştir",
    "Change provider - you can change the provider, and it will be remembered at the next start of player!":
        "Sağlayıcıyı değiştirin. Seçiminiz oynatıcıyı bir sonraki başlatışınızda hatırlanır.",
    "Change value": "Değeri değiştir",
    "Channel ": "Kanal ",
    "Channel has no EPG": "Kanalda EPG yok",
    "Channel is not available!!!": "Kanal kullanılamıyor!!!",
    "Channel link": "Kanal bağlantısı",
    "Channel link is required!": "Kanal bağlantısı gerekli!",
    "Channel list": "Kanal listesi",
    "Channel list editing style": "Kanal listesi düzenleme modu",
    "Channel list not received !!!": "Kanal listesi alınamadı!!!",
    "Channel list not received !!!<br/><br/>Enter the provider data and restart the player !!!<br/><br/>":
        "Kanal listesi alınamadı!!!<br/><br/>Sağlayıcı verilerini girin ve oynatıcıyı yeniden başlatın!!!<br/><br/>",
    "Channel list settings": "Channel list ayarları",
    "Channel list. Category: ": "Kanal listesi. Kategori: ",
    "Channel parental control": "Kanal ebeveyn kontrolü",
    Channels: "Kanallar",
    "Choose from": "Şuradan seç",
    "Choose language": "Dil seç",
    "Choose provider": "Sağlayıcı seç",
    Classic: "Klasik",
    "Clear all settings?": "Tüm ayarlar silinsin mi?",
    "Clear settings": "Ayarları sil",
    Close: "Kapat",
    "Close PiP": "PiP kapat",
    Color: "Renk",
    "Color spectrum": "Renk spektrumu",
    "Command server": "Komut sunucusu",
    "Command server address, device access code, local HTTP control, and remote text entry settings":
        "Komut sunucusu adresi, cihaz erişim kodu, yerel HTTP denetimi ve uzaktan metin girişi ayarları",
    "Configure All4you.tv in Settings -> Provider Settings":
        "All4you.tv için Ayarlar -> Sağlayıcı Ayarları bölümünü kullanın",
    "Configure BEST LiST IPTV [HLS Playlist] in Settings -> Provider Settings":
        "BEST LiST IPTV [HLS Playlist] için Ayarlar -> Sağlayıcı Ayarları bölümünü kullanın",
    "Configure BEST LiST IPTV [Stalker] in Settings -> Provider Settings":
        "BEST LiST IPTV [Stalker] için Ayarlar -> Sağlayıcı Ayarları bölümünü kullanın",
    "Configure Diamond TV in Settings -> Provider Settings":
        "Diamond TV için Ayarlar -> Sağlayıcı Ayarları bölümünü kullanın",
    "Configure DRVAO in Settings -> Provider Settings":
        "DRVAO için Ayarlar -> Sağlayıcı Ayarları bölümünü kullanın",
    "Configure Dragon Media PRO in Settings -> Provider Settings":
        "Dragon Media PRO için Ayarlar -> Sağlayıcı Ayarları bölümünü kullanın",
    "Configure Fabryka.TV in Settings -> Provider Settings":
        "Fabryka.TV için Ayarlar -> Sağlayıcı Ayarları bölümünü kullanın",
    "Configure Fox-TV in Settings -> Provider Settings":
        "Fox-TV için Ayarlar -> Sağlayıcı Ayarları bölümünü kullanın",
    "Configure FXML in Settings -> Provider Settings":
        "FXML için Ayarlar -> Sağlayıcı Ayarları bölümünü kullanın",
    "Configure GlanzTV in Settings -> Provider Settings":
        "GlanzTV için Ayarlar -> Sağlayıcı Ayarları bölümünü kullanın",
    "Configure GREAT IPTV in Settings -> Provider Settings":
        "GREAT IPTV için Ayarlar -> Sağlayıcı Ayarları bölümünü kullanın",
    "Configure IpStream.one in Settings -> Provider Settings":
        "IpStream.one için Ayarlar -> Sağlayıcı Ayarları bölümünü kullanın",
    "Configure KORONA TV in Settings -> Provider Settings":
        "KORONA TV için Ayarlar -> Sağlayıcı Ayarları bölümünü kullanın",
    "Configure MaxTV in Settings -> Provider Settings":
        "MaxTV için Ayarlar -> Sağlayıcı Ayarları bölümünü kullanın",
    "Configure New Look in Settings -> Provider Settings":
        "New Look için Ayarlar -> Sağlayıcı Ayarları bölümünü kullanın",
    "Configure OTT Prime ONLINE in Settings -> Provider Settings":
        "OTT Prime ONLINE için Ayarlar -> Sağlayıcı Ayarları bölümünü kullanın",
    "Configure POLMEDIA in Settings -> Provider Settings":
        "POLMEDIA için Ayarlar -> Sağlayıcı Ayarları bölümünü kullanın",
    "Configure PROST in Settings -> Provider Settings":
        "PROST için Ayarlar -> Sağlayıcı Ayarları bölümünü kullanın",
    "Configure RD in Settings -> Provider Settings":
        "RD için Ayarlar -> Sağlayıcı Ayarları bölümünü kullanın",
    "Configure RUSSKOETV in Settings -> Provider Settings":
        "RUSSKOETV için Ayarlar -> Sağlayıcı Ayarları bölümünü kullanın",
    "Configure Shara.club (ClubTV.pro) in Settings -> Provider Settings":
        "Shara.club (ClubTV.pro) için Ayarlar -> Sağlayıcı Ayarları bölümünü kullanın",
    "Configure ShockTv in Settings -> Provider Settings":
        "ShockTv için Ayarlar -> Sağlayıcı Ayarları bölümünü kullanın",
    "Configure Tabox in Settings -> Provider Settings":
        "Tabox için Ayarlar -> Sağlayıcı Ayarları bölümünü kullanın",
    "Configure TOP-IPTV in Settings -> Provider Settings":
        "TOP-IPTV için Ayarlar -> Sağlayıcı Ayarları bölümünü kullanın",
    "Configure Top-Tv in Settings -> Provider Settings":
        "Top-Tv için Ayarlar -> Sağlayıcı Ayarları bölümünü kullanın",
    "Configure TV DOSUG in Settings -> Provider Settings":
        "TV DOSUG için Ayarlar -> Sağlayıcı Ayarları bölümünü kullanın",
    "Configure TVClub in Settings -> Provider Settings":
        "TVClub için Ayarlar -> Sağlayıcı Ayarları bölümünü kullanın",
    "Configure ULTIFL1X in Settings -> Provider Settings":
        "ULTIFL1X için Ayarlar -> Sağlayıcı Ayarları bölümünü kullanın",
    "Configure VIP-IP.COM in Settings -> Provider Settings":
        "VIP-IP.COM için Ayarlar -> Sağlayıcı Ayarları bölümünü kullanın",
    "Configure Vidok.TV in Settings -> Provider Settings":
        "Vidok.TV için Ayarlar -> Sağlayıcı Ayarları bölümünü kullanın",
    "Configure Гомельсат (cbilling) in Settings -> Provider Settings":
        "Гомельсат (cbilling) için Ayarlar -> Sağlayıcı Ayarları bölümünü kullanın",
    "Configure МойДом in Settings -> Provider Settings":
        "МойДом için Ayarlar -> Sağlayıcı Ayarları bölümünü kullanın",
    "Configure Радуга in Settings -> Provider Settings":
        "Радуга için Ayarlar -> Sağlayıcı Ayarları bölümünü kullanın",
    "Configure Шаравоз in Settings -> Provider Settings":
        "Шаравоз için Ayarlar -> Sağlayıcı Ayarları bölümünü kullanın",
    Connect: "Bağlan",
    Connected: "Bağlandı",
    "Connected. Waiting for the channel list...":
        "Bağlandı. Kanal listesi bekleniyor…",
    "Connecting to Stalker portal...": "Stalker portalına bağlanılıyor…",
    "Connecting...": "Bağlanılıyor…",
    "Continue watching?": "İzlemeye devam edilsin mi?",
    "Copy category": "Kategoriyi kopyala",
    "Copy JSON": "JSON kopyala",
    "Could not connect to the server.": "Sunucuya bağlanılamadı.",
    "Could not update HTTP remote control.":
        "HTTP uzaktan kumanda ayarları güncellenemedi.",
    Country: "Ülke",
    "Create category": "Kategori oluştur",
    current: "geçerli",
    "Debug HUD": "Hata ayıklama paneli",
    "Debug HUD is not available": "Hata ayıklama paneli kullanılamıyor",
    Delete: "Sil",
    "Delete category": "Kategoriyi sil",
    "Delete channel": "Kanalı sil",
    "Delete list": "Listeyi sil",
    "Demo — moving test pattern": "Demo — hareketli test deseni",
    Description: "Açıklama",
    "Description of remote control buttons": "Uzaktan kumanda düğme kılavuzu",
    "Device access code": "Cihaz erişim kodu",
    "Device info:": "Cihaz bilgileri:",
    "Device MAC is required for KBC (Kinoboom) playlists":
        "KBC (Kinoboom) listeleri için cihaz MAC adresi gerekli",
    "Diamond TV": "Diamond TV",
    "Diamond TV settings": "Diamond TV ayarları",
    Director: "Yönetmen",
    "Disable HTTP remote": "HTTP kumandasını kapat",
    "Disabled by default. Enabling creates a new device access code.":
        "Varsayılan olarak kapalıdır. Etkinleştirme yeni bir cihaz erişim kodu oluşturur.",
    Disconnect: "Bağlantıyı kes",
    Disconnected: "Bağlantı kesildi",
    "Distance between lines in lists": "Listelerde satır aralığı",
    "Do you want to exit player?": "Oynatıcıdan çıkmak istiyor musunuz?",
    "Download! Wait ...": "İndiriliyor… lütfen bekleyin…",
    DRVAO: "DRVAO",
    "DRVAO settings": "DRVAO ayarları",
    "Dragon Media PRO": "Dragon Media PRO",
    "Dragon Media PRO settings": "Dragon Media PRO ayarları",
    Duration: "Süre",
    Edit: "Düzenle",
    "Edit access key": "Erişim anahtarını düzenle",
    "Edit category name": "Kategori adını düzenle",
    "Edit channel link": "Kanal bağlantısını düzenle",
    "Edit playlist data": "Oynatma listesi verilerini düzenle",
    "Edit VPortal link": "VPortal bağlantısını düzenle",
    Editor: "Düzenleyici",
    "Enable HTTP remote": "HTTP kumandasını aç",
    English: "İngilizce",
    "Enter a password (8 characters).": "Parolayı girin (8 karakter).",
    "Enter a playlist URL to access this service.":
        "Bu hizmete erişmek için oynatma listesi URL'sini girin.",
    "Enter a server address without spaces or a fragment.":
        "Sunucu adresini boşluk veya # sonrası parça olmadan girin.",
    "Enter a username (8 characters).": "Kullanıcı adını girin (8 karakter).",
    "Enter a username and password to access this service.":
        "Bu hizmete erişmek için kullanıcı adı ve parola girin.",
    "Enter a valid server address, for example 192.168.1.20:8081.":
        "Geçerli bir sunucu adresi girin, örneğin 192.168.1.20:8081.",
    "Enter access key for": "Şunun için erişim anahtarı girin:",
    "Enter an application access key (8 characters).":
        "Uygulama erişim anahtarını girin (8 karakter).",
    "Enter an ID and PIN to access this service.":
        "Bu hizmete erişmek için kimlik ve PIN girin.",
    "Enter an IPTV token (10 characters).":
        "IPTV belirtecini girin (10 karakter).",
    "Enter category name": "Kategori adını girin",
    "Enter MAC address": "MAC adresini girin",
    "Enter MAC address (e.g. 00:1A:2B:3C:4D:5E)":
        "MAC adresini girin (ör. 00:1A:2B:3C:4D:5E)",
    "Enter Media Library URL": "Medya kütüphanesi URL'sini girin",
    "Enter new category name": "Yeni kategori adını girin",
    "Enter Provider Code": "Sağlayıcı kodunu girin",
    "Enter Provider Code on PC or Phone":
        "Sağlayıcı kodunu bilgisayar veya telefondan girin",
    "Enter parental code": "Ebeveyn kodunu girin",
    "Enter password": "Parolayı girin",
    "Enter playlist archive hours": "Oynatma listesi arşiv saatlerini girin",
    "Enter playlist Name": "Oynatma listesi adını girin",
    "Enter playlist URL": "Oynatma listesi URL'sini girin",
    "Enter Stalker portal URL": "Stalker portalı URL'sini girin",
    "Enter Stalker portal URL (e.g. http://your-portal:8800)":
        "Stalker portalı URL'sini girin (ör. http://your-portal:8800)",
    "Enter Stalker portal URL (e.g. http://your-portal/stalker_portal/c/)":
        "Stalker portalı URL'sini girin (ör. http://your-portal/stalker_portal/c/)",
    "Enter the access code separately, not in the server address.":
        "Erişim kodunu sunucu adresine değil, ayrı olarak girin.",
    "Enter the command server IP or address.":
        "Komut sunucusunun IP adresini veya adresini girin.",
    "Enter the full CDN host from the cabinet stream URL (e.g. subdomain.cdn-domain.tld), not a bare subdomain":
        "Hesabınızdaki akış URL'sinden tam CDN ana bilgisayar adını girin (ör. subdomain.cdn-domain.tld), yalnızca alt alan adını değil",
    "Enter the server IP or address and this player's device access code from the server configuration. Saving both starts checking for volume, channel and other commands automatically.":
        "Sunucunun IP adresini veya adresini ve bu oynatıcının cihaz erişim kodunu sunucu yapılandırmasından girin. İkisini de kaydetmek ses, kanal ve diğer komutların otomatik olarak denetlenmesini başlatır.",
    "Enter the server's device access code (32–256 letters, digits, _ or -).":
        "Sunucudaki cihaz erişim kodunu girin (32–256 harf, rakam, _ veya -).",
    'Enter the tv.team playlist URL.<br>Playlist type: <b>OTTPlayer</b><br/><br/>The "/playlist.m3u8" suffix is added automatically if omitted.':
        "tv.team oynatma listesi URL'sini girin.<br>Liste türü: <b>OTTPlayer</b><br/><br/>“/playlist.m3u8” son eki belirtilmemişse otomatik olarak eklenir.",
    "Enter the VPortal link as shown in the cabinet":
        "VPortal bağlantısını hesabınızda gösterildiği gibi girin",
    "Enter this link in VPortal link. Playlist URL requires an M3U playlist.":
        "Bu bağlantıyı VPortal bağlantısı alanına girin. Oynatma listesi URL'si bir M3U listesi gerektirir.",
    "Enter this player's device access code to connect.":
        "Bağlanmak için bu oynatıcının cihaz erişim kodunu girin.",
    "Enter username": "Kullanıcı adını girin",
    "Enter value": "Değeri girin",
    "Enter Xtream server URL": "Xtream sunucusu URL'sini girin",
    "Enter Xtream server URL (e.g. https://your-server:8080)":
        "Xtream sunucusu URL'sini girin (ör. https://your-server:8080)",
    EPG: "TV Rehberi",
    "EPG and archive. Channel: ": "EPG ve arşiv. Kanal: ",
    "ERROR!": "Hata!",
    "Error Code!": "Geçersiz kod!",
    Exit: "Çıkış",
    "Exit player": "Oynatıcıdan çık",
    "Export settings": "Ayarları dışa aktar",
    "epg.one (Ordered)": "epg.one (sıralı)",
    "epg.one (Standard)": "epg.one (standart)",
    "epg.one (Thematic)": "epg.one (tematik)",
    "epgs...": "Program rehberleri…",
    "Fabryka.TV": "Fabryka.TV",
    "Fabryka.TV settings": "Fabryka.TV ayarları",
    "Failed to connect to Stalker portal": "Stalker portalına bağlanılamadı",
    "Failed to connect to Xtream API server":
        "Xtream API sunucusuna bağlanılamadı",
    "Failed to get user data!!!": "Kullanıcı bilgileri alınamadı!",
    "Failed to load channel list!": "Kanal listesi yüklenemedi!",
    "Failed to load channels from Stalker portal":
        "Stalker portalından kanallar yüklenemedi",
    "Failed to load channels from Xtream API":
        "Xtream API'den kanallar yüklenemedi",
    "Failed to load!": "Yüklenemedi!",
    "Favorite lists": "Favori listeleri",
    Favorites: "Favoriler",
    "File selection is not supported on this device":
        "Bu cihazda dosya seçimi desteklenmiyor",
    Filters: "Filtreler",
    "First Run Setup": "İlk çalıştırma kurulumu",
    "Font type": "Yazı tipi",
    "For download settings file open": "Ayar dosyasını indirmek için açın:",
    "For enter value open": "Değer girmek için açın:",
    "For upload settings file open": "Ayar dosyasını yüklemek için açın:",
    "Fox-TV": "Fox-TV",
    "Fox-TV settings": "Fox-TV ayarları",
    FXML: "FXML",
    "FXML settings": "FXML ayarları",
    Genre: "Tür",
    GlanzTV: "GlanzTV",
    "GlanzTV settings": "GlanzTV ayarları",
    "Go to": "Git",
    "GREAT IPTV": "GREAT IPTV",
    "GREAT IPTV settings": "GREAT IPTV ayarları",
    "Graphical indication": "Grafik göstergeler",
    Green: "Yeşil",
    "Hide / Return": "Gizle / göster",
    "Hide provider settings?": "Sağlayıcı ayarları gizlensin mi?",
    "Hide providers?": "Sağlayıcılar gizlensin mi?",
    "History in Media Library": "Medya kitaplığında geçmiş",
    "History of watched movies": "İzleme geçmişi",
    "HTTP port": "HTTP bağlantı noktası",
    "HTTP remote control is unavailable on this device.":
        "HTTP uzaktan kumandası bu cihazda kullanılamıyor.",
    ID: "Kimlik",
    "Import settings": "Ayarları içe aktar",
    "In live mode: <br/>": "Canlı modda:<br/>",
    Info: "Bilgi",
    "Infobar display timeout, s": "Bilgi çubuğu gösterim süresi, sn",
    "Infobar settings": "Bilgi çubuğu ayarları",
    Information: "Bilgi",
    "Interface credits": "Arayüzü hazırlayanlar",
    "Interface settings": "Arayüz ayarları",
    "Interface theme": "Arayüz teması",
    "Interface transparency": "Arayüz saydamlığı",
    "Invalid channel link! Enter the full host as in the cabinet stream URL (e.g. subdomain.cdn-domain.tld)":
        "Geçersiz kanal bağlantısı! Hesabınızdaki akış URL'sinde olduğu gibi tam ana bilgisayar adını girin (ör. subdomain.cdn-domain.tld)",
    "IPTV token": "IPTV belirteci",
    "IpStream.one": "IpStream.one",
    "IpStream.one settings": "IpStream.one ayarları",
    Joystick: "Oyun kolu",
    "KBC (Kinoboom) access data": "KBC (Kinoboom) erişim bilgileri",
    "KORONA TV": "KORONA TV",
    "KORONA TV settings": "KORONA TV ayarları",
    "List created": "Liste oluşturuldu",
    "List deleted": "Liste silindi",
    "List location": "Listenin konumu",
    "List renamed": "Liste yeniden adlandırıldı",
    "List type": "Liste türü",
    "Lists settings": "Liste ayarları",
    Live: "Canlı",
    Load: "Yükle",
    "Load built-in playlist:": "Yerleşik oynatma listesini yükle:",
    "Load playlist": "Oynatma listesini yükle",
    "Load settings": "Load ayarları",
    "Load settings from storage": "Ayarları depolamadan yükle",
    "Load:": "Yükle:",
    "Loading channels from Xtream API...":
        "Xtream API'den kanallar yükleniyor…",
    "Loading channels...": "Kanallar yükleniyor…",
    "Loading from API...": "API'den yükleniyor…",
    "Loading from Edem API...": "Edem API'den yükleniyor…",
    "Loading M3U playlist...": "M3U oynatma listesi yükleniyor…",
    "Loading M3U...": "M3U yükleniyor…",
    "Loading via proxy...": "Vekil sunucu üzerinden yükleniyor…",
    "Loading. Please wait...": "Yükleniyor… lütfen bekleyin…",
    "Loading...": "Yükleniyor…",
    "Local HTTP remote control": "Yerel HTTP uzaktan kumandası",
    "Local URL": "Yerel URL",
    Login: "Giriş",
    lang: "Türkçe",
    large: "büyük",
    left: "sol",
    "left-bottom": "sol alt",
    "logos...": "Logolar…",
    M3U: "M3U",
    "M3U URL": "M3U URL'si",
    "M3U URL (fallback)": "M3U URL'si (yedek)",
    "MAC address": "MAC adresi",
    "Manage lists": "Listeleri yönet",
    "Manage settings": "Ayarları yönet",
    "Manual setup": "Elle kurulum",
    MaxTV: "MaxTV",
    "MaxTV settings": "MaxTV ayarları",
    Media: "Medya",
    "Media item is no longer available": "Medya öğesi artık kullanılamıyor",
    "Media Library": "Medya kitaplığı",
    "Media Library URL": "Medya kütüphanesi URL'si",
    Menu: "Menü",
    "Menu items settings": "Menü öğesi ayarları",
    "Move category down": "Kategoriyi aşağı taşı",
    "Move category up": "Kategoriyi yukarı taşı",
    "Move channel down": "Kanala aşağı taşı",
    "Move channel up": "Kanala yukarı taşı",
    "m3u-m3u8 playlists": "m3u-m3u8 oynatma listeleri",
    medium: "orta",
    min: "dk",
    "New Look": "New Look",
    "New Look settings": "New Look ayarları",
    "New list name": "Yeni liste adı",
    Next: "Sonraki sayfa",
    "Next keyboard page": "Sonraki klavye sayfası",
    "Next TV program": "Sonraki program",
    No: "Hayır",
    "No channel name": "Kanal adı yok",
    "No saved settings found": "Kaydedilmiş ayar bulunamadı",
    "Not found": "Bulunamadı",
    "Not reduce video when showing the list (bugfix)":
        "Liste gösterilirken videoyu küçültme (hata düzeltmesi)",
    Nothing: "Hiçbir şey",
    "Number of next TV programs in channel list":
        "Kanal listesindeki sonraki program sayısı",
    "Number of rows in lists": "Listelerdeki satır sayısı",
    native: "yerel",
    no: "hayır",
    "no epg at current time": "Şu anda EPG yok",
    "not set": "ayarlanmamış",
    Off: "Kapalı",
    Ok: "Tamam",
    Open: "Aç",
    "Open in PiP": "PiP'te Aç",
    "OTT Prime ONLINE": "OTT Prime ONLINE",
    "OTT Prime ONLINE settings": "OTT Prime ONLINE ayarları",
    "OttPlay FOSS %1 is available. Download and install now?":
        "OttPlay FOSS %1 hazır. Şimdi indirip yüklemek ister misiniz?",
    "Overwrite current settings?": "Geçerli ayarların üzerine yazılsın mı?",
    off: "kapalı",
    on: "açık",
    "on ": "açık ",
    "or scan": "veya tarayın",
    "Parental control": "Ebeveyn denetimi",
    Password: "Parola",
    Pause: "Duraklat",
    "Pause/Play": "Duraklat / oynat",
    "Permanent clock on screen": "Saati ekranda her zaman göster",
    PIN: "PIN",
    "PiP exchange": "PiP yer değiştir",
    "PiP window position": "PiP penceresinin konumu",
    "PiP window size": "PiP penceresinin boyutu",
    Play: "Oynat",
    "Player and device info": "Oynatıcı ve cihaz bilgileri",
    "Player info:": "Oynatıcı bilgileri:",
    Playlist: "Oynatma listesi",
    "Playlist file": "Oynatma listesi dosyası",
    "Playlist is not loading directly...Loading via server...":
        "Oynatma listesi doğrudan yüklenmiyor...Sunucu üzerinden yükleniyor...",
    "Playlist Name": "Oynatma listesi adı",
    "Playlist URL": "Oynatma listesi URL'si",
    POLMEDIA: "POLMEDIA",
    "POLMEDIA settings": "POLMEDIA ayarları",
    "Portal URL": "Portal URL'si",
    "Position shift -10 seconds after pause":
        "Duraklatmadan sonra 10 saniye geri git",
    PROST: "PROST",
    "PROST settings": "PROST ayarları",
    Prev: "Önceki",
    "Preview in channel list": "Kanal listesinde önizleme",
    Previous: "Önceki",
    "Privacy policy": "Gizlilik politikası",
    "Protect Adult Channels": "Yetişkin kanallarını koru",
    "Protect Change Provider": "Sağlayıcı değişikliğini koru",
    "Protect Settings": "Ayarları koru",
    "p...": "p...",
    paging: "sayfalama",
    Quality: "Kalite",
    Rating: "Puan",
    RD: "RD",
    "RD settings": "RD ayarları",
    "Reconnecting…": "Yeniden bağlanılıyor…",
    Records: "Kayıtlar",
    "Records for channel: ": "Kanal kayıtları: ",
    "Records library is empty": "Kayıt kitaplığı boş",
    "Records not supported by provider": "Bu sağlayıcı kayıtları desteklemiyor",
    "Release date": "Yayın tarihi",
    "Remember previous channels": "Önceki kanalları hatırla",
    "Reminder: %1 — %2 in %3 min": "Hatırlatma: %1 — %2, %3 dk sonra",
    "Remote (color buttons N/A)": "Kumanda (renkli düğme yok)",
    "Remote (number buttons N/A)": "Kumanda (sayı düğmesi yok)",
    "Remote control": "Uzaktan kumanda",
    "Remote session expired": "Uzaktan oturumun süresi doldu",
    "Remote text entry denied": "Uzaktan metin girişi reddedildi",
    "Remote text entry error": "Uzaktan metin girişi hatası",
    "Remote text entry not configured":
        "Uzaktan metin girişi yapılandırılmamış",
    "Remote text entry requires a Device ID. Ask the server operator to provision one.":
        "Uzaktan metin girişi için cihaz kimliği gerekir. Sunucu yöneticisinden bir kimlik sağlamasını isteyin.",
    "Remove timer?": "Zamanlayıcı kaldırılsın mı?",
    Rename: "Yeniden adlandır",
    "Rename category": "Kategoriyi yeniden adlandır",
    "Rename to": "Yeni ad",
    "Repeat parental code": "Ebeveyn kodunu yeniden girin",
    "Request sended!": "İstek gönderildi!",
    "Restart player": "Oynatıcıyı yeniden başlat",
    "Restart stream": "Akışı yeniden başlat",
    "Restart stream / Live": "Akışı yeniden başlat / canlı",
    "Resume from archive?": "Arşivden devam edilsin mi?",
    "Return to previous channel": "Önceki kanala dön",
    Rewind: "Sar",
    "Rewind step by buttons %1/%2": "%1/%2 düğmelerinin geri sarma adımı",
    RUSSKOETV: "RUSSKOETV",
    "RUSSKOETV settings": "RUSSKOETV ayarları",
    Russian: "Rusça",
    right: "sağ",
    Saturation: "Doygunluk",
    "Save & load channels": "Kaydet ve kanalları yükle",
    "Save and load": "Kaydet ve yükle",
    "Save and load channels": "Kaydet ve kanalları yükle",
    "Save Settings": "Ayarları kaydet",
    "Save settings": "Ayarları kaydet",
    "Save settings and load channel list":
        "Ayarları kaydet ve kanal listesini yükle",
    "Save settings to storage": "Ayarları depolamaya kaydet",
    Script: "Senaryo",
    Search: "Ara",
    "Search programme": "Program ara",
    "Select a stream type:<br>%1": "Akış türünü seçin:<br>%1",
    "Select category to add channel": "Kanal eklemek için kategori seçin",
    "Select color": "Renk seç",
    "Select menu items": "Menü öğelerini seç",
    "Select playlist": "Oynatma listesi seç",
    "Select playlist file": "Oynatma listesi dosyasını seçin",
    "Select playlist template source for EPG and logos":
        "EPG ve logolar için oynatma listesi şablon kaynağını seçin",
    "Send request": "İstek gönder",
    "Send settings": "Ayarları gönder",
    "Send this code from your proxy in the Authorization: Bearer header.":
        "Bu kodu vekil sunucunuzdan Authorization: Bearer başlığında gönderin.",
    Server: "Sunucu",
    "Server address": "Sunucu adresi",
    "Server address (for example 192.168.1.20:8081)":
        "Sunucu adresi (örneğin 192.168.1.20:8081)",
    "Server device access code": "Sunucudaki cihaz erişim kodu",
    "Server URL": "Sunucu URL'si",
    "Server unavailable. Retrying automatically; check its address and network access.":
        "Sunucu kullanılamıyor. Otomatik olarak yeniden deneniyor; adresini ve ağ erişimini kontrol edin.",
    Set: "Ayarla",
    "Set parental code": "Ebeveyn kodunu ayarla",
    "Set timer?": "Zamanlayıcı ayarlansın mı?",
    Settings: "Ayarlar",
    "Settings could not be saved": "Ayarlar kaydedilemedi",
    "Settings loaded from storage": "Ayarlar depolamadan yüklendi",
    "Settings STB": "STB Ayarları",
    "Settings saved": "Ayarlar kaydedildi",
    "Settings saved to storage": "Ayarlar depolamaya kaydedildi",
    "Settings sended!": "Ayarlar gönderildi!",
    "Shara.club (ClubTV.pro)": "Shara.club (ClubTV.pro)",
    "Shara.club (ClubTV.pro) settings": "Shara.club (ClubTV.pro) ayarları",
    ShockTv: "ShockTv",
    "ShockTv settings": "ShockTv ayarları",
    "Show archive availability in list":
        "Listede arşiv kullanılabilirliğini göster",
    "Show channel name in list": "Listede kanal adını göster",
    "Show channel number in list": "Listede kanal numarasını göster",
    "Show channel selection list": "Kanal seçme listesini göster",
    "Show description": "Açıklamayı göster",
    "Show EPG and archive for channel": "Kanal EPG'sini ve arşivini göster",
    "Show list of channel archive records": "Kanal kayıtlarını göster",
    "Show list of channel archive records without duplication":
        "Kanal kayıtlarını yinelemesiz göster",
    "Show Media Library": "Medya kitaplığını göster",
    "Show picons in channel list": "Listede kanal simgelerini göster",
    "Show player menu": "Oynatıcı menüsünü göster",
    "Show program name": "Program adını göster",
    "Show progress in channel list": "Kanal listesinde ilerlemeyi göster",
    "Show provider settings?": "Sağlayıcı ayarları gösterilsin mi?",
    "Show providers?": "Sağlayıcılar gösterilsin mi?",
    "Show rewind window": "Sarma penceresini göster",
    "Show scrollbar in list": "Listelerde kaydırma çubuğunu göster",
    "Show thumbnails": "Küçük resimleri göster",
    "Show when changing program": "Program değiştiğinde göster",
    "Show when rewind": "Geri sararken göster",
    "Show when switching": "Kanal değiştirirken göster",
    "Sleep timer": "Uyku zamanlayıcısı",
    "Sort channels": "Kanalları sırala",
    "Stalker Portal Provider": "Stalker portalı sağlayıcısı",
    "Stalker portal settings": "Stalker portalı ayarları",
    "Stalker portals": "Stalker portalları",
    Status: "Durum",
    "Stop playback and return to live": "Oynatmayı durdur ve canlıya dön",
    "Stream type: %1": "Akış türü: %1",
    "String for search": "Arama sorgusu",
    "Su Mo Tu We Th Fr Sa": "Pa Pt Sa Ça Pe Cu Ct",
    Subtitle: "Altyazılar",
    Switch: "Değiştir",
    "Switch sound track": "Ses parçasını değiştir",
    "Switch subtitle": "Altyazıları değiştir",
    "Switch to this list": "Bu listeye geç",
    "Swop URL": "Swop URL'si",
    "saved on this device": "bu cihazda kayıtlı",
    select: "seç",
    small: "küçük",
    system: "sistem",
    Tabox: "Tabox",
    "Tabox settings": "Tabox ayarları",
    "The device ID in the address is invalid.":
        "Adresteki cihaz kimliği geçersiz.",
    "This HTTPS player cannot connect to an HTTP server. Use an HTTPS server or open the player over HTTP.":
        "Bu HTTPS oynatıcı bir HTTP sunucusuna bağlanamaz. HTTPS sunucusu kullanın veya oynatıcıyı HTTP üzerinden açın.",
    "This Play app requires HTTPS. Ask your provider for an HTTPS playlist or server URL.":
        "Bu Play uygulaması HTTPS gerektirir. Sağlayıcınızdan HTTPS oynatma listesi veya sunucu URL'si isteyin.",
    Timer: "Zamanlayıcı",
    "Timer: switch to channel?": "Zamanlayıcı: bu kanala geçilsin mi?",
    "Timeshift: one minute back": "Zaman kaydırma: bir dakika geri",
    "Timeshift: to start of TV program": "Zaman kaydırma: programın başına",
    Timezone: "Saat dilimi",
    TMDb: "TMDb",
    "TOP-IPTV": "TOP-IPTV",
    "TOP-IPTV settings": "TOP-IPTV ayarları",
    "To begining": "Başa",
    "To start of TV program / Previous TV program":
        "Programın başına / önceki programa git",
    "Toggle Aspect Ratio": "En boy oranını değiştir",
    "Toggle on-screen debug HUD": "Hata ayıklama panelini göster / gizle",
    "Toggle Zoom Mode": "Yakınlaştırma modunu değiştir",
    "Top-Tv": "Top-Tv",
    "Top-Tv settings": "Top-Tv ayarları",
    "Try demo": "Demoyu dene",
    "TV DOSUG": "TV DOSUG",
    "TV DOSUG settings": "TV DOSUG ayarları",
    TVClub: "TVClub",
    "TVClub settings": "TVClub ayarları",
    "Type of player for streaming": "Akış için oynatıcı türü",
    "top-left": "sol üst",
    "top-right": "sağ üst",
    transparent: "saydam",
    ULTIFL1X: "ULTIFL1X",
    "ULTIFL1X settings": "ULTIFL1X ayarları",
    "Update installed. Please restart OttPlay FOSS.":
        "Güncelleme yüklendi. Lütfen OttPlay FOSS'u yeniden başlatın.",
    "Use an HTTP or HTTPS server address.":
        "HTTP veya HTTPS sunucu adresi kullanın.",
    "Use HTTP or HTTPS without a username or password in the address.":
        "Adreste kullanıcı adı veya parola olmadan HTTP veya HTTPS kullanın.",
    "Use LEFT/RIGHT to select a control, OK to activate, and UP/DOWN to scroll.":
        "Bir denetim seçmek için SOL/SAĞ, etkinleştirmek için OK ve kaydırmak için YUKARI/AŞAĞI düğmelerini kullanın.",
    Username: "Kullanıcı adı",
    "Username or password is missing.": "Kullanıcı adı veya parola eksik.",
    "VIP-IP.COM": "VIP-IP.COM",
    "VIP-IP.COM settings": "VIP-IP.COM ayarları",
    "Vidok.TV": "Vidok.TV",
    "Vidok.TV settings": "Vidok.TV ayarları",
    "VOD not supported by provider": "Bu sağlayıcı VOD'u desteklemiyor",
    "Volume step, %": "Ses düzeyi adımı, %",
    "VPortal link": "VPortal bağlantısı",
    "VPortal request failed":
        "VPortal yüklenemedi. Bağlantıyı, erişim anahtarını ve portalın kullanılabilirliğini kontrol edin.",
    volume: "ses düzeyi",
    "Wrong parental code !!!": "Yanlış ebeveyn kodu!!!",
    "Xtream Codes Provider": "Xtream Codes sağlayıcısı",
    "Xtream Codes settings": "Xtream Codes ayarları",
    Year: "Yıl",
    Yellow: "Sarı",
    Yes: "Evet",
    yes: "evet",
    "Гомельсат (cbilling)": "Гомельсат (cbilling)",
    "Гомельсат (cbilling) settings": "Гомельсат (cbilling) ayarları",
    МойДом: "МойДом",
    "МойДом settings": "МойДом ayarları",
    "Ошибка обработки списка каналов! Проверьте правильность данных!!":
        "Kanal listesi işlenemedi. Sağlayıcı bilgilerinizi kontrol edin!",
    Радуга: "Радуга",
    "Радуга settings": "Радуга ayarları",
    "Редактирование ID": "Kimliği düzenle",
    "Редактирование PIN": "PIN'i düzenle",
    Шаравоз: "Шаравоз",
    "Шаравоз settings": "Шаравоз ayarları",
    "↑↓ Scroll": "↑↓ Kaydır",
};
