var keyStrings = {
    " (after changing, load playlist)":
        " (değişiklikten sonra, oynatma listesini yükleyin)",
    " added to category ": " kategorisine eklendi ",
    " added to favorites": " favorilere eklendi",
    "??? No channel name": "??? Kanal adı yok",
    Actions: "İşlemler",
    "Add channel to category": "Kanala kategori ekle",
    "Add channel to favorites": "Kanala favorilere ekle",
    All: "Tümü",
    "Archive hours": "Arşiv saatleri",
    alhabet: "abcçdefgğhıijklmnoöprsştuüvyz",
    "Buffer Size, s": "Arabellek boyutu, s",
    "built-in": "dahili",
    Category: "Kategori",
    "Channel ": "Kanal ",
    "Channel is not available!!!": "Kanal kullanılamıyor!!!",
    "Channel list": "Kanal listesi",
    "Channel list not received !!!": "Kanal listesi alınamadı!!!",
    "Channel list not received !!!<br/><br/>Enter the provider data and restart the player !!!<br/><br/>":
        "Kanal listesi alınamadı!!!<br/><br/>Sağlayıcı verilerini girin ve oynatıcıyı yeniden başlatın!!!<br/><br/>",
    "Channel list. Category: ": "Kanal listesi. Kategori: ",
    "Channel parental control": "Kanal ebeveyn kontrolü",
    Close: "Kapat",
    "Delete channel": "Kanalı sil",
    Description: "Açıklama",
    Edit: "Düzenle",
    "Edit category name": "Kategori adını düzenle",
    "Edit playlist data": "Oynatma listesi verilerini düzenle",
    Editor: "Düzenleyici",
    "Enter Media Library URL": "Medya kütüphanesi URL'sini girin",
    "Enter parental code": "Ebeveyn kodunu girin",
    "Enter playlist archive hours": "Oynatma listesi arşiv saatlerini girin",
    "Enter playlist Name": "Oynatma listesi adını girin",
    "Enter playlist URL": "Oynatma listesi URL'sini girin",
    EPG: "TV Rehberi",
    Exit: "Çıkış",
    "Failed to load channel list!": "Kanal listesi yüklenemedi!",
    Favorites: "Favoriler",
    Info: "Bilgi",
    Load: "Yükle",
    "Load playlist": "Oynatma listesini yükle",
    lang: "Türkçe",
    "Media Library URL": "Medya kütüphanesi URL'si",
    Menu: "Menü",
    "Move channel down": "Kanala aşağı taşı",
    "Move channel up": "Kanala yukarı taşı",
    "m3u-m3u8 playlists": "m3u-m3u8 oynatma listeleri",
    min: "dk",
    "No channel name": "Kanal adı yok",
    Nothing: "Hiçbir şey",
    native: "yerel",
    no: "hayır",
    "Open in PiP": "PiP'te Aç",
    off: "kapalı",
    Playlist: "Oynatma listesi",
    "Playlist file": "Oynatma listesi dosyası",
    "Playlist is not loading directly...Loading via server...":
        "Oynatma listesi doğrudan yüklenmiyor...Sunucu üzerinden yükleniyor...",
    "Playlist Name": "Oynatma listesi adı",
    "Playlist URL": "Oynatma listesi URL'si",
    "Save Settings": "Ayarları kaydet",
    Search: "Ara",
    "Select category to add channel": "Kanal eklemek için kategori seçin",
    "Select playlist": "Oynatma listesi seç",
    "Select playlist file": "Oynatma listesi dosyasını seçin",
    Settings: "Ayarlar",
    "Settings STB": "STB Ayarları",
    "Settings saved": "Ayarlar kaydedildi",
    "Stalker portals": "Stalker portalları",
    "Type of player for streaming": "Akış için oynatıcı türü",
    "Wrong parental code !!!": "Yanlış ebeveyn kodu!!!",
    yes: "evet",
};
