var keyStrings = {
    lang: "Українська",
    alhabet: "абвгґдеєжзиіїйклмнопрстуфхцчшщьюя",
    "Channel list. Category: ": "Список каналів. Категорія: ",
    EPG: "Програма",
    Category: "Категорія",
    Actions: "Дії",
    Description: "Опис",
    "Open in PiP": "Відкрити в PiP",
    "Move channel up": "Перемістити канал вгору",
    "Move channel down": "Перемістити канал вниз",
    "Delete channel": "Видалити канал",
    "Add channel to category": "Додати канал до категорії",
    "Add channel to favorites": "Додати канал до обраних",
    "Channel parental control": "Батьківський контроль каналу",
    "Channel is not available!!!": "Канал недоступний!!!",
    min: "хв",
    "Channel ": "Канал ",
    " added to category ": " додано до категорії ",
    " added to favorites": " додано до обраних",
    Favorites: "Обрані",
    "Select category to add channel": "Вибір категорії для додавання каналу",
    "Enter parental code": "Введіть батьківський код",
    "Wrong parental code !!!": "Невірний батьківський код!!!",
    Close: "Закрити",
    "Edit category name": "Редагувати назву категорії",
    Menu: "Меню",
    "Channel list": "Список каналів",
    Settings: "Налаштування",
    "Settings saved": "Налаштування збережено",
    no: "ні",
    yes: "так",
    Info: "Інфо",
    Nothing: "Нічого",
    Exit: "Вихід",
    off: "вимкнено",
    "Failed to load channel list!": "Не вдалося завантажити список каналів!",
    "??? No channel name": "??? Немає назви каналу",
    "Playlist URL": "Адреса плейлиста",
    "Archive hours": "Годин архіву",
    "Enter playlist URL": "Введення адреси плейлиста",
    "Playlist Name": "Назва плейлиста",
    "Enter playlist Name": "Введення назви плейлиста",
    "Media Library URL": "Адреса медіатеки",
    "Enter Media Library URL": "Введення адреси медіатеки",
    Playlist: "Плейлист",
    "Playlist is not loading directly...Loading via server...":
        "Плейлист не завантажується напряму...Завантаження через сервер...",
    "Select playlist": "Виберіть плейлист",
    Edit: "Редагувати",
    Load: "Завантажити",
    "Edit playlist data": "Редагування даних плейлиста",
    All: "Всі",
    Search: "Пошук",
    "m3u-m3u8 playlists": "Плейлисти m3u-m3u8",
    "Stalker portals": "Портали Stalker",
    "Settings STB": "Налаштування пристрою",
    "Type of player for streaming": "Тип плеєра для потокової передачі",
    "Buffer Size, s": "Розмір буфера, с",
    "Save Settings": "Зберегти налаштування",
    Editor: "Редактор",
    "built-in": "вбудований",
    native: "рідний",
    "No channel name": "Немає назви каналу",
    " (after changing, load playlist)": " (після зміни, завантажити плейлист)",
    "Enter playlist archive hours":
        "Введення кількості годин архіву для плейлиста",
    "Load playlist": "Завантажити плейлист",
    "Playlist file": "Файл плейлиста",
    "Select playlist file": "Вибір файлу плейлиста",
    "Channel list not received !!!<br/><br/>Enter the provider data and restart the player !!!<br/><br/>":
        "Не отримано список каналів!!!<br/><br/>Введіть дані провайдера та перезапустіть плеєр!!!<br/><br/>",
    "Channel list not received !!!": "Не отримано список каналів!!!",
};
