var keyStrings = {
    " (after changing, load playlist)": " (після зміни, завантажити плейлист)",
    " (after changing, restart player)":
        " (після зміни перезапустіть програвач)",
    " added to category ": " додано до категорії ",
    " added to favorites": " додано до обраних",
    " m ": " хв ",
    " s": " с",
    "??? No channel name": "??? Немає назви каналу",
    '"As Is"': "«Як є»",
    '"Favorites"': "«Обране»",
    '"Sliding" infobar': "Висувна інформаційна панель",
    "&darr;a": "&darr;a",
    "&uarr;A": "&uarr;A",
    "<br/><br/>In archive mode:<br/>": "<br/><br/>У режимі архіву:<br/>",
    "<br/>Loading STB...": "<br/>Завантаження пристрою…",
    "<br/>Setup STB...": "<br/>Налаштування пристрою…",
    "<br>": "<br>",
    "<br><br>": "<br><br>",
    "<br>Add<br>to category": "<br>Додати<br>до категорії",
    "<br>Add<br>to favorites": "<br>Додати<br>до обраного",
    "<br>Delete": "<br>Видалити",
    "<br>Down<br>": "<br>Вниз<br>",
    "<br>Live": "<br>Прямий ефір",
    "<br>Menu": "<br>Меню",
    "<br>Parental<br>Control": "<br>Батьківський<br>контроль",
    "<br>Pause<br>": "<br>Пауза<br>",
    "<br>Previous<br>channel": "<br>Попередній<br>канал",
    "<br>Rewind<br>": "<br>Перемотування<br>",
    "<br>Toggle<br>sound track": "<br>Змінити<br>звукову доріжку",
    "<br>Up<br>": "<br>Вгору<br>",
    "1 hour": "1 година",
    "1 minute": "1 хвилина",
    "2 hours": "2 години",
    "3 hours": "3 години",
    "10 Seconds": "10 секунд",
    "30 minutes": "30 хвилин",
    "A command expired while the player was loading channels.":
        "Термін дії команди минув під час завантаження каналів.",
    "A command was rejected by the player. Check its provider and settings.":
        "Програвач відхилив команду. Перевірте провайдера й налаштування.",
    About: "Про програму",
    "Access code": "Код доступу",
    "Access denied. Check the server access code.":
        "Доступ заборонено. Перевірте код доступу до сервера.",
    "Access key": "Ключ доступу",
    "Access key is required!": "Потрібен ключ доступу!",
    "Access settings": "Налаштування доступу",
    Actions: "Дії",
    "Active list": "Активний список",
    Actors: "Актори",
    "Add / rename / delete…": "Додати / перейменувати / видалити…",
    "Add channel to category": "Додати канал до категорії",
    "Add channel to favorites": "Додати канал до обраних",
    "Add new list": "Додати список",
    "Add to favorites": "Додати до обраного",
    Age: "Вік",
    All: "Всі",
    "All categories": "Усі категорії",
    "All4you.tv": "All4you.tv",
    "All4you.tv settings": "Налаштування All4you.tv",
    "Allowlist this Device ID": "Дозвольте цей ID пристрою",
    "An IP without a port uses HTTP port 8081. Clear the address or select Disconnect to stop.":
        "Для IP без порту використовується HTTP-порт 8081. Для відключення очистьте адресу або виберіть «Відключити».",
    "API failed, trying M3U...": "Помилка API, спроба M3U…",
    "API Server": "Сервер API",
    "API server URL": "Адреса сервера API",
    "Applying HTTP remote settings...":
        "Застосування налаштувань HTTP-пульта...",
    Archive: "Архів",
    "Archive - begin": "Архів — початок",
    "Archive hours": "Годин архіву",
    "Archive: ENTER on past programs": "Архів: ENTER на минулій передачі",
    "Archive. Channel: ": "Архів. Канал: ",
    Aspect: "Співвідношення сторін",
    Audio: "Звук",
    alhabet: "абвгґдеєжзиіїйклмнопрстуфхцчшщьюяʼ",
    always: "завжди",
    "and enter code": "і введіть код",
    Back: "Назад",
    "Back / Forward for 1 minute": "Назад / вперед на 1 хвилину",
    "Background color": "Колір тла",
    "Background color of selected item": "Колір тла вибраного пункту",
    "BEST LiST IPTV [HLS Playlist]": "BEST LiST IPTV [HLS Playlist]",
    "BEST LiST IPTV [HLS Playlist] settings":
        "Налаштування BEST LiST IPTV [HLS Playlist]",
    "BEST LiST IPTV [Stalker]": "BEST LiST IPTV [Stalker]",
    "BEST LiST IPTV [Stalker] settings":
        "Налаштування BEST LiST IPTV [Stalker]",
    "Behavior of %1/%2 buttons in lists": "Дія кнопок %1/%2 у списках",
    "Black screen while switching the channel":
        "Чорний екран під час перемикання каналів",
    Blue: "Синій",
    "Bookmark age: %1 days": "Вік закладки: %1 дн.",
    "Buffer Size, s": "Розмір буфера, с",
    "Built-in playlist:": "Вбудований список відтворення:",
    "Built-in playlists": "Вбудовані списки відтворення",
    "Button %1 function when viewing": "Дія кнопки %1 під час перегляду",
    "Button function %1 when viewing archive":
        "Дія кнопки %1 під час перегляду архіву",
    "Buttons settings": "Налаштування кнопок",
    "By alphabet": "За абеткою",
    "By time": "За часом",
    "begin/end": "початок/кінець",
    "bottom-right": "праворуч унизу",
    "built-in": "вбудований",
    "Call PiP": "Відкрити PiP",
    "Call PiP / PiP exchange": "Відкрити PiP / поміняти місцями",
    Cancel: "Скасувати",
    "Cannot delete the last category": "Неможливо видалити останню категорію",
    Category: "Категорія",
    "Category selection": "Вибір категорії",
    "Change interface language": "Змінити мову інтерфейсу",
    "Change provider": "Змінити провайдера",
    "Change provider - you can change the provider, and it will be remembered at the next start of player!":
        "Змініть провайдера. Вибір збережеться під час наступного запуску програвача.",
    "Change value": "Змінити значення",
    "Channel ": "Канал ",
    "Channel has no EPG": "Для каналу немає програми передач",
    "Channel is not available!!!": "Канал недоступний!!!",
    "Channel link": "Посилання на канал",
    "Channel link is required!": "Потрібне посилання на канал!",
    "Channel list": "Список каналів",
    "Channel list editing style": "Режим редагування списку каналів",
    "Channel list not received !!!": "Не отримано список каналів!!!",
    "Channel list not received !!!<br/><br/>Enter the provider data and restart the player !!!<br/><br/>":
        "Не отримано список каналів!!!<br/><br/>Введіть дані провайдера та перезапустіть плеєр!!!<br/><br/>",
    "Channel list settings": "Налаштування списку каналів",
    "Channel list. Category: ": "Список каналів. Категорія: ",
    "Channel parental control": "Батьківський контроль каналу",
    Channels: "Канали",
    "Choose from": "Вибрати з",
    "Choose language": "Виберіть мову",
    "Choose provider": "Виберіть провайдера",
    Classic: "Класична",
    "Clear all settings?": "Видалити всі налаштування?",
    "Clear settings": "Видалити налаштування",
    Close: "Закрити",
    "Close PiP": "Закрити PiP",
    Color: "Колір",
    "Color spectrum": "Колірна палітра",
    "Command server": "Сервер команд",
    "Command server address, device access code, local HTTP control, and remote text entry settings":
        "Адреса сервера команд, код доступу пристрою, локальне HTTP-керування та віддалене введення тексту",
    "Configure All4you.tv in Settings -> Provider Settings":
        "Налаштуйте All4you.tv у розділі Налаштування -> Налаштування провайдера",
    "Configure BEST LiST IPTV [HLS Playlist] in Settings -> Provider Settings":
        "Налаштуйте BEST LiST IPTV [HLS Playlist] у розділі Налаштування -> Налаштування провайдера",
    "Configure BEST LiST IPTV [Stalker] in Settings -> Provider Settings":
        "Налаштуйте BEST LiST IPTV [Stalker] у розділі Налаштування -> Налаштування провайдера",
    "Configure Diamond TV in Settings -> Provider Settings":
        "Налаштуйте Diamond TV у розділі Налаштування -> Налаштування провайдера",
    "Configure DRVAO in Settings -> Provider Settings":
        "Налаштуйте DRVAO у розділі Налаштування -> Налаштування провайдера",
    "Configure Dragon Media PRO in Settings -> Provider Settings":
        "Налаштуйте Dragon Media PRO у розділі Налаштування -> Налаштування провайдера",
    "Configure Fabryka.TV in Settings -> Provider Settings":
        "Налаштуйте Fabryka.TV у розділі Налаштування -> Налаштування провайдера",
    "Configure Fox-TV in Settings -> Provider Settings":
        "Налаштуйте Fox-TV у розділі Налаштування -> Налаштування провайдера",
    "Configure FXML in Settings -> Provider Settings":
        "Налаштуйте FXML у розділі Налаштування -> Налаштування провайдера",
    "Configure GlanzTV in Settings -> Provider Settings":
        "Налаштуйте GlanzTV у розділі Налаштування -> Налаштування провайдера",
    "Configure GREAT IPTV in Settings -> Provider Settings":
        "Налаштуйте GREAT IPTV у розділі Налаштування -> Налаштування провайдера",
    "Configure IpStream.one in Settings -> Provider Settings":
        "Налаштуйте IpStream.one у розділі Налаштування -> Налаштування провайдера",
    "Configure KORONA TV in Settings -> Provider Settings":
        "Налаштуйте KORONA TV у розділі Налаштування -> Налаштування провайдера",
    "Configure MaxTV in Settings -> Provider Settings":
        "Налаштуйте MaxTV у розділі Налаштування -> Налаштування провайдера",
    "Configure New Look in Settings -> Provider Settings":
        "Налаштуйте New Look у розділі Налаштування -> Налаштування провайдера",
    "Configure OTT Prime ONLINE in Settings -> Provider Settings":
        "Налаштуйте OTT Prime ONLINE у розділі Налаштування -> Налаштування провайдера",
    "Configure POLMEDIA in Settings -> Provider Settings":
        "Налаштуйте POLMEDIA у розділі Налаштування -> Налаштування провайдера",
    "Configure PROST in Settings -> Provider Settings":
        "Налаштуйте PROST у розділі Налаштування -> Налаштування провайдера",
    "Configure RD in Settings -> Provider Settings":
        "Налаштуйте RD у розділі Налаштування -> Налаштування провайдера",
    "Configure RUSSKOETV in Settings -> Provider Settings":
        "Налаштуйте RUSSKOETV у розділі Налаштування -> Налаштування провайдера",
    "Configure Shara.club (ClubTV.pro) in Settings -> Provider Settings":
        "Налаштуйте Shara.club (ClubTV.pro) у розділі Налаштування -> Налаштування провайдера",
    "Configure ShockTv in Settings -> Provider Settings":
        "Налаштуйте ShockTv у розділі Налаштування -> Налаштування провайдера",
    "Configure Tabox in Settings -> Provider Settings":
        "Налаштуйте Tabox у розділі Налаштування -> Налаштування провайдера",
    "Configure TOP-IPTV in Settings -> Provider Settings":
        "Налаштуйте TOP-IPTV у розділі Налаштування -> Налаштування провайдера",
    "Configure Top-Tv in Settings -> Provider Settings":
        "Налаштуйте Top-Tv у розділі Налаштування -> Налаштування провайдера",
    "Configure TV DOSUG in Settings -> Provider Settings":
        "Налаштуйте TV DOSUG у розділі Налаштування -> Налаштування провайдера",
    "Configure TVClub in Settings -> Provider Settings":
        "Налаштуйте TVClub у розділі Налаштування -> Налаштування провайдера",
    "Configure ULTIFL1X in Settings -> Provider Settings":
        "Налаштуйте ULTIFL1X у розділі Налаштування -> Налаштування провайдера",
    "Configure VIP-IP.COM in Settings -> Provider Settings":
        "Налаштуйте VIP-IP.COM у розділі Налаштування -> Налаштування провайдера",
    "Configure Vidok.TV in Settings -> Provider Settings":
        "Налаштуйте Vidok.TV у розділі Налаштування -> Налаштування провайдера",
    "Configure Гомельсат (cbilling) in Settings -> Provider Settings":
        "Налаштуйте Гомельсат (cbilling) у розділі Налаштування -> Налаштування провайдера",
    "Configure МойДом in Settings -> Provider Settings":
        "Налаштуйте МойДом у розділі Налаштування -> Налаштування провайдера",
    "Configure Радуга in Settings -> Provider Settings":
        "Налаштуйте Радуга у розділі Налаштування -> Налаштування провайдера",
    "Configure Шаравоз in Settings -> Provider Settings":
        "Налаштуйте Шаравоз у розділі Налаштування -> Налаштування провайдера",
    Connect: "Підключити",
    Connected: "Підключено",
    "Connected. Waiting for the channel list...":
        "Підключено. Очікування списку каналів…",
    "Connecting to Stalker portal...": "Підключення до порталу Stalker…",
    "Connecting...": "Підключення…",
    "Continue watching?": "Продовжити перегляд?",
    "Copy category": "Копіювати категорію",
    "Copy JSON": "Копіювати JSON",
    "Could not connect to the server.": "Не вдалося підключитися до сервера.",
    "Could not update HTTP remote control.":
        "Не вдалося змінити налаштування HTTP-пульта.",
    Country: "Країна",
    "Create category": "Створити категорію",
    current: "поточний",
    "Debug HUD": "Панель налагодження",
    "Debug HUD is not available": "Панель налагодження недоступна",
    Delete: "Видалити",
    "Delete category": "Видалити категорію",
    "Delete channel": "Видалити канал",
    "Delete list": "Видалити список",
    "Demo — moving test pattern": "Демо — рухома тестова таблиця",
    Description: "Опис",
    "Description of remote control buttons": "Опис кнопок пульта",
    "Device access code": "Код доступу до пристрою",
    "Device info:": "Інформація про пристрій:",
    "Device MAC is required for KBC (Kinoboom) playlists":
        "Для списків KBC (Kinoboom) потрібна MAC-адреса пристрою",
    "Diamond TV": "Diamond TV",
    "Diamond TV settings": "Налаштування Diamond TV",
    Director: "Режисер",
    "Disable HTTP remote": "Вимкнути HTTP-пульт",
    "Disabled by default. Enabling creates a new device access code.":
        "За замовчуванням вимкнено. Увімкнення створює новий код доступу до пристрою.",
    Disconnect: "Відключити",
    Disconnected: "Відключено",
    "Distance between lines in lists": "Відстань між рядками списків",
    "Do you want to exit player?": "Вийти з програвача?",
    "Download! Wait ...": "Завантаження… Зачекайте…",
    DRVAO: "DRVAO",
    "DRVAO settings": "Налаштування DRVAO",
    "Dragon Media PRO": "Dragon Media PRO",
    "Dragon Media PRO settings": "Налаштування Dragon Media PRO",
    Duration: "Тривалість",
    Edit: "Редагувати",
    "Edit access key": "Змінити ключ доступу",
    "Edit category name": "Редагувати назву категорії",
    "Edit channel link": "Змінити посилання на канал",
    "Edit playlist data": "Редагування даних плейлиста",
    "Edit VPortal link": "Змінити посилання VPortal",
    Editor: "Редактор",
    "Enable HTTP remote": "Увімкнути HTTP-пульт",
    English: "Англійська",
    "Enter a password (8 characters).": "Введіть пароль (8 символів).",
    "Enter a playlist URL to access this service.":
        "Введіть адресу списку відтворення для доступу до сервісу.",
    "Enter a server address without spaces or a fragment.":
        "Введіть адресу сервера без пробілів і фрагмента після #.",
    "Enter a username (8 characters).":
        "Введіть ім’я користувача (8 символів).",
    "Enter a username and password to access this service.":
        "Введіть ім’я користувача й пароль для доступу до сервісу.",
    "Enter a valid server address, for example 192.168.1.20:8081.":
        "Введіть правильну адресу сервера, наприклад 192.168.1.20:8081.",
    "Enter access key for": "Введіть ключ доступу для",
    "Enter an application access key (8 characters).":
        "Введіть ключ доступу застосунку (8 символів).",
    "Enter an ID and PIN to access this service.":
        "Введіть ID і PIN для доступу до сервісу.",
    "Enter an IPTV token (10 characters).": "Введіть IPTV-токен (10 символів).",
    "Enter category name": "Введіть назву категорії",
    "Enter MAC address": "Введіть MAC-адресу",
    "Enter MAC address (e.g. 00:1A:2B:3C:4D:5E)":
        "Введіть MAC-адресу (наприклад, 00:1A:2B:3C:4D:5E)",
    "Enter Media Library URL": "Введення адреси медіатеки",
    "Enter new category name": "Введіть нову назву категорії",
    "Enter Provider Code": "Введіть код провайдера",
    "Enter Provider Code on PC or Phone":
        "Введіть код провайдера на ПК або телефоні",
    "Enter parental code": "Введіть батьківський код",
    "Enter password": "Введіть пароль",
    "Enter playlist archive hours":
        "Введення кількості годин архіву для плейлиста",
    "Enter playlist Name": "Введення назви плейлиста",
    "Enter playlist URL": "Введення адреси плейлиста",
    "Enter Stalker portal URL": "Введіть адресу порталу Stalker",
    "Enter Stalker portal URL (e.g. http://your-portal:8800)":
        "Введіть адресу порталу Stalker (наприклад, http://your-portal:8800)",
    "Enter Stalker portal URL (e.g. http://your-portal/stalker_portal/c/)":
        "Введіть адресу порталу Stalker (наприклад, http://your-portal/stalker_portal/c/)",
    "Enter the access code separately, not in the server address.":
        "Введіть код доступу окремо від адреси сервера.",
    "Enter the command server IP or address.":
        "Введіть IP або адресу сервера команд.",
    "Enter the full CDN host from the cabinet stream URL (e.g. subdomain.cdn-domain.tld), not a bare subdomain":
        "Введіть повне ім’я вузла CDN з посилання на потік у кабінеті (наприклад, subdomain.cdn-domain.tld), а не лише піддомен",
    "Enter the server IP or address and this player's device access code from the server configuration. Saving both starts checking for volume, channel and other commands automatically.":
        "Введіть IP або адресу сервера та код доступу цього програвача з конфігурації сервера. Збереження обох значень автоматично запускає перевірку команд гучності, каналів та інших дій.",
    "Enter the server's device access code (32–256 letters, digits, _ or -).":
        "Введіть код доступу пристрою на сервері (32–256 літер, цифр, _ або -).",
    'Enter the tv.team playlist URL.<br>Playlist type: <b>OTTPlayer</b><br/><br/>The "/playlist.m3u8" suffix is added automatically if omitted.':
        'Введіть адресу списку tv.team.<br>Тип списку: <b>OTTPlayer</b><br/><br/>Закінчення "/playlist.m3u8" додається автоматично, якщо його немає.',
    "Enter the VPortal link as shown in the cabinet":
        "Введіть посилання VPortal з особистого кабінету",
    "Enter this link in VPortal link. Playlist URL requires an M3U playlist.":
        "Введіть це посилання в поле VPortal. Адреса списку відтворення має вести до списку M3U.",
    "Enter this player's device access code to connect.":
        "Для підключення введіть код доступу цього програвача.",
    "Enter username": "Введіть ім’я користувача",
    "Enter value": "Введіть значення",
    "Enter Xtream server URL": "Введіть адресу сервера Xtream",
    "Enter Xtream server URL (e.g. https://your-server:8080)":
        "Введіть адресу сервера Xtream (наприклад, https://your-server:8080)",
    EPG: "Програма",
    "EPG and archive. Channel: ": "Програма й архів. Канал: ",
    "ERROR!": "Помилка!",
    "Error Code!": "Неправильний код!",
    Exit: "Вихід",
    "Exit player": "Вийти з програвача",
    "Export settings": "Експорт налаштувань",
    "epg.one (Ordered)": "epg.one (За порядком)",
    "epg.one (Standard)": "epg.one (Стандартний)",
    "epg.one (Thematic)": "epg.one (Тематичний)",
    "epgs...": "Програма передач…",
    "Fabryka.TV": "Fabryka.TV",
    "Fabryka.TV settings": "Налаштування Fabryka.TV",
    "Failed to connect to Stalker portal":
        "Не вдалося підключитися до порталу Stalker",
    "Failed to connect to Xtream API server":
        "Не вдалося підключитися до сервера Xtream API",
    "Failed to get user data!!!": "Не вдалося отримати дані користувача!",
    "Failed to load channel list!": "Не вдалося завантажити список каналів!",
    "Failed to load channels from Stalker portal":
        "Не вдалося завантажити канали з порталу Stalker",
    "Failed to load channels from Xtream API":
        "Не вдалося завантажити канали з Xtream API",
    "Failed to load!": "Не вдалося завантажити!",
    "Favorite lists": "Списки обраного",
    Favorites: "Обрані",
    "File selection is not supported on this device":
        "Вибір файлу не підтримується на цьому пристрої",
    Filters: "Фільтри",
    "First Run Setup": "Початкове налаштування",
    "Font type": "Шрифт",
    "For download settings file open":
        "Щоб завантажити файл налаштувань, відкрийте",
    "For enter value open": "Щоб ввести значення, відкрийте",
    "For upload settings file open":
        "Щоб надіслати файл налаштувань, відкрийте",
    "Fox-TV": "Fox-TV",
    "Fox-TV settings": "Налаштування Fox-TV",
    FXML: "FXML",
    "FXML settings": "Налаштування FXML",
    Genre: "Жанр",
    GlanzTV: "GlanzTV",
    "GlanzTV settings": "Налаштування GlanzTV",
    "Go to": "Перейти",
    "GREAT IPTV": "GREAT IPTV",
    "GREAT IPTV settings": "Налаштування GREAT IPTV",
    "Graphical indication": "Графічні індикатори",
    Green: "Зелений",
    "Hide / Return": "Приховати / показати",
    "Hide provider settings?": "Приховати налаштування провайдера?",
    "Hide providers?": "Приховати провайдерів?",
    "History in Media Library": "Історія в медіатеці",
    "History of watched movies": "Історія перегляду",
    "HTTP port": "HTTP-порт",
    "HTTP remote control is unavailable on this device.":
        "HTTP-пульт недоступний на цьому пристрої.",
    ID: "ID",
    "Import settings": "Імпорт налаштувань",
    "In live mode: <br/>": "У прямому ефірі:<br/>",
    Info: "Інфо",
    "Infobar display timeout, s": "Час показу інформаційної панелі, с",
    "Infobar settings": "Налаштування інформаційної панелі",
    Information: "Інформація",
    "Interface credits": "Автори інтерфейсу",
    "Interface settings": "Налаштування інтерфейсу",
    "Interface theme": "Тема інтерфейсу",
    "Interface transparency": "Прозорість інтерфейсу",
    "Invalid channel link! Enter the full host as in the cabinet stream URL (e.g. subdomain.cdn-domain.tld)":
        "Неправильне посилання на канал! Введіть повне ім’я вузла з посилання на потік у кабінеті (наприклад, subdomain.cdn-domain.tld)",
    "IPTV token": "IPTV-токен",
    "IpStream.one": "IpStream.one",
    "IpStream.one settings": "Налаштування IpStream.one",
    Joystick: "Джойстик",
    "KBC (Kinoboom) access data": "Дані доступу KBC (Kinoboom)",
    "KORONA TV": "KORONA TV",
    "KORONA TV settings": "Налаштування KORONA TV",
    "List created": "Список створено",
    "List deleted": "Список видалено",
    "List location": "Розташування списку",
    "List renamed": "Список перейменовано",
    "List type": "Тип списку",
    "Lists settings": "Налаштування списків",
    Live: "Прямий ефір",
    Load: "Завантажити",
    "Load built-in playlist:": "Завантажити вбудований список:",
    "Load playlist": "Завантажити плейлист",
    "Load settings": "Завантажити налаштування",
    "Load settings from storage": "Завантажити налаштування зі сховища",
    "Load:": "Завантажити:",
    "Loading channels from Xtream API...": "Завантаження каналів з Xtream API…",
    "Loading channels...": "Завантаження каналів…",
    "Loading from API...": "Завантаження через API…",
    "Loading from Edem API...": "Завантаження з Edem API…",
    "Loading M3U playlist...": "Завантаження списку M3U…",
    "Loading M3U...": "Завантаження M3U…",
    "Loading via proxy...": "Завантаження через проксі…",
    "Loading. Please wait...": "Завантаження. Зачекайте…",
    "Loading...": "Завантаження…",
    "Local HTTP remote control": "Локальний HTTP-пульт",
    "Local URL": "Локальна адреса",
    Login: "Логін",
    lang: "Українська",
    large: "великий",
    left: "ліворуч",
    "left-bottom": "ліворуч унизу",
    "logos...": "Логотипи…",
    M3U: "M3U",
    "M3U URL": "Адреса M3U",
    "M3U URL (fallback)": "Адреса M3U (резервна)",
    "MAC address": "MAC-адреса",
    "Manage lists": "Керування списками",
    "Manage settings": "Керування налаштуваннями",
    "Manual setup": "Ручне налаштування",
    MaxTV: "MaxTV",
    "MaxTV settings": "Налаштування MaxTV",
    Media: "Медіа",
    "Media item is no longer available": "Цей матеріал більше недоступний",
    "Media Library": "Медіатека",
    "Media Library URL": "Адреса медіатеки",
    Menu: "Меню",
    "Menu items settings": "Налаштування пунктів меню",
    "Move category down": "Перемістити категорію вниз",
    "Move category up": "Перемістити категорію вгору",
    "Move channel down": "Перемістити канал вниз",
    "Move channel up": "Перемістити канал вгору",
    "m3u-m3u8 playlists": "Плейлисти m3u-m3u8",
    medium: "середній",
    min: "хв",
    "New Look": "New Look",
    "New Look settings": "Налаштування New Look",
    "New list name": "Назва нового списку",
    Next: "Наступна сторінка",
    "Next keyboard page": "Наступна сторінка клавіатури",
    "Next TV program": "Наступна передача",
    No: "Ні",
    "No channel name": "Немає назви каналу",
    "No saved settings found": "Збережені налаштування не знайдено",
    "Not found": "Не знайдено",
    "Not reduce video when showing the list (bugfix)":
        "Не зменшувати відео під час показу списку (виправлення)",
    Nothing: "Нічого",
    "Number of next TV programs in channel list":
        "Кількість наступних передач у списку каналів",
    "Number of rows in lists": "Кількість рядків у списках",
    native: "рідний",
    no: "ні",
    "no epg at current time": "Немає програми на поточний час",
    "not set": "не задано",
    Off: "Вимкнено",
    Ok: "ОК",
    Open: "Відкрити",
    "Open in PiP": "Відкрити в PiP",
    "OTT Prime ONLINE": "OTT Prime ONLINE",
    "OTT Prime ONLINE settings": "Налаштування OTT Prime ONLINE",
    "OttPlay FOSS %1 is available. Download and install now?":
        "Доступний OttPlay FOSS %1. Завантажити й установити зараз?",
    "Overwrite current settings?": "Перезаписати поточні налаштування?",
    off: "вимкнено",
    on: "увімкнено",
    "on ": "за ",
    "or scan": "або відскануйте",
    "Parental control": "Батьківський контроль",
    Password: "Пароль",
    Pause: "Пауза",
    "Pause/Play": "Пауза / відтворення",
    "Permanent clock on screen": "Постійний годинник на екрані",
    PIN: "PIN",
    "PiP exchange": "Поміняти вікна PiP місцями",
    "PiP window position": "Розташування вікна PiP",
    "PiP window size": "Розмір вікна PiP",
    Play: "Відтворити",
    "Player and device info": "Інформація про програвач і пристрій",
    "Player info:": "Інформація про програвач:",
    Playlist: "Плейлист",
    "Playlist file": "Файл плейлиста",
    "Playlist is not loading directly...Loading via server...":
        "Плейлист не завантажується напряму...Завантаження через сервер...",
    "Playlist Name": "Назва плейлиста",
    "Playlist URL": "Адреса плейлиста",
    POLMEDIA: "POLMEDIA",
    "POLMEDIA settings": "Налаштування POLMEDIA",
    "Portal URL": "Адреса порталу",
    "Position shift -10 seconds after pause":
        "Відступити на 10 секунд після паузи",
    PROST: "PROST",
    "PROST settings": "Налаштування PROST",
    Prev: "Попередня",
    "Preview in channel list": "Попередній перегляд у списку каналів",
    Previous: "Попередній канал",
    "Privacy policy": "Політика конфіденційності",
    "Protect Adult Channels": "Захистити канали для дорослих",
    "Protect Change Provider": "Захистити зміну провайдера",
    "Protect Settings": "Захистити налаштування",
    "p...": "с…",
    paging: "гортання сторінок",
    Quality: "Якість",
    Rating: "Рейтинг",
    RD: "RD",
    "RD settings": "Налаштування RD",
    "Reconnecting…": "Повторне підключення…",
    Records: "Записи",
    "Records for channel: ": "Записи каналу: ",
    "Records library is empty": "Бібліотека записів порожня",
    "Records not supported by provider": "Провайдер не підтримує записи",
    "Release date": "Дата виходу",
    "Remember previous channels": "Запам’ятовувати попередні канали",
    "Reminder: %1 — %2 in %3 min": "Нагадування: %1 — %2 через %3 хв",
    "Remote (color buttons N/A)": "Пульт без кольорових кнопок",
    "Remote (number buttons N/A)": "Пульт без цифрових кнопок",
    "Remote control": "Віддалене керування",
    "Remote session expired": "Сеанс віддаленого доступу завершився",
    "Remote text entry denied": "Віддалене введення тексту заборонено",
    "Remote text entry error": "Помилка віддаленого введення тексту",
    "Remote text entry not configured":
        "Віддалене введення тексту не налаштовано",
    "Remote text entry requires a Device ID. Ask the server operator to provision one.":
        "Для віддаленого введення тексту потрібен ID пристрою. Попросіть адміністратора сервера його надати.",
    "Remove timer?": "Видалити таймер?",
    Rename: "Перейменувати",
    "Rename category": "Перейменувати категорію",
    "Rename to": "Перейменувати на",
    "Repeat parental code": "Повторіть батьківський код",
    "Request sended!": "Запит надіслано!",
    "Restart player": "Перезапустити програвач",
    "Restart stream": "Перезапустити потік",
    "Restart stream / Live": "Перезапустити потік / прямий ефір",
    "Resume from archive?": "Продовжити з архіву?",
    "Return to previous channel": "Повернутися до попереднього каналу",
    Rewind: "Перемотування",
    "Rewind step by buttons %1/%2": "Крок перемотування кнопками %1/%2",
    RUSSKOETV: "RUSSKOETV",
    "RUSSKOETV settings": "Налаштування RUSSKOETV",
    Russian: "Російська",
    right: "праворуч",
    Saturation: "Насиченість",
    "Save & load channels": "Зберегти й завантажити канали",
    "Save and load": "Зберегти й завантажити",
    "Save and load channels": "Зберегти й завантажити канали",
    "Save Settings": "Зберегти налаштування",
    "Save settings": "Зберегти налаштування",
    "Save settings and load channel list":
        "Зберегти налаштування й завантажити список каналів",
    "Save settings to storage": "Зберегти налаштування у сховищі",
    Script: "Сценарій",
    Search: "Пошук",
    "Search programme": "Пошук передачі",
    "Select a stream type:<br>%1": "Виберіть тип потоку:<br>%1",
    "Select category to add channel": "Вибір категорії для додавання каналу",
    "Select color": "Виберіть колір",
    "Select menu items": "Виберіть пункти меню",
    "Select playlist": "Виберіть плейлист",
    "Select playlist file": "Вибір файлу плейлиста",
    "Select playlist template source for EPG and logos":
        "Виберіть шаблон списку для програми передач і логотипів",
    "Send request": "Надіслати запит",
    "Send settings": "Надіслати налаштування",
    "Send this code from your proxy in the Authorization: Bearer header.":
        "Передавайте цей код із проксі в заголовку Authorization: Bearer.",
    Server: "Сервер",
    "Server address": "Адреса сервера",
    "Server address (for example 192.168.1.20:8081)":
        "Адреса сервера (наприклад, 192.168.1.20:8081)",
    "Server device access code": "Код доступу пристрою на сервері",
    "Server URL": "Адреса сервера",
    "Server unavailable. Retrying automatically; check its address and network access.":
        "Сервер недоступний. Спробу буде повторено автоматично; перевірте адресу й доступ до мережі.",
    Set: "Установити",
    "Set parental code": "Установіть батьківський код",
    "Set timer?": "Установити таймер?",
    Settings: "Налаштування",
    "Settings could not be saved": "Не вдалося зберегти налаштування",
    "Settings loaded from storage": "Налаштування завантажено зі сховища",
    "Settings STB": "Налаштування пристрою",
    "Settings saved": "Налаштування збережено",
    "Settings saved to storage": "Налаштування збережено у сховищі",
    "Settings sended!": "Налаштування надіслано!",
    "Shara.club (ClubTV.pro)": "Shara.club (ClubTV.pro)",
    "Shara.club (ClubTV.pro) settings": "Налаштування Shara.club (ClubTV.pro)",
    ShockTv: "ShockTv",
    "ShockTv settings": "Налаштування ShockTv",
    "Show archive availability in list": "Показувати наявність архіву в списку",
    "Show channel name in list": "Показувати назву каналу в списку",
    "Show channel number in list": "Показувати номер каналу в списку",
    "Show channel selection list": "Показати список вибору каналів",
    "Show description": "Показувати опис",
    "Show EPG and archive for channel": "Показати програму й архів каналу",
    "Show list of channel archive records": "Показати записи каналу",
    "Show list of channel archive records without duplication":
        "Показати записи каналу без повторів",
    "Show Media Library": "Показати медіатеку",
    "Show picons in channel list": "Показувати значки каналів у списку",
    "Show player menu": "Показати меню програвача",
    "Show program name": "Показувати назву передачі",
    "Show progress in channel list": "Показувати перебіг у списку каналів",
    "Show provider settings?": "Показати налаштування провайдера?",
    "Show providers?": "Показати провайдерів?",
    "Show rewind window": "Показати вікно перемотування",
    "Show scrollbar in list": "Показувати смугу прокручування у списках",
    "Show thumbnails": "Показувати мініатюри",
    "Show when changing program": "Показувати під час зміни передачі",
    "Show when rewind": "Показувати під час перемотування",
    "Show when switching": "Показувати під час перемикання каналів",
    "Sleep timer": "Таймер сну",
    "Sort channels": "Сортувати канали",
    "Stalker Portal Provider": "Провайдер порталу Stalker",
    "Stalker portal settings": "Налаштування порталу Stalker",
    "Stalker portals": "Портали Stalker",
    Status: "Стан",
    "Stop playback and return to live":
        "Зупинити відтворення й повернутися до ефіру",
    "Stream type: %1": "Тип потоку: %1",
    "String for search": "Пошуковий запит",
    "Su Mo Tu We Th Fr Sa": "Нд Пн Вт Ср Чт Пт Сб",
    Subtitle: "Субтитри",
    Switch: "Перемкнути",
    "Switch sound track": "Змінити звукову доріжку",
    "Switch subtitle": "Змінити субтитри",
    "Switch to this list": "Перемкнутися на цей список",
    "Swop URL": "Адреса Swop",
    "saved on this device": "збережено на цьому пристрої",
    select: "вибрати",
    small: "малий",
    system: "системний",
    Tabox: "Tabox",
    "Tabox settings": "Налаштування Tabox",
    "The device ID in the address is invalid.":
        "В адресі вказано неправильний ID пристрою.",
    "This HTTPS player cannot connect to an HTTP server. Use an HTTPS server or open the player over HTTP.":
        "Цей HTTPS-програвач не може підключитися до HTTP-сервера. Використовуйте HTTPS-сервер або відкрийте програвач через HTTP.",
    "This Play app requires HTTPS. Ask your provider for an HTTPS playlist or server URL.":
        "Для цієї версії з Play потрібен HTTPS. Попросіть у провайдера HTTPS-адресу списку або сервера.",
    Timer: "Таймер",
    "Timer: switch to channel?": "Таймер: перемкнути канал?",
    "Timeshift: one minute back": "Таймшифт: на хвилину назад",
    "Timeshift: to start of TV program": "Таймшифт: до початку передачі",
    Timezone: "Часовий пояс",
    TMDb: "TMDb",
    "TOP-IPTV": "TOP-IPTV",
    "TOP-IPTV settings": "Налаштування TOP-IPTV",
    "To begining": "На початок",
    "To start of TV program / Previous TV program":
        "До початку передачі / попередня передача",
    "Toggle Aspect Ratio": "Змінити співвідношення сторін",
    "Toggle on-screen debug HUD": "Показати або приховати панель налагодження",
    "Toggle Zoom Mode": "Змінити режим масштабування",
    "Top-Tv": "Top-Tv",
    "Top-Tv settings": "Налаштування Top-Tv",
    "Try demo": "Спробувати демо",
    "TV DOSUG": "TV DOSUG",
    "TV DOSUG settings": "Налаштування TV DOSUG",
    TVClub: "TVClub",
    "TVClub settings": "Налаштування TVClub",
    "Type of player for streaming": "Тип плеєра для потокової передачі",
    "top-left": "ліворуч угорі",
    "top-right": "праворуч угорі",
    transparent: "прозорий",
    ULTIFL1X: "ULTIFL1X",
    "ULTIFL1X settings": "Налаштування ULTIFL1X",
    "Update installed. Please restart OttPlay FOSS.":
        "Оновлення встановлено. Перезапустіть OttPlay FOSS.",
    "Use an HTTP or HTTPS server address.":
        "Використовуйте HTTP- або HTTPS-адресу сервера.",
    "Use HTTP or HTTPS without a username or password in the address.":
        "Використовуйте HTTP або HTTPS без імені користувача й пароля в адресі.",
    "Use LEFT/RIGHT to select a control, OK to activate, and UP/DOWN to scroll.":
        "ЛІВОРУЧ/ПРАВОРУЧ — вибрати елемент, OK — виконати дію, ВГОРУ/ВНИЗ — прокрутити.",
    Username: "Ім’я користувача",
    "Username or password is missing.":
        "Не вказано ім’я користувача або пароль.",
    "VIP-IP.COM": "VIP-IP.COM",
    "VIP-IP.COM settings": "Налаштування VIP-IP.COM",
    "Vidok.TV": "Vidok.TV",
    "Vidok.TV settings": "Налаштування Vidok.TV",
    "VOD not supported by provider": "Провайдер не підтримує відео на запит",
    "Volume step, %": "Крок гучності, %",
    "VPortal link": "Посилання VPortal",
    "VPortal request failed":
        "Не вдалося завантажити VPortal. Перевірте посилання, ключ доступу й доступність порталу.",
    volume: "гучність",
    "Wrong parental code !!!": "Невірний батьківський код!!!",
    "Xtream Codes Provider": "Провайдер Xtream Codes",
    "Xtream Codes settings": "Налаштування Xtream Codes",
    Year: "Рік",
    Yellow: "Жовтий",
    Yes: "Так",
    yes: "так",
    "Гомельсат (cbilling)": "Гомельсат (cbilling)",
    "Гомельсат (cbilling) settings": "Налаштування Гомельсат (cbilling)",
    МойДом: "МойДом",
    "МойДом settings": "Налаштування МойДом",
    "Ошибка обработки списка каналов! Проверьте правильность данных!!":
        "Помилка обробки списку каналів! Перевірте дані провайдера!",
    Радуга: "Радуга",
    "Радуга settings": "Налаштування Радуга",
    "Редактирование ID": "Змінити ID",
    "Редактирование PIN": "Змінити PIN",
    Шаравоз: "Шаравоз",
    "Шаравоз settings": "Налаштування Шаравоз",
    "↑↓ Scroll": "↑↓ Прокручування",
};
