var keyStrings = {
    " (after changing, load playlist)":
        " (o'zgartirishdan so'ng, playlistni yuklang)",
    " added to category ": " kategoriyaga qo'shildi ",
    " added to favorites": " sevimlilarga qo'shildi",
    "??? No channel name": "??? Kanal nomi yo'q",
    Actions: "Harakatlar",
    "Add channel to category": "Kanalni kategoriyaga qo'shish",
    "Add channel to favorites": "Kanalni sevimlilarga qo'shish",
    All: "Barchasi",
    "Applying HTTP remote settings...":
        "HTTP pulti sozlamalari qo‘llanmoqda...",
    "Archive hours": "Arxiv soatlari",
    alhabet: "abdefghijklmnopqrstuvxyz",
    "Buffer Size, s": "Bufer hajmi, s",
    "built-in": "o'rnatilgan",
    Category: "Kategoriya",
    "Channel ": "Kanal ",
    "Channel is not available!!!": "Kanal mavjud emas!!!",
    "Channel list": "Kanallar ro'yxati",
    "Channel list not received !!!": "Kanallar ro'yxati olinmadi!!!",
    "Channel list not received !!!<br/><br/>Enter the provider data and restart the player !!!<br/><br/>":
        "Kanallar ro'yxati olinmadi!!!<br/><br/>Provayder ma'lumotlarini kiriting va pleerni qayta ishga tushiring!!!<br/><br/>",
    "Channel list. Category: ": "Kanallar ro'yxati. Kategoriya: ",
    "Channel parental control": "Kanal ota-ona nazorati",
    Close: "Yopish",
    "Could not update HTTP remote control.":
        "HTTP pulti sozlamalarini yangilab bo‘lmadi.",
    "Delete channel": "Kanalni o'chirish",
    Description: "Tavsif",
    "Device access code": "Qurilmaga kirish kodi",
    "Disable HTTP remote": "HTTP pultini o‘chirish",
    "Disabled by default. Enabling creates a new device access code.":
        "Dastlab o‘chirilgan. Yoqilganda qurilmaga kirish uchun yangi kod yaratiladi.",
    Edit: "Tahrirlash",
    "Edit category name": "Kategoriya nomini tahrirlash",
    "Edit playlist data": "Playlist ma'lumotlarini tahrirlash",
    Editor: "Muharrir",
    "Enable HTTP remote": "HTTP pultini yoqish",
    "Enter Media Library URL": "Media kutubxonasi URL kiriting",
    "Enter parental code": "Ota-ona kodini kiriting",
    "Enter playlist archive hours": "Playlist arxiv soatlarini kiriting",
    "Enter playlist Name": "Playlist nomini kiriting",
    "Enter playlist URL": "Playlist URL kiriting",
    EPG: "TV dasturi",
    Exit: "Chiqish",
    "Failed to load channel list!":
        "Kanallar ro'yxatini yuklash muvaffaqiyatsiz tugadi!",
    Favorites: "Sevimlilar",
    "HTTP port": "HTTP porti",
    "HTTP remote control is unavailable on this device.":
        "Bu qurilmada HTTP pulti mavjud emas.",
    Info: "Ma'lumot",
    Load: "Yuklash",
    "Load playlist": "Playlistni yuklash",
    "Local HTTP remote control": "Mahalliy HTTP pulti",
    lang: "O'zbekcha",
    "Media Library URL": "Media kutubxonasi URL",
    Menu: "Menyu",
    "Move channel down": "Kanalni pastga siljitish",
    "Move channel up": "Kanalni yuqoriga siljitish",
    "m3u-m3u8 playlists": "m3u-m3u8 playlistlar",
    min: "daq",
    "No channel name": "Kanal nomi yo'q",
    Nothing: "Hech narsa",
    native: "mahalliy",
    no: "yo'q",
    "Open in PiP": "PiP da ochish",
    off: "o'chirilgan",
    on: "yoqilgan",
    Playlist: "Playlist",
    "Playlist file": "Playlist fayli",
    "Playlist is not loading directly...Loading via server...":
        "Playlist to'g'ridan-to'g'ri yuklanmayapti...Server orqali yuklanmoqda...",
    "Playlist Name": "Playlist nomi",
    "Playlist URL": "Playlist URL",
    "Remote control": "Masofadan boshqarish",
    "Save Settings": "Sozlamalarni saqlash",
    Search: "Qidirish",
    "Select category to add channel":
        "Kanal qo'shish uchun kategoriyani tanlang",
    "Select playlist": "Playlistni tanlang",
    "Select playlist file": "Playlist faylini tanlang",
    "Send this code from your proxy in the Authorization: Bearer header.":
        "Bu kodni proksidan Authorization: Bearer sarlavhasida yuboring.",
    Settings: "Sozlamalar",
    "Settings STB": "STB sozlamalari",
    "Settings saved": "Sozlamalar saqlandi",
    "Stalker portals": "Stalker portallari",
    "Type of player for streaming": "Strime uchun pleer turi",
    "Wrong parental code !!!": "Noto'g'ri ota-ona kodi!!!",
    yes: "ha",
};
