var keyStrings = {
 "lang": "O'zbekcha",
 "alhabet": "abdefghijklmnopqrstuvxyz",
 "Channel list. Category: ": "Kanallar ro'yxati. Kategoriya: ",
 "EPG": "TV dasturi",
 "Category": "Kategoriya",
 "Actions": "Harakatlar",
 "Description": "Tavsif",
 "Open in PiP": "PiP da ochish",
 "Move channel up": "Kanalni yuqoriga siljitish",
 "Move channel down": "Kanalni pastga siljitish",
 "Delete channel": "Kanalni o'chirish",
 "Add channel to category": "Kanalni kategoriyaga qo'shish",
 "Add channel to favorites": "Kanalni sevimlilarga qo'shish",
 "Channel parental control": "Kanal ota-ona nazorati",
 "Channel is not available!!!": "Kanal mavjud emas!!!",
 "min": "daq",
 "Channel ": "Kanal ",
 " added to category ": " kategoriyaga qo'shildi ",
 " added to favorites": " sevimlilarga qo'shildi",
 "Favorites": "Sevimlilar",
 "Select category to add channel": "Kanal qo'shish uchun kategoriyani tanlang",
 "Enter parental code": "Ota-ona kodini kiriting",
 "Wrong parental code !!!": "Noto'g'ri ota-ona kodi!!!",
 "Close": "Yopish",
 "Edit category name": "Kategoriya nomini tahrirlash",
 "Menu": "Menyu",
 "Channel list": "Kanallar ro'yxati",
 "Settings": "Sozlamalar",
 "Settings saved": "Sozlamalar saqlandi",
 "no": "yo'q",
 "yes": "ha",
 "Info": "Ma'lumot",
 "Nothing": "Hech narsa",
 "Exit": "Chiqish",
 "off": "o'chirilgan",
 "Failed to load channel list!": "Kanallar ro'yxatini yuklash muvaffaqiyatsiz tugadi!",
 "??? No channel name": "??? Kanal nomi yo'q",
 "Playlist URL": "Playlist URL",
 "Archive hours": "Arxiv soatlari",
 "Enter playlist URL": "Playlist URL kiriting",
 "Playlist Name": "Playlist nomi",
 "Enter playlist Name": "Playlist nomini kiriting",
 "Media Library URL": "Media kutubxonasi URL",
 "Enter Media Library URL": "Media kutubxonasi URL kiriting",
 "Playlist": "Playlist",
 "Playlist is not loading directly...Loading via server...": "Playlist to'g'ridan-to'g'ri yuklanmayapti...Server orqali yuklanmoqda...",
 "Select playlist": "Playlistni tanlang",
 "Edit": "Tahrirlash",
 "Load": "Yuklash",
 "Edit playlist data": "Playlist ma'lumotlarini tahrirlash",
 "All": "Barchasi",
 "Search": "Qidirish",
 "m3u-m3u8 playlists": "m3u-m3u8 playlistlar",
 "Stalker portals": "Stalker portallari",
 "Settings STB": "STB sozlamalari",
 "Type of player for streaming": "Strime uchun pleer turi",
 "Buffer Size, s": "Bufer hajmi, s",
 "Save Settings": "Sozlamalarni saqlash",
 "Editor": "Muharrir",
 "built-in": "o'rnatilgan",
 "native": "mahalliy",
 "No channel name": "Kanal nomi yo'q",
 " (after changing, load playlist)": " (o'zgartirishdan so'ng, playlistni yuklang)",
 "Enter playlist archive hours": "Playlist arxiv soatlarini kiriting",
 "Load playlist": "Playlistni yuklash",
 "Playlist file": "Playlist fayli",
 "Select playlist file": "Playlist faylini tanlang",
 "Channel list not received !!!<br/><br/>Enter the provider data and restart the player !!!<br/><br/>": "Kanallar ro'yxati olinmadi!!!<br/><br/>Provayder ma'lumotlarini kiriting va pleerni qayta ishga tushiring!!!<br/><br/>",
 "Channel list not received !!!": "Kanallar ro'yxati olinmadi!!!"
};
