var keyStrings = {
    " (after changing, load playlist)":
        " (tải lại danh sách phát sau khi thay đổi)",
    " (after changing, restart player)":
        " (khởi động lại trình phát sau khi thay đổi)",
    " added to category ": " đã thêm vào danh mục ",
    " added to favorites": " đã thêm vào yêu thích",
    " m ": " phút ",
    " s": " giây",
    "??? No channel name": "??? Kênh không có tên",
    '"As Is"': '"Nguyên bản"',
    '"Favorites"': '"Yêu thích"',
    '"Sliding" infobar': "Thanh thông tin trượt",
    "&darr;a": "&darr;a",
    "&uarr;A": "&uarr;A",
    "<br/><br/>In archive mode:<br/>": "<br/><br/>Trong chế độ lưu trữ:<br/>",
    "<br/>Loading STB...": "<br/>Đang tải STB…",
    "<br/>Setup STB...": "<br/>Đang thiết lập STB…",
    "<br>": "<br>",
    "<br><br>": "<br><br>",
    "<br>Add<br>to category": "<br>Thêm vào<br>danh mục",
    "<br>Add<br>to favorites": "<br>Thêm vào<br>yêu thích",
    "<br>Delete": "<br>Xóa",
    "<br>Down<br>": "<br>Xuống<br>",
    "<br>Live": "<br>Trực tiếp",
    "<br>Menu": "<br>Menu",
    "<br>Parental<br>Control": "<br>Kiểm soát<br>của phụ huynh",
    "<br>Pause<br>": "<br>Tạm dừng<br>",
    "<br>Previous<br>channel": "<br>Kênh<br>trước",
    "<br>Rewind<br>": "<br>Tua lại<br>",
    "<br>Toggle<br>sound track": "<br>Đổi<br>luồng âm thanh",
    "<br>Up<br>": "<br>Lên<br>",
    "1 hour": "1 giờ",
    "1 minute": "1 phút",
    "2 hours": "2 giờ",
    "3 hours": "3 giờ",
    "10 Seconds": "10 giây",
    "30 minutes": "30 phút",
    "A command expired while the player was loading channels.":
        "Một lệnh đã hết hạn trong khi trình phát đang tải kênh.",
    "A command was rejected by the player. Check its provider and settings.":
        "Trình phát đã từ chối một lệnh. Kiểm tra nhà cung cấp và cài đặt.",
    About: "Giới thiệu",
    "Access code": "Mã truy cập",
    "Access denied. Check the server access code.":
        "Truy cập bị từ chối. Kiểm tra mã truy cập máy chủ.",
    "Access key": "Khóa truy cập",
    "Access key is required!": "Cần có khóa truy cập!",
    "Access settings": "Cài đặt truy cập",
    Actions: "Thao tác",
    "Active list": "Danh sách hiện tại",
    Actors: "Diễn viên",
    "Add / rename / delete…": "Thêm / đổi tên / xóa…",
    "Add channel to category": "Thêm kênh vào danh mục",
    "Add channel to favorites": "Thêm kênh vào yêu thích",
    "Add new list": "Thêm danh sách mới",
    "Add to favorites": "Thêm vào yêu thích",
    Age: "Độ tuổi",
    All: "Tất cả",
    "All categories": "Tất cả danh mục",
    "All4you.tv": "All4you.tv",
    "All4you.tv settings": "Cài đặt All4you.tv",
    "Allowlist this Device ID": "Cho phép ID thiết bị này",
    "An IP without a port uses HTTP port 8081. Clear the address or select Disconnect to stop.":
        "Địa chỉ IP không có cổng sẽ dùng cổng HTTP 8081. Xóa địa chỉ hoặc chọn Ngắt kết nối để dừng.",
    "API failed, trying M3U...": "API thất bại, đang thử M3U…",
    "API Server": "Máy chủ API",
    "API server URL": "URL máy chủ API",
    "Applying HTTP remote settings...":
        "Đang áp dụng cài đặt điều khiển từ xa HTTP…",
    Archive: "Lưu trữ",
    "Archive - begin": "Lưu trữ — bắt đầu",
    "Archive hours": "Số giờ lưu trữ",
    "Archive: ENTER on past programs":
        "Lưu trữ: nhấn ENTER trên chương trình đã phát",
    "Archive. Channel: ": "Lưu trữ. Kênh: ",
    Aspect: "Tỷ lệ khung hình",
    Audio: "Âm thanh",
    alhabet:
        "aàảãáạăằẳẵắặâầẩẫấậbcdđeèẻẽéẹêềểễếệghiìỉĩíịklmnoòỏõóọôồổỗốộơờởỡớợpqrstuùủũúụưừửữứựvxyỳỷỹýỵ",
    always: "luôn luôn",
    "and enter code": "và nhập mã",
    Back: "Quay lại",
    "Back / Forward for 1 minute": "Tua lùi / tiến 1 phút",
    "Background color": "Màu nền",
    "Background color of selected item": "Màu nền mục được chọn",
    "BEST LiST IPTV [HLS Playlist]": "BEST LiST IPTV [HLS Playlist]",
    "BEST LiST IPTV [HLS Playlist] settings":
        "Cài đặt BEST LiST IPTV [HLS Playlist]",
    "BEST LiST IPTV [Stalker]": "BEST LiST IPTV [Stalker]",
    "BEST LiST IPTV [Stalker] settings": "Cài đặt BEST LiST IPTV [Stalker]",
    "Behavior of %1/%2 buttons in lists":
        "Hoạt động của nút %1/%2 trong danh sách",
    "Black screen while switching the channel": "Màn hình đen khi chuyển kênh",
    Blue: "Xanh dương",
    "Bookmark age: %1 days": "Tuổi dấu trang: %1 ngày",
    "Buffer Size, s": "Dung lượng bộ đệm, giây",
    "Built-in playlist:": "Danh sách phát tích hợp:",
    "Built-in playlists": "Danh sách phát tích hợp",
    "Button %1 function when viewing": "Chức năng nút %1 khi xem",
    "Button function %1 when viewing archive":
        "Chức năng nút %1 khi xem lưu trữ",
    "Buttons settings": "Cài đặt nút",
    "By alphabet": "Theo bảng chữ cái",
    "By time": "Theo thời gian",
    "begin/end": "đầu/cuối",
    "bottom-right": "dưới phải",
    "built-in": "tích hợp",
    "Call PiP": "Mở PiP",
    "Call PiP / PiP exchange": "Mở PiP / đổi PiP",
    Cancel: "Hủy",
    "Cannot delete the last category": "Không thể xóa danh mục cuối cùng",
    Category: "Danh mục",
    "Category selection": "Chọn danh mục",
    "Change interface language": "Đổi ngôn ngữ giao diện",
    "Change provider": "Đổi nhà cung cấp",
    "Change provider - you can change the provider, and it will be remembered at the next start of player!":
        "Đổi nhà cung cấp. Lựa chọn sẽ được ghi nhớ vào lần khởi động trình phát tiếp theo.",
    "Change value": "Đổi giá trị",
    "Channel ": "Kênh ",
    "Channel has no EPG": "Kênh không có EPG",
    "Channel is not available!!!": "Kênh không khả dụng!",
    "Channel link": "Liên kết kênh",
    "Channel link is required!": "Cần có liên kết kênh!",
    "Channel list": "Danh sách kênh",
    "Channel list editing style": "Chế độ chỉnh sửa danh sách kênh",
    "Channel list not received !!!": "Chưa nhận được danh sách kênh!",
    "Channel list not received !!!<br/><br/>Enter the provider data and restart the player !!!<br/><br/>":
        "Chưa nhận được danh sách kênh!<br/><br/>Nhập thông tin nhà cung cấp và khởi động lại trình phát.<br/><br/>",
    "Channel list settings": "Cài đặt danh sách kênh",
    "Channel list. Category: ": "Danh sách kênh. Danh mục: ",
    "Channel parental control": "Kiểm soát kênh của phụ huynh",
    Channels: "Kênh",
    "Choose from": "Chọn từ",
    "Choose language": "Chọn ngôn ngữ",
    "Choose provider": "Chọn nhà cung cấp",
    Classic: "Cổ điển",
    "Clear all settings?": "Xóa tất cả cài đặt?",
    "Clear settings": "Xóa cài đặt",
    Close: "Đóng",
    "Close PiP": "Đóng PiP",
    Color: "Màu",
    "Color spectrum": "Phổ màu",
    "Command server": "Máy chủ lệnh",
    "Command server address, device access code, local HTTP control, and remote text entry settings":
        "Địa chỉ máy chủ lệnh, mã truy cập thiết bị, điều khiển HTTP cục bộ và cài đặt nhập văn bản từ xa",
    "Configure All4you.tv in Settings -> Provider Settings":
        "Cấu hình All4you.tv trong Cài đặt -> Cài đặt nhà cung cấp",
    "Configure BEST LiST IPTV [HLS Playlist] in Settings -> Provider Settings":
        "Cấu hình BEST LiST IPTV [HLS Playlist] trong Cài đặt -> Cài đặt nhà cung cấp",
    "Configure BEST LiST IPTV [Stalker] in Settings -> Provider Settings":
        "Cấu hình BEST LiST IPTV [Stalker] trong Cài đặt -> Cài đặt nhà cung cấp",
    "Configure Diamond TV in Settings -> Provider Settings":
        "Cấu hình Diamond TV trong Cài đặt -> Cài đặt nhà cung cấp",
    "Configure DRVAO in Settings -> Provider Settings":
        "Cấu hình DRVAO trong Cài đặt -> Cài đặt nhà cung cấp",
    "Configure Dragon Media PRO in Settings -> Provider Settings":
        "Cấu hình Dragon Media PRO trong Cài đặt -> Cài đặt nhà cung cấp",
    "Configure Fabryka.TV in Settings -> Provider Settings":
        "Cấu hình Fabryka.TV trong Cài đặt -> Cài đặt nhà cung cấp",
    "Configure Fox-TV in Settings -> Provider Settings":
        "Cấu hình Fox-TV trong Cài đặt -> Cài đặt nhà cung cấp",
    "Configure FXML in Settings -> Provider Settings":
        "Cấu hình FXML trong Cài đặt -> Cài đặt nhà cung cấp",
    "Configure GlanzTV in Settings -> Provider Settings":
        "Cấu hình GlanzTV trong Cài đặt -> Cài đặt nhà cung cấp",
    "Configure GREAT IPTV in Settings -> Provider Settings":
        "Cấu hình GREAT IPTV trong Cài đặt -> Cài đặt nhà cung cấp",
    "Configure IpStream.one in Settings -> Provider Settings":
        "Cấu hình IpStream.one trong Cài đặt -> Cài đặt nhà cung cấp",
    "Configure KORONA TV in Settings -> Provider Settings":
        "Cấu hình KORONA TV trong Cài đặt -> Cài đặt nhà cung cấp",
    "Configure MaxTV in Settings -> Provider Settings":
        "Cấu hình MaxTV trong Cài đặt -> Cài đặt nhà cung cấp",
    "Configure New Look in Settings -> Provider Settings":
        "Cấu hình New Look trong Cài đặt -> Cài đặt nhà cung cấp",
    "Configure OTT Prime ONLINE in Settings -> Provider Settings":
        "Cấu hình OTT Prime ONLINE trong Cài đặt -> Cài đặt nhà cung cấp",
    "Configure POLMEDIA in Settings -> Provider Settings":
        "Cấu hình POLMEDIA trong Cài đặt -> Cài đặt nhà cung cấp",
    "Configure PROST in Settings -> Provider Settings":
        "Cấu hình PROST trong Cài đặt -> Cài đặt nhà cung cấp",
    "Configure RD in Settings -> Provider Settings":
        "Cấu hình RD trong Cài đặt -> Cài đặt nhà cung cấp",
    "Configure RUSSKOETV in Settings -> Provider Settings":
        "Cấu hình RUSSKOETV trong Cài đặt -> Cài đặt nhà cung cấp",
    "Configure Shara.club (ClubTV.pro) in Settings -> Provider Settings":
        "Cấu hình Shara.club (ClubTV.pro) trong Cài đặt -> Cài đặt nhà cung cấp",
    "Configure ShockTv in Settings -> Provider Settings":
        "Cấu hình ShockTv trong Cài đặt -> Cài đặt nhà cung cấp",
    "Configure Tabox in Settings -> Provider Settings":
        "Cấu hình Tabox trong Cài đặt -> Cài đặt nhà cung cấp",
    "Configure TOP-IPTV in Settings -> Provider Settings":
        "Cấu hình TOP-IPTV trong Cài đặt -> Cài đặt nhà cung cấp",
    "Configure Top-Tv in Settings -> Provider Settings":
        "Cấu hình Top-Tv trong Cài đặt -> Cài đặt nhà cung cấp",
    "Configure TV DOSUG in Settings -> Provider Settings":
        "Cấu hình TV DOSUG trong Cài đặt -> Cài đặt nhà cung cấp",
    "Configure TVClub in Settings -> Provider Settings":
        "Cấu hình TVClub trong Cài đặt -> Cài đặt nhà cung cấp",
    "Configure ULTIFL1X in Settings -> Provider Settings":
        "Cấu hình ULTIFL1X trong Cài đặt -> Cài đặt nhà cung cấp",
    "Configure VIP-IP.COM in Settings -> Provider Settings":
        "Cấu hình VIP-IP.COM trong Cài đặt -> Cài đặt nhà cung cấp",
    "Configure Vidok.TV in Settings -> Provider Settings":
        "Cấu hình Vidok.TV trong Cài đặt -> Cài đặt nhà cung cấp",
    "Configure Гомельсат (cbilling) in Settings -> Provider Settings":
        "Cấu hình Гомельсат (cbilling) trong Cài đặt -> Cài đặt nhà cung cấp",
    "Configure МойДом in Settings -> Provider Settings":
        "Cấu hình МойДом trong Cài đặt -> Cài đặt nhà cung cấp",
    "Configure Радуга in Settings -> Provider Settings":
        "Cấu hình Радуга trong Cài đặt -> Cài đặt nhà cung cấp",
    "Configure Шаравоз in Settings -> Provider Settings":
        "Cấu hình Шаравоз trong Cài đặt -> Cài đặt nhà cung cấp",
    Connect: "Kết nối",
    Connected: "Đã kết nối",
    "Connected. Waiting for the channel list...":
        "Đã kết nối. Đang chờ danh sách kênh…",
    "Connecting to Stalker portal...": "Đang kết nối tới cổng Stalker…",
    "Connecting...": "Đang kết nối…",
    "Continue watching?": "Tiếp tục xem?",
    "Copy category": "Sao chép danh mục",
    "Copy JSON": "Sao chép JSON",
    "Could not connect to the server.": "Không thể kết nối tới máy chủ.",
    "Could not update HTTP remote control.":
        "Không thể cập nhật điều khiển từ xa HTTP.",
    Country: "Quốc gia",
    "Create category": "Tạo danh mục",
    current: "hiện tại",
    "Debug HUD": "Bảng gỡ lỗi",
    "Debug HUD is not available": "Bảng gỡ lỗi không khả dụng",
    Delete: "Xóa",
    "Delete category": "Xóa danh mục",
    "Delete channel": "Xóa kênh",
    "Delete list": "Xóa danh sách",
    "Demo — moving test pattern": "Bản thử — hình kiểm tra chuyển động",
    Description: "Mô tả",
    "Description of remote control buttons": "Hướng dẫn nút điều khiển từ xa",
    "Device access code": "Mã truy cập thiết bị",
    "Device info:": "Thông tin thiết bị:",
    "Device MAC is required for KBC (Kinoboom) playlists":
        "Danh sách phát KBC (Kinoboom) yêu cầu địa chỉ MAC của thiết bị",
    "Diamond TV": "Diamond TV",
    "Diamond TV settings": "Cài đặt Diamond TV",
    Director: "Đạo diễn",
    "Disable HTTP remote": "Tắt điều khiển từ xa HTTP",
    "Disabled by default. Enabling creates a new device access code.":
        "Mặc định tắt. Bật tính năng sẽ tạo mã truy cập thiết bị mới.",
    Disconnect: "Ngắt kết nối",
    Disconnected: "Đã ngắt kết nối",
    "Distance between lines in lists": "Khoảng cách dòng trong danh sách",
    "Do you want to exit player?": "Bạn có muốn thoát trình phát?",
    "Download! Wait ...": "Đang tải xuống… vui lòng đợi…",
    DRVAO: "DRVAO",
    "DRVAO settings": "Cài đặt DRVAO",
    "Dragon Media PRO": "Dragon Media PRO",
    "Dragon Media PRO settings": "Cài đặt Dragon Media PRO",
    Duration: "Thời lượng",
    Edit: "Chỉnh sửa",
    "Edit access key": "Chỉnh sửa khóa truy cập",
    "Edit category name": "Chỉnh sửa tên danh mục",
    "Edit channel link": "Chỉnh sửa liên kết kênh",
    "Edit playlist data": "Chỉnh sửa thông tin danh sách phát",
    "Edit VPortal link": "Chỉnh sửa liên kết VPortal",
    Editor: "Trình chỉnh sửa",
    "Enable HTTP remote": "Bật điều khiển từ xa HTTP",
    English: "Tiếng Anh",
    "Enter a password (8 characters).": "Nhập mật khẩu (8 ký tự).",
    "Enter a playlist URL to access this service.":
        "Nhập URL danh sách phát để truy cập dịch vụ này.",
    "Enter a server address without spaces or a fragment.":
        "Nhập địa chỉ máy chủ không có khoảng trắng hoặc phần neo.",
    "Enter a username (8 characters).": "Nhập tên người dùng (8 ký tự).",
    "Enter a username and password to access this service.":
        "Nhập tên người dùng và mật khẩu để truy cập dịch vụ này.",
    "Enter a valid server address, for example 192.168.1.20:8081.":
        "Nhập địa chỉ máy chủ hợp lệ, ví dụ: 192.168.1.20:8081.",
    "Enter access key for": "Nhập khóa truy cập cho",
    "Enter an application access key (8 characters).":
        "Nhập khóa truy cập ứng dụng (8 ký tự).",
    "Enter an ID and PIN to access this service.":
        "Nhập ID và PIN để truy cập dịch vụ này.",
    "Enter an IPTV token (10 characters).": "Nhập mã token IPTV (10 ký tự).",
    "Enter category name": "Nhập tên danh mục",
    "Enter MAC address": "Nhập địa chỉ MAC",
    "Enter MAC address (e.g. 00:1A:2B:3C:4D:5E)":
        "Nhập địa chỉ MAC (ví dụ: 00:1A:2B:3C:4D:5E)",
    "Enter Media Library URL": "Nhập URL thư viện đa phương tiện",
    "Enter new category name": "Nhập tên danh mục mới",
    "Enter Provider Code": "Nhập mã nhà cung cấp",
    "Enter Provider Code on PC or Phone":
        "Nhập mã nhà cung cấp trên máy tính hoặc điện thoại",
    "Enter parental code": "Nhập mã phụ huynh",
    "Enter password": "Nhập mật khẩu",
    "Enter playlist archive hours": "Nhập số giờ lưu trữ của danh sách phát",
    "Enter playlist Name": "Nhập tên danh sách phát",
    "Enter playlist URL": "Nhập URL danh sách phát",
    "Enter Stalker portal URL": "Nhập URL cổng Stalker",
    "Enter Stalker portal URL (e.g. http://your-portal:8800)":
        "Nhập URL cổng Stalker (ví dụ: http://your-portal:8800)",
    "Enter Stalker portal URL (e.g. http://your-portal/stalker_portal/c/)":
        "Nhập URL cổng Stalker (ví dụ: http://your-portal/stalker_portal/c/)",
    "Enter the access code separately, not in the server address.":
        "Nhập mã truy cập riêng, không nhập trong địa chỉ máy chủ.",
    "Enter the command server IP or address.":
        "Nhập IP hoặc địa chỉ máy chủ lệnh.",
    "Enter the full CDN host from the cabinet stream URL (e.g. subdomain.cdn-domain.tld), not a bare subdomain":
        "Nhập tên máy chủ CDN đầy đủ từ URL luồng trong trang tài khoản (ví dụ: subdomain.cdn-domain.tld), không chỉ tên miền phụ",
    "Enter the server IP or address and this player's device access code from the server configuration. Saving both starts checking for volume, channel and other commands automatically.":
        "Nhập IP hoặc địa chỉ máy chủ cùng mã truy cập thiết bị của trình phát này từ cấu hình máy chủ. Lưu cả hai sẽ tự động bắt đầu kiểm tra các lệnh âm lượng, kênh và lệnh khác.",
    "Enter the server's device access code (32–256 letters, digits, _ or -).":
        "Nhập mã truy cập thiết bị của máy chủ (32–256 chữ cái, chữ số, _ hoặc -).",
    'Enter the tv.team playlist URL.<br>Playlist type: <b>OTTPlayer</b><br/><br/>The "/playlist.m3u8" suffix is added automatically if omitted.':
        'Nhập URL danh sách phát tv.team.<br>Loại danh sách phát: <b>OTTPlayer</b><br/><br/>Hậu tố "/playlist.m3u8" sẽ được tự động thêm nếu bỏ qua.',
    "Enter the VPortal link as shown in the cabinet":
        "Nhập liên kết VPortal như hiển thị trong trang tài khoản",
    "Enter this link in VPortal link. Playlist URL requires an M3U playlist.":
        "Nhập liên kết này vào Liên kết VPortal. URL danh sách phát yêu cầu danh sách phát M3U.",
    "Enter this player's device access code to connect.":
        "Nhập mã truy cập thiết bị của trình phát này để kết nối.",
    "Enter username": "Nhập tên người dùng",
    "Enter value": "Nhập giá trị",
    "Enter Xtream server URL": "Nhập URL máy chủ Xtream",
    "Enter Xtream server URL (e.g. https://your-server:8080)":
        "Nhập URL máy chủ Xtream (ví dụ: https://your-server:8080)",
    EPG: "EPG",
    "EPG and archive. Channel: ": "EPG và lưu trữ. Kênh: ",
    "ERROR!": "Lỗi!",
    "Error Code!": "Mã không hợp lệ!",
    Exit: "Thoát",
    "Exit player": "Thoát trình phát",
    "Export settings": "Xuất cài đặt",
    "epg.one (Ordered)": "epg.one (Đã sắp xếp)",
    "epg.one (Standard)": "epg.one (Tiêu chuẩn)",
    "epg.one (Thematic)": "epg.one (Theo chủ đề)",
    "epgs...": "Lịch EPG…",
    "Fabryka.TV": "Fabryka.TV",
    "Fabryka.TV settings": "Cài đặt Fabryka.TV",
    "Failed to connect to Stalker portal": "Không thể kết nối tới cổng Stalker",
    "Failed to connect to Xtream API server":
        "Không thể kết nối tới máy chủ API Xtream",
    "Failed to get user data!!!": "Không thể lấy thông tin người dùng!",
    "Failed to load channel list!": "Không thể tải danh sách kênh!",
    "Failed to load channels from Stalker portal":
        "Không thể tải kênh từ cổng Stalker",
    "Failed to load channels from Xtream API":
        "Không thể tải kênh từ API Xtream",
    "Failed to load!": "Tải thất bại!",
    "Favorite lists": "Danh sách yêu thích",
    Favorites: "Yêu thích",
    "File selection is not supported on this device":
        "Thiết bị này không hỗ trợ chọn tệp",
    Filters: "Bộ lọc",
    "First Run Setup": "Thiết lập lần đầu",
    "Font type": "Kiểu chữ",
    "For download settings file open": "Để tải tệp cài đặt xuống, mở",
    "For enter value open": "Để nhập giá trị, mở",
    "For upload settings file open": "Để tải tệp cài đặt lên, mở",
    "Fox-TV": "Fox-TV",
    "Fox-TV settings": "Cài đặt Fox-TV",
    FXML: "FXML",
    "FXML settings": "Cài đặt FXML",
    Genre: "Thể loại",
    GlanzTV: "GlanzTV",
    "GlanzTV settings": "Cài đặt GlanzTV",
    "Go to": "Đi tới",
    "GREAT IPTV": "GREAT IPTV",
    "GREAT IPTV settings": "Cài đặt GREAT IPTV",
    "Graphical indication": "Chỉ báo đồ họa",
    Green: "Xanh lá",
    "Hide / Return": "Ẩn / hiện",
    "Hide provider settings?": "Ẩn cài đặt nhà cung cấp?",
    "Hide providers?": "Ẩn nhà cung cấp?",
    "History in Media Library": "Lịch sử trong thư viện đa phương tiện",
    "History of watched movies": "Lịch sử xem",
    "HTTP port": "Cổng HTTP",
    "HTTP remote control is unavailable on this device.":
        "Điều khiển từ xa HTTP không khả dụng trên thiết bị này.",
    ID: "ID",
    "Import settings": "Nhập cài đặt",
    "In live mode: <br/>": "Trong chế độ trực tiếp:<br/>",
    Info: "Thông tin",
    "Infobar display timeout, s": "Thời gian hiển thị thanh thông tin, giây",
    "Infobar settings": "Cài đặt thanh thông tin",
    Information: "Thông tin",
    "Interface credits": "Ghi công giao diện",
    "Interface settings": "Cài đặt giao diện",
    "Interface theme": "Chủ đề giao diện",
    "Interface transparency": "Độ trong suốt giao diện",
    "Invalid channel link! Enter the full host as in the cabinet stream URL (e.g. subdomain.cdn-domain.tld)":
        "Liên kết kênh không hợp lệ! Nhập tên máy chủ đầy đủ như trong URL luồng ở trang tài khoản (ví dụ: subdomain.cdn-domain.tld)",
    "IPTV token": "Mã token IPTV",
    "IpStream.one": "IpStream.one",
    "IpStream.one settings": "Cài đặt IpStream.one",
    Joystick: "Cần điều khiển",
    "KBC (Kinoboom) access data": "Thông tin truy cập KBC (Kinoboom)",
    "KORONA TV": "KORONA TV",
    "KORONA TV settings": "Cài đặt KORONA TV",
    "List created": "Đã tạo danh sách",
    "List deleted": "Đã xóa danh sách",
    "List location": "Vị trí danh sách",
    "List renamed": "Đã đổi tên danh sách",
    "List type": "Kiểu danh sách",
    "Lists settings": "Cài đặt danh sách",
    Live: "Trực tiếp",
    Load: "Tải",
    "Load built-in playlist:": "Tải danh sách phát tích hợp:",
    "Load playlist": "Tải danh sách phát",
    "Load settings": "Tải cài đặt",
    "Load settings from storage": "Tải cài đặt từ bộ nhớ",
    "Load:": "Tải:",
    "Loading channels from Xtream API...": "Đang tải kênh từ API Xtream…",
    "Loading channels...": "Đang tải kênh…",
    "Loading from API...": "Đang tải từ API…",
    "Loading from Edem API...": "Đang tải từ API Edem…",
    "Loading M3U playlist...": "Đang tải danh sách phát M3U…",
    "Loading M3U...": "Đang tải M3U…",
    "Loading via proxy...": "Đang tải qua proxy…",
    "Loading. Please wait...": "Đang tải… vui lòng đợi…",
    "Loading...": "Đang tải…",
    "Local HTTP remote control": "Điều khiển từ xa HTTP cục bộ",
    "Local URL": "URL cục bộ",
    Login: "Đăng nhập",
    lang: "Tiếng Việt",
    large: "lớn",
    left: "trái",
    "left-bottom": "dưới trái",
    "logos...": "Biểu trưng…",
    M3U: "M3U",
    "M3U URL": "URL M3U",
    "M3U URL (fallback)": "URL M3U (dự phòng)",
    "MAC address": "Địa chỉ MAC",
    "Manage lists": "Quản lý danh sách",
    "Manage settings": "Quản lý cài đặt",
    "Manual setup": "Thiết lập thủ công",
    MaxTV: "MaxTV",
    "MaxTV settings": "Cài đặt MaxTV",
    Media: "Đa phương tiện",
    "Media item is no longer available":
        "Nội dung đa phương tiện không còn khả dụng",
    "Media Library": "Thư viện đa phương tiện",
    "Media Library URL": "URL thư viện đa phương tiện",
    Menu: "Menu",
    "Menu items settings": "Cài đặt mục menu",
    "Move category down": "Chuyển danh mục xuống",
    "Move category up": "Chuyển danh mục lên",
    "Move channel down": "Chuyển kênh xuống",
    "Move channel up": "Chuyển kênh lên",
    "m3u-m3u8 playlists": "Danh sách phát M3U / M3U8",
    medium: "vừa",
    min: "phút",
    "New Look": "New Look",
    "New Look settings": "Cài đặt New Look",
    "New list name": "Tên danh sách mới",
    Next: "Trang tiếp",
    "Next keyboard page": "Trang bàn phím tiếp theo",
    "Next TV program": "Chương trình tiếp theo",
    No: "Không",
    "No channel name": "Kênh không có tên",
    "No saved settings found": "Không tìm thấy cài đặt đã lưu",
    "Not found": "Không tìm thấy",
    "Not reduce video when showing the list (bugfix)":
        "Không thu nhỏ video khi hiển thị danh sách (sửa lỗi)",
    Nothing: "Không có",
    "Number of next TV programs in channel list":
        "Số chương trình tiếp theo trong danh sách kênh",
    "Number of rows in lists": "Số hàng trong danh sách",
    native: "gốc",
    no: "không",
    "no epg at current time": "Không có EPG tại thời điểm hiện tại",
    "not set": "chưa đặt",
    Off: "Tắt",
    Ok: "OK",
    Open: "Mở",
    "Open in PiP": "Mở trong PiP",
    "OTT Prime ONLINE": "OTT Prime ONLINE",
    "OTT Prime ONLINE settings": "Cài đặt OTT Prime ONLINE",
    "OttPlay FOSS %1 is available. Download and install now?":
        "Đã có OttPlay FOSS %1. Tải xuống và cài đặt ngay?",
    "Overwrite current settings?": "Ghi đè cài đặt hiện tại?",
    off: "tắt",
    on: "bật",
    "on ": "bật ",
    "or scan": "hoặc quét",
    "Parental control": "Kiểm soát của phụ huynh",
    Password: "Mật khẩu",
    Pause: "Tạm dừng",
    "Pause/Play": "Tạm dừng / phát",
    "Permanent clock on screen": "Luôn hiển thị đồng hồ trên màn hình",
    PIN: "PIN",
    "PiP exchange": "Đổi PiP",
    "PiP window position": "Vị trí cửa sổ PiP",
    "PiP window size": "Kích thước cửa sổ PiP",
    Play: "Phát",
    "Player and device info": "Thông tin trình phát và thiết bị",
    "Player info:": "Thông tin trình phát:",
    Playlist: "Danh sách phát",
    "Playlist file": "Tệp danh sách phát",
    "Playlist is not loading directly...Loading via server...":
        "Không thể tải trực tiếp danh sách phát. Đang tải qua máy chủ…",
    "Playlist Name": "Tên danh sách phát",
    "Playlist URL": "URL danh sách phát",
    POLMEDIA: "POLMEDIA",
    "POLMEDIA settings": "Cài đặt POLMEDIA",
    "Portal URL": "URL cổng",
    "Position shift -10 seconds after pause":
        "Tua lùi 10 giây sau khi tạm dừng",
    PROST: "PROST",
    "PROST settings": "Cài đặt PROST",
    Prev: "Trước",
    "Preview in channel list": "Xem trước trong danh sách kênh",
    Previous: "Trước",
    "Privacy policy": "Chính sách quyền riêng tư",
    "Protect Adult Channels": "Bảo vệ kênh người lớn",
    "Protect Change Provider": "Bảo vệ thay đổi nhà cung cấp",
    "Protect Settings": "Bảo vệ cài đặt",
    "p...": "p...",
    paging: "theo trang",
    Quality: "Chất lượng",
    Rating: "Đánh giá",
    RD: "RD",
    "RD settings": "Cài đặt RD",
    "Reconnecting…": "Đang kết nối lại…",
    Records: "Bản ghi",
    "Records for channel: ": "Bản ghi của kênh: ",
    "Records library is empty": "Thư viện bản ghi trống",
    "Records not supported by provider": "Nhà cung cấp không hỗ trợ bản ghi",
    "Release date": "Ngày phát hành",
    "Remember previous channels": "Ghi nhớ kênh trước",
    "Reminder: %1 — %2 in %3 min": "Nhắc nhở: %1 — %2 sau %3 phút",
    "Remote (color buttons N/A)": "Điều khiển từ xa không có nút màu",
    "Remote (number buttons N/A)": "Điều khiển từ xa không có nút số",
    "Remote control": "Điều khiển từ xa",
    "Remote session expired": "Phiên từ xa đã hết hạn",
    "Remote text entry denied": "Nhập văn bản từ xa bị từ chối",
    "Remote text entry error": "Lỗi nhập văn bản từ xa",
    "Remote text entry not configured": "Chưa cấu hình nhập văn bản từ xa",
    "Remote text entry requires a Device ID. Ask the server operator to provision one.":
        "Nhập văn bản từ xa yêu cầu ID thiết bị. Yêu cầu quản trị viên máy chủ cấp ID.",
    "Remove timer?": "Xóa hẹn giờ?",
    Rename: "Đổi tên",
    "Rename category": "Đổi tên danh mục",
    "Rename to": "Đổi tên thành",
    "Repeat parental code": "Nhập lại mã phụ huynh",
    "Request sended!": "Đã gửi yêu cầu!",
    "Restart player": "Khởi động lại trình phát",
    "Restart stream": "Khởi động lại luồng",
    "Restart stream / Live": "Khởi động lại luồng / trực tiếp",
    "Resume from archive?": "Tiếp tục từ lưu trữ?",
    "Return to previous channel": "Quay lại kênh trước",
    Rewind: "Tua",
    "Rewind step by buttons %1/%2": "Bước tua lùi của nút %1/%2",
    RUSSKOETV: "RUSSKOETV",
    "RUSSKOETV settings": "Cài đặt RUSSKOETV",
    Russian: "Tiếng Nga",
    right: "phải",
    Saturation: "Độ bão hòa",
    "Save & load channels": "Lưu và tải kênh",
    "Save and load": "Lưu và tải",
    "Save and load channels": "Lưu và tải kênh",
    "Save Settings": "Lưu cài đặt",
    "Save settings": "Lưu cài đặt",
    "Save settings and load channel list": "Lưu cài đặt và tải danh sách kênh",
    "Save settings to storage": "Lưu cài đặt vào bộ nhớ",
    Script: "Kịch bản",
    Search: "Tìm kiếm",
    "Search programme": "Tìm chương trình",
    "Select a stream type:<br>%1": "Chọn loại luồng:<br>%1",
    "Select category to add channel": "Chọn danh mục để thêm kênh",
    "Select color": "Chọn màu",
    "Select menu items": "Chọn mục menu",
    "Select playlist": "Chọn danh sách phát",
    "Select playlist file": "Chọn tệp danh sách phát",
    "Select playlist template source for EPG and logos":
        "Chọn nguồn mẫu danh sách phát cho EPG và biểu trưng",
    "Send request": "Gửi yêu cầu",
    "Send settings": "Gửi cài đặt",
    "Send this code from your proxy in the Authorization: Bearer header.":
        "Gửi mã này từ proxy của bạn trong tiêu đề Authorization: Bearer.",
    Server: "Máy chủ",
    "Server address": "Địa chỉ máy chủ",
    "Server address (for example 192.168.1.20:8081)":
        "Địa chỉ máy chủ (ví dụ: 192.168.1.20:8081)",
    "Server device access code": "Mã truy cập thiết bị trên máy chủ",
    "Server URL": "URL máy chủ",
    "Server unavailable. Retrying automatically; check its address and network access.":
        "Máy chủ không khả dụng. Sẽ tự động thử lại; hãy kiểm tra địa chỉ và kết nối mạng.",
    Set: "Đặt",
    "Set parental code": "Đặt mã phụ huynh",
    "Set timer?": "Đặt hẹn giờ?",
    Settings: "Cài đặt",
    "Settings could not be saved": "Không thể lưu cài đặt",
    "Settings loaded from storage": "Đã tải cài đặt từ bộ nhớ",
    "Settings STB": "Cài đặt STB",
    "Settings saved": "Đã lưu cài đặt",
    "Settings saved to storage": "Đã lưu cài đặt vào bộ nhớ",
    "Settings sended!": "Đã gửi cài đặt!",
    "Shara.club (ClubTV.pro)": "Shara.club (ClubTV.pro)",
    "Shara.club (ClubTV.pro) settings": "Cài đặt Shara.club (ClubTV.pro)",
    ShockTv: "ShockTv",
    "ShockTv settings": "Cài đặt ShockTv",
    "Show archive availability in list":
        "Hiển thị trạng thái lưu trữ trong danh sách",
    "Show channel name in list": "Hiển thị tên kênh trong danh sách",
    "Show channel number in list": "Hiển thị số kênh trong danh sách",
    "Show channel selection list": "Hiển thị danh sách chọn kênh",
    "Show description": "Hiển thị mô tả",
    "Show EPG and archive for channel": "Hiển thị EPG và lưu trữ của kênh",
    "Show list of channel archive records": "Hiển thị bản ghi của kênh",
    "Show list of channel archive records without duplication":
        "Hiển thị bản ghi của kênh không trùng lặp",
    "Show Media Library": "Hiển thị thư viện đa phương tiện",
    "Show picons in channel list": "Hiển thị biểu tượng kênh trong danh sách",
    "Show player menu": "Hiển thị menu trình phát",
    "Show program name": "Hiển thị tên chương trình",
    "Show progress in channel list": "Hiển thị tiến trình trong danh sách kênh",
    "Show provider settings?": "Hiển thị cài đặt nhà cung cấp?",
    "Show providers?": "Hiển thị nhà cung cấp?",
    "Show rewind window": "Hiển thị cửa sổ tua",
    "Show scrollbar in list": "Hiển thị thanh cuộn trong danh sách",
    "Show thumbnails": "Hiển thị hình thu nhỏ",
    "Show when changing program": "Hiển thị khi đổi chương trình",
    "Show when rewind": "Hiển thị khi tua lại",
    "Show when switching": "Hiển thị khi chuyển kênh",
    "Sleep timer": "Hẹn giờ ngủ",
    "Sort channels": "Sắp xếp kênh",
    "Stalker Portal Provider": "Nhà cung cấp cổng Stalker",
    "Stalker portal settings": "Cài đặt cổng Stalker",
    "Stalker portals": "Cổng Stalker",
    Status: "Trạng thái",
    "Stop playback and return to live": "Dừng phát và quay lại trực tiếp",
    "Stream type: %1": "Loại luồng: %1",
    "String for search": "Nội dung tìm kiếm",
    "Su Mo Tu We Th Fr Sa": "CN T2 T3 T4 T5 T6 T7",
    Subtitle: "Phụ đề",
    Switch: "Chuyển",
    "Switch sound track": "Đổi luồng âm thanh",
    "Switch subtitle": "Đổi phụ đề",
    "Switch to this list": "Chuyển sang danh sách này",
    "Swop URL": "Swop URL",
    "saved on this device": "đã lưu trên thiết bị này",
    select: "chọn",
    small: "nhỏ",
    system: "hệ thống",
    Tabox: "Tabox",
    "Tabox settings": "Cài đặt Tabox",
    "The device ID in the address is invalid.":
        "ID thiết bị trong địa chỉ không hợp lệ.",
    "This HTTPS player cannot connect to an HTTP server. Use an HTTPS server or open the player over HTTP.":
        "Trình phát HTTPS này không thể kết nối tới máy chủ HTTP. Dùng máy chủ HTTPS hoặc mở trình phát qua HTTP.",
    "This Play app requires HTTPS. Ask your provider for an HTTPS playlist or server URL.":
        "Ứng dụng Play này yêu cầu HTTPS. Hãy yêu cầu nhà cung cấp cung cấp danh sách phát hoặc URL máy chủ HTTPS.",
    Timer: "Hẹn giờ",
    "Timer: switch to channel?": "Hẹn giờ: chuyển sang kênh này?",
    "Timeshift: one minute back": "Timeshift: lùi một phút",
    "Timeshift: to start of TV program": "Timeshift: về đầu chương trình",
    Timezone: "Múi giờ",
    TMDb: "TMDb",
    "TOP-IPTV": "TOP-IPTV",
    "TOP-IPTV settings": "Cài đặt TOP-IPTV",
    "To begining": "Về đầu",
    "To start of TV program / Previous TV program":
        "Về đầu chương trình / chương trình trước",
    "Toggle Aspect Ratio": "Đổi tỷ lệ khung hình",
    "Toggle on-screen debug HUD": "Bật hoặc tắt bảng gỡ lỗi trên màn hình",
    "Toggle Zoom Mode": "Đổi chế độ thu phóng",
    "Top-Tv": "Top-Tv",
    "Top-Tv settings": "Cài đặt Top-Tv",
    "Try demo": "Dùng thử",
    "TV DOSUG": "TV DOSUG",
    "TV DOSUG settings": "Cài đặt TV DOSUG",
    TVClub: "TVClub",
    "TVClub settings": "Cài đặt TVClub",
    "Type of player for streaming": "Loại trình phát trực tuyến",
    "top-left": "trên trái",
    "top-right": "trên phải",
    transparent: "trong suốt",
    ULTIFL1X: "ULTIFL1X",
    "ULTIFL1X settings": "Cài đặt ULTIFL1X",
    "Update installed. Please restart OttPlay FOSS.":
        "Đã cài đặt bản cập nhật. Hãy khởi động lại OttPlay FOSS.",
    "Use an HTTP or HTTPS server address.":
        "Dùng địa chỉ máy chủ HTTP hoặc HTTPS.",
    "Use HTTP or HTTPS without a username or password in the address.":
        "Dùng HTTP hoặc HTTPS mà không có tên người dùng hay mật khẩu trong địa chỉ.",
    "Use LEFT/RIGHT to select a control, OK to activate, and UP/DOWN to scroll.":
        "Dùng TRÁI/PHẢI để chọn điều khiển, OK để kích hoạt và LÊN/XUỐNG để cuộn.",
    Username: "Tên người dùng",
    "Username or password is missing.": "Thiếu tên người dùng hoặc mật khẩu.",
    "VIP-IP.COM": "VIP-IP.COM",
    "VIP-IP.COM settings": "Cài đặt VIP-IP.COM",
    "Vidok.TV": "Vidok.TV",
    "Vidok.TV settings": "Cài đặt Vidok.TV",
    "VOD not supported by provider": "Nhà cung cấp không hỗ trợ VOD",
    "Volume step, %": "Bước âm lượng, %",
    "VPortal link": "Liên kết VPortal",
    "VPortal request failed":
        "Không thể tải VPortal. Kiểm tra liên kết, khóa truy cập và tình trạng hoạt động của cổng.",
    volume: "âm lượng",
    "Wrong parental code !!!": "Mã phụ huynh không đúng!",
    "Xtream Codes Provider": "Nhà cung cấp Xtream Codes",
    "Xtream Codes settings": "Cài đặt Xtream Codes",
    Year: "Năm",
    Yellow: "Vàng",
    Yes: "Có",
    yes: "có",
    "Гомельсат (cbilling)": "Гомельсат (cbilling)",
    "Гомельсат (cbilling) settings": "Cài đặt Гомельсат (cbilling)",
    МойДом: "МойДом",
    "МойДом settings": "Cài đặt МойДом",
    "Ошибка обработки списка каналов! Проверьте правильность данных!!":
        "Không thể xử lý danh sách kênh. Hãy kiểm tra thông tin nhà cung cấp!",
    Радуга: "Радуга",
    "Радуга settings": "Cài đặt Радуга",
    "Редактирование ID": "Chỉnh sửa ID",
    "Редактирование PIN": "Chỉnh sửa PIN",
    Шаравоз: "Шаравоз",
    "Шаравоз settings": "Cài đặt Шаравоз",
    "↑↓ Scroll": "↑↓ Cuộn",
};
