#!/usr/bin/env node
const fs = require("node:fs");
const path = require("node:path");
const { execFileSync } = require("node:child_process");
const { loadConfig } = require("@capacitor/cli/dist/config");
const { updateAndroid } = require("@capacitor/cli/dist/android/update");
const { auditTarget } = require("./verify-android-distribution.cjs");
const root = path.resolve(__dirname, "..");

async function sync() {
    process.chdir(root);
    const config = await loadConfig();
    // Sync native plugin projects without copying a Full frontend into a shared
    // source set. Actual app assets are independently generated by each flavor.
    const staging = path.join(root, "android/build/capacitor-sync");
    fs.mkdirSync(path.join(staging, "public"), { recursive: true });
    config.android.assetsDirAbs = staging;
    config.android.webDirAbs = path.join(staging, "public");
    await updateAndroid(config);
}

async function main() {
    const target = process.argv[2];
    const tasks = {
        full: [":app:assembleFullDebug"],
        "full-release": [":app:assembleFullRelease"],
    };
    if (target !== "sync" && !tasks[target])
        throw new Error("Usage: build-android.cjs <full|full-release|sync>");
    await sync();
    if (target === "sync") return;
    execFileSync(
        process.platform === "win32" ? "gradlew.bat" : "./gradlew",
        ["--no-daemon", ...tasks[target]],
        {
            cwd: path.join(root, "android"),
            stdio: "inherit",
        }
    );
    const artifact =
        target === "full"
            ? "apk/full/debug/app-full-debug.apk"
            : "apk/full/release/app-full-release" +
              (process.env.KEYSTORE_FILE ? "" : "-unsigned") +
              ".apk";
    auditTarget(path.join(root, "android/app/build/outputs", artifact), "full");
}
if (require.main === module)
    main().catch((error) => {
        console.error(error.message);
        process.exitCode = 1;
    });
module.exports = { sync };
