#!/usr/bin/env node
const fs = require("node:fs");
const path = require("node:path");
const { execFileSync } = require("node:child_process");
const { loadConfig } = require("@capacitor/cli/dist/config");
const { updateAndroid } = require("@capacitor/cli/dist/android/update");
const { auditTarget } = require("./verify-android-distribution.cjs");
const root = path.resolve(__dirname, "..");

async function sync() {
    process.chdir(root);
    const config = await loadConfig();
    // Sync native plugin projects without copying a Full frontend into a shared
    // source set. Actual app assets are independently generated by each flavor.
    const staging = path.join(root, "android/build/capacitor-sync");
    fs.mkdirSync(path.join(staging, "public"), { recursive: true });
    config.android.assetsDirAbs = staging;
    config.android.webDirAbs = path.join(staging, "public");
    await updateAndroid(config);
}

async function main() {
    const target = process.argv[2];
    const tasks = {
        all: [
            ":app:assembleFullDebug",
            ":app:assembleFullRelease",
            ":app:assemblePlayDebug",
            ":app:bundlePlayRelease",
        ],
        full: [":app:assembleFullDebug"],
        "full-release": [":app:assembleFullRelease"],
        play: [":app:bundlePlayRelease"],
        "play-debug": [":app:assemblePlayDebug"],
    };
    if (target !== "sync" && !tasks[target])
        throw new Error(
            "Usage: build-android.cjs <full|full-release|play|play-debug|all|sync>"
        );
    await sync();
    if (target === "sync") return;
    execFileSync(
        process.platform === "win32" ? "gradlew.bat" : "./gradlew",
        ["--no-daemon", ...tasks[target]],
        {
            cwd: path.join(root, "android"),
            stdio: "inherit",
        }
    );
    const artifacts = [];
    if (target === "full" || target === "all")
        artifacts.push(["apk/full/debug/app-full-debug.apk", "full"]);
    if (target === "play-debug" || target === "all")
        artifacts.push(["apk/play/debug/app-play-debug.apk", "play"]);
    if (target === "play" || target === "all")
        artifacts.push(["bundle/playRelease/app-play-release.aab", "play"]);
    if (target === "full-release" || target === "all") {
        artifacts.push([
            "apk/full/release/app-full-release" +
                (process.env.KEYSTORE_FILE ? "" : "-unsigned") +
                ".apk",
            "full",
        ]);
    }
    for (const [artifact, flavor] of artifacts)
        auditTarget(
            path.join(root, "android/app/build/outputs", artifact),
            flavor
        );
}
if (require.main === module)
    main().catch((error) => {
        console.error(error.message);
        process.exitCode = 1;
    });
module.exports = { sync };
