/**
 * Persisted language identifiers and their selector labels. The leading English
 * language name is also the lowercase asset basename; validate this contract in
 * localization-catalog.cjs before packaging. Keep IDs, labels and order stable.
 */
export var languageNames: { [code: string]: string } = {
    _afr: "Afrikaans",
    _alb: "Albanian - Shqip",
    _amh: "Amharic - አማርኛ",
    _ara: "Arabic - العربية",
    _arm: "Armenian - Հայերեն",
    _asm: "Assamese - অসমীয়া",
    _aze: "Azerbaijani - Azərbaycanca",
    _baq: "Basque - Euskara",
    _bel: "Belarusian - Беларуская",
    _ben: "Bengali - বাংলা",
    _bos: "Bosnian - Bosanski",
    _bul: "Bulgarian - Български",
    _bur: "Burmese - မြန်မာ",
    _cat: "Catalan - Català",
    _chi: "Chinese - 简体中文",
    _cze: "Czech - Čeština",
    _dan: "Danish - Dansk",
    _dut: "Dutch - Nederlands",
    _eng: "English",
    _est: "Estonian - Eesti",
    _fil: "Filipino",
    _fin: "Finnish - Suomi",
    _fra: "French - Français",
    _geo: "Georgian - ქართული",
    _ger: "German - Deutsch",
    _gle: "Irish - Gaeilge",
    _glg: "Galician - Galego",
    _gre: "Greek - Ελληνικά",
    _guj: "Gujarati - ગુજરાતી",
    _hau: "Hausa - Hausa",
    _heb: "Hebrew - עברית",
    _hin: "Hindi - हिन्दी",
    _hrv: "Croatian - Hrvatski",
    _hun: "Hungarian - Magyar",
    _ibo: "Igbo - Igbo",
    _ice: "Icelandic - Íslenska",
    _ind: "Indonesian - Bahasa Indonesia",
    _ita: "Italian - Italiano",
    _jpn: "Japanese - 日本語",
    _kan: "Kannada - ಕನ್ನಡ",
    _kaz: "Kazakh - Қазақша",
    _khm: "Khmer - ខ្មែរ",
    _kin: "Kinyarwanda - Ikinyarwanda",
    _kir: "Kyrgyz - Кыргызча",
    _kor: "Korean - 한국어",
    _kur: "Kurdish - Kurmancî",
    _lao: "Lao - ລາວ",
    _lat: "Latvian - Latviski",
    _lit: "Lithuanian - Lietuvių",
    _mac: "Macedonian - Македонски",
    _mal: "Malayalam - മലയാളം",
    _mar: "Marathi - मराठी",
    _may: "Malay - Bahasa Melayu",
    _mlg: "Malagasy",
    _mlt: "Maltese - Malti",
    _mon: "Mongolian - Монгол",
    _nep: "Nepali - नेपाली",
    _nor: "Norwegian - Norsk bokmål",
    _ori: "Odia - ଓଡ଼ିଆ",
    _pan: "Punjabi - ਪੰਜਾਬੀ",
    _per: "Persian - فارسی",
    _pol: "Polish - Polski",
    _por: "Portuguese - Português",
    _pus: "Pashto - پښتو",
    _rou: "Romanian - Română",
    _rus: "Russian - Русский",
    _sin: "Sinhala - සිංහල",
    _slo: "Slovak - Slovenčina",
    _slv: "Slovenian - Slovenščina",
    _snd: "Sindhi - سنڌي",
    _som: "Somali - Soomaali",
    _spa: "Spanish - Español",
    _srp: "Serbian - Српски",
    _swa: "Swahili - Kiswahili",
    _swe: "Swedish - Svenska",
    _tam: "Tamil - தமிழ்",
    _tel: "Telugu - తెలుగు",
    _tgk: "Tajik - Тоҷикӣ",
    _tha: "Thai - ไทย",
    _tuk: "Turkmen - Türkmençe",
    _tur: "Turkish - Türkçe",
    _ukr: "Ukrainian - Українська",
    _urd: "Urdu - اردو",
    _uzb: "Uzbek - O'zbekcha",
    _vie: "Vietnamese - Tiếng Việt",
    _xho: "Xhosa - isiXhosa",
    _yor: "Yoruba - Yorùbá",
    _zul: "Zulu - isiZulu",
};

/** Return the shipped language asset, falling back to English for unknown codes. */
export function languageAssetPath(code: string): string {
    var label = languageNames[code];
    return (
        "/locales/" +
        (typeof label === "string" ? label : "English")
            .split(" ")[0]
            .toLowerCase() +
        ".js"
    );
}
