/** Audited driver capabilities and legacy storage identities; build asset inventory uses this data. */
(window as any).__ottProviderDriverProfiles = [
    {
        id: "demo",
        kind: "demo",
        prefix: "demo",
        title: "Demo — moving test pattern",
    },
    { id: "xtream", kind: "xtream", prefix: "xtream", title: "Xtream Codes" },
    {
        id: "stalker",
        kind: "stalker",
        prefix: "stalker",
        title: "Stalker portal",
    },
    // OTTPLAY_FULL_ONLY_BEGIN
    { id: "itv", kind: "catalog", prefix: "itv", title: "1Cent.tv" },
    { id: "ottclub", kind: "catalog", prefix: "", title: "OTTCLUB" },
    { id: "shura", kind: "catalog", prefix: "sh", title: "SHURATV" },
    { id: "1ott", kind: "named-playlist", prefix: "1ott", title: "1OTT.NET" },
    {
        id: "bestlist/stalker",
        kind: "xtream-fallback",
        prefix: "bestlist_stalker",
        title: "BEST LiST IPTV [Stalker]",
    },
    { id: "only4", kind: "named-playlist", prefix: "o4", title: "Only4.tv" },
    {
        id: "shara-tv",
        kind: "named-playlist",
        prefix: "shtv",
        title: "shara-tv",
    },
    {
        id: "tvteam",
        kind: "named-playlist",
        prefix: "tvteam",
        title: "tv.team",
    },
    { id: "all4you", kind: "operator", prefix: "all4you", title: "All4you.tv" },
    {
        id: "bestlist",
        kind: "operator",
        prefix: "bestlist",
        title: "BEST LiST IPTV [HLS Playlist]",
    },
    {
        id: "cbilling",
        kind: "operator",
        prefix: "cbilling",
        title: "Гомельсат (cbilling)",
    },
    { id: "d/maxtv", kind: "operator", prefix: "d_maxtv", title: "MaxTV" },
    {
        id: "diamondtv",
        kind: "operator",
        prefix: "diamondtv",
        title: "Diamond TV",
    },
    { id: "dosug", kind: "operator", prefix: "dosug", title: "TV DOSUG" },
    {
        id: "dragon",
        kind: "operator",
        prefix: "dragon",
        title: "Dragon Media PRO",
    },
    { id: "drvao", kind: "operator", prefix: "drvao", title: "DRVAO" },
    { id: "fabryka", kind: "operator", prefix: "fabryka", title: "Fabryka.TV" },
    { id: "fox", kind: "operator", prefix: "fox", title: "Fox-TV" },
    { id: "fxml", kind: "operator", prefix: "fxml", title: "FXML" },
    { id: "great", kind: "operator", prefix: "great", title: "GREAT IPTV" },
    {
        id: "ipstream",
        kind: "operator",
        prefix: "ipstream",
        title: "IpStream.one",
    },
    {
        id: "iptv-ott.ru",
        kind: "operator",
        prefix: "iptv-ott.ru",
        title: "VIP-IP.COM",
    },
    { id: "korona", kind: "operator", prefix: "korona", title: "KORONA TV" },
    { id: "moidom", kind: "operator", prefix: "moidom", title: "МойДом" },
    { id: "newlook", kind: "operator", prefix: "newlook", title: "New Look" },
    { id: "ottg", kind: "operator", prefix: "ottg", title: "GlanzTV" },
    {
        id: "ottprime",
        kind: "operator",
        prefix: "ottprime",
        title: "OTT Prime ONLINE",
    },
    { id: "polmedia", kind: "operator", prefix: "polmedia", title: "POLMEDIA" },
    { id: "prost", kind: "operator", prefix: "prost", title: "PROST" },
    { id: "raduga", kind: "operator", prefix: "raduga", title: "Радуга" },
    { id: "rd", kind: "operator", prefix: "rd", title: "RD" },
    {
        id: "russkoetv",
        kind: "operator",
        prefix: "russkoetv",
        title: "RUSSKOETV",
    },
    {
        id: "shara.club",
        kind: "operator",
        prefix: "shara_club",
        title: "Shara.club (ClubTV.pro)",
    },
    { id: "sharavoz", kind: "operator", prefix: "sharavoz", title: "Шаравоз" },
    { id: "shocktv", kind: "operator", prefix: "shocktv", title: "ShockTv" },
    { id: "tabox", kind: "operator", prefix: "tabox", title: "Tabox" },
    { id: "top", kind: "operator", prefix: "top", title: "Top-Tv" },
    { id: "topiptv", kind: "operator", prefix: "topiptv", title: "TOP-IPTV" },
    { id: "tvclub", kind: "operator", prefix: "tvclub", title: "TVClub" },
    { id: "ultifl1x", kind: "operator", prefix: "ultifl1x", title: "ULTIFL1X" },
    { id: "vidok", kind: "operator", prefix: "vidok", title: "Vidok.TV" },
    // OTTPLAY_FULL_ONLY_END
];
